using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Components.Aphid.TypeSystem;
using Components.Aphid.Interpreter;
// <copyright file="AphidInterpreterTest.CallFunction02.g.cs">Copyright © AutoSec Tools LLC 2019</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace Components.Aphid.Interpreter.Tests
{
    public partial class AphidInterpreterTest
    {

[TestMethod]
[PexGeneratedBy(typeof(AphidInterpreterTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void CallFunction02ThrowsNullReferenceException184()
{
    AphidInterpreter aphidInterpreter;
    AphidObject aphidObject;
    aphidInterpreter = AphidInterpreterFactory.Create();
    aphidObject =
      this.CallFunction02(aphidInterpreter, (AphidObject)null, (object[])null);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidInterpreterTest))]
[PexRaisedException(typeof(AphidRuntimeException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(AphidRuntimeException))]
public void CallFunction02ThrowsAphidRuntimeException598()
{
    AphidInterpreter aphidInterpreter;
    object o;
    AphidObject aphidObject;
    aphidInterpreter = AphidInterpreterFactory.Create();
    o = AphidObjectFactory.Create(0);
    aphidObject =
      this.CallFunction02(aphidInterpreter, (AphidObject)o, (object[])null);
}
    }
}
