using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Components.Aphid.Interpreter;
// <copyright file="AphidInterpreterTest.GetStackFrame01.g.cs">Copyright © AutoSec Tools LLC 2019</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace Components.Aphid.Interpreter.Tests
{
    public partial class AphidInterpreterTest
    {

[TestMethod]
[PexGeneratedBy(typeof(AphidInterpreterTest))]
[ExpectedException(typeof(IndexOutOfRangeException))]
public void GetStackFrameThrowsIndexOutOfRangeException741()
{
    AphidInterpreter aphidInterpreter;
    AphidFrame aphidFrame;
    aphidInterpreter = AphidInterpreterFactory.Create();
    aphidFrame = this.GetStackFrame(aphidInterpreter, 0);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidInterpreterTest))]
[ExpectedException(typeof(IndexOutOfRangeException))]
public void GetStackFrameThrowsIndexOutOfRangeException723()
{
    AphidInterpreter aphidInterpreter;
    AphidFrame aphidFrame;
    aphidInterpreter = AphidInterpreterFactory.Create();
    aphidFrame = this.GetStackFrame(aphidInterpreter, int.MaxValue);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidInterpreterTest))]
[ExpectedException(typeof(IndexOutOfRangeException))]
public void GetStackFrameThrowsIndexOutOfRangeException132()
{
    AphidInterpreter aphidInterpreter;
    AphidFrame aphidFrame;
    aphidInterpreter = AphidInterpreterFactory.Create();
    aphidFrame = this.GetStackFrame(aphidInterpreter, 2147452163);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidInterpreterTest))]
[ExpectedException(typeof(IndexOutOfRangeException))]
public void GetStackFrameThrowsIndexOutOfRangeException47()
{
    AphidInterpreter aphidInterpreter;
    AphidFrame aphidFrame;
    aphidInterpreter = AphidInterpreterFactory.Create();
    aphidFrame = this.GetStackFrame(aphidInterpreter, int.MinValue);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidInterpreterTest))]
[ExpectedException(typeof(IndexOutOfRangeException))]
public void GetStackFrame01ThrowsIndexOutOfRangeException451()
{
    AphidInterpreter aphidInterpreter;
    AphidFrame aphidFrame;
    aphidInterpreter = AphidInterpreterFactory.Create();
    aphidFrame = this.GetStackFrame01(aphidInterpreter);
}
    }
}
