using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Components.Aphid.Interpreter;
// <copyright file="AphidInterpreterTest.LeaveScope.g.cs">Copyright © AutoSec Tools LLC 2019</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace Components.Aphid.Interpreter.Tests
{
    public partial class AphidInterpreterTest
    {

[TestMethod]
[PexGeneratedBy(typeof(AphidInterpreterTest))]
[PexRaisedException(typeof(AphidInternalException) , Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(AphidInternalException))]
public void LeaveScopeThrowsAphidInternalException309()
{
    AphidInterpreter aphidInterpreter;
    bool b;
    aphidInterpreter = AphidInterpreterFactory.Create();
    b = this.LeaveScope(aphidInterpreter, false);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidInterpreterTest))]
[ExpectedException(typeof(AphidInternalException))]
public void LeaveScopeThrowsAphidInternalException590()
{
    AphidInterpreter aphidInterpreter;
    bool b;
    aphidInterpreter = AphidInterpreterFactory.Create();
    b = this.LeaveScope(aphidInterpreter, false);
}
    }
}
