using System.Reflection;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using Components.Aphid.TypeSystem;
// <copyright file="AphidObjectTest.GetPropertyInfo.g.cs">Copyright © AutoSec Tools LLC 2019</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;
using Microsoft.Pex.Engine.Exceptions;

namespace Components.Aphid.TypeSystem.Tests
{
    public partial class AphidObjectTest
    {

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
public void GetPropertyInfo387()
{
    IEnumerable<AphidPropertyInfo> iEnumerable;
    object s0 = new object();
    iEnumerable = this.GetPropertyInfo(s0, false);
    Assert.IsNotNull((object)iEnumerable);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(TargetInvocationException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(TargetInvocationException))]
public void GetPropertyInfoThrowsTargetInvocationException68()
{
    IEnumerable<AphidPropertyInfo> iEnumerable;
    iEnumerable = this.GetPropertyInfo((object)null, false);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void GetThrowsNullReferenceException519()
{
    object o;
    int i;
    o = AphidObjectFactory.Create(7);
    i = this.Get<int>((AphidObject)o);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(InvalidCastException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(InvalidCastException))]
public void GetThrowsInvalidCastException120()
{
    object o;
    int i;
    o = AphidObjectFactory.Create(0);
    i = this.Get<int>((AphidObject)o);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void GetThrowsNullReferenceException226()
{
    object o;
    int i;
    o = AphidObjectFactory.Create(679);
    i = this.Get<int>((AphidObject)o);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void GetThrowsNullReferenceException22601()
{
    object o;
    int i;
    o = AphidObjectFactory.Create(36);
    i = this.Get<int>((AphidObject)o);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void GetThrowsNullReferenceException51901()
{
    object o;
    int i;
    o = AphidObjectFactory.Create();
    i = this.Get<int>((AphidObject)o);
}
    }
}
