using System.Reflection;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using Components.Aphid.Lexer;
using Components.Aphid.Parser;
// <copyright file="AphidParserTest.ParsePrefixUnaryOperatorExpression.g.cs">Copyright © AutoSec Tools LLC 2019</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;
using Microsoft.Pex.Engine.Exceptions;

namespace Components.Aphid.Parser.Tests
{
    public partial class AphidParserTest
    {

[TestMethod]
[PexGeneratedBy(typeof(AphidParserTest))]
[PexRaisedException(typeof(TargetInvocationException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(TargetInvocationException))]
public void ParsePrefixUnaryOperatorExpressionThrowsTargetInvocationException806()
{
    AphidParser aphidParser;
    AphidExpression aphidExpression;
    aphidParser = new AphidParser((List<AphidToken>)null);
    aphidExpression = this.ParsePrefixUnaryOperatorExpression(aphidParser);
}
    }
}
