using Components.Aphid.Lexer;
using System.Collections.Generic;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Components.Aphid.Parser;
using Mantispid;
// <copyright file="AphidMutatorTest.MutateSingle.g.cs">Copyright © AutoSec Tools LLC 2019</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;
using Microsoft.Pex.Engine.Exceptions;

namespace Components.Aphid.Parser.Tests
{
    public partial class AphidMutatorTest
    {

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException818()
{
    CallIdentifierMutator callIdentifierMutator;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    aphidExpression =
      this.MutateSingle((AphidMutator)callIdentifierMutator, (AphidExpression)null);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException491()
{
    CallIdentifierMutator callIdentifierMutator;
    ForExpression forExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    forExpression =
      new ForExpression((AphidExpressionContext)null, (AphidExpression)null, 
                        (AphidExpression)null, (AphidExpression)null, (List<AphidExpression>)null);
    ((AphidExpression)forExpression).Index = 0;
    ((AphidExpression)forExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)forExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException406()
{
    CallIdentifierMutator callIdentifierMutator;
    TernaryOperatorExpression ternaryOperatorExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    ternaryOperatorExpression = new TernaryOperatorExpression
                                    ((AphidExpressionContext)null, AphidTokenType.CustomOperator011, 
                                     (AphidExpression)null, (AphidExpression)null, (AphidExpression)null);
    ((AphidExpression)ternaryOperatorExpression).Index = 0;
    ((AphidExpression)ternaryOperatorExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)ternaryOperatorExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException42()
{
    CallIdentifierMutator callIdentifierMutator;
    ExtendExpression extendExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    extendExpression = new ExtendExpression((AphidExpressionContext)null, 
                                            (IdentifierExpression)null, (ObjectExpression)null);
    ((AphidExpression)extendExpression).Index = 0;
    ((AphidExpression)extendExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)extendExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException284()
{
    CallIdentifierMutator callIdentifierMutator;
    ForEachExpression forEachExpression;
    AphidExpression aphidExpression;
    string[] ss = new string[0];
    callIdentifierMutator = new CallIdentifierMutator(ss);
    forEachExpression =
      new ForEachExpression((AphidExpressionContext)null, (AphidExpression)null, 
                            (List<AphidExpression>)null, (AphidExpression)null);
    ((AphidExpression)forEachExpression).Index = 0;
    ((AphidExpression)forEachExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)forEachExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException382()
{
    CallIdentifierMutator callIdentifierMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    binaryOperatorExpression = new BinaryOperatorExpression
                                   ((AphidExpressionContext)null, (AphidExpression)null, 
                                    AphidTokenType.CustomOperator011, (AphidExpression)null);
    ((AphidExpression)binaryOperatorExpression).Index = 0;
    ((AphidExpression)binaryOperatorExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)binaryOperatorExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException372()
{
    CallIdentifierMutator callIdentifierMutator;
    SwitchExpression switchExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    switchExpression =
      new SwitchExpression((AphidExpressionContext)null, (AphidExpression)null, 
                           (List<SwitchCase>)null, (List<AphidExpression>)null);
    ((AphidExpression)switchExpression).Index = 0;
    ((AphidExpression)switchExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)switchExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException225()
{
    CallIdentifierMutator callIdentifierMutator;
    GatorEmitExpression gatorEmitExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    gatorEmitExpression =
      new GatorEmitExpression((AphidExpressionContext)null, (AphidExpression)null);
    ((AphidExpression)gatorEmitExpression).Index = 0;
    ((AphidExpression)gatorEmitExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)gatorEmitExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle531()
{
    CallIdentifierMutator callIdentifierMutator;
    TryExpression tryExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    tryExpression =
      new TryExpression((AphidExpressionContext)null, (List<AphidExpression>)null, 
                        (IdentifierExpression)null, 
                        (List<AphidExpression>)null, (List<AphidExpression>)null);
    ((AphidExpression)tryExpression).Index = 0;
    ((AphidExpression)tryExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)tryExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException165()
{
    CallIdentifierMutator callIdentifierMutator;
    DoWhileExpression doWhileExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    doWhileExpression = new DoWhileExpression((AphidExpressionContext)null, 
                                              (AphidExpression)null, (List<AphidExpression>)null);
    ((AphidExpression)doWhileExpression).Index = 0;
    ((AphidExpression)doWhileExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)doWhileExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException993()
{
    CallIdentifierMutator callIdentifierMutator;
    DynamicMemberExpression dynamicMemberExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    dynamicMemberExpression = new DynamicMemberExpression
                                  ((AphidExpressionContext)null, (AphidExpression)null);
    ((AphidExpression)dynamicMemberExpression).Index = 0;
    ((AphidExpression)dynamicMemberExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)dynamicMemberExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException636()
{
    CallIdentifierMutator callIdentifierMutator;
    PatternExpression patternExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    patternExpression = new PatternExpression((AphidExpressionContext)null, 
                                              (AphidExpression)null, (List<AphidExpression>)null);
    ((AphidExpression)patternExpression).Index = 0;
    ((AphidExpression)patternExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)patternExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException955()
{
    CallIdentifierMutator callIdentifierMutator;
    PatternMatchingExpression patternMatchingExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    patternMatchingExpression =
      new PatternMatchingExpression((AphidExpressionContext)null, 
                                    (AphidExpression)null, (List<PatternExpression>)null);
    ((AphidExpression)patternMatchingExpression).Index = 0;
    ((AphidExpression)patternMatchingExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)patternMatchingExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(ArgumentNullException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException250()
{
    CallIdentifierMutator callIdentifierMutator;
    ObjectExpression objectExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    objectExpression = new ObjectExpression((AphidExpressionContext)null, 
                                            (List<BinaryOperatorExpression>)null, (IdentifierExpression)null);
    ((AphidExpression)objectExpression).Index = 0;
    ((AphidExpression)objectExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)objectExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException142()
{
    CallIdentifierMutator callIdentifierMutator;
    PartialOperatorExpression partialOperatorExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    partialOperatorExpression =
      new PartialOperatorExpression((AphidExpressionContext)null, 
                                    AphidTokenType.CustomOperator011, (AphidExpression)null);
    ((AphidExpression)partialOperatorExpression).Index = 0;
    ((AphidExpression)partialOperatorExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)partialOperatorExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException595()
{
    CallIdentifierMutator callIdentifierMutator;
    PartialFunctionExpression partialFunctionExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    partialFunctionExpression = new PartialFunctionExpression
                                    ((AphidExpressionContext)null, (CallExpression)null);
    ((AphidExpression)partialFunctionExpression).Index = 0;
    ((AphidExpression)partialFunctionExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)partialFunctionExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException541()
{
    CallIdentifierMutator callIdentifierMutator;
    UsingExpression usingExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    usingExpression = new UsingExpression((AphidExpressionContext)null, 
                                          (AphidExpression)null, (List<AphidExpression>)null);
    ((AphidExpression)usingExpression).Index = 0;
    ((AphidExpression)usingExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)usingExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException99301()
{
    CallIdentifierMutator callIdentifierMutator;
    IfExpression ifExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    ifExpression =
      new IfExpression((AphidExpressionContext)null, (AphidExpression)null, 
                       (List<AphidExpression>)null, (List<AphidExpression>)null);
    ((AphidExpression)ifExpression).Index = 0;
    ((AphidExpression)ifExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)ifExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException89()
{
    CallIdentifierMutator callIdentifierMutator;
    LoadLibraryExpression loadLibraryExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    loadLibraryExpression =
      new LoadLibraryExpression((AphidExpressionContext)null, (AphidExpression)null);
    ((AphidExpression)loadLibraryExpression).Index = 0;
    ((AphidExpression)loadLibraryExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)loadLibraryExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException422()
{
    CallIdentifierMutator callIdentifierMutator;
    UnaryOperatorExpression unaryOperatorExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    unaryOperatorExpression = new UnaryOperatorExpression
                                  ((AphidExpressionContext)null, AphidTokenType.CustomOperator011, 
                                   (AphidExpression)null, false);
    ((AphidExpression)unaryOperatorExpression).Index = 0;
    ((AphidExpression)unaryOperatorExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)unaryOperatorExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException805()
{
    CallIdentifierMutator callIdentifierMutator;
    LoadScriptExpression loadScriptExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    loadScriptExpression =
      new LoadScriptExpression((AphidExpressionContext)null, (AphidExpression)null);
    ((AphidExpression)loadScriptExpression).Index = 0;
    ((AphidExpression)loadScriptExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)loadScriptExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException49101()
{
    CallIdentifierMutator callIdentifierMutator;
    WhileExpression whileExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    whileExpression = new WhileExpression((AphidExpressionContext)null, 
                                          (AphidExpression)null, (List<AphidExpression>)null);
    ((AphidExpression)whileExpression).Index = 0;
    ((AphidExpression)whileExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)whileExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException440()
{
    CallIdentifierMutator callIdentifierMutator;
    ArrayAccessExpression arrayAccessExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    arrayAccessExpression = new ArrayAccessExpression((AphidExpressionContext)null, 
                                                      (AphidExpression)null, (List<AphidExpression>)null);
    ((AphidExpression)arrayAccessExpression).Index = 0;
    ((AphidExpression)arrayAccessExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)arrayAccessExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException103()
{
    CallIdentifierMutator callIdentifierMutator;
    BinaryOperatorBodyExpression binaryOperatorBodyExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    binaryOperatorBodyExpression =
      new BinaryOperatorBodyExpression((AphidExpressionContext)null, 
                                       AphidTokenType.CustomOperator011, (FunctionExpression)null);
    ((AphidExpression)binaryOperatorBodyExpression).Index = 0;
    ((AphidExpression)binaryOperatorBodyExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)binaryOperatorBodyExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException21()
{
    CallIdentifierMutator callIdentifierMutator;
    CallExpression callExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    callExpression = new CallExpression((AphidExpressionContext)null, 
                                        (AphidExpression)null, (List<AphidExpression>)null);
    ((AphidExpression)callExpression).Index = 0;
    ((AphidExpression)callExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)callExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle615()
{
    CallIdentifierMutator callIdentifierMutator;
    ThisExpression thisExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    thisExpression = new ThisExpression((AphidExpressionContext)null);
    ((AphidExpression)thisExpression).Index = 0;
    ((AphidExpression)thisExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)thisExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle440()
{
    CallIdentifierMutator callIdentifierMutator;
    TextExpression textExpression;
    AphidExpression aphidExpression;
    string[] ss = new string[0];
    callIdentifierMutator = new CallIdentifierMutator(ss);
    textExpression = new TextExpression((AphidExpressionContext)null, (string)null);
    ((AphidExpression)textExpression).Index = 0;
    ((AphidExpression)textExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)textExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle409()
{
    CallIdentifierMutator callIdentifierMutator;
    StringExpression stringExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    stringExpression =
      new StringExpression((AphidExpressionContext)null, (string)null);
    ((AphidExpression)stringExpression).Index = 0;
    ((AphidExpression)stringExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)stringExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NotImplementedException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NotImplementedException))]
public void MutateSingleThrowsNotImplementedException519()
{
    CallIdentifierMutator callIdentifierMutator;
    SwitchCase switchCase;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    switchCase = new SwitchCase((AphidExpressionContext)null, 
                                (List<AphidExpression>)null, (List<AphidExpression>)null);
    ((AphidExpression)switchCase).Index = 0;
    ((AphidExpression)switchCase).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)switchCase);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle619()
{
    CallIdentifierMutator callIdentifierMutator;
    ContinueExpression continueExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    continueExpression = new ContinueExpression((AphidExpressionContext)null);
    ((AphidExpression)continueExpression).Index = 0;
    ((AphidExpression)continueExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)continueExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(ArgumentNullException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException659()
{
    CallIdentifierMutator callIdentifierMutator;
    FunctionExpression functionExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    functionExpression = new FunctionExpression((AphidExpressionContext)null, 
                                                (List<AphidExpression>)null, (List<AphidExpression>)null);
    ((AphidExpression)functionExpression).Index = 0;
    ((AphidExpression)functionExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)functionExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle532()
{
    CallIdentifierMutator callIdentifierMutator;
    GatorOpenExpression gatorOpenExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    gatorOpenExpression = new GatorOpenExpression((AphidExpressionContext)null);
    ((AphidExpression)gatorOpenExpression).Index = 0;
    ((AphidExpression)gatorOpenExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)gatorOpenExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(ArgumentNullException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException310()
{
    CallIdentifierMutator callIdentifierMutator;
    ArrayExpression arrayExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    arrayExpression =
      new ArrayExpression((AphidExpressionContext)null, (List<AphidExpression>)null);
    ((AphidExpression)arrayExpression).Index = 0;
    ((AphidExpression)arrayExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)arrayExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle89()
{
    CallIdentifierMutator callIdentifierMutator;
    BooleanExpression booleanExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    booleanExpression = new BooleanExpression((AphidExpressionContext)null, false);
    ((AphidExpression)booleanExpression).Index = 0;
    ((AphidExpression)booleanExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)booleanExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle748()
{
    CallIdentifierMutator callIdentifierMutator;
    BreakExpression breakExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    breakExpression = new BreakExpression((AphidExpressionContext)null);
    ((AphidExpression)breakExpression).Index = 0;
    ((AphidExpression)breakExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)breakExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle53101()
{
    CallIdentifierMutator callIdentifierMutator;
    GatorCloseExpression gatorCloseExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    gatorCloseExpression = new GatorCloseExpression((AphidExpressionContext)null);
    ((AphidExpression)gatorCloseExpression).Index = 0;
    ((AphidExpression)gatorCloseExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)gatorCloseExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(ArgumentNullException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException187()
{
    CallIdentifierMutator callIdentifierMutator;
    LockExpression lockExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    lockExpression = new LockExpression((AphidExpressionContext)null, 
                                        (List<AphidExpression>)null, (List<AphidExpression>)null);
    ((AphidExpression)lockExpression).Index = 0;
    ((AphidExpression)lockExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)lockExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle634()
{
    CallIdentifierMutator callIdentifierMutator;
    NullExpression nullExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    nullExpression = new NullExpression((AphidExpressionContext)null);
    ((AphidExpression)nullExpression).Index = 0;
    ((AphidExpression)nullExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)nullExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle278()
{
    CallIdentifierMutator callIdentifierMutator;
    NumberExpression numberExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    numberExpression =
      new NumberExpression((AphidExpressionContext)null, default(decimal));
    ((AphidExpression)numberExpression).Index = 0;
    ((AphidExpression)numberExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)numberExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(ArgumentNullException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException404()
{
    CallIdentifierMutator callIdentifierMutator;
    IdentifierExpression identifierExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    identifierExpression = new IdentifierExpression((AphidExpressionContext)null, 
                                                    (string)null, (List<IdentifierExpression>)null);
    ((AphidExpression)identifierExpression).Index = 0;
    ((AphidExpression)identifierExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)identifierExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle910()
{
    CallIdentifierMutator callIdentifierMutator;
    IdentifierExpression identifierExpression;
    AphidExpression aphidExpression;
    string[] ss = new string[0];
    callIdentifierMutator = new CallIdentifierMutator(ss);
    identifierExpression = new IdentifierExpression((AphidExpressionContext)null, 
                                                    (string)null, (List<IdentifierExpression>)null);
    ((AphidExpression)identifierExpression).Index = 0;
    ((AphidExpression)identifierExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)identifierExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle936()
{
    CallIdentifierMutator callIdentifierMutator;
    IdentifierExpression identifierExpression;
    AphidExpression aphidExpression;
    string[] ss = new string[1];
    callIdentifierMutator = new CallIdentifierMutator(ss);
    identifierExpression = new IdentifierExpression((AphidExpressionContext)null, 
                                                    (string)null, (List<IdentifierExpression>)null);
    ((AphidExpression)identifierExpression).Index = 0;
    ((AphidExpression)identifierExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)identifierExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle126()
{
    CallIdentifierMutator callIdentifierMutator;
    ImplicitArgumentExpression implicitArgumentExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    implicitArgumentExpression = new ImplicitArgumentExpression
                                     ((AphidExpressionContext)null, AphidTokenType.CustomOperator011);
    ((AphidExpression)implicitArgumentExpression).Index = 0;
    ((AphidExpression)implicitArgumentExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)implicitArgumentExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle84()
{
    CallIdentifierMutator callIdentifierMutator;
    ImplicitArgumentsExpression implicitArgumentsExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    implicitArgumentsExpression = new ImplicitArgumentsExpression
                                      ((AphidExpressionContext)null, AphidTokenType.CustomOperator011);
    ((AphidExpression)implicitArgumentsExpression).Index = 0;
    ((AphidExpression)implicitArgumentsExpression).Length = 0;
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)implicitArgumentsExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException63601()
{
    CallIdentifierMutator callIdentifierMutator;
    List<AphidExpression> list;
    PatternExpression patternExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    AphidExpression[] aphidExpressions = new AphidExpression[0];
    list = new List<AphidExpression>((IEnumerable<AphidExpression>)aphidExpressions);
    patternExpression = new PatternExpression
                            ((AphidExpressionContext)null, (AphidExpression)null, list);
    ((AphidExpression)patternExpression).Index = 0;
    ((AphidExpression)patternExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)patternExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle794()
{
    CallIdentifierMutator callIdentifierMutator;
    TryExpression tryExpression;
    ForEachExpression forEachExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    tryExpression =
      new TryExpression((AphidExpressionContext)null, (List<AphidExpression>)null, 
                        (IdentifierExpression)null, 
                        (List<AphidExpression>)null, (List<AphidExpression>)null);
    ((AphidExpression)tryExpression).Index = 0;
    ((AphidExpression)tryExpression).Length = 0;
    forEachExpression = new ForEachExpression
                            ((AphidExpressionContext)null, (AphidExpression)tryExpression, 
                             (List<AphidExpression>)null, (AphidExpression)null);
    ((AphidExpression)forEachExpression).Index = 0;
    ((AphidExpression)forEachExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)forEachExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle587()
{
    CallIdentifierMutator callIdentifierMutator;
    TryExpression tryExpression;
    ForEachExpression forEachExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    tryExpression =
      new TryExpression((AphidExpressionContext)null, (List<AphidExpression>)null, 
                        (IdentifierExpression)null, 
                        (List<AphidExpression>)null, (List<AphidExpression>)null);
    ((AphidExpression)tryExpression).Index = 0;
    ((AphidExpression)tryExpression).Length = 0;
    forEachExpression = new ForEachExpression
                            ((AphidExpressionContext)null, (AphidExpression)tryExpression, 
                             (List<AphidExpression>)null, (AphidExpression)tryExpression);
    ((AphidExpression)forEachExpression).Index = 0;
    ((AphidExpression)forEachExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)forEachExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle806()
{
    CallIdentifierMutator callIdentifierMutator;
    List<AphidExpression> list;
    FunctionExpression functionExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    AphidExpression[] aphidExpressions = new AphidExpression[0];
    list = new List<AphidExpression>((IEnumerable<AphidExpression>)aphidExpressions);
    functionExpression = new FunctionExpression
                             ((AphidExpressionContext)null, list, (List<AphidExpression>)null);
    ((AphidExpression)functionExpression).Index = 0;
    ((AphidExpression)functionExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)functionExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle215()
{
    CallIdentifierMutator callIdentifierMutator;
    List<AphidExpression> list;
    TryExpression tryExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    AphidExpression[] aphidExpressions = new AphidExpression[0];
    list = new List<AphidExpression>((IEnumerable<AphidExpression>)aphidExpressions);
    tryExpression = new TryExpression
                        ((AphidExpressionContext)null, list, (IdentifierExpression)null, 
                                                             (List<AphidExpression>)null, (List<AphidExpression>)null);
    ((AphidExpression)tryExpression).Index = 0;
    ((AphidExpression)tryExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)tryExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle957()
{
    CallIdentifierMutator callIdentifierMutator;
    List<AphidExpression> list;
    LockExpression lockExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    AphidExpression[] aphidExpressions = new AphidExpression[0];
    list = new List<AphidExpression>((IEnumerable<AphidExpression>)aphidExpressions);
    lockExpression = new LockExpression
                         ((AphidExpressionContext)null, list, (List<AphidExpression>)null);
    ((AphidExpression)lockExpression).Index = 0;
    ((AphidExpression)lockExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)lockExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(ArgumentNullException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException455()
{
    CallIdentifierMutator callIdentifierMutator;
    IdentifierExpression identifierExpression;
    TryExpression tryExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    identifierExpression = new IdentifierExpression((AphidExpressionContext)null, 
                                                    (string)null, (List<IdentifierExpression>)null);
    ((AphidExpression)identifierExpression).Index = 0;
    ((AphidExpression)identifierExpression).Length = 0;
    tryExpression =
      new TryExpression((AphidExpressionContext)null, (List<AphidExpression>)null, 
                        identifierExpression, 
                        (List<AphidExpression>)null, (List<AphidExpression>)null);
    ((AphidExpression)tryExpression).Index = 0;
    ((AphidExpression)tryExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)tryExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle168()
{
    CallIdentifierMutator callIdentifierMutator;
    List<BinaryOperatorExpression> list;
    ObjectExpression objectExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    BinaryOperatorExpression[] binaryOperatorExpressions
       = new BinaryOperatorExpression[0];
    list = new List<BinaryOperatorExpression>
               ((IEnumerable<BinaryOperatorExpression>)binaryOperatorExpressions);
    objectExpression = new ObjectExpression
                           ((AphidExpressionContext)null, list, (IdentifierExpression)null);
    ((AphidExpression)objectExpression).Index = 0;
    ((AphidExpression)objectExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)objectExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[PexRaisedException(typeof(ArgumentNullException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException119()
{
    CallIdentifierMutator callIdentifierMutator;
    List<BinaryOperatorExpression> list;
    IdentifierExpression identifierExpression;
    ObjectExpression objectExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    BinaryOperatorExpression[] binaryOperatorExpressions
       = new BinaryOperatorExpression[0];
    list = new List<BinaryOperatorExpression>
               ((IEnumerable<BinaryOperatorExpression>)binaryOperatorExpressions);
    identifierExpression = new IdentifierExpression((AphidExpressionContext)null, 
                                                    (string)null, (List<IdentifierExpression>)null);
    ((AphidExpression)identifierExpression).Index = 0;
    ((AphidExpression)identifierExpression).Length = 0;
    objectExpression =
      new ObjectExpression((AphidExpressionContext)null, list, identifierExpression);
    ((AphidExpression)objectExpression).Index = 0;
    ((AphidExpression)objectExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)objectExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle815()
{
    CallIdentifierMutator callIdentifierMutator;
    List<AphidExpression> list;
    ArrayExpression arrayExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = new CallIdentifierMutator((string[])null);
    AphidExpression[] aphidExpressions = new AphidExpression[0];
    list = new List<AphidExpression>((IEnumerable<AphidExpression>)aphidExpressions);
    arrayExpression = new ArrayExpression((AphidExpressionContext)null, list);
    ((AphidExpression)arrayExpression).Index = 0;
    ((AphidExpression)arrayExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)arrayExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle389()
{
    CallIdentifierMutator callIdentifierMutator;
    IdentifierExpression identifierExpression;
    TryExpression tryExpression;
    AphidExpression aphidExpression;
    string[] ss = new string[0];
    callIdentifierMutator = new CallIdentifierMutator(ss);
    identifierExpression = new IdentifierExpression((AphidExpressionContext)null, 
                                                    (string)null, (List<IdentifierExpression>)null);
    ((AphidExpression)identifierExpression).Index = 0;
    ((AphidExpression)identifierExpression).Length = 0;
    tryExpression =
      new TryExpression((AphidExpressionContext)null, (List<AphidExpression>)null, 
                        identifierExpression, 
                        (List<AphidExpression>)null, (List<AphidExpression>)null);
    ((AphidExpression)tryExpression).Index = 0;
    ((AphidExpression)tryExpression).Length = 0;
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)tryExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void Mutate79701()
{
    IndexTrackingMutator indexTrackingMutator;
    List<AphidExpression> list;
    indexTrackingMutator = IndexTrackingMutatorFactory.Create((string[])null);
    list =
      this.Mutate((AphidMutator)indexTrackingMutator, (List<AphidExpression>)null);
    Assert.IsNull((object)list);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void Mutate15001()
{
    IndexTrackingMutator indexTrackingMutator;
    List<AphidExpression> list;
    List<AphidExpression> list1;
    indexTrackingMutator = IndexTrackingMutatorFactory.Create((string[])null);
    AphidExpression[] aphidExpressions = new AphidExpression[0];
    list = new List<AphidExpression>((IEnumerable<AphidExpression>)aphidExpressions);
    list1 = this.Mutate((AphidMutator)indexTrackingMutator, list);
    Assert.IsNotNull((object)list1);
    Assert.AreEqual<int>(0, list1.Capacity);
    Assert.AreEqual<int>(0, list1.Count);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateThrowsNullReferenceException717()
{
    IndexTrackingMutator indexTrackingMutator;
    List<AphidExpression> list;
    List<AphidExpression> list1;
    indexTrackingMutator = IndexTrackingMutatorFactory.Create((string[])null);
    AphidExpression[] aphidExpressions = new AphidExpression[1];
    list = new List<AphidExpression>((IEnumerable<AphidExpression>)aphidExpressions);
    list1 = this.Mutate((AphidMutator)indexTrackingMutator, list);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void Mutate932()
{
    IndexTrackingMutator indexTrackingMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    List<AphidExpression> list;
    List<AphidExpression> list1;
    indexTrackingMutator = IndexTrackingMutatorFactory.Create((string[])null);
    binaryOperatorExpression = BinaryOperatorExpressionFactory.Create(0);
    AphidExpression[] aphidExpressions = new AphidExpression[1];
    aphidExpressions[0] = (AphidExpression)binaryOperatorExpression;
    list = new List<AphidExpression>((IEnumerable<AphidExpression>)aphidExpressions);
    list1 = this.Mutate((AphidMutator)indexTrackingMutator, list);
    Assert.IsNotNull((object)list1);
    Assert.AreEqual<int>(4, list1.Capacity);
    Assert.AreEqual<int>(1, list1.Count);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void Mutate955()
{
    IndexTrackingMutator indexTrackingMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    List<AphidExpression> list;
    List<AphidExpression> list1;
    indexTrackingMutator = IndexTrackingMutatorFactory.Create((string[])null);
    binaryOperatorExpression = BinaryOperatorExpressionFactory.Create(65270705);
    BinaryOperatorExpression[] binaryOperatorExpressions
       = new BinaryOperatorExpression[1];
    binaryOperatorExpressions[0] = binaryOperatorExpression;
    list = new List<AphidExpression>
               ((IEnumerable<AphidExpression>)binaryOperatorExpressions);
    list1 = this.Mutate((AphidMutator)indexTrackingMutator, list);
    Assert.IsNotNull((object)list1);
    Assert.AreEqual<int>(4, list1.Capacity);
    Assert.AreEqual<int>(1, list1.Count);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void Mutate604()
{
    IndexTrackingMutator indexTrackingMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    List<AphidExpression> list;
    List<AphidExpression> list1;
    indexTrackingMutator = IndexTrackingMutatorFactory.Create((string[])null);
    binaryOperatorExpression = BinaryOperatorExpressionFactory.Create(268435456);
    AphidExpression[] aphidExpressions = new AphidExpression[1];
    aphidExpressions[0] = (AphidExpression)binaryOperatorExpression;
    list = new List<AphidExpression>((IEnumerable<AphidExpression>)aphidExpressions);
    list1 = this.Mutate((AphidMutator)indexTrackingMutator, list);
    Assert.IsNotNull((object)list1);
    Assert.AreEqual<int>(4, list1.Capacity);
    Assert.AreEqual<int>(1, list1.Count);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void MutateThrowsArgumentNullException903()
{
    IndexTrackingMutator indexTrackingMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    List<AphidExpression> list;
    List<AphidExpression> list1;
    indexTrackingMutator = IndexTrackingMutatorFactory.Create((string[])null);
    binaryOperatorExpression = BinaryOperatorExpressionFactory.Create(419415914);
    AphidExpression[] aphidExpressions = new AphidExpression[1];
    aphidExpressions[0] = (AphidExpression)binaryOperatorExpression;
    list = new List<AphidExpression>((IEnumerable<AphidExpression>)aphidExpressions);
    list1 = this.Mutate((AphidMutator)indexTrackingMutator, list);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void Mutate549()
{
    IndexTrackingMutator indexTrackingMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    List<AphidExpression> list;
    List<AphidExpression> list1;
    indexTrackingMutator = IndexTrackingMutatorFactory.Create((string[])null);
    binaryOperatorExpression = BinaryOperatorExpressionFactory.Create(414658634);
    AphidExpression[] aphidExpressions = new AphidExpression[1];
    aphidExpressions[0] = (AphidExpression)binaryOperatorExpression;
    list = new List<AphidExpression>((IEnumerable<AphidExpression>)aphidExpressions);
    list1 = this.Mutate((AphidMutator)indexTrackingMutator, list);
    Assert.IsNotNull((object)list1);
    Assert.AreEqual<int>(4, list1.Capacity);
    Assert.AreEqual<int>(1, list1.Count);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void Mutate137()
{
    IndexTrackingMutator indexTrackingMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    List<AphidExpression> list;
    List<AphidExpression> list1;
    indexTrackingMutator = IndexTrackingMutatorFactory.Create((string[])null);
    binaryOperatorExpression = BinaryOperatorExpressionFactory.Create(470781440);
    BinaryOperatorExpression[] binaryOperatorExpressions
       = new BinaryOperatorExpression[1];
    binaryOperatorExpressions[0] = binaryOperatorExpression;
    list = new List<AphidExpression>
               ((IEnumerable<AphidExpression>)binaryOperatorExpressions);
    list1 = this.Mutate((AphidMutator)indexTrackingMutator, list);
    Assert.IsNotNull((object)list1);
    Assert.AreEqual<int>(4, list1.Capacity);
    Assert.AreEqual<int>(1, list1.Count);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void Mutate847()
{
    IndexTrackingMutator indexTrackingMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    List<AphidExpression> list;
    List<AphidExpression> list1;
    string[] ss = new string[1];
    indexTrackingMutator = IndexTrackingMutatorFactory.Create(ss);
    binaryOperatorExpression = BinaryOperatorExpressionFactory.Create(16818171);
    AphidExpression[] aphidExpressions = new AphidExpression[1];
    aphidExpressions[0] = (AphidExpression)binaryOperatorExpression;
    list = new List<AphidExpression>((IEnumerable<AphidExpression>)aphidExpressions);
    list1 = this.Mutate((AphidMutator)indexTrackingMutator, list);
    Assert.IsNotNull((object)list1);
    Assert.AreEqual<int>(4, list1.Capacity);
    Assert.AreEqual<int>(1, list1.Count);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException884()
{
    CallIdentifierMutator callIdentifierMutator;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    aphidExpression =
      this.MutateSingle((AphidMutator)callIdentifierMutator, (AphidExpression)null);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException298()
{
    CallIdentifierMutator callIdentifierMutator;
    ForExpression forExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    forExpression = ForExpressionFactory.Create((AphidExpressionContext)null, 
                                                (AphidExpression)null, (AphidExpression)null, 
                                                (AphidExpression)null, (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)forExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException234()
{
    CallIdentifierMutator callIdentifierMutator;
    TernaryOperatorExpression ternaryOperatorExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    ternaryOperatorExpression =
      TernaryOperatorExpressionFactory.Create((AphidExpressionContext)null, 
                                              AphidTokenType.CustomOperator011, (AphidExpression)null, 
                                              (AphidExpression)null, (AphidExpression)null, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)ternaryOperatorExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException104()
{
    CallIdentifierMutator callIdentifierMutator;
    ExtendExpression extendExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    extendExpression = ExtendExpressionFactory.Create
                           ((AphidExpressionContext)null, (IdentifierExpression)null, 
                            (ObjectExpression)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)extendExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException278()
{
    CallIdentifierMutator callIdentifierMutator;
    ForEachExpression forEachExpression;
    AphidExpression aphidExpression;
    string[] ss = new string[0];
    callIdentifierMutator = CallIdentifierMutatorFactory.Create(ss);
    forEachExpression =
      ForEachExpressionFactory.Create((AphidExpressionContext)null, 
                                      (AphidExpression)null, (List<AphidExpression>)null, 
                                      (AphidExpression)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)forEachExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException587()
{
    CallIdentifierMutator callIdentifierMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    binaryOperatorExpression = BinaryOperatorExpressionFactory.Create(0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)binaryOperatorExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle652()
{
    CallIdentifierMutator callIdentifierMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    AphidExpression aphidExpression;
    string[] ss = new string[0];
    callIdentifierMutator = CallIdentifierMutatorFactory.Create(ss);
    binaryOperatorExpression = BinaryOperatorExpressionFactory.Create(129);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)binaryOperatorExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNotNull(aphidExpression.Context);
    Assert.AreEqual<string>((string)null, aphidExpression.Context.Filename);
    Assert.AreEqual<string>((string)null, aphidExpression.Context.Code);
    Assert.AreEqual<int>(256, aphidExpression.Index);
    Assert.AreEqual<int>(68, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle583()
{
    CallIdentifierMutator callIdentifierMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    AphidExpression aphidExpression;
    string[] ss = new string[0];
    callIdentifierMutator = CallIdentifierMutatorFactory.Create(ss);
    binaryOperatorExpression = BinaryOperatorExpressionFactory.Create(0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)binaryOperatorExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNotNull(aphidExpression.Context);
    Assert.AreEqual<string>((string)null, aphidExpression.Context.Filename);
    Assert.AreEqual<string>((string)null, aphidExpression.Context.Code);
    Assert.AreEqual<int>(2, aphidExpression.Index);
    Assert.AreEqual<int>(44, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle759()
{
    CallIdentifierMutator callIdentifierMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    AphidExpression aphidExpression;
    string[] ss = new string[0];
    callIdentifierMutator = CallIdentifierMutatorFactory.Create(ss);
    binaryOperatorExpression = BinaryOperatorExpressionFactory.Create(463470139);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)binaryOperatorExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNotNull(aphidExpression.Context);
    Assert.AreEqual<string>((string)null, aphidExpression.Context.Filename);
    Assert.AreEqual<string>((string)null, aphidExpression.Context.Code);
    Assert.AreEqual<int>(6586, aphidExpression.Index);
    Assert.AreEqual<int>(137, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException563()
{
    CallIdentifierMutator callIdentifierMutator;
    SwitchExpression switchExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    switchExpression = SwitchExpressionFactory.Create((AphidExpressionContext)null, 
                                                      (AphidExpression)null, (List<SwitchCase>)null, 
                                                      (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)switchExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException895()
{
    CallIdentifierMutator callIdentifierMutator;
    GatorEmitExpression gatorEmitExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    gatorEmitExpression = GatorEmitExpressionFactory.Create
                              ((AphidExpressionContext)null, (AphidExpression)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)gatorEmitExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle53102()
{
    CallIdentifierMutator callIdentifierMutator;
    TryExpression tryExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    tryExpression = TryExpressionFactory.Create((AphidExpressionContext)null, 
                                                (List<AphidExpression>)null, (IdentifierExpression)null, 
                                                (List<AphidExpression>)null, (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)tryExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException991()
{
    CallIdentifierMutator callIdentifierMutator;
    DoWhileExpression doWhileExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    doWhileExpression = DoWhileExpressionFactory.Create
                            ((AphidExpressionContext)null, (AphidExpression)null, 
                             (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)doWhileExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException648()
{
    CallIdentifierMutator callIdentifierMutator;
    DynamicMemberExpression dynamicMemberExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    dynamicMemberExpression = DynamicMemberExpressionFactory.Create
                                  ((AphidExpressionContext)null, (AphidExpression)null, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)dynamicMemberExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException892()
{
    CallIdentifierMutator callIdentifierMutator;
    ObjectExpression objectExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    objectExpression = ObjectExpressionFactory.Create
                           ((AphidExpressionContext)null, (List<BinaryOperatorExpression>)null, 
                            (IdentifierExpression)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)objectExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException306()
{
    CallIdentifierMutator callIdentifierMutator;
    PatternExpression patternExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    patternExpression = PatternExpressionFactory.Create
                            ((AphidExpressionContext)null, (AphidExpression)null, 
                             (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)patternExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException583()
{
    CallIdentifierMutator callIdentifierMutator;
    PatternMatchingExpression patternMatchingExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    patternMatchingExpression = PatternMatchingExpressionFactory.Create
                                    ((AphidExpressionContext)null, (AphidExpression)null, 
                                     (List<PatternExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)patternMatchingExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException968()
{
    CallIdentifierMutator callIdentifierMutator;
    PartialOperatorExpression partialOperatorExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    partialOperatorExpression = PartialOperatorExpressionFactory.Create
                                    ((AphidExpressionContext)null, AphidTokenType.CustomOperator011, 
                                     (AphidExpression)null, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)partialOperatorExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException983()
{
    CallIdentifierMutator callIdentifierMutator;
    PartialFunctionExpression partialFunctionExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    partialFunctionExpression = PartialFunctionExpressionFactory.Create
                                    ((AphidExpressionContext)null, (CallExpression)null, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)partialFunctionExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException299()
{
    CallIdentifierMutator callIdentifierMutator;
    UsingExpression usingExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    usingExpression = UsingExpressionFactory.Create
                          ((AphidExpressionContext)null, (AphidExpression)null, 
                           (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)usingExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException866()
{
    CallIdentifierMutator callIdentifierMutator;
    IfExpression ifExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    ifExpression = IfExpressionFactory.Create((AphidExpressionContext)null, 
                                              (AphidExpression)null, (List<AphidExpression>)null, 
                                              (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)ifExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException482()
{
    CallIdentifierMutator callIdentifierMutator;
    LoadLibraryExpression loadLibraryExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    loadLibraryExpression = LoadLibraryExpressionFactory.Create
                                ((AphidExpressionContext)null, (AphidExpression)null, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)loadLibraryExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException992()
{
    CallIdentifierMutator callIdentifierMutator;
    UnaryOperatorExpression unaryOperatorExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    unaryOperatorExpression =
      UnaryOperatorExpressionFactory.Create((AphidExpressionContext)null, 
                                            AphidTokenType.CustomOperator011, (AphidExpression)null, false, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)unaryOperatorExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException964()
{
    CallIdentifierMutator callIdentifierMutator;
    LoadScriptExpression loadScriptExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    loadScriptExpression = LoadScriptExpressionFactory.Create
                               ((AphidExpressionContext)null, (AphidExpression)null, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)loadScriptExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException23401()
{
    CallIdentifierMutator callIdentifierMutator;
    WhileExpression whileExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    whileExpression = WhileExpressionFactory.Create
                          ((AphidExpressionContext)null, (AphidExpression)null, 
                           (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)whileExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException973()
{
    CallIdentifierMutator callIdentifierMutator;
    ArrayAccessExpression arrayAccessExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    arrayAccessExpression = ArrayAccessExpressionFactory.Create
                                ((AphidExpressionContext)null, (AphidExpression)null, 
                                 (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)arrayAccessExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle61501()
{
    CallIdentifierMutator callIdentifierMutator;
    ThisExpression thisExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    thisExpression =
      ThisExpressionFactory.Create((AphidExpressionContext)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)thisExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException405()
{
    CallIdentifierMutator callIdentifierMutator;
    BinaryOperatorBodyExpression binaryOperatorBodyExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    binaryOperatorBodyExpression = BinaryOperatorBodyExpressionFactory.Create
                                       ((AphidExpressionContext)null, AphidTokenType.CustomOperator011, 
                                        (FunctionExpression)null, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)binaryOperatorBodyExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NullReferenceException))]
public void MutateSingleThrowsNullReferenceException876()
{
    CallIdentifierMutator callIdentifierMutator;
    CallExpression callExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    callExpression = CallExpressionFactory.Create
                         ((AphidExpressionContext)null, (AphidExpression)null, 
                          (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)callExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle44001()
{
    CallIdentifierMutator callIdentifierMutator;
    TextExpression textExpression;
    AphidExpression aphidExpression;
    string[] ss = new string[0];
    callIdentifierMutator = CallIdentifierMutatorFactory.Create(ss);
    textExpression =
      TextExpressionFactory.Create((AphidExpressionContext)null, (string)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)textExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle40901()
{
    CallIdentifierMutator callIdentifierMutator;
    StringExpression stringExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    stringExpression = StringExpressionFactory.Create
                           ((AphidExpressionContext)null, (string)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)stringExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException862()
{
    CallIdentifierMutator callIdentifierMutator;
    FunctionExpression functionExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    functionExpression = FunctionExpressionFactory.Create
                             ((AphidExpressionContext)null, (List<AphidExpression>)null, 
                              (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)functionExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle53201()
{
    CallIdentifierMutator callIdentifierMutator;
    GatorOpenExpression gatorOpenExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    gatorOpenExpression =
      GatorOpenExpressionFactory.Create((AphidExpressionContext)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)gatorOpenExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException368()
{
    CallIdentifierMutator callIdentifierMutator;
    ArrayExpression arrayExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    arrayExpression = ArrayExpressionFactory.Create
                          ((AphidExpressionContext)null, (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)arrayExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle8901()
{
    CallIdentifierMutator callIdentifierMutator;
    BooleanExpression booleanExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    booleanExpression =
      BooleanExpressionFactory.Create((AphidExpressionContext)null, false, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)booleanExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle74801()
{
    CallIdentifierMutator callIdentifierMutator;
    BreakExpression breakExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    breakExpression =
      BreakExpressionFactory.Create((AphidExpressionContext)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)breakExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(NotImplementedException))]
public void MutateSingleThrowsNotImplementedException863()
{
    CallIdentifierMutator callIdentifierMutator;
    SwitchCase switchCase;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    switchCase = SwitchCaseFactory.Create
                     ((AphidExpressionContext)null, (List<AphidExpression>)null, 
                      (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)switchCase);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle61901()
{
    CallIdentifierMutator callIdentifierMutator;
    ContinueExpression continueExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    continueExpression =
      ContinueExpressionFactory.Create((AphidExpressionContext)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)continueExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle53103()
{
    CallIdentifierMutator callIdentifierMutator;
    GatorCloseExpression gatorCloseExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    gatorCloseExpression =
      GatorCloseExpressionFactory.Create((AphidExpressionContext)null, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)gatorCloseExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException221()
{
    CallIdentifierMutator callIdentifierMutator;
    LockExpression lockExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    lockExpression = LockExpressionFactory.Create
                         ((AphidExpressionContext)null, (List<AphidExpression>)null, 
                          (List<AphidExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)lockExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
[ExpectedException(typeof(ArgumentNullException))]
public void MutateSingleThrowsArgumentNullException456()
{
    CallIdentifierMutator callIdentifierMutator;
    IdentifierExpression identifierExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    identifierExpression = IdentifierExpressionFactory.Create
                               ((AphidExpressionContext)null, (string)null, 
                                (List<IdentifierExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)identifierExpression);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle93601()
{
    CallIdentifierMutator callIdentifierMutator;
    IdentifierExpression identifierExpression;
    AphidExpression aphidExpression;
    string[] ss = new string[1];
    callIdentifierMutator = CallIdentifierMutatorFactory.Create(ss);
    identifierExpression = IdentifierExpressionFactory.Create
                               ((AphidExpressionContext)null, (string)null, 
                                (List<IdentifierExpression>)null, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)identifierExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle63401()
{
    CallIdentifierMutator callIdentifierMutator;
    NullExpression nullExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    nullExpression =
      NullExpressionFactory.Create((AphidExpressionContext)null, 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)nullExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle27801()
{
    CallIdentifierMutator callIdentifierMutator;
    NumberExpression numberExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    numberExpression = NumberExpressionFactory.Create
                           ((AphidExpressionContext)null, default(decimal), 0, 0);
    aphidExpression = this.MutateSingle
                          ((AphidMutator)callIdentifierMutator, (AphidExpression)numberExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle12601()
{
    CallIdentifierMutator callIdentifierMutator;
    ImplicitArgumentExpression implicitArgumentExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    implicitArgumentExpression = ImplicitArgumentExpressionFactory.Create
                                     ((AphidExpressionContext)null, AphidTokenType.CustomOperator011, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)implicitArgumentExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle8401()
{
    CallIdentifierMutator callIdentifierMutator;
    ImplicitArgumentsExpression implicitArgumentsExpression;
    AphidExpression aphidExpression;
    callIdentifierMutator = CallIdentifierMutatorFactory.Create((string[])null);
    implicitArgumentsExpression = ImplicitArgumentsExpressionFactory.Create
                                      ((AphidExpressionContext)null, AphidTokenType.CustomOperator011, 0, 0);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)implicitArgumentsExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNull(aphidExpression.Context);
    Assert.AreEqual<int>(0, aphidExpression.Index);
    Assert.AreEqual<int>(0, aphidExpression.Length);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidMutatorTest))]
public void MutateSingle544()
{
    CallIdentifierMutator callIdentifierMutator;
    BinaryOperatorExpression binaryOperatorExpression;
    AphidExpression aphidExpression;
    string[] ss = new string[0];
    callIdentifierMutator = CallIdentifierMutatorFactory.Create(ss);
    binaryOperatorExpression = BinaryOperatorExpressionFactory.Create(2032953452);
    aphidExpression = this.MutateSingle((AphidMutator)callIdentifierMutator, 
                                        (AphidExpression)binaryOperatorExpression);
    Assert.IsNotNull((object)aphidExpression);
    Assert.IsNotNull(aphidExpression.Context);
    Assert.AreEqual<string>((string)null, aphidExpression.Context.Filename);
    Assert.AreEqual<string>((string)null, aphidExpression.Context.Code);
    Assert.AreEqual<int>(6519, aphidExpression.Index);
    Assert.AreEqual<int>(62, aphidExpression.Length);
}
    }
}
