using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Runtime.Serialization;
using Components.Aphid.TypeSystem;
// <copyright file="AphidObjectTest.GetObjectData.g.cs">Copyright © AutoSec Tools LLC 2019</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;
using Microsoft.Pex.Engine.Exceptions;

namespace Components.Aphid.TypeSystem.Tests
{
    public partial class AphidObjectTest
    {

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void GetObjectDataThrowsNullReferenceException156()
{
    object o;
    o = AphidObjectFactory.Create(632);
    this.GetObjectData
        ((AphidObject)o, (SerializationInfo)null, default(StreamingContext));
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void GetObjectDataThrowsNullReferenceException315()
{
    object o;
    o = AphidObjectFactory.Create(0);
    this.GetObjectData
        ((AphidObject)o, (SerializationInfo)null, default(StreamingContext));
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void GetObjectDataThrowsNullReferenceException31501()
{
    object o;
    o = AphidObjectFactory.Create(256);
    this.GetObjectData
        ((AphidObject)o, (SerializationInfo)null, default(StreamingContext));
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void GetObjectDataThrowsNullReferenceException31502()
{
    object o;
    o = AphidObjectFactory.Create(9);
    this.GetObjectData
        ((AphidObject)o, (SerializationInfo)null, default(StreamingContext));
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void GetObjectDataThrowsNullReferenceException15601()
{
    object o;
    o = AphidObjectFactory.Create();
    this.GetObjectData
        ((AphidObject)o, (SerializationInfo)null, default(StreamingContext));
}
    }
}
