using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using Components.Aphid.TypeSystem;
// <copyright file="AphidObjectTest.GetScopeAncestors.g.cs">Copyright © AutoSec Tools LLC 2019</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;
using Microsoft.Pex.Engine.Exceptions;

namespace Components.Aphid.TypeSystem.Tests
{
    public partial class AphidObjectTest
    {

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
public void GetScopeAncestors61401()
{
    object o;
    List<AphidObject> list;
    o = AphidObjectFactory.Create();
    list = this.GetScopeAncestors((AphidObject)o);
    Assert.IsNotNull((object)list);
    Assert.AreEqual<int>(1, list.Capacity);
    Assert.AreEqual<int>(1, list.Count);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void GetScopeAncestorsThrowsNullReferenceException465()
{
    List<AphidObject> list;
    list = this.GetScopeAncestors((AphidObject)null);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
public void GetScopeAncestors353()
{
    object o;
    List<AphidObject> list;
    o = AphidObjectFactory.Create(0);
    list = this.GetScopeAncestors((AphidObject)o);
    Assert.IsNotNull((object)list);
    Assert.AreEqual<int>(1, list.Capacity);
    Assert.AreEqual<int>(1, list.Count);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
public void GetScopeAncestors35301()
{
    object o;
    List<AphidObject> list;
    o = AphidObjectFactory.Create(359);
    list = this.GetScopeAncestors((AphidObject)o);
    Assert.IsNotNull((object)list);
    Assert.AreEqual<int>(1, list.Capacity);
    Assert.AreEqual<int>(1, list.Count);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
public void GetScopeAncestors614()
{
    object o;
    List<AphidObject> list;
    o = AphidObjectFactory.Create(1012);
    list = this.GetScopeAncestors((AphidObject)o);
    Assert.IsNotNull((object)list);
    Assert.AreEqual<int>(1, list.Capacity);
    Assert.AreEqual<int>(1, list.Count);
}
    }
}
