using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Components.Aphid.TypeSystem;
using System.Collections.Generic;
// <copyright file="AphidObjectTest.GetStringList.g.cs">Copyright © AutoSec Tools LLC 2019</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;
using Microsoft.Pex.Engine.Exceptions;

namespace Components.Aphid.TypeSystem.Tests
{
    public partial class AphidObjectTest
    {

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(ArgumentNullException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(ArgumentNullException))]
public void GetStringListThrowsArgumentNullException678()
{
    object o;
    IEnumerable<string> iEnumerable;
    o = AphidObjectFactory.Create(7);
    iEnumerable = this.GetStringList((AphidObject)o);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(ArgumentNullException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(ArgumentNullException))]
public void GetStringListThrowsArgumentNullException15()
{
    object o;
    IEnumerable<string> iEnumerable;
    o = AphidObjectFactory.Create(0);
    iEnumerable = this.GetStringList((AphidObject)o);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(ArgumentNullException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(ArgumentNullException))]
public void GetStringListThrowsArgumentNullException1501()
{
    object o;
    IEnumerable<string> iEnumerable;
    o = AphidObjectFactory.Create(679);
    iEnumerable = this.GetStringList((AphidObject)o);
}

[TestMethod]
[PexGeneratedBy(typeof(AphidObjectTest))]
[PexRaisedException(typeof(ArgumentNullException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(ArgumentNullException))]
public void GetStringListThrowsArgumentNullException67801()
{
    object o;
    IEnumerable<string> iEnumerable;
    o = AphidObjectFactory.Create();
    iEnumerable = this.GetStringList((AphidObject)o);
}
    }
}
