using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace Components.Aphid.Lexer.Tests
{
    public partial class TokenHelperTest
    {

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest794()
{
    int i;
    i = this.GetIndexTest((string)null, 0, 0);
    Assert.AreEqual<int>(0, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
[ExpectedException(typeof(NullReferenceException))]
public void GetIndexTestThrowsNullReferenceException354()
{
    int i;
    i = this.GetIndexTest((string)null, 1, 0);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest51()
{
    int i;
    i = this.GetIndexTest("", 1, 0);
    Assert.AreEqual<int>(-1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest667()
{
    int i;
    i = this.GetIndexTest("\0", 1, 0);
    Assert.AreEqual<int>(-1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest878()
{
    int i;
    i = this.GetIndexTest("\n", 1, 0);
    Assert.AreEqual<int>(1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest697()
{
    int i;
    i = this.GetIndexTest("\n", 2, 0);
    Assert.AreEqual<int>(-1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest774()
{
    int i;
    i = this.GetIndexTest("\n\0", 2, 0);
    Assert.AreEqual<int>(-1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest562()
{
    int i;
    i = this.GetIndexTest("\n\n", 2, 0);
    Assert.AreEqual<int>(2, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest906()
{
    int i;
    i = this.GetIndexTest("\n\n", 3, 0);
    Assert.AreEqual<int>(-1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest340()
{
    int i;
    i = this.GetIndexTest("\0\0", 1, 0);
    Assert.AreEqual<int>(-1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest624()
{
    int i;
    i = this.GetIndexTest("\0\r\r", 1, 0);
    Assert.AreEqual<int>(2, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest841()
{
    int i;
    i = this.GetIndexTest("\0\r\r", 2, 0);
    Assert.AreEqual<int>(3, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest202()
{
    int i;
    i = this.GetIndexTest("\0\r\n", 1, 0);
    Assert.AreEqual<int>(3, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest35()
{
    int i;
    i = this.GetIndexTest("\0\r\n", 2, 0);
    Assert.AreEqual<int>(-1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest876()
{
    int i;
    i = this.GetIndexTest("\0\r\0", 1, 0);
    Assert.AreEqual<int>(-1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest736()
{
    int i;
    i = this.GetIndexTest("\0\r\r", 3, 0);
    Assert.AreEqual<int>(-1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest240()
{
    int i;
    i = this.GetIndexTest("\0\r\0\r", 1, 0);
    Assert.AreEqual<int>(-1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest989()
{
    int i;
    i = this.GetIndexTest("\0\r\0\r\r", 1, 0);
    Assert.AreEqual<int>(4, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest515()
{
    int i;
    i = this.GetIndexTest("\0\r\0\r\0", 1, 0);
    Assert.AreEqual<int>(-1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest862()
{
    int i;
    i = this.GetIndexTest("\0\r\r\r", 3, 0);
    Assert.AreEqual<int>(3, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest778()
{
    int i;
    i = this.GetIndexTest("\0\r\r\r", 6, 0);
    Assert.AreEqual<int>(-1, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest504()
{
    int i;
    i = this.GetIndexTest("\0\r\0\r\0\r\n\r\n", 2, 0);
    Assert.AreEqual<int>(9, i);
}

[TestMethod]
[PexGeneratedBy(typeof(TokenHelperTest))]
public void GetIndexTest721()
{
    int i;
    i = this.GetIndexTest("\0\r\0\r\0\r\n\r\n", 3, 0);
    Assert.AreEqual<int>(-1, i);
}
    }
}
