using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Threading;
using Components.Aphid.Interpreter;
using Components.Aphid.TypeSystem;
// <copyright file="TypeExtenderTest.Extend01.g.cs">Copyright © AutoSec Tools LLC 2019</copyright>
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;
using Microsoft.Pex.Engine.Exceptions;

namespace Components.Aphid.TypeSystem.Tests
{
    public partial class TypeExtenderTest
    {

[TestMethod]
[PexGeneratedBy(typeof(TypeExtenderTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void Extend01ThrowsNullReferenceException410()
{
    TypeExtender typeExtender;
    typeExtender =
      new TypeExtender((AphidInterpreter)null, (ReaderWriterLockSlim)null);
    this.Extend01
        (typeExtender, (string)null, (AphidObject)null, (string)null, (string)null);
}

[TestMethod]
[PexGeneratedBy(typeof(TypeExtenderTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void Extend01ThrowsNullReferenceException15()
{
    TypeExtender typeExtender;
    typeExtender =
      new TypeExtender((AphidInterpreter)null, (ReaderWriterLockSlim)null);
    this.Extend01(typeExtender, "", (AphidObject)null, (string)null, (string)null);
}

[TestMethod]
[PexGeneratedBy(typeof(TypeExtenderTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void Extend01ThrowsNullReferenceException111()
{
    TypeExtender typeExtender;
    typeExtender =
      new TypeExtender((AphidInterpreter)null, (ReaderWriterLockSlim)null);
    this.Extend01(typeExtender, "\0", (AphidObject)null, (string)null, (string)null);
}

[TestMethod]
[PexGeneratedBy(typeof(TypeExtenderTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void Extend01ThrowsNullReferenceException141()
{
    TypeExtender typeExtender;
    typeExtender =
      new TypeExtender((AphidInterpreter)null, (ReaderWriterLockSlim)null);
    this.Extend01(typeExtender, "됡", (AphidObject)null, (string)null, (string)null);
}

[TestMethod]
[PexGeneratedBy(typeof(TypeExtenderTest))]
[PexRaisedException(typeof(NullReferenceException), Microsoft.Pex.Engine.Exceptions.PexExceptionState.Expected), ExpectedException(typeof(NullReferenceException))]
public void Extend01ThrowsNullReferenceException93()
{
    TypeExtender typeExtender;
    typeExtender =
      new TypeExtender((AphidInterpreter)null, (ReaderWriterLockSlim)null);
    this.Extend01(typeExtender, "C", (AphidObject)null, (string)null, (string)null);
}
    }
}
