Aphid Programming Language: c:/source/Aphid/Components.Aphid/Compiler/Medusa/LLex/Resources/AddTokenTemplate.cs File Reference
AddTokenTemplate.cs File Reference
Functions
tokens. Add (new {Token}(tokenType, lexeme, index))
Variables
var index = lastIndex + 1
var lexeme = text.Substring(index, charIndex - lastIndex)
Function Documentation
Add()
tokens. Add (new {Token} tokenType, lexeme, index)
Variable Documentation
index
var index = lastIndex + 1
Definition at line 1 of file AddTokenTemplate.cs.
Referenced by Components.Aphid.Lexer.AphidToken.AphidToken(), Components.Json.JsonLexer.GetAllTokens(), Components.Aphid.Serialization.AphidObjectLexer.GetAllTokens(), Components.Aphid.Lexer.AphidLexer.GetAllTokens(), Components.Aphid.Lexer.TokenHelper.GetBraces(), Components.Aphid.Lexer.TokenHelper.GetCodeExcerpt(), Components.Aphid.VSPackage.AphidDeclarations.GetDescription(), Components.Aphid.VSPackage.AphidDeclarations.GetDisplayText(), Components.Aphid.VSPackage.AphidDeclarations.GetGlyph(), Components.Aphid.Lexer.TokenHelper.GetIndexPosition(), Components.Cypress.StringTable.GetKey(), Components.Aphid.VSPackage.AphidDeclarations.GetName(), Components.Aphid.Lexer.AphidLexer.GetToken(), LLex.RegexLexer.GetTokens(), Components.Json.JsonLexer.GetTokens(), Components.Aphid.Serialization.AphidObjectLexer.GetTokens(), Components.Aphid.Lexer.AphidLexer.GetTokens(), Components.Json.JsonToken.JsonToken(), Components.Aphid.VSPackage.AphidLanguageService.ParseSource(), LLex.RegexToken.RegexToken(), Components.External.ConsolePlus.ScannerToken.ScannerToken(), and Components.Aphid.Parser.AphidParser.SetToken().
lexeme
var lexeme = text.Substring(index, charIndex - lastIndex)
Definition at line 2 of file AddTokenTemplate.cs.
Referenced by LLex.TokenTable.Add(), LLex.TokenTable.AddLexemeCode(), Components.Aphid.Lexer.AphidToken.AphidToken(), Components.ArgToken.ArgToken(), Components.Json.JsonLexer.GetAllTokens(), Components.Aphid.Serialization.AphidObjectLexer.GetAllTokens(), Components.Aphid.Lexer.AphidLexer.GetAllTokens(), Components.Aphid.Lexer.AphidLexer.GetToken(), LLex.RegexLexer.GetTokens(), Components.Json.JsonLexer.GetTokens(), Components.Aphid.Serialization.AphidObjectLexer.GetTokens(), Components.Aphid.Lexer.AphidLexer.GetTokens(), LLex.LLexFile.Interpret(), Components.Json.JsonToken.JsonToken(), LLex.RegexToken.RegexToken(), Components.External.ConsolePlus.ScannerToken.ScannerToken(), Components.Aphid.Tests.Integration.Shared.AphidTests.Token(), and LLex.TokenEntry.TokenEntry().