Aphid Programming Language: c:/source/Aphid/Boxelder/HelloWorld.alx File Reference
HelloWorld.alx File Reference
Functions
items first (@(x) x > 100)|> print
items all (@(x) x > -1)|> print
items all (@(x) x > 10)|> print
items take (4)|> print
items skip (4)|> @take(4)|> print
items concat ([111, 222])|> print
x (0x10<< 4)|> print
Variables
items
items print
f = @(x) { items |> x |> print; }
Function Documentation
all() [1/2]
items all (@(x) x, - 1)
all() [2/2]
items all (@(x) x, 10)
concat()
items concat ()
first()
items first (@(x) x, 100)
skip()
items skip (4)
take()
items take (4)
x()
x (0x10<< 4)
Variable Documentation
f
f = @(x) { items |> x |> print; }
Definition at line 11 of file HelloWorld.alx.
Referenced by Components.Aphid.Debugging.AphidMemoryDump::Create(), Components.Aphid.Interpreter.AphidLoader::FindScriptFile(), Components.Aphid.Library.Net.HttpLibrary::HttpRequest(), if(), Components.Aphid.Interpreter.AphidLoader::LoadScript(), Components.Aphid.Library.Net.Http.HttpMessagePart::ParseFields(), Components.Cypress.NativeFunction::Serialize(), Components.External.ConsolePlus.CliArgReader::SetProperties(), and Components.Aphid.Interpreter.ExceptionHelper::StackTrace().
items
items
Initial value:
=
    range(0, 100)
    |> @where(@(x) x < 10 || x > 50)
    |> @select(@(x) x * 2)
    |> @selectMany(@(x) [ x, x * x ])
Definition at line 3 of file HelloWorld.alx.
Referenced by Components.Aphid.TypeSystem.AphidObject::ConvertFrom(), and Components.Aphid.Compiler.AphidStringEmitter::EmitTuple().
print
add print
Definition at line 9 of file HelloWorld.alx.