Aphid Programming Language: c:/source/Aphid/Components.Aphid/Library/DebugDeploy.alx File Reference
DebugDeploy.alx File Reference
Functions
if (aphidSource defined) dir
dir _print ('Script dir:~Green~{0}~R~')
if (dv > 1)
if (libDirTmp \ 'Std.alx'|> File.Exists)
while ((dir=dir.Parent) !=null)
if (libDir==null)
_print ('Found lib dir:~Green~{0}~R~', libDir)
_print ('[~Green~+~R~] Updating standard headers')
Directory GetFiles (libDir, ' *.alx') -> @(src)
_print ()
Variables
var dv = deployVerbosity defined ? deployVerbosity : 1
var _print = dv != 0 ? print : @{}
var scriptDir = (new FileInfo(Assembly.GetExecutingAssembly().Location)).Directory
var dir = scriptDir
var libDir
var libDirTmp
do
Function Documentation
_print() [1/4]
dir _print ('Script dir:~Green~{0}~R~')
_print() [2/4]
_print ('Found lib dir:~Green~{0}~R~' , libDir)
_print() [3/4]
_print (' Updating standard headers' [~Green~+~R~])
_print() [4/4]
_print ()
GetFiles()
Directory GetFiles (libDir, ' *.alx') -> @ (src)
Definition at line 42 of file DebugDeploy.alx.
References _print, dv, Path, and scriptDir.
Referenced by Components.Aphid.Library.Net.Http.AphidRequest::OnBound().
{
         var srcFilename = src |> Path.GetFileName;
         var dst = scriptDir.FullName \ 'Library' \ srcFilename;
         if (dv > 1) {
             _print('Copying ~Cyan~{0}~R~ to ~Cyan~{1}~R~', src, dst);
         } else if (dv == 1) {
             _print('Copying ~Cyan~{0}~R~', srcFilename);
         }
         File.Copy(src, dst, true);
     };
if() [1/4]
if (aphidSource defined)
if() [2/4]
if (dv, 1)
Definition at line 24 of file DebugDeploy.alx.
References _print, and libDirTmp.
                     {
             libDirTmp @_print('Checking dir: ~Cyan~{0}~R~');
         }
if() [3/4]
if (libDirTmp \ 'Std.alx'|, File. Exists)
Definition at line 28 of file DebugDeploy.alx.
References libDir, and libDirTmp.
{
             libDir = libDirTmp;
         }
if() [4/4]
if (libDir = = null)
Definition at line 34 of file DebugDeploy.alx.
References _print, and exit.
{
         _print('~Yellow~Could not find library dir~R~');
         exit(0);
     }
while()
while ((dir=dir.Parent) ! = null)
Definition at line 33 of file TestLoop.alx.
References args, exe, p, print(), si, and w.
              {
     var si = new ProcessStartInfo(exe, args[0]);
     si.UseShellExecute = false;
     var p = Process.Start(si);
     p.WaitForExit();
     print('Process has exited with code ~Cyan~{0}~R~', p.ExitCode);
     w.WaitForChanged(WatcherChangeTypes.All).Name @print("'{0}' changed");
 }
Variable Documentation
_print
_print = dv != 0 ? print : @{}
Definition at line 9 of file DebugDeploy.alx.
Referenced by GetFiles(), and if().
dir
var dir = scriptDir
Definition at line 12 of file DebugDeploy.alx.
do
do
Initial value:
{
        libDirTmp = dir.FullName \ 'Components.Aphid' \ 'Library'
Definition at line 21 of file DebugDeploy.alx.
dv
var dv = deployVerbosity defined ? deployVerbosity : 1
Definition at line 7 of file DebugDeploy.alx.
Referenced by GetFiles().
libDir
var libDir
Definition at line 17 of file DebugDeploy.alx.
Referenced by if().
libDirTmp
var libDirTmp
Definition at line 18 of file DebugDeploy.alx.
Referenced by if().
scriptDir
var scriptDir = (new FileInfo(Assembly.GetExecutingAssembly().Location)).Directory
Definition at line 11 of file DebugDeploy.alx.
Referenced by GetFiles().