Aphid Programming Language: c:/source/Aphid/Aphid/Samples/ILExample.alx File Reference
ILExample.alx File Reference
Functions
print ('Creating module')
if (asmName|> File.Exists)
$_ Emit (OpCodes.Call, Console.GetMethod('WriteLine', [String]))
$_ Emit (OpCodes.Ret)
createProgram (asmName)
si Process Start () $_.WaitForExit()
Variables
var asmName = 'foo.exe'
var si = new ProcessStartInfo(asmName)
si UseShellExecute = false
Function Documentation
createProgram()
createProgram (asmName)
Emit() [1/2]
$_ Emit (OpCodes. Call, Console. GetMethod 'WriteLine', [String])
Referenced by Components.Aphid.Compiler.AphidStringEmitter::Compile(), Components.Aphid.Compiler.AphidStringEmitter::Emit(), Components.Aphid.Compiler.AphidStringEmitter::EmitArrayAccessExpression(), Components.Aphid.Compiler.AphidStringEmitter::EmitBinaryOperatorExpression(), Components.Aphid.Compiler.AphidStringEmitter::EmitCallExpression(), Components.Aphid.Compiler.AphidStringEmitter::EmitTuple(), and Components.Aphid.Compiler.AphidStringEmitter::EmitUnaryOperatorExpression().
Emit() [2/2]
$_ Emit (OpCodes. Ret)
if()
if (asmName|, File. Exists)
Definition at line 9 of file ILExample.alx.
References asmName, and print().
Referenced by Components.Aphid.Interpreter.AphidInterpreter::CallStaticInteropFunction(), Components.Aphid.UI.AphidScopeObjectAutocompletionSource::GetWords(), Components.Cypress.BreakpointManager::HandleException(), and AphidHdl.ForUnrollMutator::MutateCore().
{
     print('Removing old assembly');
     asmName |> File.Delete;
 }
print()
print ('Creating module')
Referenced by if().
Start()
si Process Start ()
Referenced by Components.Aphid.Library.ThreadingLibrary::StartThread().
Variable Documentation
asmName
var asmName = 'foo.exe'
Definition at line 7 of file ILExample.alx.
Referenced by if().
si
var si = new ProcessStartInfo(asmName)
Definition at line 26 of file ILExample.alx.
Referenced by Components.Cypress.NativeDebugger::StartProcess(), and while().
UseShellExecute
si UseShellExecute = false
Definition at line 27 of file ILExample.alx.