Aphid Programming Language: c:/source/Aphid/Components.Aphid/Tools/ILMerge.alx File Reference
ILMerge.alx File Reference
Functions
cls ()
head ('Merging .NET Program')
Process GetProcessesByName ($_) -> @()
if (ilmergeExe==null)
print ('~Cyan~Asms:~R~ {0}', asmList)
File WriteAllText ('c:\\temp\\log.txt', '')
var Path GetExtension (outExe).Substring(1)
var Path asms (@() $_.Contains('\\') ? $_ :Path.Combine(systemPath, $_)) ->(@() '"
::$_ join (' ')]
args print ('Starting ilmerge.exe with args ~Magenta~{0}~R~')
p WaitForExit ()
Process Start ('c:\\temp\\log.txt')
new FileInfo ('AphidPortable.exe') @.Length @print('Asm size
Variables
_facade
var asms = [] !?
var flags = '/ndebug /zeroPeKind'
var getILMerge
var ilmergeExe = getILMerge()
else
var outExe = 'AphidPortable.exe'
var asmList = asms ->(@() '"{0}"' :: $_) !?
var libPaths = (asms->Path.GetDirectoryName!?->@() '/lib:"{0}"' :: $_) @join(' ')
var systemPath = 'C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6'
var args
var C
var si = new ProcessStartInfo(ilmergeExe, args)
si UseShellExecute = false
var p = Process.Start(si)
var failure
~R
Function Documentation
asms()
var Path asms (@) $_.Contains('\\') ? $_ :Path.Combine(systemPath, $_) -> (@() '"
Definition at line 77 of file ILMerge.alx.
                                           : Path.Combine(systemPath, $_))
             ->(@() '"{0}"' :: $_)
cls()
cls ()
FileInfo()
new FileInfo ('AphidPortable.exe')
Definition at line 108 of file ILMerge.alx.
Referenced by Components.External.PathHelper::GetEntryDirectory(), and Components.External.ConsolePlus.CliArgReader::SetProperties().
 : ~Cyan~{0:n0}~R~');
GetExtension()
var Path GetExtension (outExe)
GetProcessesByName()
Process GetProcessesByName ($_) -> @()
Definition at line 12 of file ILMerge.alx.
References $_.
 { $_.Kill(); $_.WaitForExit() };
head()
head ('Merging .NET Program')
if()
if (ilmergeExe = = null)
Definition at line 29 of file ILMerge.alx.
References fatal, getILMerge, ilmergeExe, and print().
{
     print('Loading NuGet.Core');
     if (load NuGet.Core == null) {
         fatal('Failed loading Nuget.Core');
     }
     using NuGet;
     print('Connecting to repository');
     var repo = PackageRepositoryFactory.Default.CreateRepository("https://packages.nuget.org/api/v2");
     var packageManager = new PackageManager(repo, '.\\');
     print('Installing package ILMerge');
     packageManager.InstallPackage('ILMerge');
     ilmergeExe = getILMerge();
     if (ilmergeExe == null) {
         fatal('Could not find ilmerge.exe');
     }
     :> 'ILMerge installed';
 } else {
join()
:: $_ join (' ')
print() [1/2]
print ('~Cyan~Asms:~R~ {0}' , asmList)
Referenced by if().
print() [2/2]
args print ('Starting ilmerge.exe with args ~Magenta~{0}~R~')
Start()
Process Start ('c:\\temp\\log.txt')
WaitForExit()
p WaitForExit ()
Referenced by Components.Aphid.Library.ExecOptions::ExecOptions().
WriteAllText()
File WriteAllText ('c:\\temp\\log.txt' , '')
Variable Documentation
_facade
_facade
Initial value:
= macro(@(f) {
    'C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.5\\Facades\\' + f
})
Definition at line 14 of file ILMerge.alx.
args
var args
Initial value:
=
    '/out:{0} Aphid.exe /target:{1} {2} /targetplatform:v4.5
Definition at line 70 of file ILMerge.alx.
asmList
var asmList = asms ->(@() '"{0}"' :: $_) !?
Definition at line 58 of file ILMerge.alx.
asms
var asms = [] !?
Definition at line 19 of file ILMerge.alx.
Referenced by Components.TypeLoader::ResolveFullType(), and Components.TypeLoader::TryGetAssemblies().
C
var C
Definition at line 70 of file ILMerge.alx.
else
else
Initial value:
{
    :> 'ILMerge already installed'
Definition at line 51 of file ILMerge.alx.
failure
var failure
Initial value:
=
    'c:\\temp\\log.txt'
    |> File.ReadAllText
    @()
        $_.Contains('was not merged in correctly. It is still listed as an external reference in the target assembly') ||
        $_.Contains('Duplicate assembly name ') ||
        $_.Contains('ILMerge.Merge: ERROR')
Definition at line 91 of file ILMerge.alx.
flags
var Path flags = '/ndebug /zeroPeKind'
Definition at line 21 of file ILMerge.alx.
Referenced by Components.Cypress.ThreadContext::GetContext(), and Components.PInvoke.KeyboardHook::ToString().
getILMerge
var getILMerge
Initial value:
= @() Directory
    .GetFiles('.\\', 'ilmerge.exe', SearchOption.AllDirectories)
    |> Enumerable.FirstOrDefault
Definition at line 23 of file ILMerge.alx.
Referenced by if().
ilmergeExe
var ilmergeExe = getILMerge()
Definition at line 27 of file ILMerge.alx.
Referenced by if().
libPaths
var Path libPaths = (asms->Path.GetDirectoryName!?->@() '/lib:"{0}"' :: $_) @join(' ')
Definition at line 63 of file ILMerge.alx.
outExe
var outExe = 'AphidPortable.exe'
Definition at line 55 of file ILMerge.alx.
p
var p = Process.Start(si)
Definition at line 86 of file ILMerge.alx.
si
var si = new ProcessStartInfo(ilmergeExe, args)
Definition at line 84 of file ILMerge.alx.
systemPath
var systemPath = 'C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.6'
Definition at line 66 of file ILMerge.alx.
UseShellExecute
si UseShellExecute = false
Definition at line 85 of file ILMerge.alx.
~R
~R
Definition at line 108 of file ILMerge.alx.