Aphid Programming Language: c:/source/Aphid/Aphid/Samples/InteropExample.alx File Reference
InteropExample.alx File Reference
Functions
print ("hello, world")
print ("Tokens")
for (x in tokens) print(x)
for (node in ast) printf("Type
intepreter Interpret (ast)
Variables
var code
var lexer = new AphidLexer(code)
var tokens = lexer.GetTokens()
var ast = AphidParser.Parse(tokens, code)
node Type
var intepreter = new AphidInterpreter(true)
Function Documentation
for() [1/2]
for (x in tokens)
Definition at line 129 of file Aphid.Tokens.alx.
References addToken, tokenChars, x, and y.
                       {
     for (y in tokenChars) {
         addToken(x + y |> regexEscape);
     }
     addToken(x |> regexEscape);
 }
for() [2/2]
for (node in ast)
Definition at line 22 of file InteropExample.alx.
                 : {0}", node.Type);
Interpret()
intepreter Interpret (ast)
Referenced by Components.Aphid.Interpreter.AphidInterpreter::Interpret(), and Components.Aphid.Interpreter.AphidInterpreter::InterpretFile().
print() [1/2]
print (" hello, world")
print() [2/2]
print ("Tokens")
Variable Documentation
ast
var ast = AphidParser.Parse(tokens, code)
Definition at line 18 of file InteropExample.alx.
Referenced by Boxelder.LambdaPositionMutator::BeginRecursiveMutationPass(), Boxelder.AphidPythonEmitter::Compile(), Coywolf.AphidPhpEmitter::Compile(), Components.Aphid.Compiler.AphidStringEmitter::Compile(), Components.Aphid.Serialization.AphidSerializer::Deserialize(), AphidHdl.AphidVerilogEmitter::Emit(), Boxelder.LambdaPositionMutator::EndRecursiveMutationPass(), Components.Aphid.Parser.AphidCodeVisitor::EndVisit(), Components.Aphid.Serialization.AphidObjectReferenceVisitor::FindReferenceAssignments(), Boxelder.AphidTreeHelper::FirstOrDefaultPath(), LLex.AlxFile::From(), LLex.LLexFile::Interpret(), Components.Aphid.Interpreter.AphidInterpreter::InterpretStream(), Components.Aphid.Interpreter.AphidLoader::LoadScript(), Components.Aphid.Parser.AphidMutator::Mutate(), Components.Aphid.Parser.AphidMutatorGroup::MutateRecursively(), Components.Aphid.Parser.AphidMutator::MutateRecursively(), Components.Aphid.Parser.AphidMacroMutator::OnMutate(), Components.Aphid.Parser.AphidMutator::OnMutate(), Components.Aphid.Interpreter.AphidScriptOptimizer::Optimize(), Components.Aphid.Parser.AphidMacro::Parse(), Components.Aphid.Parser.AphidParser::Parse(), Components.Aphid.Parser.AphidParser::ParseExpression(), and Components.Aphid.Parser.AphidVisitor::Visit().
code
var code
Initial value:
=
    '#"Std"
Definition at line 6 of file InteropExample.alx.
Referenced by LLex.TokenTable::AddCode(), LLex.TokenTable::AddLexemeCode(), Components.Aphid.Parser.AphidCodeVisitor::AphidCodeVisitor(), AphidUI.CodeViewer::AppendCode(), AphidUI.CodeViewer::AppendException(), AphidUI.CodeViewer::AppendOutput(), AphidUI.CodeViewer::AppendParserException(), Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute >::BuildType(), Components.Aphid.Parser.ParserErrorMessage::Create(), Components.Aphid.UI.AphidCli::DumpException(), Components.Aphid.UI.AphidCli::DumpExpression(), Components.Aphid.UI.AphidCli::ExecuteCode(), Mantispid.ParserGenerator::Generate(), AphidUI.KeyHelper::GetCharFromKey(), Components.Aphid.Lexer.TokenHelper::GetCodeExcerpt(), Components.Aphid.UI.AphidCli::GetErrorMessage(), Components.Aphid.UI.AphidCli::Highlight(), LLex.LLexFile::Interpret(), Components.Aphid.Interpreter.AphidInterpreter::Interpret(), Components.Aphid.Interpreter.AphidInterpreter::InterpretFile(), Components.Aphid.Interpreter.AphidInterpreter::InterpretStream(), Components.Aphid.Parser.IncludeMutator::MutateCore(), Components.Aphid.Parser.AphidParser::Parse(), Components.Aphid.Parser.AphidParser::ParseExpression(), Components.Aphid.UI.AphidRepl::Run(), AphidUI.CodeViewer::SetCode(), LLex.TokenEntry::TokenEntry(), and Components.Aphid.UI.AphidCli::TryAction().
intepreter
var intepreter = new AphidInterpreter(true)
Definition at line 27 of file InteropExample.alx.
lexer
var lexer = new AphidLexer(code)
Definition at line 10 of file InteropExample.alx.
Referenced by Components.Aphid.Serialization.AphidSerializer::Deserialize(), Components.Aphid.UI.AphidCli::DumpExpression(), LLex.AlxFile::From(), Mantispid.ParserGenerator::Generate(), Components.Aphid.Lexer.AphidLexer::GetToken(), Components.Aphid.Lexer.AphidLexer::GetTokenType(), LLex.LLexFile::Interpret(), AphidUI.Internal.CodeCanvas::OnRender(), Components.Aphid.Parser.AphidParser::Parse(), and Components.Aphid.VSPackage.AphidScanner::SetSource().
tokens
var tokens = lexer.GetTokens()
Definition at line 11 of file InteropExample.alx.
Referenced by Components.Aphid.Parser.AphidParser::AphidParser(), AphidUI.CodeViewer::AppendCode(), Components.Aphid.Tests.Integration.Shared.AphidTests::AssertTokens(), Components.Aphid.Serialization.AphidSerializer::Deserialize(), Components.Aphid.UI.AphidCli::DumpExpression(), Components.Json.JsonFormatter::Format(), LLex.AlxFile::From(), Components.Json.JsonLexer::GetAllTokens(), Components.Aphid.Serialization.AphidObjectLexer::GetAllTokens(), Components.Aphid.Lexer.AphidLexer::GetAllTokens(), Components.Aphid.Lexer.TokenHelper::GetBraces(), LLex.RegexLexer::GetTokens(), Components.Json.JsonLexer::GetTokens(), Components.Aphid.Serialization.AphidObjectLexer::GetTokens(), Components.Aphid.Lexer.AphidLexer::GetTokens(), Components.Aphid.UI.AphidScopeObjectAutocompletionSource::GetWords(), LLex.LexerGenerator::GroupTokens(), LLex.LLexFile::Interpret(), Components.Json.JsonFormatter::MakeCompliant(), Components.Aphid.Parser.AphidParser::Parse(), Components.Aphid.Parser.AphidParser::ParseExpression(), Components.Aphid.VSPackage.AphidLanguageService::ParseSource(), and LLex.RegexParser::RegexParser().
Type
node Type
Definition at line 23 of file InteropExample.alx.
Referenced by Components.Aphid.Parser.AphidParserException::AphidParserException(), Components.Aphid.TypeSystem.OperatorHelper::BinaryAnd(), Components.Aphid.TypeSystem.OperatorHelper::BinaryOr(), Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute >::BuildType(), Components.Aphid.TypeSystem.AphidTypeConverter::CanConvert(), Components.Aphid.TypeSystem.AphidTypeConverter::Convert(), Components.Aphid.TypeSystem.AphidFunctionConverter::ConvertFunctionWrapper(), Components.Aphid.Compiler.AphidAssemblyBuilder::CreateType(), Components.Aphid.Interpreter.AphidInterpreter::GetIpcContextType(), Components.Aphid.TypeSystem.AphidType::GetName(), Components.Aphid.TypeSystem.AphidObject::GetValueType(), Components.External.TypeExtension::IsDerivedFrom< TBaseType >(), Components.External.TypeExtension::IsDerivedFromOrImplements< TBaseType >(), Components.Aphid.Parser.AphidNode::IsStatement(), Components.TypeLoader::ResolveFullType(), Components.Aphid.TypeSystem.InteropTypeResolver::ResolveType(), Components.External.ConsolePlus.ScannerToken::ScannerToken(), Components.Aphid.TypeSystem.InteropMethodResolver::TryResolveStaticMember(), and Components.Aphid.TypeSystem.InteropTypeResolver::TryResolveType().