Aphid Programming Language: c:/source/Aphid/Components.Aphid/Library/ParseBinaryPerformanceTrace.alx File Reference
ParseBinaryPerformanceTrace.alx File Reference
Classes
class FrameProfile
Functions
Console Clear ()
print (profileHeader)
while (reader.BaseStream.Position< reader.BaseStream.Length)
frames orderByDescending ($_[1]).take(100) -> @() print('Name:
Ticks Ticks $_ Name Replace ('\r', '').Replace('\n'
print ()
reader Dispose ()
Variables
var dumpFrameJson
var dumpFrame
var trace = 'C:\\source\\Aphid\\Aphid\\bin\\Debug\\AphidFramePerformance.ac063cef-bf19-4ee2-a5a3-1786653a79ed.dat'
var reader = new BinaryReader(trace |> File.OpenRead)
var profileHeader = reader.ReadString()
var threadStacks = {}
var root = new ArrayList()
var parsed = 0
var frames = []
var frameTotals = {}
Ticks __pad0__
Ticks Ticks Exlusive
Ticks Ticks $_ Name n
Ticks Ticks $_ Name $_ Ticks
Ticks Ticks $_ Name $_ $_ TicksExclusive
Function Documentation
Clear()
Console Clear ()
Dispose()
reader Dispose ()
orderByDescending()
frames orderByDescending ($_[1]) -> @() print('Name:
Definition at line 129 of file ParseBinaryPerformanceTrace.alx.
                  : {0}, Ticks: {1:n0}, Ticks Exlusive: {2:n0}',
print() [1/2]
print (profileHeader)
print() [2/2]
print ()
Replace()
Ticks Ticks $_ Name Replace ('\r', '')
Referenced by Components.External.ConsolePlus.Cli::CreateTable().
while()
while ()
Definition at line 58 of file ParseBinaryPerformanceTrace.alx.
References reader, and threadStacks.
{
     var id = reader.ReadInt32();
     var stack;
     if (!(threadStacks.{id} defined)) {
         stack = new Stack();
         threadStacks.{id} = stack;
     } else {
         stack = threadStacks.{id};
     }
     var enter = reader.ReadBoolean();
     var name = reader.ReadString();
     if (enter) {
         var frame = new FrameProfile();
         frame.ThreadId = id;
         frame.Name = name;
         frame.ChildFrames = new ArrayList();
         if (stack.Count > 0) {
             stack.Peek().ChildFrames.Add(frame);
         } else {
             root.Add(frame);
         }
         stack.Push(frame);
         frames.add(frame);
         // frame.Name |> Cli.StyleEscape |> print;
     } else {
         var curFrame = stack.Pop();
         curFrame.Ticks = reader.ReadInt64();
         curFrame.Milliseconds = reader.ReadInt64();
         var arr = curFrame.ChildFrames.ToArray();
         if (arr.Length == 0) {
             curFrame.TicksExclusive = curFrame.Ticks;
             curFrame.MillisecondsExclusive = curFrame.Milliseconds;
         } else {
             _exclusive = macro(@(n) { curFrame.n - (arr->@.n+>@(x, y) x + y) });
             curFrame.TicksExclusive = _exclusive(Ticks);
             curFrame.MillisecondsExclusive = _exclusive(Milliseconds);
         }
         // if (frameTotals.{curFrame.Name} defined) {
         //  var t = frameTotals.{curFrame.Name};
         //  t.Ticks += curFrame.Ticks;
         //  t.TicksExclusive += curFrame.TicksExclusive;
         //  t.Milliseconds += curFrame.Milliseconds;
         //  t.Milliseconds += curFrame.MillisecondsExclusive;
         // } else {
         //  var t = new FrameProfile();
         //  t.Name = curFrame.Name;
         //  t.Ticks = curFrame.Ticks;
         //  t.TicksExclusive = curFrame.TicksExclusive;
         //  t.Milliseconds = curFrame.Milliseconds;
         //  t.Milliseconds = curFrame.MillisecondsExclusive;
         //  frameTotals.{curFrame.Name} = t;
         // }
     }
     // if (++parsed > 1009) {
     //  break;
     // }
 }
Variable Documentation
__pad0__
Ticks __pad0__
Definition at line 131 of file ParseBinaryPerformanceTrace.alx.
dumpFrame
var dumpFrame
Initial value:
= @{
    $_ |> toJson |> Cli.StyleEscape |> print;
}
Definition at line 38 of file ParseBinaryPerformanceTrace.alx.
dumpFrameJson
var dumpFrameJson
Initial value:
= @{
    $_ |> toJson |> Cli.StyleEscape |> print;
}
Definition at line 33 of file ParseBinaryPerformanceTrace.alx.
Exlusive
Ticks Ticks Exlusive
Definition at line 131 of file ParseBinaryPerformanceTrace.alx.
frames
var frames = []
Definition at line 55 of file ParseBinaryPerformanceTrace.alx.
frameTotals
var frameTotals = {}
Definition at line 56 of file ParseBinaryPerformanceTrace.alx.
n
Ticks Ticks $_ Name n
Definition at line 132 of file ParseBinaryPerformanceTrace.alx.
Referenced by AphidHdl.AphidVerilogEmitter::Emit(), Components.Aphid.TypeSystem.TypeExtender::GetInteropName(), Components.Aphid.Library.StandardLibrary::GetObjectType(), if(), Components.External.ConsolePlus.CliApplication< TArgs, TConfig >::Launch(), and Components.Aphid.TypeSystem.InteropTypeResolver::ResolveType().
parsed
var parsed = 0
Definition at line 54 of file ParseBinaryPerformanceTrace.alx.
profileHeader
var profileHeader = reader.ReadString()
Definition at line 45 of file ParseBinaryPerformanceTrace.alx.
reader
var reader = new BinaryReader(trace |> File.OpenRead)
Definition at line 44 of file ParseBinaryPerformanceTrace.alx.
Referenced by Components.Cypress.NativeFunction::Deserialize(), Components.Cypress.StringTable::Deserialize(), Components.Cypress.Instruction::Deserialize(), Components.Aphid.Compiler.CSharpHelper::GenerateCode(), Components.Cypress.StackDumper::GetFunctionPointers(), Components.XmlSerializerExtensions::Serialize(), and while().
root
var root = new ArrayList()
Definition at line 53 of file ParseBinaryPerformanceTrace.alx.
threadStacks
var threadStacks = {}
Definition at line 52 of file ParseBinaryPerformanceTrace.alx.
Referenced by while().
Ticks
Ticks Ticks $_ Name $_ Ticks
Definition at line 132 of file ParseBinaryPerformanceTrace.alx.
TicksExclusive
Ticks Ticks $_ Name $_ $_ TicksExclusive
Definition at line 132 of file ParseBinaryPerformanceTrace.alx.
trace
var trace = 'C:\\source\\Aphid\\Aphid\\bin\\Debug\\AphidFramePerformance.ac063cef-bf19-4ee2-a5a3-1786653a79ed.dat'
Definition at line 43 of file ParseBinaryPerformanceTrace.alx.
Referenced by Components.Aphid.UI.AphidCli::DumpStackTrace().