Aphid Programming Language: c:/source/Aphid/Components.Aphid/Library/RemoteShell.alx File Reference
RemoteShell.alx File Reference
Functions
head ('AphidShell remoting{0}' ::[isClient ? ' client' :isWorker ? ' host worker process' :isHost ? ' host' :''])
if (isHost)
else if (argList.Contains('-test'))
Variables
var cmd = getCommand()
var argList = getCommandLineArgs() |> Enumerable.ToList
var getLastArg = @() argList |> Enumerable.Last
var parseIntArg = @() getLastArg() |> Int32.Parse
var flag = { connect: '-connect', listen: '-listen', pid: '-pid' }
var isClient = argList.Contains(flag.connect)
var isHost = argList.Contains(flag.listen)
var isWorker = argList.Contains(flag.pid)
_logDate = macro(@{ DateTime.Now.ToString("MM-dd-yy.HH:mm:ss") })
_logArgs = macro(@{ $args @aq.skip(1) @format($args[0]) })
var log = @() print('[~Cyan~{0}~R~] {1}' :: [ _logDate(), _logArgs() ])
var hostRemote
var startChild
var watchParent
var listen
var connectShell
var runInteractive
var readToPrompt
var execRemoteScript
var execRemoteScriptBlock
else
Function Documentation
head()
head ('AphidShell remoting{0}' :: [isClient ? ' client' :isWorker ? ' host worker process' :isHost ? ' host' :''])
if() [1/2]
if (isHost)
Definition at line 159 of file RemoteShell.alx.
References hostRemote, isWorker, listen, and watchParent.
             {
     if (!isWorker) {
         hostRemote();
     } else {
         watchParent();
         listen();
     }
 } else if (isClient) {
if() [2/2]
else if (argList. Contains'-test')
Definition at line 179 of file RemoteShell.alx.
{
     startChild();
     runInteractive('localhost');
 } else {
Variable Documentation
_logArgs
_logArgs = macro(@{ $args @aq.skip(1) @format($args[0]) })
Definition at line 20 of file RemoteShell.alx.
_logDate
_logDate = macro(@{ DateTime.Now.ToString("MM-dd-yy.HH:mm:ss") })
Definition at line 19 of file RemoteShell.alx.
argList
var argList = getCommandLineArgs() |> Enumerable.ToList
Definition at line 11 of file RemoteShell.alx.
Referenced by Components.ArgLexer::GetTokenInfo(), and Components.ArgLexer::Tokenize().
cmd
var cmd = getCommand()
Definition at line 10 of file RemoteShell.alx.
connectShell
var connectShell
Initial value:
= @(host) {
    log('Connecting to remote ~Cyan~{0}~R~', host);
    var remoteShell = remote.connectProxy(host);
    remoteShell.Eval('#"Shell";');
    remoteShell.BasePath = 'shell';
    remoteShell.listen();
    ret remoteShell;
}
Definition at line 73 of file RemoteShell.alx.
else
else
Initial value:
{
    print('aphid RemoteShell.alx [-listen] [-connect {host} {file}]')
Definition at line 182 of file RemoteShell.alx.
execRemoteScript
var execRemoteScript
Initial value:
= @(host, scriptFile) {
    printInfo('Executing script file ~Cyan~{0}~R~', scriptFile);
    ret scriptFile |> File.ReadAllText @execRemoteScriptBlock(host);
}
Definition at line 123 of file RemoteShell.alx.
execRemoteScriptBlock
var execRemoteScriptBlock
Initial value:
= @(host, script) {
    var result = { out: null };
    try {
        var remoteShell = connectShell(host);
        remoteShell.writePrompt();
        remoteShell |> readToPrompt;
        remoteShell.execScript(script);
        remoteShell.writePrompt();
        result.out = remoteShell |> readToPrompt;
        using System.Threading;
        remoteShell.Eval(
            'using System; using System.Threading;' +
            't = new Thread(@{ ' +
                'Thread.Sleep(250); ' +
                'Environment.Exit(0) }); ' +
            't.IsBackground = false;' +
            't.Start()');
    } catch (e) {
        if (e != null) {
            print('Exception: {0}\r\n{1}', e.message, e.stack);
        }
        result.error = e;
    }
    result.success = result.out != null;
    ret result;
}
Definition at line 128 of file RemoteShell.alx.
flag
var flag = { connect: '-connect', listen: '-listen', pid: '-pid' }
Definition at line 14 of file RemoteShell.alx.
getLastArg
var getLastArg = @() argList |> Enumerable.Last
Definition at line 12 of file RemoteShell.alx.
hostRemote
var hostRemote
Initial value:
= @{
    log('Starting host');
    while (true) {
        var p = startChild();
        p.WaitForExit();
    }
}
Definition at line 30 of file RemoteShell.alx.
Referenced by if().
isClient
var isClient = argList.Contains(flag.connect)
Definition at line 15 of file RemoteShell.alx.
isHost
var isHost = argList.Contains(flag.listen)
Definition at line 16 of file RemoteShell.alx.
isWorker
var isWorker = argList.Contains(flag.pid)
Definition at line 17 of file RemoteShell.alx.
Referenced by if().
listen
var listen
Initial value:
= @{
    log('Listening on ~Cyan~{0}~R~', remote.port);
    remote.listen();
    log('Sleeping');
    Thread.Sleep(-1);
}
Definition at line 66 of file RemoteShell.alx.
Referenced by if().
log
var log = @() print('[~Cyan~{0}~R~] {1}' :: [ _logDate(), _logArgs() ])
Definition at line 21 of file RemoteShell.alx.
parseIntArg
var parseIntArg = @() getLastArg() |> Int32.Parse
Definition at line 13 of file RemoteShell.alx.
readToPrompt
var readToPrompt
Initial value:
= @(proxy) {
    var sb = new StringBuilder();
    var buffer;
    do {
        if (buffer != (buffer = proxy.readOut())) {
            buffer |> sb.Append;
        }
    } while (buffer == null || !buffer.Trim().EndsWith('> ~R~'));
    ret sb.ToString();
}
Definition at line 110 of file RemoteShell.alx.
runInteractive
var runInteractive
Initial value:
= @(host) {
    var remoteShell = connectShell(host);
    var buffer;
    while (true) {
        remoteShell.writePrompt();
        do {
            buffer = remoteShell.readOut();
            if (buffer != null) {
                buffer |> Cli.Write;
            }
        } while (buffer == null || !buffer.Trim().EndsWith('> ~R~'));
        Console.ReadLine() |> remoteShell.writeInLine;
        if (!remoteShell.execNext()) {
            remoteShell.BasePath = 'Environment';
            remoteShell.Exit(0);
            break;
        }
    }
}
Definition at line 84 of file RemoteShell.alx.
startChild
var startChild
Initial value:
= @{
    var childArgs = "{0} -listen -pid {1}" :: [
        cmd |> ArgLexer.GetTokenInfo |> Enumerable.First @.EndOffset |> cmd.Substring @() $_.Trim(),
        Process.GetCurrentProcess().Id
    ];
    log('Starting remote worker process with args ~Cyan~{0}~R~', childArgs);
    var p = Process.Start(getExe(), childArgs);
    ret p;
}
Definition at line 39 of file RemoteShell.alx.
watchParent
var watchParent
Initial value:
= @{
    var t = new Thread(@{
        var pId = parseIntArg();
        log('Waiting for parent process ~Cyan~{0}~R~ to exit', pId);
        var p = Process.GetProcessById(pId);
        if (p != null) {
            p.WaitForExit();
            exit();
        }
    });
    t.Start();
}
Definition at line 51 of file RemoteShell.alx.
Referenced by if().