Aphid Programming Language: c:/source/Aphid/Components.Aphid/Library/Remoting.alx File Reference
Remoting.alx File Reference
Functions
if (!this.{' $aphid'}.AsmBuilder.IsTypeDefined('RemoteProxy'))
sb Append ('ret ')
Variables
extend RemoteProxy
extend dynamic handle
extend dynamic name
var sb = new StringBuilder()
Function Documentation
Append()
sb Append ('ret ')
Referenced by Components.Aphid.Compiler.AphidStringEmitter::AppendLine(), Components.Aphid.Compiler.AphidStringEmitter::AppendTabs(), Components.Aphid.Compiler.AphidStringEmitter::EmitArrayAccessExpression(), Components.Aphid.Compiler.AphidStringEmitter::EmitArrayExpression(), Components.Aphid.Compiler.AphidStringEmitter::EmitBinaryOperatorExpression(), Components.Aphid.Compiler.AphidStringEmitter::EmitBooleanExpression(), Components.Aphid.Compiler.AphidStringEmitter::EmitCallExpression(), Components.Aphid.Compiler.AphidStringEmitter::EmitNullExpression(), Components.Aphid.Compiler.AphidStringEmitter::EmitNumberExpression(), Components.Aphid.Compiler.AphidStringEmitter::EmitStringExpression(), Components.Aphid.Compiler.AphidStringEmitter::EmitTuple(), Components.Aphid.Compiler.AphidStringEmitter::EmitUnaryOperatorExpression(), and Components.External.ConsolePlus.VT100::GetString().
if()
if (!this.{' $aphid'}.AsmBuilder. IsTypeDefined 'RemoteProxy')
Definition at line 5 of file Remoting.alx.
           {'$aphid'}.AsmBuilder.IsTypeDefined('RemoteProxy')) {
     class RemoteProxy { AphidFunction Connect, Guid RemoteId, string BasePath };
 }
Variable Documentation
handle
extend dynamic handle
Definition at line 9 of file Remoting.alx.
Referenced by Components.External.ConsolePlus.VT100::Enable(), Components.Cypress.NativeDebugger::ProcessDebugEvents(), and Components.Cypress.ProcessMemory::ProcessMemory().
name
extend dynamic name
Initial value:
{
        using System.Text
Definition at line 12 of file Remoting.alx.
Referenced by Components.Aphid.Interpreter.AphidInterpreter::AddImport(), Components.Aphid.Compiler.CodeMemberMethodExtension::AddParameter(), Components.Aphid.Parser.AphidAttributeAttribute::AphidAttributeAttribute(), Components.Aphid.VSPackage.AphidDeclaration::AphidDeclaration(), Components.Aphid.Interpreter.AphidFrame::AphidFrame(), Components.Aphid.TypeSystem.AphidInteropFunctionAttribute::AphidInteropFunctionAttribute(), Components.Aphid.Interpreter.AphidLibraryAttribute::AphidLibraryAttribute(), Components.Aphid.Parser.AphidMacro::AphidMacro(), Components.Aphid.TypeSystem.AphidPropertyAttribute::AphidPropertyAttribute(), Components.Aphid.TypeSystem.AphidPropertyInfo::AphidPropertyInfo(), Components.Aphid.Compiler.CodeHelper::Arg(), Components.Aphid.Compiler.BuildNumber::BuildNumber(), Components.Aphid.Interpreter.AphidInterpreter::CallFunction(), Components.External.ConsolePlus.CliApplication< TArgs, TConfig >::CliApplication(), Mantispid.EnumBuilder::CreateEnum(), Components.Aphid.Compiler.AphidAssemblyBuilder::CreateType(), Components.CrossProcessLock::CrossProcessLock(), Components.External.ConsolePlus.Cli::DumpTable(), Components.Aphid.Compiler.CodeExpressionExtension::GetMethod(), Components.Aphid.Compiler.CodeExpressionExtension::GetProperty(), Components.Aphid.Library.Net.Http.HttpUpload::HttpUpload(), LLex.LLexFile::Interpret(), Components.Aphid.Compiler.CodeExpressionExtension::InvokeMethod(), Mantispid.RuleStructResolver::Is(), Components.External.ConsolePlus.CliApplication< TArgs, TConfig >::Launch(), Components.Aphid.Parser.AphidAttributeScanner::Match(), Components.Cypress.NativeFunction::NativeFunction(), LLex.LLexNameInfo::Parse(), Components.Aphid.Interpreter.AphidInterpreter::PushFrame(), Components.Aphid.Parser.AphidAttributeScanner::Require(), Components.Aphid.TypeSystem.AphidAlias::Resolve(), Mantispid.RuleStructResolver::Resolve(), Components.Aphid.TypeSystem.InteropTypeResolver::ResolveType(), Mantispid.RuleStruct::RuleStruct(), Components.External.ConsolePlus.CliArgReader::SetProperties(), Components.Aphid.Compiler.StringCompilerCli::StringCompilerCli(), Components.Aphid.Tests.Integration.Shared.UIComponent::UIComponent(), Components.Aphid.TypeSystem.InteropTypeResolver::Unalias(), Components.Aphid.Compiler.CodeHelper::VarDecl(), and Components.Aphid.Compiler.CodeHelper::VarRef().
RemoteProxy
extend RemoteProxy
Initial value:
{
    Eval: @(s, code) code |> remote._remoteTable.{s.RemoteId}.eval
Definition at line 9 of file Remoting.alx.
sb
var sb = new StringBuilder()
Definition at line 14 of file Remoting.alx.
Referenced by Components.External.ConsolePlus.VT100::Append(), Components.Aphid.Parser.ParserErrorMessage::Create(), Components.External.StringTree::Create< TNode >(), Components.Json.JsonFormatter::Format(), AphidUI.KeyHelper::GetCharFromKey(), Components.Aphid.Lexer.TokenHelper::GetCodeExcerpt(), Components.Aphid.UI.AphidCli::GetErrorMessage(), Components.Aphid.TypeSystem.TypeExtender::GetInteropName(), Components.Aphid.TypeSystem.InteropMethodResolver::GetMethodDescription(), Components.External.ConsolePlus.VT100::GetString(), Components.StringExtension::InsertLineNumbers(), Components.Json.JsonFormatter::MakeCompliant(), Components.Aphid.Parser.StringParser::Parse(), Components.Cypress.ProcessMemory::ReadAscii(), Components.Cypress.ProcessMemory::ReadUnicode(), Components.Aphid.Tests.Integration.Shared.ScriptedTests::RunTestScript(), Components.Aphid.Serialization.AphidSerializer::Serialize(), Components.Aphid.Interpreter.ExceptionHelper::StackTrace(), and Components.Cypress.DebuggerEventArgs::ToString().