Aphid Programming Language: c:/source/Aphid/Aphid/Samples/TcpExample.alx File Reference
TcpExample.alx File Reference
Variables
var client = tcp.connect('google.com', 80)
Variable Documentation
client
var client = tcp.connect('google.com', 80)
Definition at line 4 of file TcpExample.alx.
Referenced by Components.Aphid.Library.Net.Http.HttpClient::Connect(), Components.Aphid.Library.Net.HttpLibrary::HttpRequest(), Components.Aphid.Library.Net.TcpLibrary::TcpConnect(), Components.Aphid.Library.Net.UdpLibrary::UdpClose(), Components.Aphid.Library.Net.UdpLibrary::UdpCreate(), Components.Aphid.Library.Net.UdpLibrary::UdpReceive(), and Components.Aphid.Library.Net.UdpLibrary::UdpSend().