Aphid Programming Language: c:/source/Aphid/Aphid/Samples/VbsExample.alx File Reference
VbsExample.alx File Reference
Functions
Debug Print ('[#] Starting')
Sub GreetUser (Name)
MsgBox ("Hello " &Name &"!")
Sub LogAdminActivity ()
LogAdminActivity2 ()
Sub TestGreet ()
Debug Print ('[?] Validate user input')
Debug Print ('[?] Check if user {0} is admin', Name)
Debug Print ('[+] User is admin')
Debug Print ('[-] User is not admin')
evalVbsBlocks ()
Variables
End Sub
Name = InputBox('Enter Name', DefaultResponse:='John')
End If
Admin = "John"
Else
ExpectedDepth = 0
If Depth = ExpectedDepth Then
extend AphidExpression
var vbNullString = ""
load System Windows Forms
var MsgBox = MessageBox.Show
load Microsoft VisualBasic
var InputBox = Interaction.InputBox
var Indent = @() (++Depth) * ''
var Unindent = @() (Depth--) * ''
var Margin = @() Depth * ' '
var Debug
var root = this.{'$scope'}
var vbsContext = { sub: null, nodes: [], }
var evalVbsBlocks
var getVbsBlocks = @() this.{'$parent'}.{'$block'}-?@(x) x.isVbs()
var replaceIf
var replaceAndOperators
var replaceNamedArguments
var parseVbsBlock
var instrumentBlocks
Function Documentation
evalVbsBlocks()
evalVbsBlocks ()
GreetUser()
GreetUser (Name)
LogAdminActivity()
LogAdminActivity ()
LogAdminActivity2()
Sub LogAdminActivity2 ()
MsgBox()
MsgBox ("Hello " &Name &"!")
Print() [1/5]
Debug Print (' Starting' [#])
Print() [2/5]
Debug Print (' Validate user input' [?])
Print() [3/5]
Debug Print (' Check if user {0} is admin' [?], Name)
Print() [4/5]
Debug Print (' User is admin' [+])
Print() [5/5]
Debug Print (' User is not admin' [-])
TestGreet()
TestGreet ()
Variable Documentation
Admin
var Admin = "John"
Definition at line 31 of file VbsExample.alx.
AphidExpression
extend AphidExpression
Initial value:
{
    isVbs: @(x) x.hasHeader(As VBS),
    isSubStart: @(x) x.isCall() && x.func().isId() && x.func().oneAttr(Sub),
    getSubName: @(x) x.func().id(),
    isSubEnd: @(x) x.isId() && x.oneAttr(End) && x.id() == 'Sub',
}
var Name
Definition at line 53 of file VbsExample.alx.
Referenced by Components.Aphid.Parser.ScriptMutator::MutateCore().
Debug
var Debug
Initial value:
= {
    Print: @() {
        switch ($args.Count) {
            0: Cli.WriteLine();
            1: Cli.WriteLine(Margin() + $_, []);
            default: Cli.WriteLine(Margin() + $_, $args @aq.skip(1));
        }
    }
}
Definition at line 83 of file VbsExample.alx.
Referenced by Components.Aphid.VSPackage.AphidAuthoringScope::GetDeclarations(), Components.Aphid.VSPackage.AphidLanguageService::ParseSource(), and Components.Aphid.Tests.Integration.Shared.InteropTestBase::StaticPathTestUnsafe< TValue >().
Depth
var Depth = ExpectedDepth Then
Definition at line 46 of file VbsExample.alx.
Else
Else
Definition at line 36 of file VbsExample.alx.
evalVbsBlocks
var evalVbsBlocks
Initial value:
= @{
    getVbsBlocks()
        -> @(b) [ replaceAndOperators, replaceNamedArguments, replaceIf, parseVbsBlock ]
        -> @()$_(b);
    print('Done parsing, evaluating VB\r\n');
    [ instrumentBlocks, evalAst ]->@() vbsContext.nodes |> $_;
}
Definition at line 96 of file VbsExample.alx.
ExpectedDepth
var ExpectedDepth = 0
Definition at line 43 of file VbsExample.alx.
Forms
load System Windows Forms
Definition at line 66 of file VbsExample.alx.
getVbsBlocks
var getVbsBlocks = @() this.{'$parent'}.{'$block'}-?@(x) x.isVbs()
Definition at line 105 of file VbsExample.alx.
If
End If
Definition at line 28 of file VbsExample.alx.
Indent
var Indent = @() (++Depth) * ''
Definition at line 76 of file VbsExample.alx.
InputBox
var InputBox = Interaction.InputBox
Definition at line 73 of file VbsExample.alx.
instrumentBlocks
var instrumentBlocks
Definition at line 384 of file VbsExample.alx.
Margin
var Margin = @() Depth * ' '
Definition at line 78 of file VbsExample.alx.
MsgBox
var MsgBox = MessageBox.Show
Definition at line 68 of file VbsExample.alx.
Name
p2 Name = InputBox('Enter Name', DefaultResponse:='John')
Definition at line 23 of file VbsExample.alx.
Referenced by Components.Aphid.Parser.AphidAttributeAttribute::AphidAttributeAttribute(), Components.Aphid.VSPackage.AphidDeclaration::AphidDeclaration(), Components.Aphid.TypeSystem.AphidInteropFunctionAttribute::AphidInteropFunctionAttribute(), Components.Aphid.Interpreter.AphidLibraryAttribute::AphidLibraryAttribute(), Components.Aphid.Parser.AphidMacro::AphidMacro(), Components.Aphid.TypeSystem.AphidPropertyAttribute::AphidPropertyAttribute(), Components.Aphid.TypeSystem.AphidPropertyInfo::AphidPropertyInfo(), Components.Aphid.Compiler.BuildNumber::BuildNumber(), Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute >::BuildType(), Components.External.ConsolePlus.CliApplication< TArgs, TConfig >::CliApplication(), Components.Cypress.NativeFunction::Deserialize(), Components.Aphid.TypeSystem.AphidRef::Get(), Components.Aphid.Library.Net.Http.HttpUpload::HttpUpload(), Components.External.ConsolePlus.CliApplication< TArgs, TConfig >::Launch(), Mantispid.TypeInferenceMutator::MutateCore(), Components.Aphid.Parser.AphidMacroMutator::MutateCore(), Components.Cypress.NativeFunction::NativeFunction(), Components.Aphid.Parser.AphidMacro::Parse(), Components.Cypress.NativeFunction::Serialize(), Components.Aphid.Library.Net.Http.AphidUpload::ToHttpUpload(), Components.Cypress.NativeFunction::ToString(), Components.Aphid.Interpreter.AphidFrame::ToString(), Components.Aphid.Debugging.AphidTrace::TraceUnsafe(), Components.Aphid.TypeSystem.TypeExtender::TryResolve(), and Components.Aphid.Tests.Integration.Shared.UIComponent::UIComponent().
parseVbsBlock
var parseVbsBlock
Definition at line 332 of file VbsExample.alx.
replaceAndOperators
var replaceAndOperators
Initial value:
= @{
    print('[R] Replacing & operators');
    $_.Body @ast.walk(@(node, context) {
        if (!context.isRoot &&
            !context.isBlock) {
        }
        if (!context.isRoot &&
            !context.isBlock &&
            node.is(BinaryOperator) &&
            node.Operator == AphidTokenType.BinaryAndOperator) {
            @print('[+] Replacing & operator in expression {0}', node);
            using System.Reflection;
            node
                .GetType()
                .GetField('_operator', BindingFlags.NonPublic | BindingFlags.Instance)
                .SetValue(node, AphidTokenType.AdditionOperator);
        }
    })
}
Definition at line 262 of file VbsExample.alx.
replaceIf
var replaceIf
Definition at line 107 of file VbsExample.alx.
replaceNamedArguments
var replaceNamedArguments
Definition at line 286 of file VbsExample.alx.
root
var root = this.{'$scope'}
Definition at line 93 of file VbsExample.alx.
Sub
End Sub
Definition at line 11 of file VbsExample.alx.
Unindent
var Unindent = @() (Depth--) * ''
Definition at line 77 of file VbsExample.alx.
vbNullString
var vbNullString = ""
Definition at line 64 of file VbsExample.alx.
vbsContext
var vbsContext = { sub: null, nodes: [], }
Definition at line 94 of file VbsExample.alx.
VisualBasic
load Microsoft VisualBasic
Definition at line 70 of file VbsExample.alx.