Aphid Programming Language: Components.Aphid.Parser.AphidMutator Class Reference
Components.Aphid.Parser.AphidMutator Class Reference abstract
Public Member Functions
AphidMutator ()
List< AphidExpression > Mutate (List< AphidExpression > ast)
List< AphidExpression > MutateRecursively (List< AphidExpression > expression)
virtual void Reset ()
Protected Member Functions
abstract List< AphidExpression > MutateCore (AphidExpression expression, out bool hasChanged)
virtual List< AphidExpression > OnMutate (List< AphidExpression > ast)
virtual void BeginRecursiveMutationPass (List< AphidExpression > ast)
virtual void EndRecursiveMutationPass (List< AphidExpression > ast)
void FinalizeMutation ()
Properties
Stack< AphidExpression > Ancestors [get]
bool HasMutated [get]
bool IsStatement [get]
bool HasFinalized [get]
Detailed Description
Definition at line 8 of file AphidMutator.cs.
Constructor & Destructor Documentation
AphidMutator()
Components.Aphid.Parser.AphidMutator.AphidMutator ()
Definition at line 18 of file AphidMutator.cs.
         {
             Ancestors = new Stack<AphidExpression>();
         }
Member Function Documentation
BeginRecursiveMutationPass()
virtual void Components.Aphid.Parser.AphidMutator.BeginRecursiveMutationPass (List< AphidExpression > ast) protected virtual
Reimplemented in Boxelder.LambdaPositionMutator.
Definition at line 30 of file AphidMutator.cs.
 { }
EndRecursiveMutationPass()
virtual void Components.Aphid.Parser.AphidMutator.EndRecursiveMutationPass (List< AphidExpression > ast) protected virtual
Reimplemented in Boxelder.LambdaPositionMutator.
Definition at line 32 of file AphidMutator.cs.
 { }
FinalizeMutation()
void Components.Aphid.Parser.AphidMutator.FinalizeMutation () protected
Definition at line 446 of file AphidMutator.cs.
         {
             HasFinalized = true;
         }
Mutate()
List<AphidExpression> Components.Aphid.Parser.AphidMutator.Mutate (List< AphidExpression > ast)
Definition at line 39 of file AphidMutator.cs.
References ast.
Referenced by Components.Aphid.Compiler.AphidStringEmitter.Compile(), Components.Aphid.Serialization.AphidSerializer.Deserialize(), and AphidHdl.DynamicIdentifierMutator.MutateCore().
         {
             CheckAncestorStack();
             var mutatedAst = MutateInternal(ast);
             CheckAncestorStack();
             return mutatedAst;
         }
MutateCore()
abstract List<AphidExpression> Components.Aphid.Parser.AphidMutator.MutateCore (AphidExpression expression, out bool hasChanged) protected pure virtual
Implemented in Boxelder.LambdaPositionMutator, Components.Aphid.Parser.ScriptMutator, Components.Aphid.Parser.IncludeMutator, Components.Aphid.Parser.AphidMacroMutator, Mantispid.IndexTrackingMutator, Components.Aphid.Parser.ConstantFoldingMutator, Mantispid.TypeInferenceMutator, AphidHdl.ReplacementMutator, Mantispid.CallIdentifierMutator, Mantispid.DeclarativeStatementMutator, Boxelder.SwitchToIfMutator, Components.Aphid.Parser.BuildConstMutator, Boxelder.UnaryExpressionMutator, Components.Aphid.Parser.PartialOperatorMutator, Components.Aphid.Parser.AphidMacroBodyMutator, AphidHdl.ForUnrollMutator, Mantispid.PlusEqualMutator, Components.Aphid.Serialization.AphidObjectThisKeywordMutator, AphidHdl.DynamicIdentifierMutator, AphidHdl.NumberToStringMutator, Components.Aphid.Parser.AphidIdDirectiveMutator, and Components.Aphid.Parser.PipelineToCallMutator.
MutateRecursively()
List<AphidExpression> Components.Aphid.Parser.AphidMutator.MutateRecursively (List< AphidExpression > expression)
Definition at line 400 of file AphidMutator.cs.
References ast, and expression.
Referenced by Mantispid.ParserGenerator.Generate(), Components.Aphid.Interpreter.AphidInterpreter.InterpretStream(), and Components.Aphid.Interpreter.AphidLoader.LoadScript().
         {
             List<AphidExpression> ast = expression;
             var anyMutations = false;
             do
             {
                 Reset();
                 BeginRecursiveMutationPass(ast);
                 ast = MutateInternal(ast);
                 EndRecursiveMutationPass(ast);
                 if (HasMutated)
                 {
                     anyMutations = true;
                 }
             } while (HasMutated && !HasFinalized);
             HasMutated = anyMutations;
             return ast;
         }
OnMutate()
virtual List<AphidExpression> Components.Aphid.Parser.AphidMutator.OnMutate (List< AphidExpression > ast) protected virtual
Reimplemented in Components.Aphid.Parser.AphidMacroMutator.
Definition at line 25 of file AphidMutator.cs.
References ast.
         {
             return ast;
         }
Reset()
virtual void Components.Aphid.Parser.AphidMutator.Reset () virtual
Definition at line 423 of file AphidMutator.cs.
         {
             HasMutated = false;
         }
Property Documentation
Ancestors
Stack<AphidExpression> Components.Aphid.Parser.AphidMutator.Ancestors get protected
Definition at line 10 of file AphidMutator.cs.
 { get; private set; }
HasFinalized
bool Components.Aphid.Parser.AphidMutator.HasFinalized get
Definition at line 16 of file AphidMutator.cs.
 { get; private set; }
HasMutated
bool Components.Aphid.Parser.AphidMutator.HasMutated get
Definition at line 12 of file AphidMutator.cs.
 { get; private set; }
IsStatement
bool Components.Aphid.Parser.AphidMutator.IsStatement get protected
Definition at line 14 of file AphidMutator.cs.
Referenced by Mantispid.DeclarativeStatementMutator.MutateCore(), Mantispid.TypeInferenceMutator.MutateCore(), and Boxelder.LambdaPositionMutator.MutateCore().
 { get; private set; }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Parser/AphidMutator.cs