Aphid Programming Language: LLex.AlxFile Class Reference
LLex.AlxFile Class Reference
Classes
class LLexFile
class LLexMode
class LLexToken
Static Public Member Functions
static string Interpret (string file)
static string From (AphidObject retVal)
Detailed Description
Definition at line 10 of file AlxFile.cs.
Member Function Documentation
From()
static string LLex.AlxFile.From (AphidObject retVal) static
Definition at line 69 of file AlxFile.cs.
References ast, Components.Aphid.TypeSystem.AphidObject.Bind(), i, LLex.LexerGenerator.IgnoreCase, IsNullOrEmpty(), l, lexer, LLex.LLexNameInfo.Parse(), t, token, tokens, x, and y.
Referenced by LLex.AlxFile.Interpret().
         {
             var llexFile = new LLexFile();
             retVal.Bind(llexFile);
             var tokenTable = new TokenTable();
             tokenTable.Ignore = llexFile.Ignore;
             var nameInfo = LLexNameInfo.Parse(llexFile.Name);
             int z = 0;
             var modeTable = llexFile.Modes.ToDictionary(x => x.Mode, x => z++);
             var tokenTypes = new List<string>();
             foreach (var mode in llexFile.Modes)
             {
                 tokenTable.SetMode(modeTable[mode.Mode]);
                 foreach (var token in mode.Tokens)
                 {
                     if (token.Regex != null)
                     {
                         var regexLexer = new RegexLexer(token.Regex);
                         var tokens = regexLexer.GetTokens();
                         var parser = new RegexParser(tokens.ToArray());
                         var ast = parser.Parse();
                         var compiler = new RegexCompiler(ast);
                         var strings = compiler.ExpandRegex();
                         foreach (var l in strings)
{
                             if (token.Code != null)
{
                                 tokenTable.AddLexemeCode(l, token.Code);
                                 continue;
                             }
                             if (!tokenTypes.Contains(token.TokenType))
                                 tokenTypes.Add(token.TokenType);
                             if (!string.IsNullOrEmpty(token.NewMode))
{
                                 tokenTable.Add(l, token.TokenType, modeTable[token.NewMode]);
                             }
                             else
{
                                 tokenTable.Add(l, token.TokenType);
                             }
                         }
                     }
                     else if (token.Code != null)
                     {
                         tokenTable.AddCode(token.Code);
                     }
                     else if (token.TokenType != null)
                     {
                         tokenTable.AddCode("return {TokenType}." + token.TokenType + ";\r\n");
                     }
                     else
                     {
                         throw new NotImplementedException(
                             "Token with no regex, code, or type not supported.");
                     }
                 }
                 foreach (var keyword in mode.Keywords ?? new string[0])
                 {
                     tokenTable.AddKeyword(keyword);
                     var t = keyword + "Keyword";
                     if (mode.KeywordTail != null)
                     {
                         tokenTable.AddLexemeCode(keyword, mode.KeywordTail.Replace("{Keyword}", t));
                     }
                     else
                     {
                         tokenTable.Add(keyword, t);
                     }
                 }
                 if (!string.IsNullOrEmpty(mode.KeywordDefault))
                 {
                     var k = mode.Keywords
                         .SelectMany(x => Enumerable
                             .Range(1, x.Length - 1)
                             .Select(y => x.Remove(y))
                             .ToArray())
                         .Distinct()
                         .ToArray();
                     foreach (var i in k)
                     {
                         if (tokenTable.Lists.Any(x => x.Value.Any(y => y.Lexeme == i)))
{
                             continue;
                         }
                         tokenTable.AddLexemeCode(i, mode.KeywordDefault);
                     }
                 }
             }
             var generator = new LexerGenerator(tokenTable) { IgnoreCase = llexFile.IgnoreCase };
             var lexer = generator.Generate();
             return lexer
                 .Replace("{Lexer}", nameInfo.LexerName)
                 .Replace("{Token}", nameInfo.TokenName)
                 .Replace("{TokenType}", nameInfo.TokenTypeName)
                 .Replace("{LexerNamespace}", nameInfo.Namespace);
         }
Interpret()
static string LLex.AlxFile.Interpret (string file) static
Definition at line 60 of file AlxFile.cs.
References LLex.AlxFile.From().
         {
             var interpreter = new AphidInterpreter();
             interpreter.InterpretFile(file);
             var retVal = interpreter.GetReturnValue();
             return From(retVal);
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Compiler/Medusa/LLex/AlxFile.cs