Aphid Programming Language: AphidUI.AphidRepl Class Reference
AphidUI.AphidRepl Class Reference
Interaction logic for AphidReply.xaml
Public Member Functions
AphidRepl ()
void MainWindow_KeyDown (object sender, KeyEventArgs e)
void InputTextBox_KeyDown (object sender, KeyEventArgs e)
Static Public Member Functions
static void IsMultiLineChanged (DependencyObject sender, DependencyPropertyChangedEventArgs args)
static void CodeChanged (DependencyObject sender, DependencyPropertyChangedEventArgs args)
Static Public Attributes
static readonly DependencyProperty IsMultiLineProperty
static readonly DependencyProperty CodeProperty
Properties
AphidReplViewModel ViewModel [get]
bool IsMultiLine [get, set]
string Code [get, set]
bool LineOptionsVisible [get, set]
Events
EventHandler ExecutionCompleted
Detailed Description
Interaction logic for AphidReply.xaml
Definition at line 22 of file AphidRepl.xaml.cs.
Constructor & Destructor Documentation
AphidRepl()
AphidUI.AphidRepl.AphidRepl ()
Definition at line 64 of file AphidRepl.xaml.cs.
References AphidUI.ViewModels.AphidReplViewModel.ClearConsole(), e, AphidUI.ViewModels.AphidReplViewModel.Execute(), AphidUI.AphidRepl.InputTextBox_KeyDown(), AphidUI.ViewModels.AphidReplViewModel.IsControlInitialized, AphidUI.AphidRepl.LineOptionsVisible, AphidUI.AphidRepl.MainWindow_KeyDown(), AphidUI.ViewModels.ViewModel.PropertyChanged, AphidUI.ViewModels.AphidReplViewModel.Reset(), and AphidUI.ViewModels.AphidReplViewModel.Stop().
Referenced by AphidUI.AphidRepl.CodeChanged(), and AphidUI.AphidRepl.IsMultiLineChanged().
         {
             InitializeComponent();
             LayoutRoot.DataContext = _viewModel = new AphidReplViewModel(OutputTextBox2);
             LineOptionsVisible = true;
             KeyDown += MainWindow_KeyDown;
             ExpressionTextBox.PreviewKeyDown += InputTextBox_KeyDown;
             RunMenuItem.Click += (o, e) => _viewModel.Execute(ExecutionCallback);
             StopMenuItem.Click += (o, e) => _viewModel.Stop();
             ClearMenuItem.Click += (o, e) => _viewModel.ClearConsole();
             ResetMenuItem.Click += (o, e) => _viewModel.Reset();
             _viewModel.IsControlInitialized = true;
             _viewModel.PropertyChanged += vm_PropertyChanged;
         }
Member Function Documentation
CodeChanged()
static void AphidUI.AphidRepl.CodeChanged (DependencyObject sender, DependencyPropertyChangedEventArgs args) static
Definition at line 141 of file AphidRepl.xaml.cs.
References AphidUI.AphidRepl.AphidRepl(), args, and string.
         {
             var viewer = (AphidRepl)sender;
             if ((string)args.OldValue == (string)args.NewValue)
             {
                 return;
             }
             viewer._viewModel.Code = (string)args.NewValue;
         }
InputTextBox_KeyDown()
void AphidUI.AphidRepl.InputTextBox_KeyDown (object sender, KeyEventArgs e)
Definition at line 97 of file AphidRepl.xaml.cs.
References e, AphidUI.ViewModels.AphidReplViewModel.Execute(), AphidUI.ViewModels.AphidReplViewModel.SetNextCode(), and AphidUI.ViewModels.AphidReplViewModel.SetPreviousCode().
Referenced by AphidUI.AphidRepl.AphidRepl().
         {
             var tb = (CodeTextBox)sender;
             switch (e.Key)
             {
                 case Key.Enter:
                     _viewModel.Execute(() =>
                     {
                         tb.Focus();
                         Keyboard.Focus(tb);
                         //tb.ScrollToEnd();
                     });
                     break;
                 case Key.Up:
                     _viewModel.SetPreviousCode();
                     //tb.ScrollToEnd();
                     break;
                 case Key.Down:
                     _viewModel.SetNextCode();
                     //tb.ScrollToEnd();
                     break;
             }
         }
IsMultiLineChanged()
static void AphidUI.AphidRepl.IsMultiLineChanged (DependencyObject sender, DependencyPropertyChangedEventArgs args) static
Definition at line 135 of file AphidRepl.xaml.cs.
References AphidUI.AphidRepl.AphidRepl(), and args.
         {
             var viewer = (AphidRepl)sender;
             viewer._viewModel.IsMultiLine = (bool)args.NewValue;
         }
MainWindow_KeyDown()
void AphidUI.AphidRepl.MainWindow_KeyDown (object sender, KeyEventArgs e)
Definition at line 87 of file AphidRepl.xaml.cs.
References e, and AphidUI.ViewModels.AphidReplViewModel.Execute().
Referenced by AphidUI.AphidRepl.AphidRepl().
         {
             switch (e.Key)
             {
                 case Key.F5:
                     _viewModel.Execute(ExecutionCallback);
                     break;
             }
         }
Member Data Documentation
CodeProperty
readonly DependencyProperty AphidUI.AphidRepl.CodeProperty static
Initial value:
= DependencyProperty.Register(
            "Code", typeof(string), typeof(AphidRepl), new PropertyMetadata(CodeChanged))
Definition at line 42 of file AphidRepl.xaml.cs.
IsMultiLineProperty
readonly DependencyProperty AphidUI.AphidRepl.IsMultiLineProperty static
Initial value:
= DependencyProperty.Register(
          "IsMultiLine", typeof(bool), typeof(AphidRepl), new PropertyMetadata(false, IsMultiLineChanged))
Definition at line 33 of file AphidRepl.xaml.cs.
Property Documentation
Code
string AphidUI.AphidRepl.Code get set
Definition at line 46 of file AphidRepl.xaml.cs.
         {
             get { return (string)GetValue(CodeProperty); }
             set { SetValue(CodeProperty, value); }
         }
IsMultiLine
bool AphidUI.AphidRepl.IsMultiLine get set
Definition at line 37 of file AphidRepl.xaml.cs.
         {
             get { return (bool)GetValue(IsMultiLineProperty); }
             set { SetValue(IsMultiLineProperty, value); }
         }
LineOptionsVisible
bool AphidUI.AphidRepl.LineOptionsVisible get set
Definition at line 54 of file AphidRepl.xaml.cs.
Referenced by AphidUI.AphidRepl.AphidRepl().
         {
             get { return _lineOptionsVisible; }
             set
             {
                 _lineOptionsVisible = value;
                 _viewModel.LineOptionVisibility = value ? Visibility.Visible : Visibility.Collapsed;
             }
         }
ViewModel
AphidReplViewModel AphidUI.AphidRepl.ViewModel get
Definition at line 29 of file AphidRepl.xaml.cs.
         {
             get { return _viewModel; }
         }
Event Documentation
ExecutionCompleted
EventHandler AphidUI.AphidRepl.ExecutionCompleted
Definition at line 24 of file AphidRepl.xaml.cs.
The documentation for this class was generated from the following file:
c:/source/Aphid/AphidUI/AphidRepl.xaml.cs