Aphid Programming Language: Components.Aphid.UI.AphidRepl Class Reference
Components.Aphid.UI.AphidRepl Class Reference
Public Member Functions
AphidRepl ()
AphidRepl (AphidInterpreter interpreter)
AphidRepl (AphidInterpreter interpreter, AphidSerializer serializer)
void Run ()
Properties
AphidSerializer Serializer [get, set]
AphidInterpreter Interpreter [get, set]
List< AphidExpression > Prologue [get, set]
List< AphidExpression > Epilogue [get, set]
Detailed Description
Definition at line 19 of file AphidRepl.cs.
Constructor & Destructor Documentation
AphidRepl() [1/3]
Components.Aphid.UI.AphidRepl.AphidRepl ()
Definition at line 41 of file AphidRepl.cs.
             : this(null)
         {
         }
AphidRepl() [2/3]
Components.Aphid.UI.AphidRepl.AphidRepl (AphidInterpreter interpreter)
Definition at line 46 of file AphidRepl.cs.
             : this(interpreter, null)
         {
         }
AphidRepl() [3/3]
Components.Aphid.UI.AphidRepl.AphidRepl (AphidInterpreter interpreter, AphidSerializer serializer)
Definition at line 51 of file AphidRepl.cs.
         {
             Interpreter = interpreter ?? new AphidInterpreter();
             Serializer = serializer ?? new AphidSerializer(Interpreter) { IgnoreSpecialVariables = true, };
             Prologue = new List<AphidExpression>();
             Epilogue = new List<AphidExpression>();
         }
Member Function Documentation
Run()
void Components.Aphid.UI.AphidRepl.Run ()
Definition at line 59 of file AphidRepl.cs.
References code, console, e, is, Components.Aphid.Debugging.AphidErrorReporter.SaveErrorInformation(), Components.Aphid.UI.AphidCli.TryAction(), Components.External.ConsolePlus.Cli.WriteCriticalErrorMessage(), and x.
         {
             if (Interpreter == null)
             {
                 Interpreter = new AphidInterpreter();
             }
             using (var console = new AphidAutocompleteConsole(Interpreter))
             {
                 while (true)
                 {
                     var isDumpDefined = Interpreter.CurrentScope.IsDefined(AphidName.DumpSerializer);
                     if (!_isSerializerShared || !isDumpDefined)
                     {
                         if (isDumpDefined)
{
                             Interpreter.CurrentScope.Remove(AphidName.DumpSerializer);
                         }
                         Interpreter.CurrentScope.Add(
                             AphidName.DumpSerializer,
                             new AphidObject(Serializer));
                         Interpreter.CurrentScope.Add(
                             "prologue",
                             new AphidObject(Prologue));
                         Interpreter.CurrentScope.Add(
                             "epilogue",
                             new AphidObject(Epilogue));
                         _isSerializerShared = true;
                     }
                     string code;
                     if (!Debugger.IsAttached)
                     {
                         try
{
                             code = console.ReadLine();
                         }
                         catch (Exception e)
{
                             Cli.WriteCriticalErrorMessage(
                                 "Internal error encountered in autocomplete console:\r\n{0}",
                                 e.Message);
                             AphidErrorReporter.SaveErrorInformation(e, Interpreter);
                             if (e is ReflectionTypeLoadException)
{
                                 var loaderExceptions = ((ReflectionTypeLoadException)e).LoaderExceptions;
                                 Cli.WriteCriticalErrorMessage(
                                     "Loader exceptions:\r\n{0}",
                                     loaderExceptions.Select(x => x.Message).JoinLines());
                             }
                             continue;
                         }
                     }
                     else
                     {
                         code = console.ReadLine();
                     }
                     if (!Debugger.IsAttached)
                     {
                         RunBlock(Prologue, handleExceptions: true);
                         AphidCli.TryAction(Interpreter, code, () => RunCode(code));
                         RunBlock(Epilogue, handleExceptions: true);
                     }
                     else
                     {
                         var backup = Interpreter.SetIsInTryCatchFinally(true);
                         RunBlock(Prologue, handleExceptions: false);
                         RunCode(code);
                         RunBlock(Epilogue, handleExceptions: false);
                         Interpreter.SetIsInTryCatchFinally(backup);
                     }
                     Interpreter.ResetState();
                 }
             }
         }
Property Documentation
Epilogue
List<AphidExpression> Components.Aphid.UI.AphidRepl.Epilogue get set
Definition at line 39 of file AphidRepl.cs.
 { get; set; }
Interpreter
AphidInterpreter Components.Aphid.UI.AphidRepl.Interpreter get set
Definition at line 35 of file AphidRepl.cs.
 { get; set; }
Prologue
List<AphidExpression> Components.Aphid.UI.AphidRepl.Prologue get set
Definition at line 37 of file AphidRepl.cs.
 { get; set; }
Serializer
AphidSerializer Components.Aphid.UI.AphidRepl.Serializer get set
Definition at line 26 of file AphidRepl.cs.
         {
             get { return _serializer; }
             set
             {
                 _serializer = value;
                 _isSerializerShared = false;
             }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/UI/AphidRepl.cs