Aphid Programming Language: Components.Aphid.Compiler.AphidStringEmitter Class Reference
Components.Aphid.Compiler.AphidStringEmitter Class Reference
Public Member Functions
virtual void Emit (List< AphidExpression > statements)
virtual string Compile (string filename, List< AphidExpression > ast)
Protected Member Functions
void Indent ()
void Unindent ()
string GetTabs ()
void AppendTabs ()
void AppendLine ()
void Append (string format, params object[] args)
void Append (string value)
void Append (object value)
virtual void EmitHeader ()
virtual void BeginExpression (AphidExpression expression)
virtual void EndExpression (AphidExpression expression)
string GetOperator (Dictionary< AphidTokenType, string > table, AphidTokenType op)
virtual string GetUnaryPrefixOperator (AphidTokenType op)
virtual string GetUnaryPostfixOperator (AphidTokenType op)
virtual string GetBinaryOperator (AphidTokenType op)
virtual void EmitUnaryOperatorExpression (UnaryOperatorExpression expression, bool isStatement=false)
virtual void EmitBinaryOperatorExpression (BinaryOperatorExpression expression, bool isStatement=false)
virtual void EmitStringExpression (StringExpression expression, bool isStatement=false)
virtual void EmitNumberExpression (NumberExpression expression, bool isStatement=false)
virtual void EmitNullExpression (NullExpression expression, bool isStatement=false)
virtual void EmitBooleanExpression (BooleanExpression expression, bool isStatement=false)
virtual void EmitCallExpression (CallExpression expression, bool isStatement=false)
virtual void EmitArrayExpression (ArrayExpression expression, bool isStatement=false)
virtual void EmitArrayAccessExpression (ArrayAccessExpression expression, bool isStatement=false)
void EmitTuple (IEnumerable< AphidExpression > items, string prefix="", string suffix="")
virtual void Emit (AphidExpression expression, bool isStatement=false)
virtual void EmitBreakExpression (BreakExpression expression, bool isStatement=false)
virtual void EmitDoWhileExpression (DoWhileExpression expression, bool isStatement=false)
virtual void EmitDynamicMemberExpression (DynamicMemberExpression expression, bool isStatement=false)
virtual void EmitExtendExpression (ExtendExpression expression, bool isStatement=false)
virtual void EmitForEachExpression (ForEachExpression expression, bool isStatement=false)
virtual void EmitForExpression (ForExpression expression, bool isStatement=false)
virtual void EmitFunctionExpression (FunctionExpression expression, bool isStatement=false)
virtual void EmitGatorCloseExpression (GatorCloseExpression expression, bool isStatement=false)
virtual void EmitGatorEmitExpression (GatorEmitExpression expression, bool isStatement=false)
virtual void EmitGatorOpenExpression (GatorOpenExpression expression, bool isStatement=false)
virtual void EmitIdentifierExpression (IdentifierExpression expression, bool isStatement=false)
virtual void EmitIfExpression (IfExpression expression, bool isStatement=false)
virtual void EmitLoadLibraryExpression (LoadLibraryExpression expression, bool isStatement=false)
virtual void EmitLoadScriptExpression (LoadScriptExpression expression, bool isStatement=false)
virtual void EmitObjectExpression (ObjectExpression expression, bool isStatement=false)
virtual void EmitPartialFunctionExpression (PartialFunctionExpression expression, bool isStatement=false)
virtual void EmitPatternExpression (PatternExpression expression, bool isStatement=false)
virtual void EmitPatternMatchingExpression (PatternMatchingExpression expression, bool isStatement=false)
virtual void EmitSwitchCase (SwitchCase expression, bool isStatement=false)
virtual void EmitSwitchExpression (SwitchExpression expression, bool isStatement=false)
virtual void EmitTernaryOperatorExpression (TernaryOperatorExpression expression, bool isStatement=false)
virtual void EmitTextExpression (TextExpression expression, bool isStatement=false)
virtual void EmitThisExpression (ThisExpression expression, bool isStatement=false)
virtual void EmitTryExpression (TryExpression expression, bool isStatement=false)
virtual void EmitWhileExpression (WhileExpression expression, bool isStatement=false)
virtual void BeginStatement (AphidExpression expression)
virtual void EndStatement (AphidExpression expression)
Protected Attributes
StringBuilder _out = new StringBuilder()
Properties
Stack< List< AphidExpression > > Scope [get]
Detailed Description
Definition at line 10 of file AphidStringEmitter.cs.
Member Function Documentation
Append() [1/3]
void Components.Aphid.Compiler.AphidStringEmitter.Append (string format, params object [] args) protected
Definition at line 103 of file AphidStringEmitter.cs.
References args, and format.
Referenced by Boxelder.AphidPythonEmitter.BeginStatement(), Coywolf.AphidPhpEmitter.BeginStatement(), Coywolf.AphidPhpEmitter.Emit(), Boxelder.AphidPythonEmitter.EmitBinaryOperatorExpression(), Coywolf.AphidPhpEmitter.EmitBinaryOperatorExpression(), Boxelder.AphidPythonEmitter.EmitBooleanExpression(), Boxelder.AphidPythonEmitter.EmitBreakExpression(), Coywolf.AphidPhpEmitter.EmitCallExpression(), Coywolf.AphidPhpEmitter.EmitClassDeclaration(), Coywolf.AphidPhpEmitter.EmitClassMember(), Boxelder.AphidPythonEmitter.EmitClassStatement(), Boxelder.AphidPythonEmitter.EmitDictionaryExpression(), Coywolf.AphidPhpEmitter.EmitEchoStatement(), Boxelder.AphidPythonEmitter.EmitForEachExpression(), Coywolf.AphidPhpEmitter.EmitForEachExpression(), Boxelder.AphidPythonEmitter.EmitFromStatement(), Boxelder.AphidPythonEmitter.EmitFunctionDeclarationStatement(), Coywolf.AphidPhpEmitter.EmitFunctionExpression(), Coywolf.AphidPhpEmitter.EmitGatorCloseExpression(), Coywolf.AphidPhpEmitter.EmitGatorEmitExpression(), Coywolf.AphidPhpEmitter.EmitGatorOpenExpression(), Coywolf.AphidPhpEmitter.EmitHeader(), Boxelder.AphidPythonEmitter.EmitHeader(), Boxelder.AphidPythonEmitter.EmitIdentifierExpression(), Coywolf.AphidPhpEmitter.EmitIdentifierExpression(), Boxelder.AphidPythonEmitter.EmitIdentifierStatement(), Boxelder.AphidPythonEmitter.EmitIfExpression(), Coywolf.AphidPhpEmitter.EmitIfExpression(), Boxelder.AphidPythonEmitter.EmitImportStatement(), Boxelder.AphidPythonEmitter.EmitNullExpression(), Boxelder.AphidPythonEmitter.EmitNumberExpression(), Coywolf.AphidPhpEmitter.EmitObjectExpression(), Boxelder.AphidPythonEmitter.EmitPartialFunctionExpression(), Coywolf.AphidPhpEmitter.EmitPartialFunctionExpression(), Boxelder.AphidPythonEmitter.EmitRaw(), Coywolf.AphidPhpEmitter.EmitStringExpression(), Boxelder.AphidPythonEmitter.EmitTernaryOperatorExpression(), Coywolf.AphidPhpEmitter.EmitTernaryOperatorExpression(), Coywolf.AphidPhpEmitter.EmitTextExpression(), Boxelder.AphidPythonEmitter.EmitTryExpression(), Coywolf.AphidPhpEmitter.EmitUnaryOperatorExpression(), Coywolf.AphidPhpEmitter.EmitUsed(), Boxelder.AphidPythonEmitter.EmitWhileExpression(), and Coywolf.AphidPhpEmitter.EmitWhileExpression().
         {
             _out.AppendFormat(format, args);
         }
Append() [2/3]
void Components.Aphid.Compiler.AphidStringEmitter.Append (string value) protected
Definition at line 108 of file AphidStringEmitter.cs.
References value.
         {
             _out.Append(value);
         }
Append() [3/3]
void Components.Aphid.Compiler.AphidStringEmitter.Append (object value) protected
Definition at line 113 of file AphidStringEmitter.cs.
References value.
         {
             _out.Append(value.ToString());
         }
AppendLine()
void Components.Aphid.Compiler.AphidStringEmitter.AppendLine () protected
Definition at line 98 of file AphidStringEmitter.cs.
References Append().
Referenced by Boxelder.AphidPythonEmitter.EmitClassStatement(), Boxelder.AphidPythonEmitter.EmitFunctionDeclarationStatement(), and Boxelder.AphidPythonEmitter.EndStatement().
         {
             Append("\r\n");
         }
AppendTabs()
void Components.Aphid.Compiler.AphidStringEmitter.AppendTabs () protected
Definition at line 93 of file AphidStringEmitter.cs.
References Append().
Referenced by Coywolf.AphidPhpEmitter.EmitCallExpression(), Boxelder.AphidPythonEmitter.EmitClassStatement(), Boxelder.AphidPythonEmitter.EmitFunctionDeclarationStatement(), and Boxelder.AphidPythonEmitter.EmitIfExpression().
         {
             Append(GetTabs());
         }
BeginExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.BeginExpression (AphidExpression expression) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter.
Definition at line 150 of file AphidStringEmitter.cs.
 { }
BeginStatement()
virtual void Components.Aphid.Compiler.AphidStringEmitter.BeginStatement (AphidExpression expression) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter, and Boxelder.AphidPythonEmitter.
Definition at line 81 of file AphidStringEmitter.g.cs.
 { }
Compile()
virtual string Components.Aphid.Compiler.AphidStringEmitter.Compile (string filename, List< AphidExpression > ast) virtual
Reimplemented in Coywolf.AphidPhpEmitter, and Boxelder.AphidPythonEmitter.
Definition at line 155 of file AphidStringEmitter.cs.
References ast, Emit(), Components.Aphid.Parser.AphidMutator.Mutate(), and Components.Aphid.Compiler.BuildNumberRepository.NextBuildNumber().
         {
             var buildNumber = new BuildNumberRepository().NextBuildNumber(filename);
             ast = new BuildConstMutator(buildNumber).Mutate(ast);
             _out.Clear();
             EmitHeader();
             Emit(ast);
             return _out.ToString();
         }
Emit() [1/2]
virtual void Components.Aphid.Compiler.AphidStringEmitter.Emit (AphidExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter.
Definition at line 10 of file AphidStringEmitter.g.cs.
References expression.
         {
             BeginExpression(expression);
             switch (expression.Type)
             {
                 case AphidExpressionType.ArrayAccessExpression: EmitArrayAccessExpression((ArrayAccessExpression)expression, isStatement); break;
                 case AphidExpressionType.ArrayExpression: EmitArrayExpression((ArrayExpression)expression, isStatement); break;
                 case AphidExpressionType.BinaryOperatorExpression: EmitBinaryOperatorExpression((BinaryOperatorExpression)expression, isStatement); break;
                 case AphidExpressionType.BooleanExpression: EmitBooleanExpression((BooleanExpression)expression, isStatement); break;
                 case AphidExpressionType.BreakExpression: EmitBreakExpression((BreakExpression)expression, isStatement); break;
                 case AphidExpressionType.CallExpression: EmitCallExpression((CallExpression)expression, isStatement); break;
                 case AphidExpressionType.DoWhileExpression: EmitDoWhileExpression((DoWhileExpression)expression, isStatement); break;
                 case AphidExpressionType.DynamicMemberExpression: EmitDynamicMemberExpression((DynamicMemberExpression)expression, isStatement); break;
                 case AphidExpressionType.ExtendExpression: EmitExtendExpression((ExtendExpression)expression, isStatement); break;
                 case AphidExpressionType.ForEachExpression: EmitForEachExpression((ForEachExpression)expression, isStatement); break;
                 case AphidExpressionType.ForExpression: EmitForExpression((ForExpression)expression, isStatement); break;
                 case AphidExpressionType.FunctionExpression: EmitFunctionExpression((FunctionExpression)expression, isStatement); break;
                 case AphidExpressionType.GatorCloseExpression: EmitGatorCloseExpression((GatorCloseExpression)expression, isStatement); break;
                 case AphidExpressionType.GatorEmitExpression: EmitGatorEmitExpression((GatorEmitExpression)expression, isStatement); break;
                 case AphidExpressionType.GatorOpenExpression: EmitGatorOpenExpression((GatorOpenExpression)expression, isStatement); break;
                 case AphidExpressionType.IdentifierExpression: EmitIdentifierExpression((IdentifierExpression)expression, isStatement); break;
                 case AphidExpressionType.IfExpression: EmitIfExpression((IfExpression)expression, isStatement); break;
                 case AphidExpressionType.LoadLibraryExpression: EmitLoadLibraryExpression((LoadLibraryExpression)expression, isStatement); break;
                 case AphidExpressionType.LoadScriptExpression: EmitLoadScriptExpression((LoadScriptExpression)expression, isStatement); break;
                 case AphidExpressionType.NullExpression: EmitNullExpression((NullExpression)expression, isStatement); break;
                 case AphidExpressionType.NumberExpression: EmitNumberExpression((NumberExpression)expression, isStatement); break;
                 case AphidExpressionType.ObjectExpression: EmitObjectExpression((ObjectExpression)expression, isStatement); break;
                 case AphidExpressionType.PartialFunctionExpression: EmitPartialFunctionExpression((PartialFunctionExpression)expression, isStatement); break;
                 case AphidExpressionType.PatternExpression: EmitPatternExpression((PatternExpression)expression, isStatement); break;
                 case AphidExpressionType.PatternMatchingExpression: EmitPatternMatchingExpression((PatternMatchingExpression)expression, isStatement); break;
                 case AphidExpressionType.UnaryOperatorExpression: EmitUnaryOperatorExpression((UnaryOperatorExpression)expression, isStatement); break;
                 case AphidExpressionType.StringExpression: EmitStringExpression((StringExpression)expression, isStatement); break;
                 case AphidExpressionType.SwitchCase: EmitSwitchCase((SwitchCase)expression, isStatement); break;
                 case AphidExpressionType.SwitchExpression: EmitSwitchExpression((SwitchExpression)expression, isStatement); break;
                 case AphidExpressionType.TernaryOperatorExpression: EmitTernaryOperatorExpression((TernaryOperatorExpression)expression, isStatement); break;
                 case AphidExpressionType.TextExpression: EmitTextExpression((TextExpression)expression, isStatement); break;
                 case AphidExpressionType.ThisExpression: EmitThisExpression((ThisExpression)expression, isStatement); break;
                 case AphidExpressionType.TryExpression: EmitTryExpression((TryExpression)expression, isStatement); break;
                 case AphidExpressionType.WhileExpression: EmitWhileExpression((WhileExpression)expression, isStatement); break;
                 default:
                     throw new NotImplementedException();
             }
             EndExpression(expression);
         }
Emit() [2/2]
virtual void Components.Aphid.Compiler.AphidStringEmitter.Emit (List< AphidExpression > statements) virtual
Reimplemented in Coywolf.AphidPhpEmitter.
Definition at line 120 of file AphidStringEmitter.cs.
References Emit().
Referenced by Boxelder.AphidPythonEmitter.EmitBinaryOperatorExpression(), Boxelder.AphidPythonEmitter.EmitBlock(), Boxelder.AphidPythonEmitter.EmitClassStatement(), Boxelder.AphidPythonEmitter.EmitDictionaryExpression(), Boxelder.AphidPythonEmitter.EmitForEachExpression(), Boxelder.AphidPythonEmitter.EmitFunctionDeclarationStatement(), Boxelder.AphidPythonEmitter.EmitIfExpression(), Boxelder.AphidPythonEmitter.EmitPartialFunctionExpression(), Boxelder.AphidPythonEmitter.EmitTernaryOperatorExpression(), and Boxelder.AphidPythonEmitter.EmitWhileExpression().
         {
             _scope.Push(statements);
             foreach (var stmt in statements)
             {
                 BeginStatement(stmt);
                 if (Debugger.IsAttached)
                 {
                     Emit(stmt, isStatement: true);
                 }
                 else
                 {
                     try
                     {
                         Emit(stmt, isStatement: true);
                     }
                     catch (NotImplementedException)
                     {
                         throw new InvalidOperationException(string.Format("{0} is not supported.", stmt.Type));
                     }
                 }
                 EndStatement(stmt);
             }
             _scope.Pop();
         }
EmitArrayAccessExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitArrayAccessExpression (ArrayAccessExpression expression, bool isStatement = false) protected virtual
Definition at line 270 of file AphidStringEmitter.cs.
References Append(), Emit(), and expression.
         {
             Emit(expression.ArrayExpression);
             Append("[");
             EmitTuple(expression.KeyExpressions);
             Append("]");
         }
EmitArrayExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitArrayExpression (ArrayExpression expression, bool isStatement = false) protected virtual
Definition at line 263 of file AphidStringEmitter.cs.
References Append(), and expression.
         {
             Append("[");
             EmitTuple(expression.Elements);
             Append("]");
         }
EmitBinaryOperatorExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitBinaryOperatorExpression (BinaryOperatorExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter, and Boxelder.AphidPythonEmitter.
Definition at line 209 of file AphidStringEmitter.cs.
References Append(), Emit(), and expression.
         {
             if (!isStatement)
             {
                 Append("(");
             }
             Emit(expression.LeftOperand);
             Append(GetBinaryOperator(expression.Operator));
             Emit(expression.RightOperand);
             if (!isStatement)
             {
                 Append(")");
             }
         }
EmitBooleanExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitBooleanExpression (BooleanExpression expression, bool isStatement = false) protected virtual
Reimplemented in Boxelder.AphidPythonEmitter.
Definition at line 250 of file AphidStringEmitter.cs.
References Append(), and expression.
         {
             Append(expression.Value ? "true" : "false");
         }
EmitBreakExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitBreakExpression (BreakExpression expression, bool isStatement = false) protected virtual
Reimplemented in Boxelder.AphidPythonEmitter.
Definition at line 55 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitCallExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitCallExpression (CallExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter, and Boxelder.AphidPythonEmitter.
Definition at line 255 of file AphidStringEmitter.cs.
References Append(), Emit(), and expression.
         {
             Emit(expression.FunctionExpression);
             Append("(");
             EmitTuple(expression.Args);
             Append(")");
         }
EmitDoWhileExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitDoWhileExpression (DoWhileExpression expression, bool isStatement = false) protected virtual
Definition at line 56 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitDynamicMemberExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitDynamicMemberExpression (DynamicMemberExpression expression, bool isStatement = false) protected virtual
Definition at line 57 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitExtendExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitExtendExpression (ExtendExpression expression, bool isStatement = false) protected virtual
Definition at line 58 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitForEachExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitForEachExpression (ForEachExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter, and Boxelder.AphidPythonEmitter.
Definition at line 59 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitForExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitForExpression (ForExpression expression, bool isStatement = false) protected virtual
Definition at line 60 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitFunctionExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitFunctionExpression (FunctionExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter.
Definition at line 61 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitGatorCloseExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitGatorCloseExpression (GatorCloseExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter.
Definition at line 62 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitGatorEmitExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitGatorEmitExpression (GatorEmitExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter.
Definition at line 63 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitGatorOpenExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitGatorOpenExpression (GatorOpenExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter.
Definition at line 64 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitHeader()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitHeader () protected virtual
Reimplemented in Boxelder.AphidPythonEmitter, and Coywolf.AphidPhpEmitter.
Definition at line 118 of file AphidStringEmitter.cs.
 { }
EmitIdentifierExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitIdentifierExpression (IdentifierExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter, and Boxelder.AphidPythonEmitter.
Definition at line 65 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitIfExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitIfExpression (IfExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter, and Boxelder.AphidPythonEmitter.
Definition at line 66 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitLoadLibraryExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitLoadLibraryExpression (LoadLibraryExpression expression, bool isStatement = false) protected virtual
Definition at line 67 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitLoadScriptExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitLoadScriptExpression (LoadScriptExpression expression, bool isStatement = false) protected virtual
Definition at line 68 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitNullExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitNullExpression (NullExpression expression, bool isStatement = false) protected virtual
Reimplemented in Boxelder.AphidPythonEmitter.
Definition at line 245 of file AphidStringEmitter.cs.
References Append().
         {
             Append("null");
         }
EmitNumberExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitNumberExpression (NumberExpression expression, bool isStatement = false) protected virtual
Reimplemented in Boxelder.AphidPythonEmitter.
Definition at line 239 of file AphidStringEmitter.cs.
References Append(), and expression.
         {
             Append(expression.Value);
         }
EmitObjectExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitObjectExpression (ObjectExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter, and Boxelder.AphidPythonEmitter.
Definition at line 69 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitPartialFunctionExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitPartialFunctionExpression (PartialFunctionExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter, and Boxelder.AphidPythonEmitter.
Definition at line 70 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitPatternExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitPatternExpression (PatternExpression expression, bool isStatement = false) protected virtual
Definition at line 71 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitPatternMatchingExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitPatternMatchingExpression (PatternMatchingExpression expression, bool isStatement = false) protected virtual
Definition at line 72 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitStringExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitStringExpression (StringExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter.
Definition at line 227 of file AphidStringEmitter.cs.
References Append(), expression, and Components.Aphid.Parser.StringParser.Parse().
         {
             var escaped = StringParser
                 .Parse(expression.Value)
                 .Replace("\\", "\\\\")
                 .Replace("\n", "\\n")
                 .Replace("\r", "\\r")
                 .Replace("\"", "\\\"");
             Append("\"{0}\"", escaped);
         }
EmitSwitchCase()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitSwitchCase (SwitchCase expression, bool isStatement = false) protected virtual
Definition at line 73 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitSwitchExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitSwitchExpression (SwitchExpression expression, bool isStatement = false) protected virtual
Definition at line 74 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitTernaryOperatorExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitTernaryOperatorExpression (TernaryOperatorExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter, and Boxelder.AphidPythonEmitter.
Definition at line 75 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitTextExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitTextExpression (TextExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter.
Definition at line 76 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitThisExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitThisExpression (ThisExpression expression, bool isStatement = false) protected virtual
Definition at line 77 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitTryExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitTryExpression (TryExpression expression, bool isStatement = false) protected virtual
Reimplemented in Boxelder.AphidPythonEmitter.
Definition at line 78 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EmitTuple()
void Components.Aphid.Compiler.AphidStringEmitter.EmitTuple (IEnumerable< AphidExpression > items, string prefix = "", string suffix = "") protected
Definition at line 278 of file AphidStringEmitter.cs.
References Append(), Emit(), first, and items.
Referenced by Coywolf.AphidPhpEmitter.EmitCallExpression(), Coywolf.AphidPhpEmitter.EmitClassMember(), Coywolf.AphidPhpEmitter.EmitEchoStatement(), Boxelder.AphidPythonEmitter.EmitFunctionDeclarationStatement(), Coywolf.AphidPhpEmitter.EmitFunctionExpression(), Boxelder.AphidPythonEmitter.EmitPartialFunctionExpression(), Coywolf.AphidPhpEmitter.EmitUnaryOperatorExpression(), and Coywolf.AphidPhpEmitter.EmitUsed().
         {
             var first = true;
             foreach (var arg in items)
             {
                 if (!first)
                 {
                     Append(", ");
                 }
                 else
                 {
                     first = false;
                 }
                 Append(prefix);
                 Emit(arg);
                 Append(suffix);
             }
         }
EmitUnaryOperatorExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitUnaryOperatorExpression (UnaryOperatorExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter.
Definition at line 194 of file AphidStringEmitter.cs.
References Append(), Emit(), and expression.
         {
             if (expression.IsPostfix)
             {
                 Emit(expression.Operand);
                 Append(GetUnaryPostfixOperator(expression.Operator));
             }
             else
             {
                 Append(GetUnaryPrefixOperator(expression.Operator));
                 Emit(expression.Operand);
             }
         }
EmitWhileExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EmitWhileExpression (WhileExpression expression, bool isStatement = false) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter, and Boxelder.AphidPythonEmitter.
Definition at line 79 of file AphidStringEmitter.g.cs.
 { throw new NotImplementedException(); }
EndExpression()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EndExpression (AphidExpression expression) protected virtual
Reimplemented in Coywolf.AphidPhpEmitter.
Definition at line 152 of file AphidStringEmitter.cs.
 { }
EndStatement()
virtual void Components.Aphid.Compiler.AphidStringEmitter.EndStatement (AphidExpression expression) protected virtual
Reimplemented in Boxelder.AphidPythonEmitter.
Definition at line 83 of file AphidStringEmitter.g.cs.
 { }
GetBinaryOperator()
virtual string Components.Aphid.Compiler.AphidStringEmitter.GetBinaryOperator (AphidTokenType op) protected virtual
Reimplemented in Boxelder.AphidPythonEmitter.
Definition at line 188 of file AphidStringEmitter.cs.
         {
             return GetOperator(_binaryOperators, op);
         }
GetOperator()
string Components.Aphid.Compiler.AphidStringEmitter.GetOperator (Dictionary< AphidTokenType, string > table, AphidTokenType op) protected
Definition at line 166 of file AphidStringEmitter.cs.
References out.
         {
             string s;
             if (!table.TryGetValue(op, out s))
             {
                 throw new NotImplementedException();
             }
             return s;
         }
GetTabs()
string Components.Aphid.Compiler.AphidStringEmitter.GetTabs () protected
Definition at line 88 of file AphidStringEmitter.cs.
Referenced by Boxelder.AphidPythonEmitter.BeginStatement(), Coywolf.AphidPhpEmitter.BeginStatement(), Coywolf.AphidPhpEmitter.EmitCallExpression(), Coywolf.AphidPhpEmitter.EmitClassDeclaration(), Coywolf.AphidPhpEmitter.EmitClassMember(), Coywolf.AphidPhpEmitter.EmitForEachExpression(), Coywolf.AphidPhpEmitter.EmitFunctionExpression(), Coywolf.AphidPhpEmitter.EmitIfExpression(), and Coywolf.AphidPhpEmitter.EmitWhileExpression().
         {
             return string.Join("", _tabs);
         }
GetUnaryPostfixOperator()
virtual string Components.Aphid.Compiler.AphidStringEmitter.GetUnaryPostfixOperator (AphidTokenType op) protected virtual
Definition at line 183 of file AphidStringEmitter.cs.
         {
             return GetOperator(_unaryPostfixOperators, op);
         }
GetUnaryPrefixOperator()
virtual string Components.Aphid.Compiler.AphidStringEmitter.GetUnaryPrefixOperator (AphidTokenType op) protected virtual
Reimplemented in Boxelder.AphidPythonEmitter.
Definition at line 178 of file AphidStringEmitter.cs.
         {
             return GetOperator(_unaryPrefixOperators, op);
         }
Indent()
void Components.Aphid.Compiler.AphidStringEmitter.Indent () protected
Definition at line 78 of file AphidStringEmitter.cs.
Referenced by Boxelder.AphidPythonEmitter.EmitBlock(), Coywolf.AphidPhpEmitter.EmitCallExpression(), Coywolf.AphidPhpEmitter.EmitClassDeclaration(), Coywolf.AphidPhpEmitter.EmitClassMember(), Boxelder.AphidPythonEmitter.EmitClassStatement(), Boxelder.AphidPythonEmitter.EmitForEachExpression(), Coywolf.AphidPhpEmitter.EmitForEachExpression(), Boxelder.AphidPythonEmitter.EmitFunctionDeclarationStatement(), Coywolf.AphidPhpEmitter.EmitFunctionExpression(), Boxelder.AphidPythonEmitter.EmitIfExpression(), Coywolf.AphidPhpEmitter.EmitIfExpression(), Boxelder.AphidPythonEmitter.EmitWhileExpression(), and Coywolf.AphidPhpEmitter.EmitWhileExpression().
         {
             _tabs.Push("    ");
         }
Unindent()
void Components.Aphid.Compiler.AphidStringEmitter.Unindent () protected
Definition at line 83 of file AphidStringEmitter.cs.
Referenced by Boxelder.AphidPythonEmitter.EmitBlock(), Coywolf.AphidPhpEmitter.EmitCallExpression(), Coywolf.AphidPhpEmitter.EmitClassDeclaration(), Coywolf.AphidPhpEmitter.EmitClassMember(), Boxelder.AphidPythonEmitter.EmitClassStatement(), Boxelder.AphidPythonEmitter.EmitForEachExpression(), Coywolf.AphidPhpEmitter.EmitForEachExpression(), Boxelder.AphidPythonEmitter.EmitFunctionDeclarationStatement(), Coywolf.AphidPhpEmitter.EmitFunctionExpression(), Boxelder.AphidPythonEmitter.EmitIfExpression(), Coywolf.AphidPhpEmitter.EmitIfExpression(), Boxelder.AphidPythonEmitter.EmitWhileExpression(), and Coywolf.AphidPhpEmitter.EmitWhileExpression().
         {
             _tabs.Pop();
         }
Member Data Documentation
_out
StringBuilder Components.Aphid.Compiler.AphidStringEmitter._out = new StringBuilder() protected
Definition at line 69 of file AphidStringEmitter.cs.
Property Documentation
Scope
Stack<List<AphidExpression> > Components.Aphid.Compiler.AphidStringEmitter.Scope get protected
Definition at line 74 of file AphidStringEmitter.cs.
Referenced by Coywolf.AphidPhpEmitter.EmitUsed().
         {
             get { return _scope; }
         }
The documentation for this class was generated from the following files:
c:/source/Aphid/Components.Aphid/Compiler/AphidStringEmitter.cs
c:/source/Aphid/Components.Aphid/Compiler/AphidStringEmitter.g.cs