Aphid Programming Language: Components.Aphid.Parser.AphidParser Class Reference
Components.Aphid.Parser.AphidParser Class Reference
Public Member Functions
AphidParser (List< AphidToken > tokens)
bool Match (AphidTokenType tokenType)
bool NextToken ()
bool PreviousToken ()
bool SetToken (int index)
System.Collections.Generic.List< AphidExpression > Parse ()
AphidExpression ParseExpression ()
Static Public Member Functions
static List< AphidExpression > Parse (List< AphidToken > tokens, string code)
static List< AphidExpression > Parse (List< AphidToken > tokens, string code, bool useImplicitReturns=true)
static List< AphidExpression > Parse (List< AphidToken > tokens, string code, string filename, bool useImplicitReturns=true)
static AphidExpression ParseExpression (string code)
static AphidExpression ParseExpression (List< AphidToken > tokens, string code)
static List< AphidExpression > Parse (string code)
static List< AphidExpression > Parse (string code, bool isTextDocument=false, bool useImplicitReturns=true)
static List< AphidExpression > Parse (string code, string filename, bool isTextDocument=false, bool useImplicitReturns=true)
static List< AphidExpression > ParseFile (string filename)
static List< AphidExpression > ParseFile (string filename, bool isTextDocument=false, bool useImplicitReturns=true)
Properties
AphidToken CurrentToken [get]
bool UseImplicitReturns [get, set]
Detailed Description
Definition at line 11 of file AphidParser.cs.
Constructor & Destructor Documentation
AphidParser()
Components.Aphid.Parser.AphidParser.AphidParser (List< AphidToken > tokens)
Definition at line 26 of file AphidParser.cs.
References tokens.
         {
             UseImplicitReturns = true;
             _tokens = tokens;
         }
Member Function Documentation
Match()
bool Components.Aphid.Parser.AphidParser.Match (AphidTokenType tokenType)
Definition at line 33 of file AphidParser.cs.
References Components.Aphid.Lexer.AphidToken.TokenType.
         {
             if (_currentToken.TokenType == tokenType)
             {
                 NextToken();
                 return true;
             }
             else
             {
                 throw new AphidParserException(_currentToken, tokenType);
             }
         }
NextToken()
bool Components.Aphid.Parser.AphidParser.NextToken ()
Definition at line 47 of file AphidParser.cs.
References i, Components.Aphid.Lexer.AphidToken.Index, and Components.Aphid.Lexer.AphidToken.Lexeme.
         {
             _tokenIndex++;
             if (_tokenIndex < _tokens.Count)
             {
                 _currentToken = _tokens[_tokenIndex];
                 return true;
             }
             else
             {
                 var i = _currentToken.Index + _currentToken.Lexeme.Length;
                 _currentToken = default(AphidToken);
                 _currentToken.Index = i;
                 return false;
             }
         }
Parse() [1/7]
static List<AphidExpression> Components.Aphid.Parser.AphidParser.Parse (List< AphidToken > tokens, string code) static
Definition at line 101 of file AphidParser.cs.
References code, Parse, and tokens.
Referenced by Components.Aphid.UI.AphidScopeObjectAutocompletionSource.GetWords(), Components.Aphid.Interpreter.AphidInterpreter.InterpretStream(), Components.Aphid.Interpreter.AphidLoader.LoadScript(), Components.Aphid.Parser.IncludeMutator.MutateCore(), Components.Aphid.Interpreter.AphidScriptOptimizer.Optimize(), Components.Aphid.Parser.AphidParser.ParseExpression(), Components.Aphid.Tests.Integration.Shared.AphidTests.ParseScript(), and Components.Aphid.Parser.ScriptMutator.ScriptMutator().
         {
             return Parse(tokens, code, useImplicitReturns: true);
         }
Parse() [2/7]
static List<AphidExpression> Components.Aphid.Parser.AphidParser.Parse (List< AphidToken > tokens, string code, bool useImplicitReturns = true) static
Definition at line 106 of file AphidParser.cs.
References code, Parse, and tokens.
         {
             return Parse(tokens, code, null, useImplicitReturns);
         }
Parse() [3/7]
static List<AphidExpression> Components.Aphid.Parser.AphidParser.Parse (List< AphidToken > tokens, string code, string filename, bool useImplicitReturns = true) static
Definition at line 114 of file AphidParser.cs.
References AphidParser, ast, code, Path, and tokens.
         {
             var parser = new AphidParser(tokens)
             {
                 UseImplicitReturns = useImplicitReturns
             };
             var ast = parser.Parse();
             new AphidCodeVisitor(
                 code,
                 filename != null ? Path.GetFullPath(filename) : null)
                 .Visit(ast);
             return ast;
         }
Parse() [4/7]
static List<AphidExpression> Components.Aphid.Parser.AphidParser.Parse (string code) static
Definition at line 154 of file AphidParser.cs.
References code, and Parse.
         {
             return Parse(code, useImplicitReturns: true);
         }
Parse() [5/7]
static List<AphidExpression> Components.Aphid.Parser.AphidParser.Parse (string code, bool isTextDocument = false, bool useImplicitReturns = true) static
Definition at line 159 of file AphidParser.cs.
References code, and Parse.
         {
             return Parse(code, null, isTextDocument, useImplicitReturns);
         }
Parse() [6/7]
static List<AphidExpression> Components.Aphid.Parser.AphidParser.Parse (string code, string filename, bool isTextDocument = false, bool useImplicitReturns = true) static
Definition at line 167 of file AphidParser.cs.
References code, lexer, and Parse.
         {
             var lexer = new AphidLexer(code);
             if (isTextDocument)
             {
                 lexer.SetTextMode();
             }
             return Parse(
                 lexer.GetTokens(),
                 code,
                 filename,
                 useImplicitReturns: useImplicitReturns);
         }
Parse() [7/7]
System.Collections.Generic.List<AphidExpression> Components.Aphid.Parser.AphidParser.Parse ()
Definition at line 2272 of file AphidParser.g.cs.
References ParseStatement.
         {
             var expressionSequence = new System.Collections.Generic.List<AphidExpression>();
             NextToken();
             for (
             ; ((_currentToken.TokenType == AphidTokenType.None)
                         == false);
             )
             {
                 expressionSequence.Add(ParseStatement());
             }
             return expressionSequence;
         }
ParseExpression() [1/3]
static AphidExpression Components.Aphid.Parser.AphidParser.ParseExpression (string code) static
Definition at line 135 of file AphidParser.cs.
References code, and ParseExpression.
Referenced by Components.Aphid.Serialization.AphidSerializer.Deserialize(), and Components.Aphid.UI.AphidCli.DumpExpression().
         {
             return ParseExpression(new AphidLexer(code).GetTokens(), code);
         }
ParseExpression() [2/3]
static AphidExpression Components.Aphid.Parser.AphidParser.ParseExpression (List< AphidToken > tokens, string code) static
Definition at line 140 of file AphidParser.cs.
References ast, code, Components.Aphid.Parser.AphidParser.Parse(), and tokens.
         {
             var ast = AphidParser.Parse(tokens, code);
             if (ast.Count != 1)
             {
                 throw new AphidParserException(
                     "Expected end of expression, found: {0}",
                     code.Substring(ast[1].Index));
             }
             return ast[0];
         }
ParseExpression() [3/3]
AphidExpression Components.Aphid.Parser.AphidParser.ParseExpression ()
Definition at line 2728 of file AphidParser.g.cs.
References ParseAssignmentExpression.
         {
             return ParseAssignmentExpression();
         }
ParseFile() [1/2]
static List<AphidExpression> Components.Aphid.Parser.AphidParser.ParseFile (string filename) static
Definition at line 187 of file AphidParser.cs.
Referenced by Components.Aphid.Tests.Integration.Shared.AphidTests.ParseScript().
         {
             return ParseFile(
                 filename,
                 isTextDocument: false,
                 useImplicitReturns: true);
         }
ParseFile() [2/2]
static List<AphidExpression> Components.Aphid.Parser.AphidParser.ParseFile (string filename, bool isTextDocument = false, bool useImplicitReturns = true) static
Definition at line 195 of file AphidParser.cs.
References Parse.
         {
             return Parse(
                 File.ReadAllText(filename),
                 filename,
                 isTextDocument,
                 useImplicitReturns);
         }
PreviousToken()
bool Components.Aphid.Parser.AphidParser.PreviousToken ()
Definition at line 66 of file AphidParser.cs.
References Components.Aphid.Lexer.AphidToken.Index.
         {
             if (_tokens.Count == 0 || _tokenIndex == 0)
             {
                 _currentToken = default(AphidToken);
                 _currentToken.Index = -1;
                 return false;
             }
             else
             {
                 _currentToken = _tokens[--_tokenIndex];
                 return true;
             }
         }
SetToken()
bool Components.Aphid.Parser.AphidParser.SetToken (int index)
Definition at line 84 of file AphidParser.cs.
References index, and Components.Aphid.Lexer.AphidToken.Index.
         {
             _tokenIndex = index;
             if (_tokenIndex < _tokens.Count)
             {
                 _currentToken = _tokens[_tokenIndex];
                 return true;
             }
             else
             {
                 _currentToken = default(AphidToken);
                 _currentToken.Index = -1;
                 return false;
             }
         }
Property Documentation
CurrentToken
AphidToken Components.Aphid.Parser.AphidParser.CurrentToken get
Definition at line 20 of file AphidParser.cs.
         {
             get { return _currentToken; }
         }
UseImplicitReturns
bool Components.Aphid.Parser.AphidParser.UseImplicitReturns get set
Definition at line 24 of file AphidParser.cs.
 { get; set; }
The documentation for this class was generated from the following files:
c:/source/Aphid/Components.Aphid/Parser/AphidParser.cs
c:/source/Aphid/Components.Aphid/Parser/AphidParser.g.cs