Aphid Programming Language: Boxelder.AphidPythonEmitter Class Reference
Boxelder.AphidPythonEmitter Class Reference
Public Member Functions
override string Compile (string filename, List< AphidExpression > ast)
Public Member Functions inherited from Components.Aphid.Compiler.AphidStringEmitter
virtual void Emit (List< AphidExpression > statements)
Protected Member Functions
override void BeginStatement (AphidExpression expression)
override void EndStatement (AphidExpression expression)
override void EmitHeader ()
override void EmitNumberExpression (NumberExpression expression, bool isStatement=false)
override void EmitBooleanExpression (BooleanExpression expression, bool isStatement=false)
override void EmitIdentifierExpression (IdentifierExpression expression, bool isStatement=false)
override void EmitNullExpression (NullExpression expression, bool isStatement=false)
void EmitIdentifierStatement (IdentifierExpression expression)
override void EmitBinaryOperatorExpression (BinaryOperatorExpression expression, bool isStatement=false)
override void EmitTernaryOperatorExpression (TernaryOperatorExpression expression, bool isStatement=false)
void EmitFunctionDeclarationStatement (BinaryOperatorExpression expression, bool isMember)
override void EmitPartialFunctionExpression (PartialFunctionExpression expression, bool isStatement=false)
override void EmitIfExpression (IfExpression expression, bool isStatement=false)
override void EmitForEachExpression (ForEachExpression expression, bool isStatement=false)
override void EmitWhileExpression (WhileExpression expression, bool isStatement=false)
override void EmitBreakExpression (BreakExpression expression, bool isStatement=false)
override void EmitCallExpression (CallExpression expression, bool isStatement=false)
override void EmitObjectExpression (ObjectExpression expression, bool isStatement=false)
void EmitDictionaryExpression (ObjectExpression expression)
void EmitObjectStatement (ObjectExpression statement)
void EmitClassStatement (ObjectExpression statement, ClassDeclarationAttributes attributes, string[] unparsedAttributes)
override void EmitTryExpression (TryExpression expression, bool isStatement=false)
void EmitImportStatement (CallExpression statement)
void EmitFromStatement (CallExpression statement)
void EmitRaw (CallExpression statement)
void EmitBlock (List< AphidExpression > block)
override string GetBinaryOperator (AphidTokenType op)
override string GetUnaryPrefixOperator (AphidTokenType op)
Protected Member Functions inherited from Components.Aphid.Compiler.AphidStringEmitter
void Indent ()
void Unindent ()
string GetTabs ()
void AppendTabs ()
void AppendLine ()
void Append (string format, params object[] args)
void Append (string value)
void Append (object value)
virtual void BeginExpression (AphidExpression expression)
virtual void EndExpression (AphidExpression expression)
string GetOperator (Dictionary< AphidTokenType, string > table, AphidTokenType op)
virtual string GetUnaryPostfixOperator (AphidTokenType op)
virtual void EmitUnaryOperatorExpression (UnaryOperatorExpression expression, bool isStatement=false)
virtual void EmitStringExpression (StringExpression expression, bool isStatement=false)
virtual void EmitArrayExpression (ArrayExpression expression, bool isStatement=false)
virtual void EmitArrayAccessExpression (ArrayAccessExpression expression, bool isStatement=false)
void EmitTuple (IEnumerable< AphidExpression > items, string prefix="", string suffix="")
virtual void Emit (AphidExpression expression, bool isStatement=false)
virtual void EmitDoWhileExpression (DoWhileExpression expression, bool isStatement=false)
virtual void EmitDynamicMemberExpression (DynamicMemberExpression expression, bool isStatement=false)
virtual void EmitExtendExpression (ExtendExpression expression, bool isStatement=false)
virtual void EmitForExpression (ForExpression expression, bool isStatement=false)
virtual void EmitFunctionExpression (FunctionExpression expression, bool isStatement=false)
virtual void EmitGatorCloseExpression (GatorCloseExpression expression, bool isStatement=false)
virtual void EmitGatorEmitExpression (GatorEmitExpression expression, bool isStatement=false)
virtual void EmitGatorOpenExpression (GatorOpenExpression expression, bool isStatement=false)
virtual void EmitLoadLibraryExpression (LoadLibraryExpression expression, bool isStatement=false)
virtual void EmitLoadScriptExpression (LoadScriptExpression expression, bool isStatement=false)
virtual void EmitPatternExpression (PatternExpression expression, bool isStatement=false)
virtual void EmitPatternMatchingExpression (PatternMatchingExpression expression, bool isStatement=false)
virtual void EmitSwitchCase (SwitchCase expression, bool isStatement=false)
virtual void EmitSwitchExpression (SwitchExpression expression, bool isStatement=false)
virtual void EmitTextExpression (TextExpression expression, bool isStatement=false)
virtual void EmitThisExpression (ThisExpression expression, bool isStatement=false)
Additional Inherited Members
Protected Attributes inherited from Components.Aphid.Compiler.AphidStringEmitter
StringBuilder _out = new StringBuilder()
Properties inherited from Components.Aphid.Compiler.AphidStringEmitter
Stack< List< AphidExpression > > Scope [get]
Detailed Description
Definition at line 12 of file AphidPythonEmitter.cs.
Member Function Documentation
BeginStatement()
override void Boxelder.AphidPythonEmitter.BeginStatement (AphidExpression expression) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 58 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), and Components.Aphid.Compiler.AphidStringEmitter.GetTabs().
         {
             Append(GetTabs());
             _isEndingStatements = false;
         }
Compile()
override string Boxelder.AphidPythonEmitter.Compile (string filename, List< AphidExpression > ast) virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 32 of file AphidPythonEmitter.cs.
References ast.
         {
             var mutators = new AphidMutator[]
             {
                 new IncludeMutator(),
                 new AphidMacroMutator(),
                 new PipelineToCallMutator(),
                 new PartialOperatorMutator(),
                 new UnaryExpressionMutator(),
                 new LambdaPositionMutator(),
                 new SwitchToIfMutator(),
             };
             foreach (var mutator in mutators)
             {
                 ast = mutator.MutateRecursively(ast);
             }
             return base.Compile(filename, ast);
         }
EmitBinaryOperatorExpression()
override void Boxelder.AphidPythonEmitter.EmitBinaryOperatorExpression (BinaryOperatorExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 135 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Components.Aphid.Compiler.AphidStringEmitter.Emit(), Boxelder.AphidPythonEmitter.EmitFunctionDeclarationStatement(), expression, and Boxelder.AphidPythonEmitter.GetBinaryOperator().
         {
             if (expression.RightOperand.Type != AphidExpressionType.FunctionExpression)
             {
                 var useParens = !isStatement && expression.Operator != AphidTokenType.AssignmentOperator;
                 if (useParens)
                 {
                     Append("(");
                 }
                 Emit(expression.LeftOperand);
                 Append(GetBinaryOperator(expression.Operator));
                 Emit(expression.RightOperand);
                 if (useParens)
                 {
                     Append(")");
                 }
             }
             else
             {
                 EmitFunctionDeclarationStatement(expression, isMember: false);
             }
         }
EmitBlock()
void Boxelder.AphidPythonEmitter.EmitBlock (List< AphidExpression > block) protected
Definition at line 494 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Emit(), Components.Aphid.Compiler.AphidStringEmitter.Indent(), and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
Referenced by Boxelder.AphidPythonEmitter.EmitTryExpression().
         {
             Indent();
             Emit(block);
             Unindent();
         }
EmitBooleanExpression()
override void Boxelder.AphidPythonEmitter.EmitBooleanExpression (BooleanExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 89 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), and expression.
         {
             Append(expression.Value ? "True" : "False");
         }
EmitBreakExpression()
override void Boxelder.AphidPythonEmitter.EmitBreakExpression (BreakExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 264 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append().
         {
             Append("break");
         }
EmitCallExpression()
override void Boxelder.AphidPythonEmitter.EmitCallExpression (CallExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 269 of file AphidPythonEmitter.cs.
References Boxelder.AphidPythonEmitter.EmitFromStatement(), Boxelder.AphidPythonEmitter.EmitImportStatement(), Boxelder.AphidPythonEmitter.EmitRaw(), and expression.
         {
             if (expression.FunctionExpression.Type == AphidExpressionType.IdentifierExpression)
             {
                 var id = expression.FunctionExpression.ToIdentifier().Identifier;
                 if (isStatement)
                 {
                     switch (id)
                     {
                         case "import":
                             EmitImportStatement(expression);
                             return;
                         case "from":
                             EmitFromStatement(expression);
                             return;
                     }
                 }
                 switch (id)
                 {
                     case "__emit":
                         EmitRaw(expression);
                         return;
                 }
             }
             base.EmitCallExpression(expression, isStatement);
         }
EmitClassStatement()
void Boxelder.AphidPythonEmitter.EmitClassStatement (ObjectExpression statement, ClassDeclarationAttributes attributes, string [] unparsedAttributes) protected
Definition at line 364 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Components.Aphid.Compiler.AphidStringEmitter.AppendLine(), Components.Aphid.Compiler.AphidStringEmitter.AppendTabs(), Components.Aphid.Compiler.AphidStringEmitter.Emit(), Boxelder.AphidPythonEmitter.EmitFunctionDeclarationStatement(), Components.Aphid.Parser.IdentifierExpression.Identifier, Components.Aphid.Parser.ObjectExpression.Identifier, Components.Aphid.Compiler.AphidStringEmitter.Indent(), Boxelder.ClassDeclarationAttributes.IsAutoInit, Boxelder.ClassDeclarationAttributes.IsIter, p, Components.Aphid.Parser.ObjectExpression.Pairs, and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
Referenced by Boxelder.AphidPythonEmitter.EmitObjectStatement().
         {
             if (unparsedAttributes.Length > 1)
             {
                 throw new NotImplementedException();
             }
             if (attributes.IsIter)
             {
                 statement.Pairs.Add(CreateIterExpression());
             }
             if (attributes.IsAutoInit)
             {
                 UpdateInitExpression(statement);
             }
             Append(
                 "class {0}({1}):",
                 statement.Identifier.Identifier,
                 unparsedAttributes.Any() ? unparsedAttributes.First() : "");
             Indent();
             AppendLine();
             foreach (var p in statement.Pairs)
             {
                 AppendTabs();
                 if (p.RightOperand.Type != AphidExpressionType.FunctionExpression)
                 {
                     Emit(p.LeftOperand);
                     Append(" = ");
                     Emit(p.RightOperand);
                     AppendLine();
                 }
                 else
                 {
                     EmitFunctionDeclarationStatement(p, isMember: true);
                 }
             }
             Unindent();
             AppendLine();
         }
EmitDictionaryExpression()
void Boxelder.AphidPythonEmitter.EmitDictionaryExpression (ObjectExpression expression) protected
Definition at line 312 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Components.Aphid.Compiler.AphidStringEmitter.Emit(), and expression.
Referenced by Boxelder.AphidPythonEmitter.EmitObjectExpression().
         {
             if (expression.Identifier != null)
             {
                 throw new NotImplementedException();
             }
             Append("{");
             var isFirst = true;
             foreach (var kvp in expression.Pairs)
             {
                 if (!isFirst)
                 {
                     Append(", ");
                 }
                 else
                 {
                     isFirst = false;
                 }
                 var exp = new StringExpression(
                     string.Format("'{0}'", kvp.LeftOperand.ToIdentifier().Identifier));
                 Emit(exp);
                 Append(": ");
                 Emit(kvp.RightOperand);
             }
             Append("}");
         }
EmitForEachExpression()
override void Boxelder.AphidPythonEmitter.EmitForEachExpression (ForEachExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 242 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Components.Aphid.Compiler.AphidStringEmitter.Emit(), expression, Components.Aphid.Compiler.AphidStringEmitter.Indent(), and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
         {
             Append("for ");
             Emit(expression.Element);
             Append(" in ");
             Emit(expression.Collection);
             Append(":\r\n");
             Indent();
             Emit(expression.Body);
             Unindent();
         }
EmitFromStatement()
void Boxelder.AphidPythonEmitter.EmitFromStatement (CallExpression statement) protected
Definition at line 468 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), and Components.Aphid.Parser.CallExpression.Args.
Referenced by Boxelder.AphidPythonEmitter.EmitCallExpression().
         {
             if (statement.Args.Count < 2 || !HasAllStringArgs(statement))
             {
                 throw new InvalidOperationException();
             }
             // Injectable, should be fixed.
             var strings = ParseStringArgs(statement);
             Append(
                 "from {0} import {1}",
                 strings.First(),
                 string.Join(", ", strings.Skip(1)));
         }
EmitFunctionDeclarationStatement()
void Boxelder.AphidPythonEmitter.EmitFunctionDeclarationStatement (BinaryOperatorExpression expression, bool isMember) protected
Definition at line 180 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Components.Aphid.Compiler.AphidStringEmitter.AppendLine(), Components.Aphid.Compiler.AphidStringEmitter.AppendTabs(), Components.Aphid.Compiler.AphidStringEmitter.Emit(), Components.Aphid.Compiler.AphidStringEmitter.EmitTuple(), expression, func, id, Components.Aphid.Compiler.AphidStringEmitter.Indent(), out, and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
Referenced by Boxelder.AphidPythonEmitter.EmitBinaryOperatorExpression(), and Boxelder.AphidPythonEmitter.EmitClassStatement().
         {
             var id = expression.LeftOperand.ToIdentifier();
             var func = expression.RightOperand.ToFunction();
             string[] unparsed;
             var attrs = AphidAttributeParser.Parse<FunctionDeclarationAttributes>(id, out unparsed);
             if ((!isMember && attrs.IsStatic) || unparsed.Any())
             {
                 throw new NotImplementedException();
             }
             if (attrs.IsStatic)
             {
                 Append("@staticmethod\r\n");
                 AppendTabs();
             }
             Append("def {0}(", id.Identifier);
             if (isMember && !attrs.IsStatic)
             {
                 Append("self{0}", func.Args.Any() ? ", " : "");
             }
             EmitTuple(func.Args);
             Append("):\r\n");
             Indent();
             Emit(func.Body);
             Unindent();
             AppendLine();
         }
EmitHeader()
override void Boxelder.AphidPythonEmitter.EmitHeader () protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 73 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), and string.
         {
             var version = Assembly.GetExecutingAssembly().GetName().Version;
             var border = new string('#', 64) + "\r\n";
             Append(
                 "{0}# Compiled from Aphid to Python by Boxelder {1}\r\n# {2}\r\n{0}",
                 border,
                 version,
                 "https://github.com/John-Leitch/Aphid/releases");
         }
EmitIdentifierExpression()
override void Boxelder.AphidPythonEmitter.EmitIdentifierExpression (IdentifierExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 94 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Boxelder.AphidPythonEmitter.EmitIdentifierStatement(), and expression.
         {
             if (!isStatement)
             {
                 if (expression.Attributes.Any())
                 {
                     throw new NotImplementedException();
                 }
                 Append(expression.Identifier);
             }
             else
             {
                 EmitIdentifierStatement(expression);
             }
         }
EmitIdentifierStatement()
void Boxelder.AphidPythonEmitter.EmitIdentifierStatement (IdentifierExpression expression) protected
Definition at line 116 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), expression, and out.
Referenced by Boxelder.AphidPythonEmitter.EmitIdentifierExpression().
         {
             string[] unparsed;
             var attrs = AphidAttributeParser.Parse<IdentifierStatementAttributes>(expression, out unparsed);
             if (unparsed.Any())
             {
                 throw new NotImplementedException();
             }
             else if (attrs.IsThrow)
             {
                 Append("raise {0}", expression.Identifier);
             }
             else
             {
                 throw new NotImplementedException();
             }
         }
EmitIfExpression()
override void Boxelder.AphidPythonEmitter.EmitIfExpression (IfExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 223 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Components.Aphid.Compiler.AphidStringEmitter.AppendTabs(), Components.Aphid.Compiler.AphidStringEmitter.Emit(), expression, Components.Aphid.Compiler.AphidStringEmitter.Indent(), and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
         {
             Append("if ");
             Emit(expression.Condition);
             Append(":\r\n");
             Indent();
             Emit(expression.Body);
             Unindent();
             if (expression.ElseBody != null && expression.ElseBody.Any())
             {
                 AppendTabs();
                 Append("else:\r\n");
                 Indent();
                 Emit(expression.ElseBody);
                 Unindent();
             }
         }
EmitImportStatement()
void Boxelder.AphidPythonEmitter.EmitImportStatement (CallExpression statement) protected
Definition at line 455 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), and Components.Aphid.Parser.CallExpression.Args.
Referenced by Boxelder.AphidPythonEmitter.EmitCallExpression().
         {
             if (!statement.Args.Any() || !HasAllStringArgs(statement))
             {
                 throw new NotImplementedException();
             }
             Append("import ");
             // Injectable, should be fixed.
             var names = string.Join(", ", ParseStringArgs(statement));
             Append("{0}", names);
         }
EmitNullExpression()
override void Boxelder.AphidPythonEmitter.EmitNullExpression (NullExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 111 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append().
         {
             Append("None");
         }
EmitNumberExpression()
override void Boxelder.AphidPythonEmitter.EmitNumberExpression (NumberExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 84 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), and expression.
         {
             Append(expression.Value);
         }
EmitObjectExpression()
override void Boxelder.AphidPythonEmitter.EmitObjectExpression (ObjectExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 300 of file AphidPythonEmitter.cs.
References Boxelder.AphidPythonEmitter.EmitDictionaryExpression(), Boxelder.AphidPythonEmitter.EmitObjectStatement(), and expression.
         {
             if (isStatement)
             {
                 EmitObjectStatement(expression);
             }
             else
             {
                 EmitDictionaryExpression(expression);
             }
         }
EmitObjectStatement()
void Boxelder.AphidPythonEmitter.EmitObjectStatement (ObjectExpression statement) protected
Definition at line 344 of file AphidPythonEmitter.cs.
References Boxelder.AphidPythonEmitter.EmitClassStatement(), Components.Aphid.Parser.ObjectExpression.Identifier, and out.
Referenced by Boxelder.AphidPythonEmitter.EmitObjectExpression().
         {
             if (statement.Identifier == null)
             {
                 throw new NotImplementedException();
             }
             string[] otherAttrs;
             var attrs = AphidAttributeParser.Parse<ClassDeclarationAttributes>(statement.Identifier, out otherAttrs);
             if (attrs.IsClass)
             {
                 EmitClassStatement(statement, attrs, otherAttrs);
             }
             else
             {
                 throw new NotImplementedException();
             }
         }
EmitPartialFunctionExpression()
override void Boxelder.AphidPythonEmitter.EmitPartialFunctionExpression (PartialFunctionExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 213 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Components.Aphid.Compiler.AphidStringEmitter.Emit(), Components.Aphid.Compiler.AphidStringEmitter.EmitTuple(), and expression.
         {
             var id = NextVarId();
             Append("(lambda {0}:", id);
             Emit(expression.Call.FunctionExpression);
             Append("(");
             EmitTuple(expression.Call.Args);
             Append(", {0}))", id);
         }
EmitRaw()
void Boxelder.AphidPythonEmitter.EmitRaw (CallExpression statement) protected
Definition at line 484 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), and Components.Aphid.Parser.CallExpression.Args.
Referenced by Boxelder.AphidPythonEmitter.EmitCallExpression().
         {
             if (statement.Args.Count != 1 || !HasAllStringArgs(statement))
             {
                 throw new NotImplementedException();
             }
             Append(ParseStringArgs(statement).Single());
         }
EmitTernaryOperatorExpression()
override void Boxelder.AphidPythonEmitter.EmitTernaryOperatorExpression (TernaryOperatorExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 161 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Components.Aphid.Compiler.AphidStringEmitter.Emit(), and expression.
         {
             switch (expression.Operator)
             {
                 case AphidTokenType.ConditionalOperator:
                     Append("((");
                     Emit(expression.SecondOperand);
                     Append(") if (");
                     Emit(expression.FirstOperand);
                     Append(") else (");
                     Emit(expression.ThirdOperand);
                     Append("))");
                     break;
                 default:
                     throw new NotImplementedException();
             }
         }
EmitTryExpression()
override void Boxelder.AphidPythonEmitter.EmitTryExpression (TryExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 413 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Boxelder.AphidPythonEmitter.EmitBlock(), expression, and x.
         {
             Append("try:\r\n");
             EmitBlock(expression.TryBody);
             if (expression.CatchBody != null)
             {
                 if (expression.CatchArg == null)
                 {
                     AppendStatement("except:\r\n");
                 }
                 else
                 {
                     var attrs = string.Join(
                         ", ",
                         expression.CatchArg.Attributes.Any() ?
                         expression.CatchArg.Attributes
                             .Select(x => x.Identifier)
                             .ToArray() :
                         new[] { "BaseException" });
                     AppendStatement(
                         "except ({0}) as {1}:\r\n",
                         attrs,
                         expression.CatchArg.Identifier);
                 }
                 EmitBlock(expression.CatchBody);
             }
             if (expression.FinallyBody != null)
             {
                 AppendStatement("finally:\r\n");
                 EmitBlock(expression.FinallyBody);
             }
         }
EmitWhileExpression()
override void Boxelder.AphidPythonEmitter.EmitWhileExpression (WhileExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 254 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Components.Aphid.Compiler.AphidStringEmitter.Emit(), expression, Components.Aphid.Compiler.AphidStringEmitter.Indent(), and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
         {
             Append("while ");
             Emit(expression.Condition);
             Append(":\r\n");
             Indent();
             Emit(expression.Body);
             Unindent();
         }
EndStatement()
override void Boxelder.AphidPythonEmitter.EndStatement (AphidExpression expression) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 64 of file AphidPythonEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.AppendLine().
         {
             if (!_isEndingStatements)
             {
                 AppendLine();
                 _isEndingStatements = true;
             }
         }
GetBinaryOperator()
override string Boxelder.AphidPythonEmitter.GetBinaryOperator (AphidTokenType op) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 508 of file AphidPythonEmitter.cs.
References out, and value.
Referenced by Boxelder.AphidPythonEmitter.EmitBinaryOperatorExpression().
         {
             string value;
             return !_binaryOperators.TryGetValue(op, out value) ?
                 base.GetBinaryOperator(op) :
                 value;
         }
GetUnaryPrefixOperator()
override string Boxelder.AphidPythonEmitter.GetUnaryPrefixOperator (AphidTokenType op) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 517 of file AphidPythonEmitter.cs.
References out, and value.
         {
             string value;
             return !_unaryPrefixOperators.TryGetValue(op, out value) ?
                 base.GetUnaryPrefixOperator(op) :
                 value;
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Boxelder/AphidPythonEmitter.cs