Aphid Programming Language: Components.Aphid.Tests.Integration.Shared.AphidTests Class Reference
Components.Aphid.Tests.Integration.Shared.AphidTests Class Reference
Static Public Member Functions
static void IsFalse (bool value)
static void IsTrue (bool value)
static void IsFoo (object value)
static void Is9 (object value)
static void IsNull (object value)
static void NotNull (object value)
static void IsFail (Action action)
static void AllFail (params Action[] actions)
static void IsThrow (Action action)
static void AllThrow (params Action[] actions)
static void IsThrow< TException > (Action action)
static void AllThrow< TException > (params Action[] actions)
Protected Member Functions
virtual List< AphidExpression > ParseScript (AphidInterpreter interpreter, string script)
AphidInterpreter GetNextInterpreter ()
AphidObject Execute (string script)
void Execute (string script, Action< AphidObject > action)
void Is (string script, Func< AphidObject, bool > predicate)
void Is< TValue > (string script, Func< TValue, bool > predicate)
List< AphidToken > GetTokens (string script)
void AssertTokens (string script, AphidToken[] tokens)
AphidToken Token (AphidTokenType type, string lexeme)
AphidToken Token (AphidTokenType type)
void AssertEquals (object expected, string script)
void AssertFoo (string script)
void Assert9 (string script)
void AssertTrue (string script)
void AssertFalse (string script)
void AssertExpEquals (object expected, string expression)
void AssertExpFoo (string expression)
void AssertExp9 (string expression)
void AssertExpTrue (string expression)
void AssertExpFalse (string expression)
void AssertCollectionIs< TElement > (string script, params TElement[] expected)
Properties
virtual bool LoadStd [get]
Detailed Description
Definition at line 20 of file AphidTests.cs.
Member Function Documentation
AllFail()
static void Components.Aphid.Tests.Integration.Shared.AphidTests.AllFail (params Action [] actions) static
Definition at line 192 of file AphidTests.cs.
         {
             CollectionAssert.IsNotEmpty(actions);
             actions.Iter(IsFail);
         }
AllThrow()
static void Components.Aphid.Tests.Integration.Shared.AphidTests.AllThrow (params Action [] actions) static
Definition at line 203 of file AphidTests.cs.
         {
             CollectionAssert.IsNotEmpty(actions);
             actions.Iter(IsThrow);
         }
AllThrow< TException >()
static void Components.Aphid.Tests.Integration.Shared.AphidTests.AllThrow< TException > (params Action [] actions) static
Type Constraints
TException : Exception
Definition at line 215 of file AphidTests.cs.
                              : Exception
         {
             CollectionAssert.IsNotEmpty(actions);
             actions.Iter(IsThrow<TException>);
         }
Assert9()
void Components.Aphid.Tests.Integration.Shared.AphidTests.Assert9 (string script) protected
Definition at line 232 of file AphidTests.cs.
References script.
         {
             AssertEquals(9m, script);
         }
AssertCollectionIs< TElement >()
void Components.Aphid.Tests.Integration.Shared.AphidTests.AssertCollectionIs< TElement > (string script, params TElement [] expected) protected
Definition at line 277 of file AphidTests.cs.
References script.
         {
             CollectionAssert.AreEqual(expected, (IEnumerable)Execute(script).Value);
         }
AssertEquals()
void Components.Aphid.Tests.Integration.Shared.AphidTests.AssertEquals (object expected, string script) protected
Definition at line 222 of file AphidTests.cs.
References script.
         {
             Assert.AreEqual(expected, Execute(script).Value);
         }
AssertExp9()
void Components.Aphid.Tests.Integration.Shared.AphidTests.AssertExp9 (string expression) protected
Definition at line 262 of file AphidTests.cs.
References expression.
         {
             Assert9(CreateStatement(expression));
         }
AssertExpEquals()
void Components.Aphid.Tests.Integration.Shared.AphidTests.AssertExpEquals (object expected, string expression) protected
Definition at line 252 of file AphidTests.cs.
References expression.
         {
             AssertEquals(expected, CreateStatement(expression));
         }
AssertExpFalse()
void Components.Aphid.Tests.Integration.Shared.AphidTests.AssertExpFalse (string expression) protected
Definition at line 272 of file AphidTests.cs.
References expression.
         {
             AssertFalse(CreateStatement(expression));
         }
AssertExpFoo()
void Components.Aphid.Tests.Integration.Shared.AphidTests.AssertExpFoo (string expression) protected
Definition at line 257 of file AphidTests.cs.
References expression.
         {
             AssertFoo(CreateStatement(expression));
         }
AssertExpTrue()
void Components.Aphid.Tests.Integration.Shared.AphidTests.AssertExpTrue (string expression) protected
Definition at line 267 of file AphidTests.cs.
References expression.
         {
             AssertTrue(CreateStatement(expression));
         }
AssertFalse()
void Components.Aphid.Tests.Integration.Shared.AphidTests.AssertFalse (string script) protected
Definition at line 242 of file AphidTests.cs.
References script.
         {
             AssertEquals(false, script);
         }
AssertFoo()
void Components.Aphid.Tests.Integration.Shared.AphidTests.AssertFoo (string script) protected
Definition at line 227 of file AphidTests.cs.
References script.
         {
             AssertEquals("foo", script);
         }
AssertTokens()
void Components.Aphid.Tests.Integration.Shared.AphidTests.AssertTokens (string script, AphidToken [] tokens) protected
Definition at line 131 of file AphidTests.cs.
References i, script, and tokens.
         {
             var tokens2 = GetTokens(script);
             Assert.AreEqual(tokens.Length, tokens2.Count);
             for (int i = 0; i < tokens.Length; i++)
             {
                 Assert.AreEqual(tokens[i].TokenType, tokens2[i].TokenType);
                 if (tokens[i].Lexeme != null)
                 {
                     Assert.AreEqual(tokens[i].Lexeme, tokens2[i].Lexeme);
                 }
             }
         }
AssertTrue()
void Components.Aphid.Tests.Integration.Shared.AphidTests.AssertTrue (string script) protected
Definition at line 237 of file AphidTests.cs.
References script.
         {
             AssertEquals(true, script);
         }
Execute() [1/2]
AphidObject Components.Aphid.Tests.Integration.Shared.AphidTests.Execute (string script) protected
Definition at line 96 of file AphidTests.cs.
References Components.Aphid.Interpreter.AphidInterpreter.GetReturnValue(), Components.Aphid.Interpreter.AphidInterpreter.Interpret(), Components.Aphid.Interpreter.AphidInterpreter.Loader, Path, script, and Components.Aphid.Interpreter.AphidLoader.SearchPaths.
         {
             AphidInterpreter interpreter;
             lock (_nextInterpreter)
             {
                 interpreter = _nextInterpreter.Value ?? new AphidInterpreter();
                 _nextInterpreter.Value = null;
             }
             interpreter.Loader.SearchPaths.Add(Path.Combine(Environment.CurrentDirectory, "Library"));
             interpreter.Interpret(ParseScript(interpreter, script));
             return interpreter.GetReturnValue();
         }
Execute() [2/2]
void Components.Aphid.Tests.Integration.Shared.AphidTests.Execute (string script, Action< AphidObject > action) protected
Definition at line 111 of file AphidTests.cs.
References script.
         {
             action(Execute(script));
         }
GetNextInterpreter()
AphidInterpreter Components.Aphid.Tests.Integration.Shared.AphidTests.GetNextInterpreter () protected
Definition at line 86 of file AphidTests.cs.
         {
             lock (_nextInterpreter)
             {
                 return _nextInterpreter.Value != null ?
                     _nextInterpreter.Value :
                     _nextInterpreter.Value = new AphidInterpreter();
             }
         }
GetTokens()
List<AphidToken> Components.Aphid.Tests.Integration.Shared.AphidTests.GetTokens (string script) protected
Definition at line 126 of file AphidTests.cs.
References Components.Aphid.Lexer.AphidLexer.GetAllTokens(), and script.
         {
             return new AphidLexer(script).GetAllTokens();
         }
Is()
void Components.Aphid.Tests.Integration.Shared.AphidTests.Is (string script, Func< AphidObject, bool > predicate) protected
Definition at line 116 of file AphidTests.cs.
References predicate, and script.
         {
             Assert.IsTrue(predicate(Execute(script)));
         }
Is9()
static void Components.Aphid.Tests.Integration.Shared.AphidTests.Is9 (object value) static
Definition at line 172 of file AphidTests.cs.
References value.
         {
             Assert.AreEqual(9m, value);
         }
Is< TValue >()
void Components.Aphid.Tests.Integration.Shared.AphidTests.Is< TValue > (string script, Func< TValue, bool > predicate) protected
Definition at line 121 of file AphidTests.cs.
References predicate, and script.
         {
             Assert.IsTrue(predicate((TValue)Execute(script).Value));
         }
IsFail()
static void Components.Aphid.Tests.Integration.Shared.AphidTests.IsFail (Action action) static
Definition at line 187 of file AphidTests.cs.
         {
             IsThrow<AssertionException>(action);
         }
IsFalse()
static void Components.Aphid.Tests.Integration.Shared.AphidTests.IsFalse (bool value) static
Definition at line 157 of file AphidTests.cs.
References value.
         {
             Assert.IsFalse(value);
         }
IsFoo()
static void Components.Aphid.Tests.Integration.Shared.AphidTests.IsFoo (object value) static
Definition at line 167 of file AphidTests.cs.
References value.
         {
             Assert.AreEqual("foo", value);
         }
IsNull()
static void Components.Aphid.Tests.Integration.Shared.AphidTests.IsNull (object value) static
Definition at line 177 of file AphidTests.cs.
References value.
         {
             Assert.IsNull(value);
         }
IsThrow()
static void Components.Aphid.Tests.Integration.Shared.AphidTests.IsThrow (Action action) static
Definition at line 198 of file AphidTests.cs.
         {
             Assert.Catch(() => action());
         }
IsThrow< TException >()
static void Components.Aphid.Tests.Integration.Shared.AphidTests.IsThrow< TException > (Action action) static
Type Constraints
TException : Exception
Definition at line 209 of file AphidTests.cs.
                              : Exception
         {
             Assert.Catch<TException>(() => action());
         }
IsTrue()
static void Components.Aphid.Tests.Integration.Shared.AphidTests.IsTrue (bool value) static
Definition at line 162 of file AphidTests.cs.
References value.
         {
             Assert.IsTrue(value);
         }
NotNull()
static void Components.Aphid.Tests.Integration.Shared.AphidTests.NotNull (object value) static
Definition at line 182 of file AphidTests.cs.
References value.
         {
             Assert.NotNull(value);
         }
ParseScript()
virtual List<AphidExpression> Components.Aphid.Tests.Integration.Shared.AphidTests.ParseScript (AphidInterpreter interpreter, string script) protected virtual
Reimplemented in Components.Aphid.Tests.Integration.QueryTests.
Definition at line 51 of file AphidTests.cs.
References Components.Aphid.Interpreter.AphidLoader.FindScriptFile(), Components.Aphid.Interpreter.AphidInterpreter.Loader, Components.Aphid.Parser.AphidParser.Parse(), Components.Aphid.Parser.AphidParser.ParseFile(), and script.
         {
             List<AphidExpression> initNodes = null;
             if (LoadStd)
             {
                 lock (_cachedStdNodesSync)
                 {
                     if (_cachedStdNodes == null)
                     {
                         var stdFile = interpreter.Loader.FindScriptFile(null, "Std.alx");
                         _cachedStdNodes = PreprocessAst(AphidParser.ParseFile(stdFile));
                         _cachedStdNodes.Add(_cachedUsing);
                     }
                     initNodes = _cachedStdNodes;
                 }
             }
             else
             {
                 initNodes = _cachedUsingBlock;
             }
             return initNodes.Concat(PreprocessAst(AphidParser.Parse(script))).ToList();
         }
Token() [1/2]
AphidToken Components.Aphid.Tests.Integration.Shared.AphidTests.Token (AphidTokenType type, string lexeme) protected
Definition at line 147 of file AphidTests.cs.
References lexeme.
         {
             return new AphidToken(type, lexeme, 0);
         }
Token() [2/2]
AphidToken Components.Aphid.Tests.Integration.Shared.AphidTests.Token (AphidTokenType type) protected
Definition at line 152 of file AphidTests.cs.
         {
             return Token(type, null);
         }
Property Documentation
LoadStd
virtual bool Components.Aphid.Tests.Integration.Shared.AphidTests.LoadStd get protected
Definition at line 49 of file AphidTests.cs.
 { get { return false; } }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid.Tests.Integration/Shared/AphidTests.cs