Aphid Programming Language: Components.Cypress.ProcessMemory Class Reference
Components.Cypress.ProcessMemory Class Reference
Public Member Functions
ProcessMemory (IntPtr handle)
byte [] ReadBytes (IntPtr address, int count)
uint [] ReadUInt32s (IntPtr address, int count)
MEMORY_BASIC_INFORMATION ReadMemoryInfo (IntPtr address)
bool IsExecutable (IntPtr address)
CONTEXT GetContext (uint threadId)
string ReadAscii (IntPtr address, int bufferSize=0x100)
string ReadUnicode (IntPtr address, int bufferSize=0x100)
int Write (IntPtr address, byte[] buffer)
IntPtr Allocate (uint size, MemoryProtection memoryProtection)
IntPtr Allocate (uint size, AllocationType allocationType, MemoryProtection memoryProtection)
bool ReadArg (IntPtr thread, int number, out uint value)
uint [] ReadArgs (IntPtr thread, int count)
Properties
IntPtr Handle [get]
Detailed Description
Definition at line 11 of file ProcessMemory.cs.
Constructor & Destructor Documentation
ProcessMemory()
Components.Cypress.ProcessMemory.ProcessMemory (IntPtr handle)
Definition at line 15 of file ProcessMemory.cs.
References handle.
         {
             Handle = handle;
         }
Member Function Documentation
Allocate() [1/2]
IntPtr Components.Cypress.ProcessMemory.Allocate (uint size, MemoryProtection memoryProtection)
Definition at line 170 of file ProcessMemory.cs.
         {
             return Allocate(
                 size,
                 AllocationType.Reserve | AllocationType.Commit,
                 memoryProtection);
         }
Allocate() [2/2]
IntPtr Components.Cypress.ProcessMemory.Allocate (uint size, AllocationType allocationType, MemoryProtection memoryProtection)
Definition at line 180 of file ProcessMemory.cs.
References Components.PInvoke.Kernel32.VirtualAllocEx().
         {
             return Kernel32.VirtualAllocEx(
                 Handle,
                 IntPtr.Zero,
                 size,
                 allocationType,
                 memoryProtection);
         }
GetContext()
CONTEXT Components.Cypress.ProcessMemory.GetContext (uint threadId)
Definition at line 83 of file ProcessMemory.cs.
References Components.PInvoke.Kernel32.CloseHandle(), Components.PInvoke.Kernel32.GetThreadContext(), Components.PInvoke.Kernel32.OpenThread(), and success.
         {
             var threadHandle = Kernel32.OpenThread(ThreadAccess.THREAD_GET_CONTEXT, false, threadId);
             var context = new CONTEXT();
             context.ContextFlags = CONTEXT_FLAGS.CONTEXT_ALL;
             var success = Kernel32.GetThreadContext(threadHandle, ref context);
             Kernel32.CloseHandle(threadHandle);
             return context;
         }
IsExecutable()
bool Components.Cypress.ProcessMemory.IsExecutable (IntPtr address)
Definition at line 72 of file ProcessMemory.cs.
         {
             var memInfo = ReadMemoryInfo(address);
             return
                 memInfo.Protect == AllocationProtect.PAGE_EXECUTE ||
                 memInfo.Protect == AllocationProtect.PAGE_EXECUTE_READ ||
                 memInfo.Protect == AllocationProtect.PAGE_EXECUTE_READWRITE ||
                 memInfo.Protect == AllocationProtect.PAGE_EXECUTE_WRITECOPY;
         }
ReadArg()
bool Components.Cypress.ProcessMemory.ReadArg (IntPtr thread, int number, out uint value)
Definition at line 193 of file ProcessMemory.cs.
References Components.Cypress.ThreadContext.GetContext(), and value.
         {
             var ctx = ThreadContext.GetContext(thread, CONTEXT_FLAGS.CONTEXT_ALL);
             var valueBuffer = ReadUInt32s((IntPtr)(ctx.Esp + (0x4 * (number + 1))), 1);
             if (valueBuffer == null || valueBuffer.Length != 1)
             {
                 value = 0;
                 return false;
             }
             else
             {
                 value = valueBuffer[0];
                 return true;
             }
         }
ReadArgs()
uint [] Components.Cypress.ProcessMemory.ReadArgs (IntPtr thread, int count)
Definition at line 210 of file ProcessMemory.cs.
References count, and Components.Cypress.ThreadContext.GetContext().
         {
             var ctx = ThreadContext.GetContext(thread, CONTEXT_FLAGS.CONTEXT_ALL);
             return ReadUInt32s((IntPtr)(ctx.Esp + 0x4), count);
         }
ReadAscii()
string Components.Cypress.ProcessMemory.ReadAscii (IntPtr address, int bufferSize = 0x100)
Definition at line 95 of file ProcessMemory.cs.
References i, and sb.
         {
             var sb = new StringBuilder();
             var inString = true;
             do
             {
                 var tmp = ReadBytes(address, bufferSize);
                 if (tmp == null)
                 {
                     return sb.ToString();
                 }
                 int i = 0;
                 for (i = 0; i < tmp.Length; i ++)
                 {
                     if (tmp[i] == 0)
                     {
                         inString = false;
                         break;
                     }
                 }
                 sb.Append(_encoding.GetString(tmp, 0, i));
                 address += bufferSize;
             } while (inString);
             return sb.ToString();
         }
ReadBytes()
byte [] Components.Cypress.ProcessMemory.ReadBytes (IntPtr address, int count)
Definition at line 20 of file ProcessMemory.cs.
References buffer, byte, count, out, and Components.PInvoke.Kernel32.ReadProcessMemory().
Referenced by Components.Cypress.NativeHook.Hook(), and Components.Cypress.BreakpointManager.SetBreakpoint().
         {
             var buffer = new byte[count];
             var bytesRead = 0;
             if (!Kernel32.ReadProcessMemory(
                 Handle,
                 address,
                 buffer,
                 buffer.Length,
                 out bytesRead))
             {
                 return null;
             }
             Array.Resize(ref buffer, bytesRead);
             return buffer;
         }
ReadMemoryInfo()
MEMORY_BASIC_INFORMATION Components.Cypress.ProcessMemory.ReadMemoryInfo (IntPtr address)
Definition at line 59 of file ProcessMemory.cs.
References out, and Components.PInvoke.Kernel32.VirtualQueryEx().
         {
             MEMORY_BASIC_INFORMATION m;
             var result = Kernel32.VirtualQueryEx(
                 Handle,
                 address,
                 out m,
                 (uint)Marshal.SizeOf(typeof(MEMORY_BASIC_INFORMATION)));
             return m;
         }
ReadUInt32s()
uint [] Components.Cypress.ProcessMemory.ReadUInt32s (IntPtr address, int count)
Definition at line 40 of file ProcessMemory.cs.
References count, and i.
         {
             var bytes = ReadBytes(address, count * sizeof(uint));
             if (bytes == null)
             {
                 return null;
             }
             var uints = new uint[count];
             for (int i = 0; i < count; i++)
             {
                 uints[i] = BitConverter.ToUInt32(bytes, i * sizeof(uint));
             }
             return uints;
         }
ReadUnicode()
string Components.Cypress.ProcessMemory.ReadUnicode (IntPtr address, int bufferSize = 0x100)
Definition at line 126 of file ProcessMemory.cs.
References i, and sb.
         {
             var sb = new StringBuilder();
             var inString = true;
             do
             {
                 var tmp = ReadBytes(address, bufferSize);
                 if (tmp == null)
                 {
                     return sb.ToString();
                 }
                 int i = 0;
                 for (i = 0; i < tmp.Length; i += 2)
                 {
                     if (tmp[i] == 0 && tmp[i + 1] == 0)
                     {
                         inString = false;
                         break;
                     }
                 }
                 sb.Append(Encoding.Unicode.GetString(tmp, 0, i));
                 address += bufferSize;
             } while (inString);
             return sb.ToString();
         }
Write()
int Components.Cypress.ProcessMemory.Write (IntPtr address, byte [] buffer)
Definition at line 158 of file ProcessMemory.cs.
References buffer, out, and Components.PInvoke.Kernel32.WriteProcessMemory().
Referenced by Components.Cypress.BreakpointManager.HandleException(), Components.Cypress.NativeHook.Hook(), and Components.Cypress.BreakpointManager.SetBreakpoint().
         {
             int bytesWritten;
             return Kernel32.WriteProcessMemory(
                 Handle,
                 address, buffer, buffer.Length,
                 out bytesWritten) ?
                 bytesWritten :
                 -1;
         }
Property Documentation
Handle
IntPtr Components.Cypress.ProcessMemory.Handle get
Definition at line 13 of file ProcessMemory.cs.
 { get; private set; }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/External/Debugging/ProcessMemory.cs