Aphid Programming Language: Components.Aphid.Library.Net.Http.HttpRequest Class Reference
Components.Aphid.Library.Net.Http.HttpRequest Class Reference
Public Member Functions
HttpRequest ()
void SetMultipart (string boundary="boundary5230")
void SetContentLength ()
string BuildRelativeUrl ()
string BuildAbsoluteUrl (string host)
string CreateHeader (string host)
Public Member Functions inherited from Components.Aphid.Library.Net.Http.HttpMessagePart
void ParseFields (string fields, bool skipFirstLine)
void ClearField (string field)
List< string > GetField (string field)
bool HasField (string field)
void SetField (string field, string value)
void SetField (string field, int value)
void SetField (string field, long value)
bool FieldContains (string field, string value)
void ResetField (string field, string value)
void ResetField (string field, int value)
void ResetField (string field, long value)
bool TryGetInt (string field, out int value)
string GetAttributeString ()
Properties
string Path [get, set]
string Method [get, set]
string Version [get, set]
FieldValuePair [] QueryString [get, set]
FieldValuePair [] PostValues [get, set]
HttpUpload [] Uploads [get, set]
bool IsMultipart [get, set]
string Boundary [get, set]
string StartBoundary [get, set]
string EndBoundary [get, set]
Properties inherited from Components.Aphid.Library.Net.Http.HttpMessagePart
Dictionary< string, List< string > > FieldDictionary [get]
Detailed Description
Definition at line 10 of file HttpRequest.cs.
Constructor & Destructor Documentation
HttpRequest()
Components.Aphid.Library.Net.Http.HttpRequest.HttpRequest ()
Definition at line 32 of file HttpRequest.cs.
References Components.Aphid.Library.Net.Http.HttpMethod.Get, Path, and Components.Aphid.Library.Net.Http.HttpVersion.V11.
         {
             Path = "/";
             Method = HttpMethod.Get;
             Version = HttpVersion.V11;
         }
Member Function Documentation
BuildAbsoluteUrl()
string Components.Aphid.Library.Net.Http.HttpRequest.BuildAbsoluteUrl (string host)
Definition at line 65 of file HttpRequest.cs.
         {
             return "http://" + host + BuildRelativeUrl();
         }
BuildRelativeUrl()
string Components.Aphid.Library.Net.Http.HttpRequest.BuildRelativeUrl ()
Definition at line 53 of file HttpRequest.cs.
References Components.Aphid.Library.Net.Http.FormUrlEncoder.Encode(), and Path.
         {
             var url = (Path[0] == '/' ? "" : "/") + Path;
             if (QueryString != null && QueryString.Any())
             {
                 url += "?" + FormUrlEncoder.Encode(QueryString);
             }
             return url;
         }
CreateHeader()
string Components.Aphid.Library.Net.Http.HttpRequest.CreateHeader (string host)
Definition at line 70 of file HttpRequest.cs.
Referenced by Components.Aphid.Library.Net.Http.HttpClient.Write().
         {
             return Method + " " + BuildRelativeUrl() + " HTTP/" + Version + "\r\n" +
                 GetAttributeString() + "\r\n\r\n";
         }
SetContentLength()
void Components.Aphid.Library.Net.Http.HttpRequest.SetContentLength ()
Definition at line 48 of file HttpRequest.cs.
         {
             ResetField(HttpField.ContentLength, 0);
         }
SetMultipart()
void Components.Aphid.Library.Net.Http.HttpRequest.SetMultipart (string boundary = "boundary5230")
Definition at line 39 of file HttpRequest.cs.
Referenced by Components.Aphid.Library.Net.Http.HttpClient.Write().
         {
             IsMultipart = true;
             Boundary = boundary;
             StartBoundary = "--" + Boundary + "\r\n";
             EndBoundary = "--" + Boundary + "--\r\n";
             ResetField(HttpField.ContentType, MimeType.Multipart + "; boundary=" + boundary);
         }
Property Documentation
Boundary
string Components.Aphid.Library.Net.Http.HttpRequest.Boundary get set
Definition at line 26 of file HttpRequest.cs.
Referenced by Components.Aphid.Library.Net.Http.HttpClient.Write().
 { get; set; }
EndBoundary
string Components.Aphid.Library.Net.Http.HttpRequest.EndBoundary get set
Definition at line 30 of file HttpRequest.cs.
 { get; set; }
IsMultipart
bool Components.Aphid.Library.Net.Http.HttpRequest.IsMultipart get set
Definition at line 24 of file HttpRequest.cs.
Referenced by Components.Aphid.Library.Net.Http.HttpClient.Write().
 { get; set; }
Method
string Components.Aphid.Library.Net.Http.HttpRequest.Method get set
Definition at line 14 of file HttpRequest.cs.
Referenced by Components.Aphid.Library.Net.Http.HttpClient.Write().
 { get; set; }
Path
string Components.Aphid.Library.Net.Http.HttpRequest.Path get set
Definition at line 12 of file HttpRequest.cs.
 { get; set; }
PostValues
FieldValuePair [] Components.Aphid.Library.Net.Http.HttpRequest.PostValues get set
Definition at line 20 of file HttpRequest.cs.
Referenced by Components.Aphid.Library.Net.Http.HttpClient.Write().
 { get; set; }
QueryString
FieldValuePair [] Components.Aphid.Library.Net.Http.HttpRequest.QueryString get set
Definition at line 18 of file HttpRequest.cs.
 { get; set; }
StartBoundary
string Components.Aphid.Library.Net.Http.HttpRequest.StartBoundary get set
Definition at line 28 of file HttpRequest.cs.
 { get; set; }
Uploads
HttpUpload [] Components.Aphid.Library.Net.Http.HttpRequest.Uploads get set
Definition at line 22 of file HttpRequest.cs.
Referenced by Components.Aphid.Library.Net.Http.HttpClient.Write().
 { get; set; }
Version
string Components.Aphid.Library.Net.Http.HttpRequest.Version get set
Definition at line 16 of file HttpRequest.cs.
 { get; set; }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Library/Net/Http/HttpRequest.cs