Aphid Programming Language: Components.Cypress.NativeFunction Class Reference
Components.Cypress.NativeFunction Class Reference
Public Member Functions
NativeFunction ()
NativeFunction (uint address, string name, int size)
override string ToString ()
void Serialize (StringTable table, BinaryWriter writer)
Static Public Member Functions
static void Serialize (Stream stream, NativeFunction[] functions)
static NativeFunction Deserialize (StringTable table, BinaryReader reader)
static NativeFunction [] Deserialize (Stream stream)
static NativeFunction [] Deserialize (string filename)
Properties
uint Address [get, set]
string Name [get, set]
int Size [get, set]
Instruction [] Disassembly [get, set]
Detailed Description
Definition at line 11 of file NativeFunction.cs.
Constructor & Destructor Documentation
NativeFunction() [1/2]
Components.Cypress.NativeFunction.NativeFunction ()
Definition at line 36 of file NativeFunction.cs.
         {
         }
NativeFunction() [2/2]
Components.Cypress.NativeFunction.NativeFunction (uint address, string name, int size)
Definition at line 40 of file NativeFunction.cs.
References name, and Name.
             : this()
         {
             Address = address;
             Name = name;
             Size = size;
         }
Member Function Documentation
Deserialize() [1/3]
static NativeFunction Components.Cypress.NativeFunction.Deserialize (StringTable table, BinaryReader reader) static
Definition at line 81 of file NativeFunction.cs.
References Components.Cypress.Instruction.Deserialize(), func, Name, reader, and x.
Referenced by Components.Cypress.NativeFunction.Deserialize().
         {
             var func = new NativeFunction()
             {
                 Address = reader.ReadUInt32(),
                 Name = table[reader.ReadInt32()],
                 Size = reader.ReadInt32(),
                 Disassembly = Enumerable
                     .Range(0, reader.ReadInt32())
                     .Select(x => Instruction.Deserialize(table, reader))
                     .ToArray(),
             };
             foreach (var inst in func.Disassembly)
             {
                 inst.Function = func;
             }
             if (func.Disassembly.Length == 0)
             {
                 func.Disassembly = new[]
                 {
                     new Instruction()
                     {
                         Address = func.Address,
                         Mnemonic = "nop",
                     },
                 };
             }
             else if (func.Size == 0)
             {
                 func.Size = func.Disassembly
                     .Sum(x => x.ByteString != null ? x.ByteString.Length / 2 : 0);
             }
             return func;
         }
Deserialize() [2/3]
static NativeFunction [] Components.Cypress.NativeFunction.Deserialize (Stream stream) static
Definition at line 119 of file NativeFunction.cs.
References Components.Cypress.NativeFunction.Deserialize(), Components.Cypress.StringTable.Deserialize(), reader, and x.
         {
             var reader = new BinaryReader(stream);
             var table = StringTable.Deserialize(reader);
             reader.BaseStream.Position = 0x4;
             var funcCount = reader.ReadInt32();
             var funcs = Enumerable
                 .Range(0, funcCount)
                 .Select(x => NativeFunction.Deserialize(table, reader))
                 .ToArray();
             return funcs;
         }
Deserialize() [3/3]
static NativeFunction [] Components.Cypress.NativeFunction.Deserialize (string filename) static
Definition at line 134 of file NativeFunction.cs.
         {
             using (var s = File.OpenRead(filename))
             {
                 return Deserialize(s);
             }
         }
Serialize() [1/2]
void Components.Cypress.NativeFunction.Serialize (StringTable table, BinaryWriter writer)
Definition at line 53 of file NativeFunction.cs.
References Name.
         {
             writer.Write(Address);
             writer.Write(table[Name]);
             writer.Write(Size);
             writer.Write(Disassembly.Length);
             foreach (var d in Disassembly)
             {
                 d.Serialize(table, writer);
             }
         }
Serialize() [2/2]
static void Components.Cypress.NativeFunction.Serialize (Stream stream, NativeFunction [] functions) static
Definition at line 65 of file NativeFunction.cs.
References f.
         {
             var writer = new BinaryWriter(stream);
             writer.Write(0);
             writer.Write(functions.Length);
             var table = new StringTable();
             foreach (var f in functions)
             {
                 f.Serialize(table, writer);
             }
             table.Serialize(writer);
         }
ToString()
override string Components.Cypress.NativeFunction.ToString ()
Definition at line 48 of file NativeFunction.cs.
References Name.
         {
             return string.Format("{0:X8}: {1}", Address, Name);
         }
Property Documentation
Address
uint Components.Cypress.NativeFunction.Address get set
Definition at line 13 of file NativeFunction.cs.
 { get; set; }
Disassembly
Instruction [] Components.Cypress.NativeFunction.Disassembly get set
Definition at line 22 of file NativeFunction.cs.
         {
             get { return _disassembly; }
             set
             {
                 //if (Size == 0 && value != null)
                 //{
                 //    Size = value
                 //        .Sum(x => x.ByteString != null ? x.ByteString.Length / 2 : 0);
                 //}
                 _disassembly = value;
             }
         }
Name
string Components.Cypress.NativeFunction.Name get set
Definition at line 15 of file NativeFunction.cs.
 { get; set; }
Size
int Components.Cypress.NativeFunction.Size get set
Definition at line 17 of file NativeFunction.cs.
 { get; set; }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/External/Debugging/NativeFunction.cs