Aphid Programming Language: Components.Aphid.Compiler.CodeHelper Class Reference
Components.Aphid.Compiler.CodeHelper Class Reference
Static Public Member Functions
static CodeVariableReferenceExpression VarRef (string name)
static CodeVariableDeclarationStatement VarDecl (Type type, string name)
static CodeVariableDeclarationStatement VarDecl (Type type, string name, CodeExpression init)
static CodeVariableDeclarationStatement VarDecl (string type, string name)
static CodeVariableDeclarationStatement VarDecl (string type, string name, CodeExpression init)
static CodeVariableDeclarationStatement VarDecl (string name)
static CodeVariableDeclarationStatement VarDecl (string name, CodeExpression init)
static CodePropertyReferenceExpression PropRef (CodeExpression targetObject, params string[] propertyNames)
static CodePropertyReferenceExpression PropRef (params string[] propertyNames)
static CodeFieldReferenceExpression FieldRef (CodeExpression targetObject, params string[] propertyNames)
static CodeFieldReferenceExpression FieldRef (params string[] propertyNames)
static CodeBinaryOperatorExpression BinOpExp (CodeExpression left, CodeBinaryOperatorType op, CodeExpression right)
static CodeExpression BinOpExpJoin (this IEnumerable< CodeExpression > expressions, CodeBinaryOperatorType op)
static CodeArgumentReferenceExpression Arg (string name)
static CodeTypeReference TypeRef (Type type)
static CodeTypeReference TypeRef< T > ()
static CodeTypeReference TypeRef (string typeName)
static CodeTypeReferenceExpression TypeRefExp (Type type)
static CodeTypeReferenceExpression TypeRefExp (string typeName)
static CodeTypeReferenceExpression TypeRefExp< T > ()
static CodeTypeOfExpression TypeOf (string type)
static CodeTypeOfExpression TypeOf (Type type)
static CodeMethodReturnStatement Return (CodeExpression expression)
static CodeMethodReturnStatement Return (string variableName)
static CodePrimitiveExpression True ()
static CodePrimitiveExpression False ()
static CodePrimitiveExpression Null ()
static CodeThisReferenceExpression This ()
static CodeObjectCreateExpression New (Type createType, params CodeExpression[] parameters)
static CodeObjectCreateExpression New (CodeTypeReference createType, params CodeExpression[] parameters)
static CodeAssignStatement Assign (CodeExpression left, CodeExpression right)
static CodeAssignStatement Assign (string variableName, CodeExpression right)
static CodeAssignStatement Assign (string leftVariableName, string rightVariableName)
static CodeMethodInvokeExpression Invoke (CodeExpression targetObject, string methodName, params CodeExpression[] parameters)
static CodeMethodInvokeExpression Invoke (CodeExpression targetObject, string methodName, CodeTypeReference[] typeParameters, params CodeExpression[] parameters)
static CodeMethodInvokeExpression Invoke (CodeExpression targetObject, string methodName, string[] typeParameters, params CodeExpression[] parameters)
static CodeMethodInvokeExpression Invoke (string methodName, params CodeExpression[] parameters)
static CodeIterationStatement While (CodeExpression testExpression, params CodeStatement[] statements)
static CodeExpressionStatement Stmt (CodeExpression expression)
static CodeExpression Eq (CodeExpression left, CodeExpression right)
static CodeExpression LessThan (CodeExpression left, CodeExpression right)
static CodeExpression LessThanEq (CodeExpression left, CodeExpression right)
static CodeExpression GreaterThan (CodeExpression left, CodeExpression right)
static CodeExpression GreaterThanEq (CodeExpression left, CodeExpression right)
static CodeExpression Add (CodeExpression left, CodeExpression right)
static CodeExpression Sub (CodeExpression left, CodeExpression right)
static CodeExpression Inc (CodeVariableReferenceExpression exp)
static CodeExpression Dec (CodeVariableReferenceExpression exp)
static CodeAssignStatement IncStmt (CodeVariableReferenceExpression exp)
static CodeAssignStatement DecStmt (CodeVariableReferenceExpression exp)
static CodePrimitiveExpression Value (int value)
static CodePrimitiveExpression Value (string value)
static void AddRange (this CodeStatementCollection collection, params CodeStatement[] statements)
Detailed Description
Definition at line 8 of file CodeHelper.cs.
Member Function Documentation
Add()
static CodeExpression Components.Aphid.Compiler.CodeHelper.Add (CodeExpression left, CodeExpression right) static
Definition at line 261 of file CodeHelper.cs.
References Components.Aphid.Compiler.CodeHelper.BinOpExp().
         {
             return CodeHelper.BinOpExp(left, CodeBinaryOperatorType.Add, right);
         }
AddRange()
static void Components.Aphid.Compiler.CodeHelper.AddRange (this CodeStatementCollection collection, params CodeStatement [] statements) static
Definition at line 326 of file CodeHelper.cs.
References collection.
         {
             collection.AddRange(statements);
         }
Arg()
static CodeArgumentReferenceExpression Components.Aphid.Compiler.CodeHelper.Arg (string name) static
Definition at line 96 of file CodeHelper.cs.
References name.
         {
             return new CodeArgumentReferenceExpression(name);
         }
Assign() [1/3]
static CodeAssignStatement Components.Aphid.Compiler.CodeHelper.Assign (CodeExpression left, CodeExpression right) static
Definition at line 181 of file CodeHelper.cs.
Referenced by Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute >.BuildType().
         {
             return new CodeAssignStatement(left, right);
         }
Assign() [2/3]
static CodeAssignStatement Components.Aphid.Compiler.CodeHelper.Assign (string variableName, CodeExpression right) static
Definition at line 186 of file CodeHelper.cs.
         {
             return Assign(VarRef(variableName), right);
         }
Assign() [3/3]
static CodeAssignStatement Components.Aphid.Compiler.CodeHelper.Assign (string leftVariableName, string rightVariableName) static
Definition at line 191 of file CodeHelper.cs.
         {
             return Assign(VarRef(leftVariableName), VarRef(rightVariableName));
         }
BinOpExp()
static CodeBinaryOperatorExpression Components.Aphid.Compiler.CodeHelper.BinOpExp (CodeExpression left, CodeBinaryOperatorType op, CodeExpression right) static
Definition at line 79 of file CodeHelper.cs.
Referenced by Components.Aphid.Compiler.CodeHelper.Add(), Components.Aphid.Compiler.CodeHelper.BinOpExpJoin(), Components.Aphid.Compiler.CodeHelper.Eq(), Components.Aphid.Compiler.CodeHelper.GreaterThan(), Components.Aphid.Compiler.CodeHelper.GreaterThanEq(), Components.Aphid.Compiler.CodeHelper.LessThan(), Components.Aphid.Compiler.CodeHelper.LessThanEq(), and Components.Aphid.Compiler.CodeHelper.Sub().
         {
             return new CodeBinaryOperatorExpression(left, op, right);
         }
BinOpExpJoin()
static CodeExpression Components.Aphid.Compiler.CodeHelper.BinOpExpJoin (this IEnumerable< CodeExpression > expressions, CodeBinaryOperatorType op) static
Definition at line 84 of file CodeHelper.cs.
References Components.Aphid.Compiler.CodeHelper.BinOpExp(), and x.
         {
             CodeExpression codeExp = expressions.First();
             foreach (var x in expressions.Skip(1))
             {
                 codeExp = CodeHelper.BinOpExp(codeExp, op, x);
             }
             return codeExp;
         }
Dec()
static CodeExpression Components.Aphid.Compiler.CodeHelper.Dec (CodeVariableReferenceExpression exp) static
Definition at line 276 of file CodeHelper.cs.
         {
             return IncDec(exp, CodeBinaryOperatorType.Subtract);
         }
DecStmt()
static CodeAssignStatement Components.Aphid.Compiler.CodeHelper.DecStmt (CodeVariableReferenceExpression exp) static
Definition at line 299 of file CodeHelper.cs.
         {
             return IncDecStmt(exp, CodeBinaryOperatorType.Subtract);
         }
Eq()
static CodeExpression Components.Aphid.Compiler.CodeHelper.Eq (CodeExpression left, CodeExpression right) static
Definition at line 236 of file CodeHelper.cs.
References Components.Aphid.Compiler.CodeHelper.BinOpExp().
         {
             return CodeHelper.BinOpExp(left, CodeBinaryOperatorType.ValueEquality, right);
         }
False()
static CodePrimitiveExpression Components.Aphid.Compiler.CodeHelper.False () static
Definition at line 156 of file CodeHelper.cs.
Referenced by Components.Aphid.Compiler.AphidObjectGenerator.CreateCodeObject().
         {
             return new CodePrimitiveExpression(false);
         }
FieldRef() [1/2]
static CodeFieldReferenceExpression Components.Aphid.Compiler.CodeHelper.FieldRef (CodeExpression targetObject, params string [] propertyNames) static
Definition at line 62 of file CodeHelper.cs.
References p.
Referenced by Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute >.BuildType().
         {
             CodeFieldReferenceExpression exp = null;
             foreach (var p in propertyNames)
             {
                 exp = new CodeFieldReferenceExpression(exp ?? targetObject, p);
             }
             return exp;
         }
FieldRef() [2/2]
static CodeFieldReferenceExpression Components.Aphid.Compiler.CodeHelper.FieldRef (params string [] propertyNames) static
Definition at line 74 of file CodeHelper.cs.
         {
             return FieldRef(This(), propertyNames);
         }
GreaterThan()
static CodeExpression Components.Aphid.Compiler.CodeHelper.GreaterThan (CodeExpression left, CodeExpression right) static
Definition at line 251 of file CodeHelper.cs.
References Components.Aphid.Compiler.CodeHelper.BinOpExp().
         {
             return CodeHelper.BinOpExp(left, CodeBinaryOperatorType.GreaterThan, right);
         }
GreaterThanEq()
static CodeExpression Components.Aphid.Compiler.CodeHelper.GreaterThanEq (CodeExpression left, CodeExpression right) static
Definition at line 256 of file CodeHelper.cs.
References Components.Aphid.Compiler.CodeHelper.BinOpExp().
         {
             return CodeHelper.BinOpExp(left, CodeBinaryOperatorType.GreaterThanOrEqual, right);
         }
Inc()
static CodeExpression Components.Aphid.Compiler.CodeHelper.Inc (CodeVariableReferenceExpression exp) static
Definition at line 271 of file CodeHelper.cs.
         {
             return IncDec(exp, CodeBinaryOperatorType.Add);
         }
IncStmt()
static CodeAssignStatement Components.Aphid.Compiler.CodeHelper.IncStmt (CodeVariableReferenceExpression exp) static
Definition at line 294 of file CodeHelper.cs.
         {
             return IncDecStmt(exp, CodeBinaryOperatorType.Add);
         }
Invoke() [1/4]
static CodeMethodInvokeExpression Components.Aphid.Compiler.CodeHelper.Invoke (CodeExpression targetObject, string methodName, params CodeExpression [] parameters) static
Definition at line 196 of file CodeHelper.cs.
         {
             return new CodeMethodInvokeExpression(targetObject, methodName, parameters);
         }
Invoke() [2/4]
static CodeMethodInvokeExpression Components.Aphid.Compiler.CodeHelper.Invoke (CodeExpression targetObject, string methodName, CodeTypeReference [] typeParameters, params CodeExpression [] parameters) static
Definition at line 201 of file CodeHelper.cs.
         {
             var methodRef = new CodeMethodReferenceExpression(targetObject, methodName, typeParameters);
             return new CodeMethodInvokeExpression(methodRef, parameters);
         }
Invoke() [3/4]
static CodeMethodInvokeExpression Components.Aphid.Compiler.CodeHelper.Invoke (CodeExpression targetObject, string methodName, string [] typeParameters, params CodeExpression [] parameters) static
Definition at line 208 of file CodeHelper.cs.
References x.
         {
             return Invoke(
                 targetObject,
                 methodName,
                 typeParameters.Select(x => new CodeTypeReference(x)).ToArray(),
                 parameters);
         }
Invoke() [4/4]
static CodeMethodInvokeExpression Components.Aphid.Compiler.CodeHelper.Invoke (string methodName, params CodeExpression [] parameters) static
Definition at line 217 of file CodeHelper.cs.
         {
             return Invoke(null, methodName, parameters);
         }
LessThan()
static CodeExpression Components.Aphid.Compiler.CodeHelper.LessThan (CodeExpression left, CodeExpression right) static
Definition at line 241 of file CodeHelper.cs.
References Components.Aphid.Compiler.CodeHelper.BinOpExp().
         {
             return CodeHelper.BinOpExp(left, CodeBinaryOperatorType.LessThan, right);
         }
LessThanEq()
static CodeExpression Components.Aphid.Compiler.CodeHelper.LessThanEq (CodeExpression left, CodeExpression right) static
Definition at line 246 of file CodeHelper.cs.
References Components.Aphid.Compiler.CodeHelper.BinOpExp().
         {
             return CodeHelper.BinOpExp(left, CodeBinaryOperatorType.LessThanOrEqual, right);
         }
New() [1/2]
static CodeObjectCreateExpression Components.Aphid.Compiler.CodeHelper.New (Type createType, params CodeExpression [] parameters) static
Definition at line 171 of file CodeHelper.cs.
         {
             return new CodeObjectCreateExpression(createType, parameters);
         }
New() [2/2]
static CodeObjectCreateExpression Components.Aphid.Compiler.CodeHelper.New (CodeTypeReference createType, params CodeExpression [] parameters) static
Definition at line 176 of file CodeHelper.cs.
         {
             return new CodeObjectCreateExpression(createType, parameters);
         }
Null()
static CodePrimitiveExpression Components.Aphid.Compiler.CodeHelper.Null () static
Definition at line 161 of file CodeHelper.cs.
         {
             return new CodePrimitiveExpression();
         }
PropRef() [1/2]
static CodePropertyReferenceExpression Components.Aphid.Compiler.CodeHelper.PropRef (CodeExpression targetObject, params string [] propertyNames) static
Definition at line 45 of file CodeHelper.cs.
References p.
         {
             CodePropertyReferenceExpression exp = null;
             foreach (var p in propertyNames)
             {
                 exp = new CodePropertyReferenceExpression(exp ?? targetObject, p);
             }
             return exp;
         }
PropRef() [2/2]
static CodePropertyReferenceExpression Components.Aphid.Compiler.CodeHelper.PropRef (params string [] propertyNames) static
Definition at line 57 of file CodeHelper.cs.
         {
             return PropRef(null, propertyNames);
         }
Return() [1/2]
static CodeMethodReturnStatement Components.Aphid.Compiler.CodeHelper.Return (CodeExpression expression) static
Definition at line 141 of file CodeHelper.cs.
References expression.
Referenced by Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute >.BuildType(), and Components.Aphid.Compiler.AphidObjectGenerator.CreateCodeObject().
         {
             return new CodeMethodReturnStatement(expression);
         }
Return() [2/2]
static CodeMethodReturnStatement Components.Aphid.Compiler.CodeHelper.Return (string variableName) static
Definition at line 146 of file CodeHelper.cs.
References Components.Aphid.Compiler.CodeHelper.VarRef().
         {
             return Return(CodeHelper.VarRef(variableName));
         }
Stmt()
static CodeExpressionStatement Components.Aphid.Compiler.CodeHelper.Stmt (CodeExpression expression) static
Definition at line 231 of file CodeHelper.cs.
References expression.
         {
             return new CodeExpressionStatement(expression);
         }
Sub()
static CodeExpression Components.Aphid.Compiler.CodeHelper.Sub (CodeExpression left, CodeExpression right) static
Definition at line 266 of file CodeHelper.cs.
References Components.Aphid.Compiler.CodeHelper.BinOpExp().
         {
             return CodeHelper.BinOpExp(left, CodeBinaryOperatorType.Subtract, right);
         }
This()
static CodeThisReferenceExpression Components.Aphid.Compiler.CodeHelper.This () static
Definition at line 166 of file CodeHelper.cs.
         {
             return new CodeThisReferenceExpression();
         }
True()
static CodePrimitiveExpression Components.Aphid.Compiler.CodeHelper.True () static
Definition at line 151 of file CodeHelper.cs.
         {
             return new CodePrimitiveExpression(true);
         }
TypeOf() [1/2]
static CodeTypeOfExpression Components.Aphid.Compiler.CodeHelper.TypeOf (string type) static
Definition at line 131 of file CodeHelper.cs.
         {
             return new CodeTypeOfExpression(type);
         }
TypeOf() [2/2]
static CodeTypeOfExpression Components.Aphid.Compiler.CodeHelper.TypeOf (Type type) static
Definition at line 136 of file CodeHelper.cs.
         {
             return new CodeTypeOfExpression(type);
         }
TypeRef() [1/2]
static CodeTypeReference Components.Aphid.Compiler.CodeHelper.TypeRef (Type type) static
Definition at line 101 of file CodeHelper.cs.
Referenced by Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute >.BuildType(), Mantispid.EnumBuilder.CreateEnum(), Mantispid.ParserCode.GetListTypeRef(), and Mantispid.ParserCode.GetTypeRef().
         {
             return new CodeTypeReference(type);
         }
TypeRef() [2/2]
static CodeTypeReference Components.Aphid.Compiler.CodeHelper.TypeRef (string typeName) static
Definition at line 111 of file CodeHelper.cs.
         {
             return new CodeTypeReference(typeName);
         }
TypeRef< T >()
static CodeTypeReference Components.Aphid.Compiler.CodeHelper.TypeRef< T > () static
Definition at line 106 of file CodeHelper.cs.
         {
             return TypeRef(typeof(T));
         }
TypeRefExp() [1/2]
static CodeTypeReferenceExpression Components.Aphid.Compiler.CodeHelper.TypeRefExp (Type type) static
Definition at line 116 of file CodeHelper.cs.
         {
             return new CodeTypeReferenceExpression(type);
         }
TypeRefExp() [2/2]
static CodeTypeReferenceExpression Components.Aphid.Compiler.CodeHelper.TypeRefExp (string typeName) static
Definition at line 121 of file CodeHelper.cs.
         {
             return new CodeTypeReferenceExpression(typeName);
         }
TypeRefExp< T >()
static CodeTypeReferenceExpression Components.Aphid.Compiler.CodeHelper.TypeRefExp< T > () static
Definition at line 126 of file CodeHelper.cs.
         {
             return TypeRefExp(typeof(T));
         }
Value() [1/2]
static CodePrimitiveExpression Components.Aphid.Compiler.CodeHelper.Value (int value) static
Definition at line 316 of file CodeHelper.cs.
References value.
Referenced by Mantispid.EnumBuilder.CreateEnum().
         {
             return new CodePrimitiveExpression(value);
         }
Value() [2/2]
static CodePrimitiveExpression Components.Aphid.Compiler.CodeHelper.Value (string value) static
Definition at line 321 of file CodeHelper.cs.
References value.
         {
             return new CodePrimitiveExpression(value);
         }
VarDecl() [1/6]
static CodeVariableDeclarationStatement Components.Aphid.Compiler.CodeHelper.VarDecl (Type type, string name) static
Definition at line 15 of file CodeHelper.cs.
References name.
         {
             return new CodeVariableDeclarationStatement(type, name);
         }
VarDecl() [2/6]
static CodeVariableDeclarationStatement Components.Aphid.Compiler.CodeHelper.VarDecl (Type type, string name, CodeExpression init) static
Definition at line 20 of file CodeHelper.cs.
References init, and name.
         {
             return new CodeVariableDeclarationStatement(type, name, init);
         }
VarDecl() [3/6]
static CodeVariableDeclarationStatement Components.Aphid.Compiler.CodeHelper.VarDecl (string type, string name) static
Definition at line 25 of file CodeHelper.cs.
References name.
         {
             return new CodeVariableDeclarationStatement(type, name);
         }
VarDecl() [4/6]
static CodeVariableDeclarationStatement Components.Aphid.Compiler.CodeHelper.VarDecl (string type, string name, CodeExpression init) static
Definition at line 30 of file CodeHelper.cs.
References init, and name.
         {
             return new CodeVariableDeclarationStatement(type, name, init);
         }
VarDecl() [5/6]
static CodeVariableDeclarationStatement Components.Aphid.Compiler.CodeHelper.VarDecl (string name) static
Definition at line 35 of file CodeHelper.cs.
References name.
         {
             return new CodeVariableDeclarationStatement("var", name);
         }
VarDecl() [6/6]
static CodeVariableDeclarationStatement Components.Aphid.Compiler.CodeHelper.VarDecl (string name, CodeExpression init) static
Definition at line 40 of file CodeHelper.cs.
References init, and name.
         {
             return new CodeVariableDeclarationStatement("var", name, init);
         }
VarRef()
static CodeVariableReferenceExpression Components.Aphid.Compiler.CodeHelper.VarRef (string name) static
Definition at line 10 of file CodeHelper.cs.
References name.
Referenced by Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute >.BuildType(), and Components.Aphid.Compiler.CodeHelper.Return().
         {
             return new CodeVariableReferenceExpression(name);
         }
While()
static CodeIterationStatement Components.Aphid.Compiler.CodeHelper.While (CodeExpression testExpression, params CodeStatement [] statements) static
Definition at line 222 of file CodeHelper.cs.
         {
             return new CodeIterationStatement(
                 new CodeSnippetStatement(""),
                 testExpression,
                 new CodeSnippetStatement(""),
                 statements);
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Compiler/CodeHelper.cs