Aphid Programming Language: Mantispid.ParserGenerator Class Reference
Mantispid.ParserGenerator Class Reference
Public Member Functions
string Generate (List< AphidExpression > nodes, string code)
Detailed Description
Definition at line 34 of file ParserGenerator.cs.
Member Function Documentation
Generate()
string Mantispid.ParserGenerator.Generate (List< AphidExpression > nodes, string code)
Definition at line 69 of file ParserGenerator.cs.
References Mantispid.ParserGeneratorConfig.BaseClass, code, Mantispid.EnumBuilder.CreateEnum(), Mantispid.RuleTypeBuilder.CreateRuleTypeClasses(), Components.Aphid.Compiler.CSharpHelper.GenerateCode(), lexer, Components.Aphid.Parser.AphidMutator.MutateRecursively(), Mantispid.ParserGeneratorConfig.Namespace, Mantispid.ParserGeneratorConfig.ParserClass, r, and x.
         {
             ParseDirectives(nodes);
             var lexer = GenerateLexer(nodes, code);
             ParseRuleStructs(nodes);
             nodes = new PlusEqualMutator().MutateRecursively(nodes);
             var rules = GetRules(nodes);
             _ruleNames = GetRuleNames(nodes).ToArray();
             var mutator = new TypeInferenceMutator(_config);
             foreach (var r in rules)
             {
                 nodes.Remove(r);
             }
             do
             {
                 rules = rules
                     .Select(x => new BinaryOperatorExpression(
                         x.LeftOperand,
                         x.Operator,
                         new FunctionExpression(
                             x.RightOperand.ToFunction().Args,
                             mutator.MutateRecursively(x.RightOperand.ToFunction().Body))))
                     .ToArray();
             }
             while (mutator.HasMutated);
             nodes.AddRange(rules);
             var declMutator = new DeclarativeStatementMutator(_tokenTypes, _ruleNames);
             nodes = declMutator.Mutate(nodes);
             nodes = AddIndexTracking(nodes);
             var ruleTypeBuilder = new RuleTypeBuilder(
                 _config.BaseClass,
                 _ruleTypes.Select(x => x.Value));
             var typeClasses = ruleTypeBuilder.CreateRuleTypeClasses();
             var enumBuilder = new EnumBuilder(_config.BaseClass, _ruleTypes.Select(x => x.Key));
             var enumDecl = enumBuilder.CreateEnum();
             var ns = new CodeNamespace(
                 string.Join(".", _config.Namespace.Concat(new[] { "Parser" })));
             ns.Imports.Add(new CodeNamespaceImport(
                 string.Join(".", _config.Namespace.Concat(new[] { "Lexer" }))));
             ns.Imports.Add(new CodeNamespaceImport("System.Linq"));
             ns.Imports.Add(new CodeNamespaceImport("System.Collections.Generic"));
             ns.Types.Add(enumDecl);
             ns.Types.AddRange(typeClasses);
             var parserType = new CodeTypeDeclaration(_config.ParserClass)
             {
                 IsPartial = true,
             };
             parserType.Members.AddRange(nodes.Select(Generate).Where(x => x != null).ToArray());
             ns.Types.Add(parserType);
             var str = CSharpHelper.GenerateCode(ns);
             return str + "\r\n\r\n" + lexer;
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Compiler/Medusa/Mantispid/ParserGenerator.cs