Aphid Programming Language: Components.Aphid.Debugging.AphidTrace Class Reference
Components.Aphid.Debugging.AphidTrace Class Reference
Public Member Functions
AphidTrace (string name, string outputFile, AphidInterpreter interpreter)
AphidTrace (string name, Stream outputStream, AphidInterpreter interpreter)
void Open ()
void Trace (string format, params object[] args)
void Trace (string message)
void Trace (TraceLevel level, string format, params object[] args)
void Trace (TraceLevel level, string message)
void TraceUnsafe (TraceLevel level, string message)
void TraceText (string format, params object[] args)
void TraceText (string message)
void Dispose ()
void Flush ()
Public Member Functions inherited from Components.Aphid.Interpreter.AphidRuntimeComponent
AphidRuntimeComponent (AphidInterpreter interpreter)
Properties
AphidTraceSettings Settings [get, set]
string Name [get]
string OutputFile [get]
bool IsOpened [get]
bool MultiprocessSafe [get, set]
bool ThreadSafe [get, set]
Properties inherited from Components.Aphid.Interpreter.AphidRuntimeComponent
AphidInterpreter Interpreter [get]
Detailed Description
Definition at line 12 of file AphidTrace.cs.
Constructor & Destructor Documentation
AphidTrace() [1/2]
Components.Aphid.Debugging.AphidTrace.AphidTrace (string name, string outputFile, AphidInterpreter interpreter)
Definition at line 38 of file AphidTrace.cs.
References Path.
             : this(name, interpreter)
         {
             OutputFile = Path.GetFullPath(outputFile);
         }
AphidTrace() [2/2]
Components.Aphid.Debugging.AphidTrace.AphidTrace (string name, Stream outputStream, AphidInterpreter interpreter)
Definition at line 44 of file AphidTrace.cs.
             : this(name, interpreter)
         {
             _writer = new StreamWriter(_stream = outputStream);
             IsOpened = true;
         }
Member Function Documentation
Dispose()
void Components.Aphid.Debugging.AphidTrace.Dispose ()
Definition at line 214 of file AphidTrace.cs.
         {
             lock (this)
             {
                 if (_isDisposed)
                 {
                     throw new InvalidOperationException("AphidTrace already disposed.");
                 }
                 if (_stream != null)
                 {
                     _stream.Dispose();
                     _stream = null;
                     _writer = null;
                 }
                 _isDisposed = true;
             }
         }
Flush()
void Components.Aphid.Debugging.AphidTrace.Flush ()
Definition at line 234 of file AphidTrace.cs.
         {
             _stream.Flush();
         }
Open()
void Components.Aphid.Debugging.AphidTrace.Open ()
Definition at line 58 of file AphidTrace.cs.
         {
             lock (this)
             {
                 if (IsOpened)
                 {
                     throw new InvalidOperationException("AphidTrace already opened.");
                 }
                 _stream = File.Open(
                     OutputFile,
                     FileMode.OpenOrCreate,
                     FileAccess.Write,
                     FileShare.ReadWrite);
                 _writer = new StreamWriter(_stream);
                 IsOpened = true;
             }
         }
Trace() [1/4]
void Components.Aphid.Debugging.AphidTrace.Trace (string format, params object [] args)
Definition at line 78 of file AphidTrace.cs.
References args, and format.
Referenced by Components.Aphid.Interpreter.AphidInterpreter.EnterScope(), and Components.Aphid.Interpreter.AphidInterpreter.LeaveScope().
         {
             Trace(Settings.DefaultMessageTraceLevel, format, args);
         }
Trace() [2/4]
void Components.Aphid.Debugging.AphidTrace.Trace (string message)
Definition at line 83 of file AphidTrace.cs.
         {
             Trace(Settings.DefaultMessageTraceLevel, message);
         }
Trace() [3/4]
void Components.Aphid.Debugging.AphidTrace.Trace (TraceLevel level, string format, params object [] args)
Definition at line 88 of file AphidTrace.cs.
References args, and format.
         {
             Trace(level, string.Format(format, args));
         }
Trace() [4/4]
void Components.Aphid.Debugging.AphidTrace.Trace (TraceLevel level, string message)
Definition at line 93 of file AphidTrace.cs.
         {
             if (MultiprocessSafe)
             {
                 using (new CrossProcessLock(GetLockName()))
                 {
                     TraceUnsafe(level, message);
                 }
             }
             else if (ThreadSafe)
             {
                 lock(this)
                 {
                     TraceUnsafe(level, message);
                 }
             }
             else
             {
                 TraceUnsafe(level, message);
             }
         }
TraceText() [1/2]
void Components.Aphid.Debugging.AphidTrace.TraceText (string format, params object [] args)
Definition at line 175 of file AphidTrace.cs.
References args, and format.
Referenced by Components.Aphid.Interpreter.AphidInterpreter.PopFrame(), and Components.Aphid.Interpreter.AphidInterpreter.PushFrame().
         {
             TraceText(string.Format(format, args));
         }
TraceText() [2/2]
void Components.Aphid.Debugging.AphidTrace.TraceText (string message)
Definition at line 180 of file AphidTrace.cs.
         {
             if (MultiprocessSafe)
             {
                 using (new CrossProcessLock(GetLockName()))
                 {
                     TraceTextUnsafe(message);
                 }
             }
             else if (ThreadSafe)
             {
                 lock(this)
                 {
                     TraceTextUnsafe(message);
                 }
             }
             else
             {
                 TraceTextUnsafe(message);
             }
         }
TraceUnsafe()
void Components.Aphid.Debugging.AphidTrace.TraceUnsafe (TraceLevel level, string message)
Definition at line 115 of file AphidTrace.cs.
References Name, Components.Aphid.Interpreter.ExceptionHelper.StackTrace(), Components.Aphid.Debugging.AphidTraceSettings.TimestampFormat, Components.Aphid.Debugging.AphidTraceSettings.TraceAphidStack, Components.Aphid.Debugging.AphidTraceSettings.TraceClrStack, Components.Aphid.Debugging.AphidTraceSettings.TraceCurrentExpression, Components.Aphid.Debugging.AphidTraceSettings.TraceCurrentStatement, Components.Aphid.Debugging.AphidTraceSettings.TraceTimestamp, and x.
         {
             if (!IsOpened)
             {
                 throw new InvalidOperationException("AphidTrace is not open.");
             }
             if (_settings.TraceTimestamp)
             {
                 _writer.Write(DateTime.Now.ToString(_settings.TimestampFormat + " "));
             }
             _writer.WriteLine(string.Format("{0} {1}: {2}\r\n", Name, level, message));
             if (_settings.TraceCurrentStatement)
             {
                 _writer.Write("Current statement: ");
                 _writer.WriteLine(
                     Interpreter.CurrentStatement != null ?
                     Interpreter.CurrentStatement.ToString() :
                     "[null]");
                 _writer.WriteLine();
             }
             if (_settings.TraceCurrentExpression)
             {
                 _writer.Write("Current expression: ");
                 _writer.WriteLine(
                     Interpreter.CurrentExpression != null ?
                     Interpreter.CurrentExpression.ToString() :
                     "[null]");
                 _writer.WriteLine();
             }
             if (_settings.TraceAphidStack)
             {
                 var stack = ExceptionHelper.StackTrace(Interpreter.GetStackTrace());
                 _writer.WriteLine("Aphid stack trace:\r\n" + stack);
                 _writer.WriteLine();
             }
             if (_settings.TraceClrStack)
             {
                 _writer.WriteLine("CLR stack trace:\r\n" +
                     new StackTrace()
                         .GetFrames()
                         .Select(x => x.ToString())
                         .Join());
                 _writer.WriteLine();
             }
             _writer.Flush();
         }
Property Documentation
IsOpened
bool Components.Aphid.Debugging.AphidTrace.IsOpened get
Definition at line 32 of file AphidTrace.cs.
 { get; private set; }
MultiprocessSafe
bool Components.Aphid.Debugging.AphidTrace.MultiprocessSafe get set
Definition at line 34 of file AphidTrace.cs.
 { get; set; }
Name
string Components.Aphid.Debugging.AphidTrace.Name get
Definition at line 28 of file AphidTrace.cs.
 { get; private set; }
OutputFile
string Components.Aphid.Debugging.AphidTrace.OutputFile get
Definition at line 30 of file AphidTrace.cs.
 { get; private set; }
Settings
AphidTraceSettings Components.Aphid.Debugging.AphidTrace.Settings get set
Definition at line 23 of file AphidTrace.cs.
         {
             get { return _settings; }
             set { _settings = value; }
         }
ThreadSafe
bool Components.Aphid.Debugging.AphidTrace.ThreadSafe get set
Definition at line 36 of file AphidTrace.cs.
 { get; set; }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Debugging/AphidTrace.cs