Aphid Programming Language: Components.Aphid.Library.Net.UdpLibrary Class Reference
Components.Aphid.Library.Net.UdpLibrary Class Reference
Static Public Member Functions
static UdpClient UdpCreate ()
static AphidObject UdpSend (AphidInterpreter interpreter, AphidObject clientObj, AphidObject datagramObj, AphidObject hostObj, AphidObject portObj)
static AphidObject UdpReceive (UdpClient client, decimal port)
static void UdpClose (UdpClient client)
Detailed Description
Definition at line 14 of file UdpLibrary.cs.
Member Function Documentation
UdpClose()
static void Components.Aphid.Library.Net.UdpLibrary.UdpClose (UdpClient client) static
Definition at line 89 of file UdpLibrary.cs.
References client.
         {
             lock (_clients)
             {
                 client.Close();
                 _clients.Remove(client);
             }
         }
UdpCreate()
static UdpClient Components.Aphid.Library.Net.UdpLibrary.UdpCreate () static
Definition at line 19 of file UdpLibrary.cs.
References client.
         {
             var client = new UdpClient();
             lock (_clients)
             {
                 _clients.Add(client);
             }
             return client;
         }
UdpReceive()
static AphidObject Components.Aphid.Library.Net.UdpLibrary.UdpReceive (UdpClient client, decimal port) static
Definition at line 72 of file UdpLibrary.cs.
References buffer, client, and Components.Aphid.TypeSystem.AphidObject.ConvertFrom().
         {
             var ep = new IPEndPoint(IPAddress.Any, (int)port);
             var buffer = client.Receive(ref ep);
             var datagram = new Datagram()
             {
                 LocalPort = (int)port,
                 RemotePort = ep.Port,
                 RemoteHost = ep.Address.ToString(),
                 Data = buffer,
             };
             return AphidObject.ConvertFrom(datagram);
         }
UdpSend()
static AphidObject Components.Aphid.Library.Net.UdpLibrary.UdpSend (AphidInterpreter interpreter, AphidObject clientObj, AphidObject datagramObj, AphidObject hostObj, AphidObject portObj) static
Definition at line 50 of file UdpLibrary.cs.
References buffer, client, Components.Aphid.TypeSystem.AphidObject.ConvertFrom(), string, Components.Aphid.Library.AphidByteConverter.ToBytes(), and Components.Aphid.TypeSystem.AphidObject.Value.
         {
             var host = (string)hostObj.Value;
             var address = GetIPV4Address(host);
             var port = (decimal)portObj.Value;
             var ep = new IPEndPoint(address, (int)port);
             var buffer = new AphidByteConverter(interpreter).ToBytes(datagramObj);
             var client = (UdpClient)clientObj.Value;
             client.Send(buffer, buffer.Length, ep);
             var datagram = new Datagram()
             {
                 LocalPort = ep.Port,
                 RemotePort = (int)port,
                 RemoteHost = host,
                 Data = buffer,
             };
             return AphidObject.ConvertFrom(datagram);
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Library/Net/UdpLibrary.cs