Aphid Programming Language: Components.Aphid.Library.StandardLibrary Class Reference
Components.Aphid.Library.StandardLibrary Class Reference
Static Public Member Functions
static void Extend (AphidInterpreter interpreter, AphidObject type, AphidObject extensions)
static AphidObject Serialize (AphidInterpreter interpreter, AphidObject obj)
static AphidObject Deserialize (AphidInterpreter interpreter, AphidObject obj)
static List< AphidObject > GetBytes (string value)
static string GetBytes (List< AphidObject > bytes)
static string GetObjectType (object obj)
static decimal CovertToNumber (AphidInterpreter interpreter, object obj)
static decimal RandomInt (decimal minValue, decimal maxValue)
static List< AphidObject > Keys (AphidObject obj)
static void SetValue (AphidInterpreter interpreter, AphidObject dst, object src)
Static Public Attributes
static Encoding Encoding = Encoding.GetEncoding("iso-8859-1")
Detailed Description
Definition at line 14 of file StandardLibrary.cs.
Member Function Documentation
CovertToNumber()
static decimal Components.Aphid.Library.StandardLibrary.CovertToNumber (AphidInterpreter interpreter, object obj) static
Definition at line 116 of file StandardLibrary.cs.
References Components.Aphid.Interpreter.AphidInterpreter.CreateRuntimeException(), is, and obj.
         {
             if (obj is string)
             {
                 return decimal.Parse((string)obj);
             }
             else
             {
                 throw interpreter.CreateRuntimeException(
                     "Could not parse number: {0}",
                     obj);
             }
         }
Deserialize()
static AphidObject Components.Aphid.Library.StandardLibrary.Deserialize (AphidInterpreter interpreter, AphidObject obj) static
Definition at line 33 of file StandardLibrary.cs.
References Components.Aphid.Serialization.AphidSerializer.Deserialize(), obj, and Components.Aphid.Interpreter.AphidInterpreter.Serializer.
         {
             return interpreter.Serializer.Deserialize((string)obj.Value);
         }
Extend()
static void Components.Aphid.Library.StandardLibrary.Extend (AphidInterpreter interpreter, AphidObject type, AphidObject extensions) static
Definition at line 19 of file StandardLibrary.cs.
References Components.Aphid.TypeSystem.TypeExtender.Extend(), string, Components.Aphid.Interpreter.AphidInterpreter.TypeExtender, and Components.Aphid.TypeSystem.AphidObject.Value.
         {
             var typeStr = (string)type.Value;
             interpreter.TypeExtender.Extend((string)type.Value, extensions, null, null);
         }
GetBytes() [1/2]
static List<AphidObject> Components.Aphid.Library.StandardLibrary.GetBytes (string value) static
Definition at line 39 of file StandardLibrary.cs.
References value, and x.
         {
             return Encoding.GetBytes(value).Select(x => new AphidObject((decimal)x)).ToList();
         }
GetBytes() [2/2]
static string Components.Aphid.Library.StandardLibrary.GetBytes (List< AphidObject > bytes) static
Definition at line 45 of file StandardLibrary.cs.
References byte, and x.
         {
             return Encoding.GetString(bytes.Select(x => (byte)(decimal)x.Value).ToArray());
         }
GetObjectType()
static string Components.Aphid.Library.StandardLibrary.GetObjectType (object obj) static
Definition at line 68 of file StandardLibrary.cs.
References n, and obj.
         {
             var n = obj.GetType().Name;
             switch (n)
             {
                 case "List`1":
                     return "list";
                 case "Decimal":
                     return "number";
                 case "String":
                     return "string";
                 default:
                     return "Unknown";
             }
         }
Keys()
static List<AphidObject> Components.Aphid.Library.StandardLibrary.Keys (AphidObject obj) static
Definition at line 366 of file StandardLibrary.cs.
References obj, and x.
         {
             return obj.Select(x => new AphidObject(x.Key)).ToList();
         }
RandomInt()
static decimal Components.Aphid.Library.StandardLibrary.RandomInt (decimal minValue, decimal maxValue) static
Definition at line 194 of file StandardLibrary.cs.
         {
             lock (_random)
             {
                 return (decimal)_random.Next((int)minValue, (int)maxValue);
             }
         }
Serialize()
static AphidObject Components.Aphid.Library.StandardLibrary.Serialize (AphidInterpreter interpreter, AphidObject obj) static
Definition at line 27 of file StandardLibrary.cs.
References obj, Components.Aphid.Serialization.AphidSerializer.Serialize(), and Components.Aphid.Interpreter.AphidInterpreter.Serializer.
         {
             return new AphidObject(interpreter.Serializer.Serialize(obj));
         }
SetValue()
static void Components.Aphid.Library.StandardLibrary.SetValue (AphidInterpreter interpreter, AphidObject dst, object src) static
Definition at line 372 of file StandardLibrary.cs.
References Components.Aphid.TypeSystem.AphidObject.Value, and Components.Aphid.Interpreter.AphidInterpreter.ValueHelper.
         {
             dst.Value = interpreter.ValueHelper.Unwrap(src);
         }
Member Data Documentation
Encoding
Encoding Components.Aphid.Library.StandardLibrary.Encoding = Encoding.GetEncoding("iso-8859-1") static
Definition at line 16 of file StandardLibrary.cs.
Referenced by Components.Aphid.Library.StreamLibrary.StreamWrite(), and Components.Aphid.Library.AphidByteConverter.ToBytes().
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Library/StandardLibrary.cs