Aphid Programming Language: Components.Cypress.NativeDebugger Class Reference
Components.Cypress.NativeDebugger Class Reference
Public Member Functions
NativeDebugger ()
void Detach ()
void Detach (DebugProcess process)
void Kill ()
ProcessMemory GetMemory (IntPtr processHandle)
void ProcessDebugEvents ()
void StartProcess (string command, EventHandler< DebuggerEventArgs > handler)
void StartProcess (string command)
void Attach (params int[] processIds)
Properties
bool IsStarted [get, set]
bool HideWindows [get, set]
bool CreateNewConsole [get, set]
bool HashException [get, set]
int HashSize [get, set]
List< DebugProcess > Processes [get]
DateTime StartTime [get]
int Timeout [get, set]
bool ReadFaultingInstructions [get, set]
Events
EventHandler< DebuggerEventArgs > DebugEventReceived
EventHandler Killing
Detailed Description
Definition at line 13 of file NativeDebugger.cs.
Constructor & Destructor Documentation
NativeDebugger()
Components.Cypress.NativeDebugger.NativeDebugger ()
Definition at line 41 of file NativeDebugger.cs.
References Components.EnvironmentHelper.IsX86().
         {
             HashSize = 32;
             HashException = true;
             Processes = new List<DebugProcess>();
             ReadFaultingInstructions = true;
             _readers = new Dictionary<IntPtr, ProcessMemory>();
             if (!EnvironmentHelper.IsX86())
             {
                 throw new NotImplementedException("NativeDebugger only supports x86.");
             }
         }
Member Function Documentation
Attach()
void Components.Cypress.NativeDebugger.Attach (params int [] processIds)
Definition at line 560 of file NativeDebugger.cs.
References Components.PInvoke.Kernel32.DebugActiveProcess(), and Components.PInvoke.Kernel32.DebugSetProcessKillOnExit().
         {
             _debugThread = Thread.CurrentThread;
             LockProcesses(() =>
             {
                 foreach (var processId in processIds)
                 {
                     var pid = (uint)processId;
                     AddProcess(pid);
                     if (!Kernel32.DebugActiveProcess(pid))
                     {
                         var error = Marshal.GetLastWin32Error();
                         throw new Win32Exception(error);
                         throw new InvalidOperationException("Could not attach to process.");
                     }
                 }
             });
             Kernel32.DebugSetProcessKillOnExit(false);
             ProcessDebugEvents();
         }
Detach() [1/2]
void Components.Cypress.NativeDebugger.Detach ()
Definition at line 153 of file NativeDebugger.cs.
References p.
         {
             foreach (var p in Processes)
             {
                 Detach(p);
             }
         }
Detach() [2/2]
void Components.Cypress.NativeDebugger.Detach (DebugProcess process)
Definition at line 161 of file NativeDebugger.cs.
References p.
         {
             foreach (var p in process.Children)
             {
                 Detach(p);
             }
             DetachNode(process);
         }
GetMemory()
ProcessMemory Components.Cypress.NativeDebugger.GetMemory (IntPtr processHandle)
Definition at line 257 of file NativeDebugger.cs.
References out.
         {
             lock (_readers)
             {
                 ProcessMemory mem;
                 if (!_readers.TryGetValue(processHandle, out mem))
                 {
                     _readers.Add(processHandle, mem = new ProcessMemory(processHandle));
                 }
                 return mem;
             }
         }
Kill()
void Components.Cypress.NativeDebugger.Kill ()
Definition at line 186 of file NativeDebugger.cs.
References p.
         {
             if (Killing != null)
             {
                 Killing(this, new EventArgs());
             }
             LockProcesses(() =>
             {
                 _killProcesses = true;
                 foreach (var p in Processes)
                 {
                     Kill(p);
                 }
             });
         }
ProcessDebugEvents()
void Components.Cypress.NativeDebugger.ProcessDebugEvents ()
Definition at line 272 of file NativeDebugger.cs.
References buffer, byte, Components.PInvoke.Kernel32.CloseHandle(), handle, out, p, Components.PInvoke.Kernel32.ReadProcessMemory(), and Components.PInvoke.Kernel32.WaitForDebugEvent().
         {
             IsStarted = true;
             var debugEvent = new DEBUG_EVENT();
             while (!_killProcesses && IsStarted && Processes.Count != 0)
             {
                 if (!Kernel32.WaitForDebugEvent(ref debugEvent, 200))
                 {
                     var error = Marshal.GetLastWin32Error();
                     //if (error == 121 || _killProcesses)
                     /*if (_killProcesses)
                     {
                         KillCore();
                         break;
                     }
                     else */if (error != 121)
                     {
                         throw new Win32Exception(error);
                     }
                     else
                     {
                         if (Timeout > 0 &&
                             (DateTime.Now - StartTime).TotalMilliseconds > Timeout)
{
                             Kill();
                             return;
                         }
                         else
{
                             continue;
                         }
                     }
                 }
                 Process p = null;
                 LockProcesses(() =>
                 {
                     if (_processTable.ContainsKey(debugEvent.dwProcessId))
                     {
                         p = _processTable[debugEvent.dwProcessId];
                     }
                 });
                 byte[] buffer = null;
                 string hash = "[NO HASH]";
                 switch (debugEvent.dwDebugEventCode)
                 {
                     case DebugEventType.CREATE_PROCESS_DEBUG_EVENT:
                         if (p != null)
{
                             var mem = new ProcessMemory(p.Handle);
                             lock (_readers)
{
                                 _readers.Add(p.Handle, mem);
                             }
 #if FULL_DBG
                             if (!_hookManagers.ContainsKey(p.Handle))
{
                                 _hookManagers.Add(p.Handle, new HookManager(mem));
                                 _breakpointManagers.Add(p.Handle, new BreakpointManager(mem));
                             }
 #endif
                         }
                         lock (_loaderBreakpointTable)
{
                             if (!_loaderBreakpointTable.ContainsKey(debugEvent.dwProcessId))
                                 _loaderBreakpointTable.Add(debugEvent.dwProcessId, false);
                         }
                         LockProcesses(() =>
{
                             AddProcess(debugEvent.dwProcessId);
                             p = _processTable[debugEvent.dwProcessId];
                         });
                         Kernel32.CloseHandle(debugEvent.CreateProcessInfo.hFile);
                         break;
                     case DebugEventType.EXIT_PROCESS_DEBUG_EVENT:
                         lock (_loaderBreakpointTable)
{
                             if (_loaderBreakpointTable.ContainsKey(debugEvent.dwProcessId))
{
                                 _loaderBreakpointTable.Remove(debugEvent.dwProcessId);
                             }
                         }
                         LockProcesses(() => RemoveProcess(debugEvent.dwProcessId));
                         if (p != null)
{
                             lock (_readers)
{
                                 try
{
                                     // Swallow exceptions caused by accessing Process.Handle after
                                     // process has exited.
                                     _readers.Remove(p.Handle);
                                 }
                                 catch { }
                             }
                         }
                         break;
                     case DebugEventType.LOAD_DLL_DEBUG_EVENT:
                         Kernel32.CloseHandle(debugEvent.LoadDll.hFile);
                         break;
                     case DebugEventType.EXCEPTION_DEBUG_EVENT:
                         lock (_loaderBreakpointTable)
{
                             if (debugEvent.Exception.ExceptionRecord.ExceptionCode == ExceptionCode.EXCEPTION_BREAKPOINT)
{
                                 if (!_loaderBreakpointTable.ContainsKey(debugEvent.dwProcessId))
                                     _loaderBreakpointTable.Add(debugEvent.dwProcessId, false);
                                 if (!_loaderBreakpointTable[debugEvent.dwProcessId])
{
                                     _loaderBreakpointTable[debugEvent.dwProcessId] = true;
                                     debugEvent.ContinueUnhandled();
                                     continue;
                                 }
                             }
                         }
                         if (p != null)
{
                             if (HashException)
{
                                 hash = GetExceptionHash(p, debugEvent);
                             }
                             if (ReadFaultingInstructions)
{
                                 buffer = new byte[32];
                                 int bytesRead;
                                 IntPtr exPtr = IntPtr.Zero;
                                 try
{
                                     exPtr = (IntPtr)debugEvent.Exception.ExceptionRecord.ExceptionAddress;
                                 }
                                 catch (OverflowException)
{
                                 }
                                 if (Kernel32.ReadProcessMemory(
                                     p.Handle,
                                     exPtr,
                                     buffer,
                                     buffer.Length,
                                     out bytesRead))
{
                                     if (bytesRead < buffer.Length)
{
                                         Array.Resize(ref buffer, bytesRead);
                                     }
                                 }
                                 else
{
                                     buffer = null;
                                 }
                                     //hash = CreateInstructionHash(buffer.Take(HashSize));
                             }
                         }
                         //elser
                         //{
                         //    throw new InvalidOperationException();
                         //}
                         break;
                 }
                 if (DebugEventReceived != null)
                 {
                     IntPtr handle;
                     try
                     {
                         handle = p != null ? p.Handle : IntPtr.Zero;
                     }
                     catch
                     {
                         handle = IntPtr.Zero;
                     }
 #if FULL_DBG
                     BreakpointManager breakpoints;
                     if (!_breakpointManagers.TryGetValue(handle, out breakpoints))
                     {
                         _breakpointManagers.Add(handle, breakpoints = new BreakpointManager(GetMemory(handle)));
                     }
                     HookManager hooks;
                     if (!_hookManagers.TryGetValue(handle, out hooks))
                     {
                         _hookManagers.Add(handle, hooks = new HookManager(GetMemory(handle)));
                     }
 #endif
                     DebugEventReceived(this,
                         new DebuggerEventArgs(
                             handle,
                             buffer,
                             hash,
                             debugEvent,
                             GetMemory(handle)
 #if FULL_DBG
                             ,
                             breakpoints,
                             hooks
 #endif
                             ));
                 }
                 if (Timeout > 0 &&
                             (DateTime.Now - StartTime).TotalMilliseconds > Timeout)
                 {
                     Kill();
                     return;
                 }
             }
             //KillCore();
         }
StartProcess() [1/2]
void Components.Cypress.NativeDebugger.StartProcess (string command, EventHandler< DebuggerEventArgs > handler)
Definition at line 504 of file NativeDebugger.cs.
         {
             DebugEventReceived += handler;
             StartProcess(command);
             DebugEventReceived -= handler;
         }
StartProcess() [2/2]
void Components.Cypress.NativeDebugger.StartProcess (string command)
Definition at line 511 of file NativeDebugger.cs.
References Components.PInvoke.Kernel32.CloseHandle(), Components.PInvoke.Kernel32.CreateProcess(), Components.PInvoke.Kernel32.DebugSetProcessKillOnExit(), and si.
         {
             StartTime = DateTime.Now;
             Kernel32.DebugSetProcessKillOnExit(true);
             _debugThread = Thread.CurrentThread;
             var pi = new PROCESS_INFORMATION();
             var si = new STARTUPINFO()
             {
                 cb = Marshal.SizeOf(typeof(STARTUPINFO))
             };
             var creationFlags = ProcessCreationFlags.DEBUG_PROCESS;
             if (CreateNewConsole)
             {
                 creationFlags |= ProcessCreationFlags.CREATE_NEW_CONSOLE;
             }
             if (HideWindows)
             {
                 creationFlags |= ProcessCreationFlags.CREATE_NO_WINDOW;
                 si.dwFlags = 1; // STARTF_USESHOWWINDOW
             }
             if (!Kernel32.CreateProcess(
                 null,
                 command,
                 IntPtr.Zero,
                 IntPtr.Zero,
                 false,
                 creationFlags,
                 IntPtr.Zero,
                 null,
                 si,
                 pi))
             {
                 throw new Win32Exception(Marshal.GetLastWin32Error());
             }
             LockProcesses(() => AddProcess(pi.dwProcessId));
             ProcessDebugEvents();
             //Kernel32.CloseHandle(si.hStdError);
             //Kernel32.CloseHandle(si.hStdInput);
             //Kernel32.CloseHandle(si.hStdOutput);
             Kernel32.CloseHandle(pi.hThread);
             Kernel32.CloseHandle(pi.hProcess);
         }
Property Documentation
CreateNewConsole
bool Components.Cypress.NativeDebugger.CreateNewConsole get set
Definition at line 33 of file NativeDebugger.cs.
 { get; set; }
HashException
bool Components.Cypress.NativeDebugger.HashException get set
Definition at line 34 of file NativeDebugger.cs.
 { get; set; }
HashSize
int Components.Cypress.NativeDebugger.HashSize get set
Definition at line 35 of file NativeDebugger.cs.
 { get; set; }
HideWindows
bool Components.Cypress.NativeDebugger.HideWindows get set
Definition at line 32 of file NativeDebugger.cs.
 { get; set; }
IsStarted
bool Components.Cypress.NativeDebugger.IsStarted get set
Definition at line 31 of file NativeDebugger.cs.
 { get; set; }
Processes
List<DebugProcess> Components.Cypress.NativeDebugger.Processes get
Definition at line 36 of file NativeDebugger.cs.
 { get; private set; }
ReadFaultingInstructions
bool Components.Cypress.NativeDebugger.ReadFaultingInstructions get set
Definition at line 39 of file NativeDebugger.cs.
 { get; set; }
StartTime
DateTime Components.Cypress.NativeDebugger.StartTime get
Definition at line 37 of file NativeDebugger.cs.
 { get; private set; }
Timeout
int Components.Cypress.NativeDebugger.Timeout get set
Definition at line 38 of file NativeDebugger.cs.
 { get; set; }
Event Documentation
DebugEventReceived
EventHandler<DebuggerEventArgs> Components.Cypress.NativeDebugger.DebugEventReceived
Definition at line 15 of file NativeDebugger.cs.
Killing
EventHandler Components.Cypress.NativeDebugger.Killing
Definition at line 16 of file NativeDebugger.cs.
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/External/Debugging/NativeDebugger.cs