Aphid Programming Language: Mantispid.TypeInferenceMutator Class Reference
Mantispid.TypeInferenceMutator Class Reference
Public Member Functions
TypeInferenceMutator (ParserGeneratorConfig config)
Public Member Functions inherited from Components.Aphid.Parser.AphidMutator
AphidMutator ()
List< AphidExpression > Mutate (List< AphidExpression > ast)
List< AphidExpression > MutateRecursively (List< AphidExpression > expression)
virtual void Reset ()
Protected Member Functions
override List< AphidExpression > MutateCore (AphidExpression expression, out bool hasChanged)
Protected Member Functions inherited from Components.Aphid.Parser.AphidMutator
virtual List< AphidExpression > OnMutate (List< AphidExpression > ast)
virtual void BeginRecursiveMutationPass (List< AphidExpression > ast)
virtual void EndRecursiveMutationPass (List< AphidExpression > ast)
void FinalizeMutation ()
Additional Inherited Members
Properties inherited from Components.Aphid.Parser.AphidMutator
Stack< AphidExpression > Ancestors [get]
bool HasMutated [get]
bool IsStatement [get]
bool HasFinalized [get]
Detailed Description
Definition at line 12 of file TypeInferenceMutator.cs.
Constructor & Destructor Documentation
TypeInferenceMutator()
Mantispid.TypeInferenceMutator.TypeInferenceMutator (ParserGeneratorConfig config)
Definition at line 20 of file TypeInferenceMutator.cs.
         {
             _config = config;
         }
Member Function Documentation
MutateCore()
override List<AphidExpression> Mantispid.TypeInferenceMutator.MutateCore (AphidExpression expression, out bool hasChanged) protected virtual
Implements Components.Aphid.Parser.AphidMutator.
Definition at line 25 of file TypeInferenceMutator.cs.
References Mantispid.SymbolTable< TValue >.Add(), expression, Mantispid.ParserIdentifier.FromIdentifierExpression(), Components.Aphid.Parser.CallExpression.FunctionExpression, Components.Aphid.Parser.AphidMutator.IsStatement, Components.Aphid.Parser.BinaryOperatorExpression.LeftOperand, Name, Components.Aphid.Parser.UnaryOperatorExpression.Operand, out, Components.Aphid.Parser.BinaryOperatorExpression.RightOperand, Mantispid.SymbolTable< TValue >.TryResolve(), Components.Aphid.Parser.AphidNode.Type, and Components.Aphid.Parser.FunctionExpression.Type.
         {
             hasChanged = false;
             if (IsStatement && expression.Type == AphidExpressionType.IdentifierExpression)
             {
                 var idExp = expression.ToIdentifier();
                 var currentId = ParserIdentifier.FromIdentifierExpression(idExp);
                 ParserIdentifier inferredId;
                 if (!_idTable.TryResolve(idExp.Identifier, out inferredId))
                 {
                     _idTable.Add(idExp.Identifier, currentId);
                     hasChanged = true;
                 }
                 else
                 {
                     if (!currentId.IsList && inferredId.IsList)
                     {
                         currentId.IsList = inferredId.IsList;
                         currentId.Type = inferredId.Type;
                         hasChanged = true;
                         return new List<AphidExpression>
{
                             new BinaryOperatorExpression(
                                 currentId.ToIdentifierExpression(),
                                 AphidTokenType.AssignmentOperator,
                                 new IdentifierExpression(
                                     currentId.Type ?? _config.BaseClass,
                                     new List<IdentifierExpression> { new IdentifierExpression("list") }))
                         };
                     }
                 }
             }
             CallExpression funcExp;
             BinaryOperatorExpression binOpExp;
             if (expression.Type == AphidExpressionType.CallExpression &&
                 (funcExp = expression.ToCall()).FunctionExpression.Type == AphidExpressionType.BinaryOperatorExpression &&
                 ((binOpExp = funcExp.FunctionExpression.ToBinaryOperator()).Operator == AphidTokenType.MemberOperator) &&
                 binOpExp.LeftOperand.Type == AphidExpressionType.IdentifierExpression &&
                 binOpExp.RightOperand.Type == AphidExpressionType.IdentifierExpression &&
                 binOpExp.RightOperand.ToIdentifier().Identifier == "Add")
             {
                 var id = binOpExp.LeftOperand.ToIdentifier().Identifier;
                 ParserIdentifier ids;
                 if (!_idTable.TryResolve(id, out ids))
                 {
                     _idTable.Add(id, ids = new ParserIdentifier() { Name = id });
                 }
                 if (!ids.IsList)
                 {
                     ids.IsList = true;
                     if (ids.Type == null)
                     {
                         ids.Type = _config.BaseClass;
                     }
                     hasChanged = true;
                 }
             }
             UnaryOperatorExpression unOpExp;
             if (expression.Type == AphidExpressionType.UnaryOperatorExpression &&
                 (unOpExp = expression.ToUnaryOperator()).Operator == AphidTokenType.retKeyword)
             {
                 if (unOpExp.Operand.Type == AphidExpressionType.IdentifierExpression)
                 {
                     var retId = unOpExp.Operand.ToIdentifier();
                     if (!_returnIds.Contains(retId.Identifier))
                     {
                         hasChanged = true;
                         _returnIds.Add(retId.Identifier);
                     }
                 }
             }
             //else if (expression.Type == AphidNodeType.BinaryOperatorExpression &&
             //    (binOpExp = expression.ToBinaryOperator()).
             return new List<AphidExpression> { expression };
             //throw new NotImplementedException();
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Compiler/Medusa/Mantispid/TypeInferenceMutator.cs