Aphid Programming Language: Components.Aphid.UI.AphidCli Class Reference
Components.Aphid.UI.AphidCli Class Reference
Static Public Member Functions
static bool TryAction (AphidInterpreter interpreter, string code, Action action)
static bool TryAction (AphidInterpreter interpreter, string code, Action action, bool allowErrorReporting)
static void ExecuteCode (string code)
static void ExecuteCode (AphidInterpreter interpreter, string code)
static void ExecuteCode (string code, bool isTextDocument)
static AphidObject DumpExpression (string code)
static AphidObject DumpExpression (AphidInterpreter interpreter, string code)
static void ExecuteCode (AphidInterpreter interpreter, string code, bool isTextDocument)
static void DumpException (AphidParserException exception, string code)
static void DumpException (AphidRuntimeException exception, AphidInterpreter interpreter)
static void DumpException (AphidLoadScriptException exception, AphidInterpreter interpreter)
static void DumpException (Exception exception, AphidInterpreter interpreter)
static void DumpStackTrace (AphidInterpreter interpreter)
static string GetErrorMessage (AphidParserException exception, string code)
static string GetErrorMessage (AphidRuntimeException exception)
static string GetErrorMessage (AphidLoadScriptException exception, string code)
static string GetErrorMessage (Exception exception)
static void WriteSubheader (string text, string style="")
static void WriteErrorMessage (string format, params object[] arg)
static void WriteMessage (ConsoleColor tokenColor, char token, string format, params object[] arg)
static string Highlight (string code)
Properties
static bool ShowClrStack [get, set]
static int ExcerptSurroundingLines [get, set]
static Action< string > WriteOut [get, set]
static Action< string > WriteLineOut [get, set]
static Exception LastException [get, set]
Detailed Description
Definition at line 18 of file AphidCli.cs.
Member Function Documentation
DumpException() [1/4]
static void Components.Aphid.UI.AphidCli.DumpException (AphidParserException exception, string code) static
Definition at line 173 of file AphidCli.cs.
References code, and Components.External.ConsolePlus.Cli.StyleEscape().
Referenced by Components.Aphid.UI.AphidCli.ExecuteCode(), and Components.Aphid.UI.AphidCli.TryAction().
         {
             WriteErrorMessage(Cli.StyleEscape(GetErrorMessage(exception, code)));
         }
DumpException() [2/4]
static void Components.Aphid.UI.AphidCli.DumpException (AphidRuntimeException exception, AphidInterpreter interpreter) static
Definition at line 178 of file AphidCli.cs.
References Components.External.ConsolePlus.Cli.StyleEscape().
         {
             WriteErrorMessage(Cli.StyleEscape(GetErrorMessage(exception)));
             DumpStackTrace(interpreter);
         }
DumpException() [3/4]
static void Components.Aphid.UI.AphidCli.DumpException (AphidLoadScriptException exception, AphidInterpreter interpreter) static
Definition at line 186 of file AphidCli.cs.
References Components.Aphid.Interpreter.AphidLoadScriptException.ScriptFile, and Components.External.ConsolePlus.Cli.StyleEscape().
         {
             WriteErrorMessage(
                 Cli.StyleEscape(
                     GetErrorMessage(
                         exception,
                         File.ReadAllText(exception.ScriptFile))));
             DumpStackTrace(interpreter);
         }
DumpException() [4/4]
static void Components.Aphid.UI.AphidCli.DumpException (Exception exception, AphidInterpreter interpreter) static
Definition at line 199 of file AphidCli.cs.
References Components.External.ConsolePlus.Cli.StyleEscape().
         {
             WriteErrorMessage(Cli.StyleEscape(GetErrorMessage(exception)));
             if (interpreter != null)
             {
                 DumpStackTrace(interpreter);
             }
         }
DumpExpression() [1/2]
static AphidObject Components.Aphid.UI.AphidCli.DumpExpression (string code) static
Definition at line 106 of file AphidCli.cs.
References code.
         {
             return DumpExpression(new AphidInterpreter(), code);
         }
DumpExpression() [2/2]
static AphidObject Components.Aphid.UI.AphidCli.DumpExpression (AphidInterpreter interpreter, string code) static
Definition at line 111 of file AphidCli.cs.
References code, Components.Aphid.Interpreter.AphidInterpreter.GetReturnValue(), Components.Aphid.Interpreter.AphidInterpreter.Interpret(), lexer, Components.Aphid.Parser.AphidParser.ParseExpression(), tokens, Components.Aphid.TypeSystem.AphidObject.Value, and Components.Aphid.Parser.AphidVisitor.VisitExpression().
         {
             AphidObject result = null;
             TryAction(
                 interpreter,
                 code,
                 () =>
                 {
                     if (code.Trim() == "")
                     {
                         return;
                     }
                     var lexer = new AphidLexer(code);
                     var tokens = lexer.GetTokens();
                     var exp = AphidParser.ParseExpression(tokens, code);
                     var retExp = new UnaryOperatorExpression(AphidTokenType.retKeyword, exp);
                     new AphidCodeVisitor(code).VisitExpression(retExp);
                     interpreter.Interpret(retExp);
                     result = interpreter.GetReturnValue();
                     if (result != null && (result.Value != null || result.Any()))
                     {
                         Console.WriteLine(new AphidSerializer(interpreter).Serialize(result));
                     }
                 });
             return result;
         }
DumpStackTrace()
static void Components.Aphid.UI.AphidCli.DumpStackTrace (AphidInterpreter interpreter) static
Definition at line 211 of file AphidCli.cs.
References frame, Components.Aphid.Interpreter.AphidInterpreter.GetStackTrace(), i, Components.External.ConsolePlus.Cli.StyleEscape(), trace, and x.
         {
             var trace = interpreter.GetStackTrace();
             var i = 0;
             if (!Console.IsOutputRedirected)
             {
                 WriteSubheader("Stack Trace", "~|Blue~~White~");
             }
             else
             {
                 WriteErrorMessage("Stack Trace");
             }
             foreach (var frame in trace)
             {
                 var rawFrameStr = frame.ToString(true);
                 var frameStr = Cli.StyleEscape(
                     !"\r\n".Any(rawFrameStr.Contains) ?
                         rawFrameStr :
                         rawFrameStr
                             .NormalizeLines()
                             .SplitLines()
                             .Select(x => x.Trim())
                             .Join(" "));
                 var truncated = false;
                 int maxWidth;
                 try
                 {
                     maxWidth = Console.WindowWidth - 12;
                 }
                 catch
                 {
                     // Todo: Move constant into config.
                     maxWidth = 80;
                 }
                 if (frameStr.Length > maxWidth)
                 {
                     frameStr = frameStr.Remove(maxWidth);
                     truncated = true;
                 }
                 frameStr = Highlight(frameStr);
                 if (truncated)
                 {
                     frameStr += " ~White~...~R~";
                 }
                 var frameOut = string.Format(
                     "[~White~{0:x4}~R~] {1}",
                     i++,
                     frameStr);
                 WriteLineOut(frameOut);
             }
             WriteLineOut("");
             var statement = interpreter.CurrentStatement;
             if (statement == null)
             {
                 return;
             }
             WriteLineOut(
                 string.Format(
                     "Faulting statement: {0}",
                     Highlight(
                         Cli.StyleEscape(
                             statement.Code != null ?
                                 statement.Code.Substring(statement.Index, statement.Length) :
                                 statement.ToString()))));
             DumpExcerpt(statement);
             var file = interpreter.GetScriptFilename();
             if (file != null)
             {
                 WriteLineOut(string.Format("Script: ~Yellow~{0}~R~", file));
             }
         }
ExecuteCode() [1/4]
static void Components.Aphid.UI.AphidCli.ExecuteCode (string code) static
Definition at line 91 of file AphidCli.cs.
References code.
         {
             ExecuteCode(code, isTextDocument: false);
         }
ExecuteCode() [2/4]
static void Components.Aphid.UI.AphidCli.ExecuteCode (AphidInterpreter interpreter, string code) static
Definition at line 96 of file AphidCli.cs.
References code.
         {
             ExecuteCode(interpreter, code, isTextDocument: false);
         }
ExecuteCode() [3/4]
static void Components.Aphid.UI.AphidCli.ExecuteCode (string code, bool isTextDocument) static
Definition at line 101 of file AphidCli.cs.
References code.
         {
             ExecuteCode(new AphidInterpreter(), code, isTextDocument);
         }
ExecuteCode() [4/4]
static void Components.Aphid.UI.AphidCli.ExecuteCode (AphidInterpreter interpreter, string code, bool isTextDocument) static
Definition at line 142 of file AphidCli.cs.
References code, Components.Aphid.UI.AphidCli.DumpException(), and Components.Aphid.Interpreter.AphidInterpreter.Interpret().
         {
             try
             {
                 interpreter.Interpret(code, isTextDocument);
             }
             catch (AphidParserException exception)
             {
                 AphidCli.DumpException(exception, code);
                 Environment.Exit((int)AphidExitCode.ParserError);
             }
             catch (AphidLoadScriptException exception)
             {
                 AphidCli.DumpException(exception, interpreter);
                 Environment.Exit((int)AphidExitCode.LoadScriptError);
             }
             catch (AphidRuntimeException exception)
             {
                 AphidCli.DumpException(exception, interpreter);
                 Environment.Exit((int)AphidExitCode.RuntimeError);
             }
             catch (Exception exception)
             {
                 AphidCli.DumpException(exception, interpreter);
                 Environment.Exit((int)AphidExitCode.GeneralError);
             }
         }
GetErrorMessage() [1/4]
static string Components.Aphid.UI.AphidCli.GetErrorMessage (AphidParserException exception, string code) static
Definition at line 327 of file AphidCli.cs.
References code, and Components.Aphid.Parser.ParserErrorMessage.Create().
         {
             return string.Format(
                 "Parser exception\r\n{0}",
                 ParserErrorMessage.Create(code, exception));
         }
GetErrorMessage() [2/4]
static string Components.Aphid.UI.AphidCli.GetErrorMessage (AphidRuntimeException exception) static
Definition at line 336 of file AphidCli.cs.
         {
             return string.Format(
                 "Unexpected runtime exception\r\n\r\n{0}\r\n",
                 exception.Message);
         }
GetErrorMessage() [3/4]
static string Components.Aphid.UI.AphidCli.GetErrorMessage (AphidLoadScriptException exception, string code) static
Definition at line 343 of file AphidCli.cs.
References Components.Aphid.Interpreter.AphidLoadScriptException.AphidRuntimeException, code, Components.Aphid.Interpreter.AphidLoadScriptException.LoadScriptExceptionType, Components.Aphid.Interpreter.AphidLoadScriptException.ParserException, sb, and t.
         {
             var sb = new StringBuilder("Load script exception\r\n");
             var t = exception.LoadScriptExceptionType;
             sb.AppendLine(
                 t == AphidExceptionType.ParserException ?
                     GetErrorMessage(exception.ParserException, code) :
                 t == AphidExceptionType.AphidRuntimeException ?
                     GetErrorMessage(exception.AphidRuntimeException) :
                 GetErrorMessage(exception.InnerException));
             return sb.ToString();
         }
GetErrorMessage() [4/4]
static string Components.Aphid.UI.AphidCli.GetErrorMessage (Exception exception) static
Definition at line 358 of file AphidCli.cs.
References ShowClrStack, and Components.Aphid.Interpreter.ExceptionHelper.Unwrap().
         {
             var ex = ExceptionHelper.Unwrap(exception);
             return string.Format(
                 ShowClrStack ?
                     "Unexpected exception: {0}\r\n\r\n{1}\r\n" :
                     "Unexpected exception: {0}\r\n",
                 ex.Message,
                 ex.StackTrace);
         }
Highlight()
static string Components.Aphid.UI.AphidCli.Highlight (string code) static
Definition at line 398 of file AphidCli.cs.
References code, Components.External.ConsolePlus.VT100.GetString(), and Components.Aphid.UI.AphidSyntaxHighlighter.Highlight().
         {
             return code.Trim().Any() ? VT100.GetString(_highlighter.Highlight(code)) : code;
         }
TryAction() [1/2]
static bool Components.Aphid.UI.AphidCli.TryAction (AphidInterpreter interpreter, string code, Action action) static
Definition at line 43 of file AphidCli.cs.
References code.
Referenced by Components.Aphid.UI.AphidRepl.Run().
         {
             return TryAction(interpreter, code, action, allowErrorReporting: false);
         }
TryAction() [2/2]
static bool Components.Aphid.UI.AphidCli.TryAction (AphidInterpreter interpreter, string code, Action action, bool allowErrorReporting) static
Definition at line 48 of file AphidCli.cs.
References code, Components.Aphid.UI.AphidCli.DumpException(), Components.Aphid.Debugging.AphidErrorReporter.SaveErrorInformation(), and Components.Aphid.Interpreter.AphidInterpreter.SetIsInTryCatchFinally().
         {
             try
             {
                 var backup = interpreter.SetIsInTryCatchFinally(true);
                 action();
                 interpreter.SetIsInTryCatchFinally(backup);
                 return true;
             }
             catch (AphidParserException exception)
             {
                 LastException = exception;
                 AphidCli.DumpException(exception, code);
             }
             catch (AphidLoadScriptException exception)
             {
                 LastException = exception;
                 AphidCli.DumpException(exception, interpreter);
             }
             catch (AphidRuntimeException exception)
             {
                 LastException = exception;
                 AphidCli.DumpException(exception, interpreter);
             }
             catch (Exception exception)
             {
                 LastException = exception;
                 AphidCli.DumpException(exception, interpreter);
             }
             if (allowErrorReporting)
             {
                 AphidErrorReporter.SaveErrorInformation(LastException, interpreter);
             }
             return false;
         }
WriteErrorMessage()
static void Components.Aphid.UI.AphidCli.WriteErrorMessage (string format, params object [] arg) static
Definition at line 381 of file AphidCli.cs.
References format.
         {
             WriteMessage(
                 ConsoleColor.Red,
                 _errorChar,
                 format,
                 arg);
         }
WriteMessage()
static void Components.Aphid.UI.AphidCli.WriteMessage (ConsoleColor tokenColor, char token, string format, params object [] arg) static
Definition at line 390 of file AphidCli.cs.
References format, and token.
         {
             WriteLineOut(
                 string.Format(
                     string.Format(_messageFormat, tokenColor, token, format.Replace("{", "{{").Replace("}", "}}")),
                     arg));
         }
WriteSubheader()
static void Components.Aphid.UI.AphidCli.WriteSubheader (string text, string style = "") static
Definition at line 370 of file AphidCli.cs.
References Components.External.ConsolePlus.Cli.BufferWidth, Components.External.ConsolePlus.Cli.Escape(), string, style, and text.
         {
             WriteLineOut(
                 string.Format(
                     "{0}  {1}{2}{3}",
                     style,
                     Cli.Escape(text),
                     new string(' ', Cli.BufferWidth - text.Length - 3),
                     "~R~"));
         }
Property Documentation
ExcerptSurroundingLines
int Components.Aphid.UI.AphidCli.ExcerptSurroundingLines static get set
Definition at line 28 of file AphidCli.cs.
 { get; set; }
LastException
Exception Components.Aphid.UI.AphidCli.LastException static get set
Definition at line 34 of file AphidCli.cs.
 { get; set; }
ShowClrStack
bool Components.Aphid.UI.AphidCli.ShowClrStack static get set
Definition at line 26 of file AphidCli.cs.
 { get; set; }
WriteLineOut
Action<string> Components.Aphid.UI.AphidCli.WriteLineOut static get set
Definition at line 32 of file AphidCli.cs.
 { get; set; }
WriteOut
Action<string> Components.Aphid.UI.AphidCli.WriteOut static get set
Definition at line 30 of file AphidCli.cs.
 { get; set; }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/UI/AphidCli.cs