Aphid Programming Language: AphidUI.CodeTextBox Class Reference
AphidUI.CodeTextBox Class Reference
Interaction logic for CodeEditor.xaml
Public Member Functions
CodeTextBox ()
Static Public Member Functions
static void OnTextChanged (DependencyObject d, DependencyPropertyChangedEventArgs e)
static void OnAcceptsReturnChanged (DependencyObject d, DependencyPropertyChangedEventArgs e)
Static Public Attributes
static readonly DependencyProperty TextProperty
static readonly DependencyProperty AcceptsReturnProperty
Properties
string Text [get, set]
bool AcceptsReturn [get, set]
Detailed Description
Interaction logic for CodeEditor.xaml
Definition at line 22 of file CodeTextBox.xaml.cs.
Constructor & Destructor Documentation
CodeTextBox()
AphidUI.CodeTextBox.CodeTextBox ()
Definition at line 70 of file CodeTextBox.xaml.cs.
References AphidUI.Internal.CodeCanvas.TextChanged, and AphidUI.Internal.CodeCanvas.UserControl_KeyDown().
Referenced by AphidUI.CodeTextBox.OnAcceptsReturnChanged().
         {
             InitializeComponent();
             _codeCanvas = Viewer.Content as CodeCanvas;
             if (_codeCanvas == null)
             {
                 var border = Viewer.Content as Border;
                 _codeCanvas = border.Child as CodeCanvas;
                 if (_codeCanvas == null)
                 {
                     throw new InvalidOperationException();
                 }
             }
             _codeCanvas.TextChanged += CodeEditor_TextChanged;
             Viewer.PreviewKeyDown += _codeCanvas.UserControl_KeyDown;
             SetScrollBarVisibility();
             //SizeChanged += _codeCanvas.UserControl_SizeChanged;
         }
Member Function Documentation
OnAcceptsReturnChanged()
static void AphidUI.CodeTextBox.OnAcceptsReturnChanged (DependencyObject d, DependencyPropertyChangedEventArgs e) static
Definition at line 61 of file CodeTextBox.xaml.cs.
References AphidUI.CodeTextBox.CodeTextBox(), e, and t.
         {
             var t = (CodeTextBox)d;
             var b = (bool)e.NewValue;
             t.SetScrollBarVisibility();
             t._codeCanvas.AcceptsReturn = b;
         }
OnTextChanged()
static void AphidUI.CodeTextBox.OnTextChanged (DependencyObject d, DependencyPropertyChangedEventArgs e) static
Definition at line 38 of file CodeTextBox.xaml.cs.
References e, string, and t.
         {
             var v = (string)e.NewValue;
             var t = (CodeTextBox)d;
             if (t.TextBox.Text != v)
             {
                 t.TextBox.SetText(v);
             }
         }
Member Data Documentation
AcceptsReturnProperty
readonly DependencyProperty AphidUI.CodeTextBox.AcceptsReturnProperty static
Initial value:
= DependencyProperty.Register(
                "AcceptsReturn",
                typeof(bool),
                typeof(CodeTextBox),
                new FrameworkPropertyMetadata(false, new PropertyChangedCallback(OnAcceptsReturnChanged)))
Definition at line 49 of file CodeTextBox.xaml.cs.
TextProperty
readonly DependencyProperty AphidUI.CodeTextBox.TextProperty static
Initial value:
= DependencyProperty.Register(
                "Text",
                typeof(string),
                typeof(CodeTextBox),
                new FrameworkPropertyMetadata(null, new PropertyChangedCallback(OnTextChanged)))
Definition at line 26 of file CodeTextBox.xaml.cs.
Property Documentation
AcceptsReturn
bool AphidUI.CodeTextBox.AcceptsReturn get set
Definition at line 56 of file CodeTextBox.xaml.cs.
         {
             get { return (bool)GetValue(AcceptsReturnProperty); }
             set { SetValue(AcceptsReturnProperty, value); }
         }
Text
string AphidUI.CodeTextBox.Text get set
Definition at line 33 of file CodeTextBox.xaml.cs.
         {
             get { return (string)GetValue(TextProperty); }
             set { SetValue(TextProperty, value); }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/AphidUI/CodeTextBox.xaml.cs