Aphid Programming Language: Components.Cypress.MemoryDump Class Reference
Components.Cypress.MemoryDump Class Reference
Static Public Member Functions
static void Create (string filename)
static void Create (int processId, string filename)
static void Create (Process process, string filename)
Detailed Description
Definition at line 15 of file MemoryDump.cs.
Member Function Documentation
Create() [1/3]
static void Components.Cypress.MemoryDump.Create (string filename) static
Definition at line 17 of file MemoryDump.cs.
Referenced by Components.Aphid.Debugging.AphidMemoryDump.Create().
         {
             Create(Process.GetCurrentProcess(), filename);
         }
Create() [2/3]
static void Components.Cypress.MemoryDump.Create (int processId, string filename) static
Definition at line 22 of file MemoryDump.cs.
         {
             Create(Process.GetProcessById(processId), filename);
         }
Create() [3/3]
static void Components.Cypress.MemoryDump.Create (Process process, string filename) static
Definition at line 27 of file MemoryDump.cs.
References Components.PInvoke.MINIDUMP_EXCEPTION_INFORMATION.ClientPointers, Components.PInvoke.MINIDUMP_EXCEPTION_INFORMATION.ExceptionPointers, Components.PInvoke.Kernel32.GetCurrentThreadId(), Components.PInvoke.DbgHelp.MiniDumpWriteDump(), and Components.PInvoke.MINIDUMP_EXCEPTION_INFORMATION.ThreadId.
         {
             using (var s = File.Create(filename))
             {
                 var ptrs = System.Runtime.InteropServices.Marshal.GetExceptionPointers();
                 bool result;
                 if (ptrs == IntPtr.Zero)
                 {
                     result = DbgHelp.MiniDumpWriteDump(
                         process.Handle,
                         (uint)process.Id,
                         s.SafeFileHandle.DangerousGetHandle(),
                         MiniDumpType.MiniDumpWithFullMemory,
                         IntPtr.Zero,
                         IntPtr.Zero,
                         IntPtr.Zero);
                 }
                 else
                 {
                     MINIDUMP_EXCEPTION_INFORMATION mei;
                     mei.ClientPointers = false;
                     mei.ExceptionPointers = ptrs;
                     mei.ThreadId = Kernel32.GetCurrentThreadId();
                     result = DbgHelp.MiniDumpWriteDump(
                         process.Handle,
                         (uint)process.Id,
                         s.SafeFileHandle.DangerousGetHandle(),
                         MiniDumpType.MiniDumpWithFullMemory,
                         ref mei,
                         IntPtr.Zero,
                         IntPtr.Zero);
                 }
                 if (!result)
                 {
                     throw new InvalidOperationException(
                         string.Format("Failed creating memory dump '{0}'.", filename),
                         new Win32Exception(Marshal.GetLastWin32Error()));
                 }
             }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/External/Debugging/MemoryDump.cs