Aphid Programming Language: Mantispid.EnumBuilder Class Reference
Mantispid.EnumBuilder Class Reference
Public Member Functions
EnumBuilder (string baseTypeName, IEnumerable< string > ruleTypes)
CodeTypeDeclaration CreateEnum ()
Detailed Description
Definition at line 12 of file EnumBuilder.cs.
Constructor & Destructor Documentation
EnumBuilder()
Mantispid.EnumBuilder.EnumBuilder (string baseTypeName, IEnumerable< string > ruleTypes)
Definition at line 18 of file EnumBuilder.cs.
         {
             _baseTypeName = baseTypeName;
             _ruleTypes = ruleTypes;
         }
Member Function Documentation
CreateEnum()
CodeTypeDeclaration Mantispid.EnumBuilder.CreateEnum ()
Definition at line 29 of file EnumBuilder.cs.
References name, Components.Aphid.Compiler.CodeHelper.TypeRef(), Components.Aphid.Compiler.CodeHelper.Value(), and x.
Referenced by Mantispid.ParserGenerator.Generate().
         {
             var name = GetEnumName();
             var decl = new CodeTypeDeclaration(name) { IsEnum = true };
             decl.CustomAttributes.Add(
                 new CodeAttributeDeclaration(
                     CodeHelper.TypeRef<DataContractAttribute>(),
                     new CodeAttributeArgument("Name", CodeHelper.Value(name))));
             decl.Members.AddRange(
                 _ruleTypes
                 .Select(x => new CodeMemberField(name, x)
                 {
                     CustomAttributes = new CodeAttributeDeclarationCollection(
                         new[]
{
                             new CodeAttributeDeclaration(
                                 CodeHelper.TypeRef<EnumMemberAttribute>())
                         })
                 })
                 .ToArray());
             return decl;
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Compiler/Medusa/Mantispid/EnumBuilder.cs