Aphid Programming Language: AphidUI.ViewModels.AphidReplViewModel Class Reference
AphidUI.ViewModels.AphidReplViewModel Class Reference
Public Member Functions
AphidReplViewModel (CodeViewer outputTextBox)
void SetPreviousCode ()
void SetNextCode ()
void Execute (Action callback=null)
void Stop ()
void ClearCode ()
void ClearConsole ()
void ResetInterpreter ()
void Reset ()
Static Public Member Functions
static void Dump (AphidInterpreter interpreter, AphidObject obj)
Public Attributes
const string NoValue = "Expression has been evaluated and has no value"
Properties
bool IsControlInitialized [get, set]
bool IsExecuting [get, set]
bool IsMultiLine [get, set]
string Code [get, set]
string Output [get, set]
string Status [get, set]
Visibility ExpressionVisibility [get, set]
Visibility StatementsVisibility [get, set]
Visibility RunVisibility [get, set]
Visibility StopVisibility [get, set]
Visibility LineOptionVisibility [get, set]
CodeViewer CodeViewer [get]
AphidInterpreter Interpreter [get]
ObservableCollection< VariableViewModel > Variables [get]
ObservableCollection< ExpressionViewModel > Expressions [get]
Additional Inherited Members
Protected Member Functions inherited from AphidUI.ViewModels.ViewModel
void InvokePropertyChanged ([CallerMemberName] string callerName=null)
void SetProperty< T > (ref T property, T value, [CallerMemberName] string callerName=null)
Events inherited from AphidUI.ViewModels.ViewModel
PropertyChangedEventHandler PropertyChanged
Detailed Description
Definition at line 4 of file ViewModels.g.cs.
Constructor & Destructor Documentation
AphidReplViewModel()
AphidUI.ViewModels.AphidReplViewModel.AphidReplViewModel (CodeViewer outputTextBox)
Definition at line 77 of file WindowViewModel.cs.
References AphidUI.CodeViewer.Clear(), and x.
         {
             _configProperties = new Lazy<string[]>(() => GetType()
                 .GetMembers()
                 .Where(x => x.GetCustomAttributes(typeof(SettingAttribute), true).Any())
                 .Select(x => x.Name)
                 .ToArray());
             //var type = new DynamicDataClassExtractor<AphidReplViewModel, SettingAttribute>().InstantiatePopulated(this, "AphidUIConfig");
             //using (var s = new MemoryStream())
             //{
             //    var serializer = new XmlSerializer(type.GetType());
             //    serializer.Serialize(s, type);
             //    s.Position = 0;
             //    var type2= serializer.Deserialize(s);
             //}
             Code = "";
             Status = "Ready";
             IsMultiLine = false;
             IsExecuting = false;
             LineOptionVisibility = Visibility.Visible;
             _codeViewer = outputTextBox;
             _codeViewer.Document.Blocks.Clear();
             _expressions.CollectionChanged += Expressions_CollectionChanged;
             InitInterpreter();
             PropertyChanged += AphidReplViewModel_PropertyChanged;
         }
Member Function Documentation
ClearCode()
void AphidUI.ViewModels.AphidReplViewModel.ClearCode ()
Definition at line 599 of file WindowViewModel.cs.
         {
             Code = "";
         }
ClearConsole()
void AphidUI.ViewModels.AphidReplViewModel.ClearConsole ()
Definition at line 604 of file WindowViewModel.cs.
References AphidUI.CodeViewer.Clear().
Referenced by AphidUI.AphidRepl.AphidRepl().
         {
             _codeViewer.Document.Blocks.Clear();
         }
Dump()
static void AphidUI.ViewModels.AphidReplViewModel.Dump (AphidInterpreter interpreter, AphidObject obj) static
Definition at line 273 of file WindowViewModel.cs.
References Components.Aphid.Interpreter.AphidInterpreter.CurrentScope, obj, out, and Components.Aphid.TypeSystem.AphidObject.TryResolve().
         {
             AphidObject vmObj;
             interpreter.CurrentScope.TryResolve(ViewModelName, out vmObj);
             var vm = (AphidReplViewModel)vmObj.Value;
             var serializer = new AphidSerializer(interpreter) { IgnoreFunctions = false };
             vm._codeViewer.Dispatcher.Invoke(() =>
             {
                 if (obj != null)
                 {
                     vm._codeViewer.AppendCode(serializer.Serialize(obj));
                 }
                 else
                 {
                     throw new InvalidOperationException();
                 }
             });
         }
Execute()
void AphidUI.ViewModels.AphidReplViewModel.Execute (Action callback = null)
Definition at line 485 of file WindowViewModel.cs.
Referenced by AphidUI.AphidRepl.AphidRepl(), AphidUI.AphidRepl.InputTextBox_KeyDown(), and AphidUI.AphidRepl.MainWindow_KeyDown().
         {
             IsExecuting = true;
             Status = "Running script...";
             if (_interpreterThread == null)
             {
                 CreateInterpreterThread();
             }
             _callback = callback;
             _interpreterReset.Set();
         }
Reset()
void AphidUI.ViewModels.AphidReplViewModel.Reset ()
Definition at line 615 of file WindowViewModel.cs.
References AphidUI.CodeViewer.Clear().
Referenced by AphidUI.AphidRepl.AphidRepl().
         {
             Code = "";
             _codeViewer.Document.Blocks.Clear();
             _variables.Clear();
         }
ResetInterpreter()
void AphidUI.ViewModels.AphidReplViewModel.ResetInterpreter ()
Definition at line 609 of file WindowViewModel.cs.
         {
             _interpreter = new AphidInterpreter();
             InitInterpreter();
         }
SetNextCode()
void AphidUI.ViewModels.AphidReplViewModel.SetNextCode ()
Definition at line 253 of file WindowViewModel.cs.
Referenced by AphidUI.AphidRepl.InputTextBox_KeyDown().
         {
             Code = GetNextCode();
         }
SetPreviousCode()
void AphidUI.ViewModels.AphidReplViewModel.SetPreviousCode ()
Definition at line 241 of file WindowViewModel.cs.
Referenced by AphidUI.AphidRepl.InputTextBox_KeyDown().
         {
             Code = GetPreviousCode();
         }
Stop()
void AphidUI.ViewModels.AphidReplViewModel.Stop ()
Definition at line 537 of file WindowViewModel.cs.
References AphidUI.CodeViewer.AppendOutput().
Referenced by AphidUI.AphidRepl.AphidRepl().
         {
             if (_interpreterThread != null)
             {
                 try
                 {
                     _interpreterThread.Abort();
                 }
                 catch { }
             }
             InvokeDispatcher(() =>
             {
                 _codeViewer.AppendOutput("Stopped");
                 _codeViewer.ScrollToEnd();
                 Status = "Script stopped";
             });
             IsExecuting = false;
         }
Member Data Documentation
NoValue
const string AphidUI.ViewModels.AphidReplViewModel.NoValue = "Expression has been evaluated and has no value"
Definition at line 21 of file WindowViewModel.cs.
Property Documentation
Code
string AphidUI.ViewModels.AphidReplViewModel.Code get set
Definition at line 57 of file ViewModels.g.cs.
         {
             get
             {
                 return _Code;
             }
             set
             {
                 _Code = value;
                 OnCodeChanged();
                 InvokePropertyChanged("Code");
             }
         }
CodeViewer
CodeViewer AphidUI.ViewModels.AphidReplViewModel.CodeViewer get
Definition at line 30 of file WindowViewModel.cs.
         {
             get { return _codeViewer; }
         }
Expressions
ObservableCollection<ExpressionViewModel> AphidUI.ViewModels.AphidReplViewModel.Expressions get
Definition at line 73 of file WindowViewModel.cs.
         {
             get { return _expressions; }
         }
ExpressionVisibility
Visibility AphidUI.ViewModels.AphidReplViewModel.ExpressionVisibility get set
Definition at line 105 of file ViewModels.g.cs.
         {
             get
             {
                 return _ExpressionVisibility;
             }
             set
             {
                 _ExpressionVisibility = value;
                 OnExpressionVisibilityChanged();
                 InvokePropertyChanged("ExpressionVisibility");
             }
         }
Interpreter
AphidInterpreter AphidUI.ViewModels.AphidReplViewModel.Interpreter get
Definition at line 37 of file WindowViewModel.cs.
         {
             get { return _interpreter; }
         }
IsControlInitialized
bool AphidUI.ViewModels.AphidReplViewModel.IsControlInitialized get set
Definition at line 9 of file ViewModels.g.cs.
Referenced by AphidUI.AphidRepl.AphidRepl().
         {
             get
             {
                 return _IsControlInitialized;
             }
             set
             {
                 _IsControlInitialized = value;
                 OnIsControlInitializedChanged();
                 InvokePropertyChanged("IsControlInitialized");
             }
         }
IsExecuting
bool AphidUI.ViewModels.AphidReplViewModel.IsExecuting get set
Definition at line 25 of file ViewModels.g.cs.
         {
             get
             {
                 return _IsExecuting;
             }
             set
             {
                 _IsExecuting = value;
                 OnIsExecutingChanged();
                 InvokePropertyChanged("IsExecuting");
             }
         }
IsMultiLine
bool AphidUI.ViewModels.AphidReplViewModel.IsMultiLine get set
Definition at line 41 of file ViewModels.g.cs.
         {
             get
             {
                 return _IsMultiLine;
             }
             set
             {
                 _IsMultiLine = value;
                 OnIsMultiLineChanged();
                 InvokePropertyChanged("IsMultiLine");
             }
         }
LineOptionVisibility
Visibility AphidUI.ViewModels.AphidReplViewModel.LineOptionVisibility get set
Definition at line 169 of file ViewModels.g.cs.
         {
             get
             {
                 return _LineOptionVisibility;
             }
             set
             {
                 _LineOptionVisibility = value;
                 OnLineOptionVisibilityChanged();
                 InvokePropertyChanged("LineOptionVisibility");
             }
         }
Output
string AphidUI.ViewModels.AphidReplViewModel.Output get set
Definition at line 73 of file ViewModels.g.cs.
         {
             get
             {
                 return _Output;
             }
             set
             {
                 _Output = value;
                 OnOutputChanged();
                 InvokePropertyChanged("Output");
             }
         }
RunVisibility
Visibility AphidUI.ViewModels.AphidReplViewModel.RunVisibility get set
Definition at line 137 of file ViewModels.g.cs.
         {
             get
             {
                 return _RunVisibility;
             }
             set
             {
                 _RunVisibility = value;
                 OnRunVisibilityChanged();
                 InvokePropertyChanged("RunVisibility");
             }
         }
StatementsVisibility
Visibility AphidUI.ViewModels.AphidReplViewModel.StatementsVisibility get set
Definition at line 121 of file ViewModels.g.cs.
         {
             get
             {
                 return _StatementsVisibility;
             }
             set
             {
                 _StatementsVisibility = value;
                 OnStatementsVisibilityChanged();
                 InvokePropertyChanged("StatementsVisibility");
             }
         }
Status
string AphidUI.ViewModels.AphidReplViewModel.Status get set
Definition at line 89 of file ViewModels.g.cs.
         {
             get
             {
                 return _Status;
             }
             set
             {
                 _Status = value;
                 OnStatusChanged();
                 InvokePropertyChanged("Status");
             }
         }
StopVisibility
Visibility AphidUI.ViewModels.AphidReplViewModel.StopVisibility get set
Definition at line 153 of file ViewModels.g.cs.
         {
             get
             {
                 return _StopVisibility;
             }
             set
             {
                 _StopVisibility = value;
                 OnStopVisibilityChanged();
                 InvokePropertyChanged("StopVisibility");
             }
         }
Variables
ObservableCollection<VariableViewModel> AphidUI.ViewModels.AphidReplViewModel.Variables get
Definition at line 66 of file WindowViewModel.cs.
         {
             get { return _variables; }
         }
The documentation for this class was generated from the following files:
c:/source/Aphid/AphidUI/ViewModels/ViewModels.g.cs
c:/source/Aphid/AphidUI/ViewModels/WindowViewModel.cs