Aphid Programming Language: Components.Aphid.Parser.AphidExpression Class Reference
Components.Aphid.Parser.AphidExpression Class Reference
Public Member Functions
override string ToString ()
AphidExpression WithPositionFrom (AphidExpression expression)
Public Member Functions inherited from Components.Aphid.Parser.AphidNode
bool IsStatement ()
Properties
int Index [get, set]
int Length [get, set]
string Code [get, set]
string Filename [get, set]
bool HasBreakpoint [get, set]
Properties inherited from Components.Aphid.Parser.AphidNode
abstract AphidExpressionType Type [get]
Detailed Description
Definition at line 7 of file AphidExpression.cs.
Member Function Documentation
ToString()
override string Components.Aphid.Parser.AphidExpression.ToString ()
Definition at line 31 of file AphidExpression.cs.
Referenced by Components.Aphid.Compiler.AphidAssemblyBuilder.CreateType(), and Components.Aphid.Interpreter.AphidInterpreter.PushFrame().
         {
             if (Code != null && Index != -1 && Length != -1)
             {
                 return Code.Substring(Index, Length);
             }
             else
             {
                 return base.ToString();
             }
         }
WithPositionFrom()
AphidExpression Components.Aphid.Parser.AphidExpression.WithPositionFrom (AphidExpression expression)
Definition at line 43 of file AphidExpression.cs.
References expression.
Referenced by AphidHdl.ForUnrollMutator.MutateCore().
         {
             Index = expression.Index;
             Length = expression.Length;
             Code = expression.Code;
             return this;
         }
Property Documentation
Code
string Components.Aphid.Parser.AphidExpression.Code get set
Definition at line 25 of file AphidExpression.cs.
Referenced by Components.Aphid.Parser.AphidCodeVisitor.EndVisit().
 { get; set; }
Filename
string Components.Aphid.Parser.AphidExpression.Filename get set
Definition at line 27 of file AphidExpression.cs.
Referenced by Components.Aphid.Parser.AphidCodeVisitor.EndVisit().
 { get; set; }
HasBreakpoint
bool Components.Aphid.Parser.AphidExpression.HasBreakpoint get set
Definition at line 29 of file AphidExpression.cs.
 { get; set; }
Index
int Components.Aphid.Parser.AphidExpression.Index get set
Definition at line 12 of file AphidExpression.cs.
Referenced by Components.Aphid.Parser.AphidCodeVisitor.EndVisit(), and Components.Aphid.UI.AphidScopeObjectAutocompletionSource.GetWords().
         {
             get { return _index; }
             set { _index = value; }
         }
Length
int Components.Aphid.Parser.AphidExpression.Length get set
Definition at line 20 of file AphidExpression.cs.
Referenced by Components.Aphid.Parser.AphidCodeVisitor.EndVisit().
         {
             get { return _length; }
             set { _length = value; }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Parser/AphidExpression.cs