Aphid Programming Language: AphidUI.Internal.CodeCanvas Class Reference
AphidUI.Internal.CodeCanvas Class Reference
Interaction logic for CodeTextBox.xaml
Public Member Functions
CodeCanvas ()
void SetText (string text)
void UpdateSize ()
void UserControl_KeyDown (object sender, KeyEventArgs e)
void UserControl_MouseDown (object sender, MouseButtonEventArgs e)
Protected Member Functions
override void OnRender (DrawingContext drawingContext)
Properties
bool AcceptsReturn [get, set]
string Text [get]
Events
RoutedEventHandler TextChanged
Detailed Description
Interaction logic for CodeTextBox.xaml
Definition at line 26 of file CodeCanvas.xaml.cs.
Constructor & Destructor Documentation
CodeCanvas()
AphidUI.Internal.CodeCanvas.CodeCanvas ()
Definition at line 57 of file CodeCanvas.xaml.cs.
         {
             InitializeComponent();
             AcceptsReturn = false;
             FontFamily = new System.Windows.Media.FontFamily("Lucida console");
             FontSize = 12;
             DependencyPropertyDescriptor
                 .FromProperty(Control.FontSizeProperty, typeof(CodeCanvas))
                 .AddValueChanged(this, FontSizeChanged);
             DependencyPropertyDescriptor
                 .FromProperty(Control.FontFamilyProperty, typeof(CodeCanvas))
                 .AddValueChanged(this, FontFamilyChanged);
             FontSizeChanged(this, new EventArgs());
             FontFamilyChanged(this, new EventArgs());
         }
Member Function Documentation
OnRender()
override void AphidUI.Internal.CodeCanvas.OnRender (DrawingContext drawingContext) protected
Definition at line 588 of file CodeCanvas.xaml.cs.
References IsNullOrEmpty(), lexer, AphidUI.DebugHelper.Trace(), x, and y.
         {
             DebugHelper.Trace();
             if (glyphFace == null)
             {
                 return;
             }
             else if (string.IsNullOrEmpty(_text))
             {
                 _currentColumn = 0;
                 _currentRow = 0;
                 MoveCaretToCurrentCell();
                 SetDefaultSize();
                 CreateDocument(new List<AphidToken>());
                 return;
             }
             var lexer = new AphidLexer(_text);
             CreateDocument(lexer.GetAllTokens());
             double greatestX = 0, greatestY = 0;
             for (int y = 0; y < _document.Count; y++)
             {
                 for (int x = 0; x < _document[y].Count; x++)
                 {
                     var cell = _document[y][x];
                     if (cell.Char == '\n')
                     {
                         continue;
                     }
                     var glyph = BuildGlyphRun(x, y, cell.Char);
                     drawingContext.DrawGlyphRun(
                         new SolidColorBrush(GetColor(cell.Type)),
                         glyph);
                     var x2 = glyph.BaselineOrigin.X + _cellWidth;
                     if (x2 > greatestX)
                     {
                         greatestX = x2;
                     }
                     if (glyph.BaselineOrigin.Y > greatestY)
                     {
                         //greatestY = glyph.BaselineOrigin.Y + 20;
                         greatestY = glyph.BaselineOrigin.Y;
                     }
                 }
             }
             var caretY = Canvas.GetTop(_caret) + _caret.Height;
             if (caretY > greatestY)
             {
                 greatestY = caretY;
             }
             Width = greatestX;
             Height = greatestY;
         }
SetText()
void AphidUI.Internal.CodeCanvas.SetText (string text)
Definition at line 653 of file CodeCanvas.xaml.cs.
References t, text, and AphidUI.DebugHelper.Trace().
         {
             DebugHelper.Trace();
             if (text == null)
             {
                 text = "";
             }
             var t = text
                 .Replace("\r\n", "\n")
                 .Replace('\r', '\n')
                 .Replace("\t", "    ");
             if (t != _text)
             {
                 _text = t;
                 UpdateDocument();
             }
         }
UpdateSize()
void AphidUI.Internal.CodeCanvas.UpdateSize ()
Definition at line 690 of file CodeCanvas.xaml.cs.
References AphidUI.DebugHelper.Trace().
         {
             DebugHelper.Trace();
             Canvas.Width = this.ActualWidth;
             Canvas.Height = this.ActualHeight;
             var viewer = Parent as ScrollViewer;
             if (viewer == null)
             {
                 viewer = (Parent as FrameworkElement).Parent as ScrollViewer;
                 if (viewer == null)
                 {
                     throw new InvalidOperationException();
                 }
             }
             var viewerWidth = viewer.ActualWidth - SystemParameters.VerticalScrollBarWidth - 2;
             if (viewerWidth > Canvas.Width)
             {
                 LineBorder.Width = viewerWidth;
                 Canvas.Width = viewerWidth;
             }
             else
             {
                 LineBorder.Width = Canvas.Width + 4;
             }
             if (viewer.ActualHeight > Canvas.Height)
             {
                 Canvas.Height = viewer.ActualHeight;
             }
             MoveCaretToCurrentCell();
         }
UserControl_KeyDown()
void AphidUI.Internal.CodeCanvas.UserControl_KeyDown (object sender, KeyEventArgs e)
Definition at line 728 of file CodeCanvas.xaml.cs.
References e, and AphidUI.DebugHelper.Trace().
Referenced by AphidUI.CodeTextBox.CodeTextBox().
         {
             DebugHelper.Trace();
             switch (e.Key)
             {
                 case Key.LeftShift:
                 case Key.RightShift:
                 case Key.LeftAlt:
                 case Key.RightAlt:
                 case Key.LeftCtrl:
                 case Key.RightCtrl:
                 case Key.CapsLock:
                 case Key.LWin:
                 case Key.RWin:
                     return;
                 case Key.Up:
                     MoveCaretUp();
                     e.Handled = true;
                     break;
                 case Key.Down:
                     MoveCaretDown();
                     e.Handled = true;
                     break;
                 case Key.Left:
                     MoveCaretLeft();
                     e.Handled = true;
                     break;
                 case Key.Right:
                     MoveCaretRight();
                     e.Handled = true;
                     break;
                 case Key.PageUp:
                     MoveCaretPage(true);
                     e.Handled = true;
                     break;
                 case Key.PageDown:
                     MoveCaretPage(false);
                     e.Handled = true;
                     break;
                 case Key.Home:
                     MoveCaretHome();
                     e.Handled = true;
                     break;
                 case Key.End:
                     if ((Keyboard.Modifiers & ModifierKeys.Control) == ModifierKeys.Control)
                     {
                         _currentRow = _document.Count - 1;
                     }
                     MoveCaretEnd();
                     e.Handled = true;
                     break;
                 case Key.Back:
                     if (_currentColumn == 0)
                     {
                         if (_currentRow == 0)
{
                             return;
                         }
                         _currentRow--;
                         _currentColumn = _document[_currentRow].Count;
                     }
                     var row = _document[_currentRow];
                     var cell = row[_currentColumn - 1];
                     _text = _text.Remove(cell.Index, 1);
                     _currentColumn--;
                     MoveCaretToCurrentCell();
                     UpdateDocument();
                     e.Handled = true;
                     break;
                 case Key.Delete:
                     row = _document[_currentRow];
                     if (_currentColumn < row.Count)
                     {
                         cell = row[_currentColumn];
                         _text = _text.Remove(cell.Index, 1);
                         UpdateDocument();
                     }
                     break;
                 default:
                     if (((Keyboard.Modifiers & ModifierKeys.Control) == ModifierKeys.Control) ||
                         ((Keyboard.Modifiers & ModifierKeys.Alt) == ModifierKeys.Alt))
                     {
                         return;
                     }
                     HandlePrintableKey(e);
                     break;
             }
         }
UserControl_MouseDown()
void AphidUI.Internal.CodeCanvas.UserControl_MouseDown (object sender, MouseButtonEventArgs e)
Definition at line 834 of file CodeCanvas.xaml.cs.
References Count, e, AphidUI.DebugHelper.Trace(), x, and y.
         {
             DebugHelper.Trace();
             var point = e.GetPosition((IInputElement)sender);
             double x = point.X + 4, y = point.Y;
             if (x < 0)
             {
                 x = 0;
             }
             if (y < 0)
             {
                 y = 0;
             }
             _currentColumn = (int)Math.Floor(x / _cellWidth);
             _currentRow = (int)Math.Floor(y / _cellHeight);
             if (_currentRow >= _document.Count)
             {
                 _currentRow = _document.Count - 1;
             }
             if (_currentColumn >= _document[_currentRow].Count)
             {
                 MoveCaretEnd();
             }
             MoveCaretToCurrentCell();
             Keyboard.Focus(Canvas);
             e.Handled = true;
         }
Property Documentation
AcceptsReturn
bool AphidUI.Internal.CodeCanvas.AcceptsReturn get set
Definition at line 33 of file CodeCanvas.xaml.cs.
         {
             get { return _acceptsReturn; }
             set
             {
                 _acceptsReturn = value;
                 LineBorder.Visibility = value ? Visibility.Visible : Visibility.Collapsed;
             }
         }
Text
string AphidUI.Internal.CodeCanvas.Text get
Definition at line 45 of file CodeCanvas.xaml.cs.
         {
             get { return _text; }
         }
Event Documentation
TextChanged
RoutedEventHandler AphidUI.Internal.CodeCanvas.TextChanged
Definition at line 28 of file CodeCanvas.xaml.cs.
Referenced by AphidUI.CodeTextBox.CodeTextBox().
The documentation for this class was generated from the following file:
c:/source/Aphid/AphidUI/Internal/CodeCanvas.xaml.cs