Aphid Programming Language: LLex.TokenTable Class Reference
LLex.TokenTable Class Reference
Public Member Functions
TokenTable ()
void SetMode (int mode)
void Add (TokenEntry entry)
void Add (string[] lexemes, string tokenType)
void AddKeyword (string keyword)
void Add (string lexeme, string tokenType)
void Add (string lexeme, string tokenType, int newMode)
void AddLexemeCode (string lexeme, string code)
void AddCode (string code)
void AddLexemeCode (string lexeme, string code, int newMode)
Properties
string [] Ignore [get, set]
List< string > KeywordTokens [get]
List< string > Keywords [get]
Dictionary< int, List< TokenEntry > > Lists [get]
int Mode [get]
Detailed Description
Definition at line 8 of file TokenTable.cs.
Constructor & Destructor Documentation
TokenTable()
LLex.TokenTable.TokenTable ()
Definition at line 41 of file TokenTable.cs.
References LLex.TokenTable.SetMode().
         {
             SetMode(0);
         }
Member Function Documentation
Add() [1/4]
void LLex.TokenTable.Add (TokenEntry entry)
Definition at line 54 of file TokenTable.cs.
Referenced by LLex.TokenTable.Add(), LLex.TokenTable.AddCode(), and LLex.TokenTable.AddLexemeCode().
         {
             _lists[_mode].Add(entry);
         }
Add() [2/4]
void LLex.TokenTable.Add (string [] lexemes, string tokenType)
Definition at line 59 of file TokenTable.cs.
References LLex.TokenTable.Add(), and lexeme.
         {
             foreach (var lexeme in lexemes)
                 Add(new TokenEntry(lexeme, tokenType));
         }
Add() [3/4]
void LLex.TokenTable.Add (string lexeme, string tokenType)
Definition at line 73 of file TokenTable.cs.
References LLex.TokenTable.Add(), and lexeme.
         {
             Add(new TokenEntry(lexeme, tokenType));
         }
Add() [4/4]
void LLex.TokenTable.Add (string lexeme, string tokenType, int newMode)
Definition at line 78 of file TokenTable.cs.
References LLex.TokenTable.Add(), and lexeme.
         {
             Add(new TokenEntry(lexeme, tokenType) { NewMode = newMode });
         }
AddCode()
void LLex.TokenTable.AddCode (string code)
Definition at line 88 of file TokenTable.cs.
References LLex.TokenTable.Add(), and code.
         {
             Add(new TokenEntry(null, "None", code));
         }
AddKeyword()
void LLex.TokenTable.AddKeyword (string keyword)
Definition at line 65 of file TokenTable.cs.
         {
             var tokenType = keyword + "Keyword";
             _keywordTokens.Add(tokenType);
             _keywords.Add(keyword);
             //Add(keyword, tokenType);
         }
AddLexemeCode() [1/2]
void LLex.TokenTable.AddLexemeCode (string lexeme, string code)
Definition at line 83 of file TokenTable.cs.
References LLex.TokenTable.Add(), code, and lexeme.
         {
             Add(new TokenEntry(lexeme, "None", code));
         }
AddLexemeCode() [2/2]
void LLex.TokenTable.AddLexemeCode (string lexeme, string code, int newMode)
Definition at line 93 of file TokenTable.cs.
References LLex.TokenTable.Add(), code, and lexeme.
         {
             Add(new TokenEntry(lexeme, "None", code) { NewMode = newMode });
         }
SetMode()
void LLex.TokenTable.SetMode (int mode)
Definition at line 46 of file TokenTable.cs.
Referenced by LLex.TokenTable.TokenTable().
         {
             if (!_lists.ContainsKey(mode))
                 _lists.Add(mode, new List<TokenEntry>());
             _mode = mode;
         }
Property Documentation
Ignore
string [] LLex.TokenTable.Ignore get set
Definition at line 10 of file TokenTable.cs.
Referenced by LLex.LexerGenerator.Generate().
 { get; set; }
Keywords
List<string> LLex.TokenTable.Keywords get
Definition at line 22 of file TokenTable.cs.
         {
             get { return _keywords; }
         }
KeywordTokens
List<string> LLex.TokenTable.KeywordTokens get
Definition at line 15 of file TokenTable.cs.
Referenced by LLex.LexerGenerator.EmitState(), and LLex.LexerGenerator.GenerateIsKeyword().
         {
             get { return _keywordTokens; }
         }
Lists
Dictionary<int, List<TokenEntry> > LLex.TokenTable.Lists get
Definition at line 30 of file TokenTable.cs.
Referenced by LLex.LexerGenerator.Generate().
         {
             get { return _lists; }
         }
Mode
int LLex.TokenTable.Mode get
Definition at line 37 of file TokenTable.cs.
         {
             get { return _mode; }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Compiler/Medusa/LLex/TokenTable.cs