Aphid Programming Language: LLex.LexerGenerator Class Reference
LLex.LexerGenerator Class Reference
Public Member Functions
LexerGenerator (TokenTable table)
LexerState GroupTokens (IEnumerable< TokenEntry > tokens)
void GroupTokens (IEnumerable< TokenEntry > tokens, int groupIndex, LexerState state)
string EmitState (LexerState state, bool root, IEnumerable< string > defaults=null)
string GenerateIsKeyword ()
string Generate ()
Properties
bool IgnoreCase [get, set]
Detailed Description
Definition at line 9 of file LexerGenerator.cs.
Constructor & Destructor Documentation
LexerGenerator()
LLex.LexerGenerator.LexerGenerator (TokenTable table)
Definition at line 15 of file LexerGenerator.cs.
         {
             this.table = table;
         }
Member Function Documentation
EmitState()
string LLex.LexerGenerator.EmitState (LexerState state, bool root, IEnumerable< string > defaults = null)
Definition at line 115 of file LexerGenerator.cs.
References Components.Aphid.Properties.Resources.CaseTemplate, LLex.LexerState.Children, LLex.TokenTable.KeywordTokens, root, Components.Aphid.Properties.Resources.RootStateTemplate, Components.Aphid.Properties.Resources.StateTemplate, t, LLex.LexerState.Token, x, and y.
Referenced by LLex.LexerGenerator.Generate().
         {
             if (table.KeywordTokens.Contains(state.Token))
             {
                 //defaults
             }
             string childTemplates;
             if (state.Children.Any())
             {
                 childTemplates = state.Children
                     .Select(x =>
                     {
                         var isCode = !string.IsNullOrEmpty(x.Code);
                         string body = "";
                         if (isCode)
                             body += x.Code;
                         if (x.NewMode != null)
                             body += "mode = " + x.NewMode.ToString() + ";\r\n";
                         if (x.Token != "None")
{
                             body += "return {TokenType}." + x.Token.ToString() + ";\r\n";
                         }
                         else
                             body += "\r\nbreak;\r\n";
                         var t = Components.Aphid.Properties.Resources.CaseTemplate
                             .Replace("{{Cases}}", CreateCases(EncodeChar(x.State)))
                             .Replace("{{Body}}", body)
                             .Replace("{{States}}", x.Children.Any() ? EmitState(x, false) : "");
                         return t;
                     })
                     .Aggregate((x, y) => x + "\r\n" + y);
             }
             else
             {
                 return "";
             }
             if (defaults != null && defaults.Any())
                 childTemplates += "\r\ndefault:\r\n" +
                     defaults.Aggregate((x, y) => x + "\r\n" + y) + "\r\nbreak;\r\n";
             var template = !root ?
                 Components.Aphid.Properties.Resources.StateTemplate :
                 Components.Aphid.Properties.Resources.RootStateTemplate;
             return template.Replace("{{States}}", childTemplates);
         }
Generate()
string LLex.LexerGenerator.Generate ()
Definition at line 196 of file LexerGenerator.cs.
References Components.Aphid.Properties.Resources.AddTokenTemplate, LLex.LexerGenerator.EmitState(), LLex.LexerGenerator.GenerateIsKeyword(), LLex.LexerGenerator.GroupTokens(), LLex.TokenTable.Ignore, Components.Aphid.Properties.Resources.LexicalAnalyzerTemplate, LLex.TokenTable.Lists, root, x, and y.
         {
             var enums = new [] { "None" }
                 .Concat(table.Lists
                     .SelectMany(x => x.Value)
                     .Select(x => x.TokenType)
                     .Concat(new[] { "Unknown", "EndOfFile" })
                     .Concat(table.Lists
                         .SelectMany(y => y.Value)
                         .Where(y => y.Code != null)
                         .SelectMany(y => Regex
                             .Matches(y.Code, @"TokenType\}?\s*.\s*([a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*)")
                             .OfType<Match>()
                             .Select(z => z.Groups[1].Value)))
                     .Distinct()
                     .Where(x => x != "None")
                     .OrderBy(x => x))
                 .Aggregate((x, y) => x + ",\r\n" + y);
             var root = table.Lists
                 .Select(x => @"
                     if (mode == " + x.Key + @")
                     {
                         " + EmitState(GroupTokens(x.Value), true, GetDefaults(x.Value)) + @"
                     }
                     ")
                 .Aggregate((x, y) => x + "else " + y);
             var s = Components.Aphid.Properties.Resources.LexicalAnalyzerTemplate
                 .Replace("{Root}", root)
                 .Replace("{Enums}", enums)
                 .Replace("{IsKeyword}", GenerateIsKeyword())
                 .Replace("{Ignore}", GenerateIgnore());
             if (table.Ignore != null && table.Ignore.Length != 0)
             {
                 s = s.Replace("{Body}", GenerateIgnore());
             }
             return s
                 .Replace("{Body}", Components.Aphid.Properties.Resources.AddTokenTemplate)
                 .Replace("{AllBody}", Components.Aphid.Properties.Resources.AddTokenTemplate)
                 .Replace("PreviousChar();", "charIndex--;");
         }
GenerateIsKeyword()
string LLex.LexerGenerator.GenerateIsKeyword ()
Definition at line 172 of file LexerGenerator.cs.
References LLex.TokenTable.KeywordTokens, x, and y.
Referenced by LLex.LexerGenerator.Generate().
         {
             return table.KeywordTokens.Any() ?
                 table.KeywordTokens
                     .Select(x => "TokenType == {TokenType}." + x)
                     .Aggregate((x, y) => x + "||\r\n" + new string(' ', 16) + y) :
                 "false";
         }
GroupTokens() [1/2]
LexerState LLex.LexerGenerator.GroupTokens (IEnumerable< TokenEntry > tokens)
Definition at line 45 of file LexerGenerator.cs.
References tokens.
Referenced by LLex.LexerGenerator.Generate(), and LLex.LexerGenerator.GroupTokens().
         {
             var state = new LexerState();
             GroupTokens(tokens, 0, state);
             SetNone(state, false);
             return state;
         }
GroupTokens() [2/2]
void LLex.LexerGenerator.GroupTokens (IEnumerable< TokenEntry > tokens, int groupIndex, LexerState state)
Definition at line 56 of file LexerGenerator.cs.
References group, LLex.LexerGenerator.GroupTokens(), tokens, and x.
         {
             var groups = tokens
                 .Where(x => x.Lexeme != null && groupIndex < x.Lexeme.Length)
                 .GroupBy(x => x.Lexeme[groupIndex]);
             foreach (var group in groups)
             {
                 var groupState = new LexerState();
                 groupState.State = group.Key;
                 var returnTokens = group.Where(x => x.Lexeme.Length - 1 == groupIndex).ToArray();
                 if (returnTokens.Length > 1)
                 {
                     Console.WriteLine(
                         "Invalid token declared {0} times: {1}",
                         returnTokens.Length,
                         returnTokens[0].Lexeme);
                 }
                 var returnToken = returnTokens.FirstOrDefault();
                 if (returnToken != null && returnToken.Lexeme != null)
                 {
                     groupState.Token = returnToken.TokenType;
                     groupState.Code = returnToken.Code;
                     groupState.NewMode = returnToken.NewMode;
                 }
                 else
                 {
                     groupState.Token = "Unknown";
                 }
                 state.Children.Add(groupState);
                 GroupTokens(group, groupIndex + 1, groupState);
             }
         }
Property Documentation
IgnoreCase
bool LLex.LexerGenerator.IgnoreCase get set
Definition at line 13 of file LexerGenerator.cs.
Referenced by LLex.AlxFile.From().
 { get; set; }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Compiler/Medusa/LLex/LexerGenerator.cs