Aphid Programming Language: Components.Aphid.Parser.AphidExpressionHelper Class Reference
Components.Aphid.Parser.AphidExpressionHelper Class Reference
Static Public Member Functions
static System.Collections.Generic.IEnumerable< AphidExpression > GetCollection (System.Collections.Generic.IEnumerable< AphidExpression > collection)
Detailed Description
Definition at line 2253 of file AphidParser.g.cs.
Member Function Documentation
GetCollection()
static System.Collections.Generic.IEnumerable<AphidExpression> Components.Aphid.Parser.AphidExpressionHelper.GetCollection (System.Collections.Generic.IEnumerable< AphidExpression > collection) static
Definition at line 2256 of file AphidParser.g.cs.
References collection.
Referenced by Components.Aphid.Parser.ArrayAccessExpression.GetChildren(), Components.Aphid.Parser.CallExpression.GetChildren(), Components.Aphid.Parser.DoWhileExpression.GetChildren(), Components.Aphid.Parser.ForEachExpression.GetChildren(), Components.Aphid.Parser.ForExpression.GetChildren(), Components.Aphid.Parser.FunctionExpression.GetChildren(), Components.Aphid.Parser.IfExpression.GetChildren(), Components.Aphid.Parser.ObjectExpression.GetChildren(), Components.Aphid.Parser.PatternExpression.GetChildren(), Components.Aphid.Parser.PatternMatchingExpression.GetChildren(), Components.Aphid.Parser.UsingExpression.GetChildren(), Components.Aphid.Parser.SwitchCase.GetChildren(), Components.Aphid.Parser.SwitchExpression.GetChildren(), Components.Aphid.Parser.TryExpression.GetChildren(), and Components.Aphid.Parser.WhileExpression.GetChildren().
         {
             if ((collection == null))
             {
                 return new AphidExpression[0];
             }
             else
             {
                 return collection;
             }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Parser/AphidParser.g.cs