Aphid Programming Language: Components.Cypress.ThreadContext Class Reference
Components.Cypress.ThreadContext Class Reference
Static Public Member Functions
static CONTEXT GetContext (IntPtr thread, CONTEXT_FLAGS flags)
static bool SetContext (IntPtr thread, CONTEXT context)
static bool SetEip (IntPtr thread, uint eip)
static bool EnableSingleStep (IntPtr thread, uint eip)
static bool DisableSingleStep (IntPtr thread)
Detailed Description
Definition at line 10 of file ThreadContext.cs.
Member Function Documentation
DisableSingleStep()
static bool Components.Cypress.ThreadContext.DisableSingleStep (IntPtr thread) static
Definition at line 41 of file ThreadContext.cs.
References Components.PInvoke.CONTEXT.EFlags, Components.Cypress.ThreadContext.GetContext(), and Components.Cypress.ThreadContext.SetContext().
Referenced by Components.Cypress.BreakpointManager.HandleException().
         {
             var context = ThreadContext.GetContext(thread, CONTEXT_FLAGS.CONTEXT_CONTROL);
             context.EFlags &= ~0x100u;
             return ThreadContext.SetContext(thread, context);
         }
EnableSingleStep()
static bool Components.Cypress.ThreadContext.EnableSingleStep (IntPtr thread, uint eip) static
Definition at line 32 of file ThreadContext.cs.
References Components.PInvoke.CONTEXT.EFlags, Components.Cypress.ThreadContext.GetContext(), and Components.Cypress.ThreadContext.SetContext().
Referenced by Components.Cypress.BreakpointManager.HandleException().
         {
             var context = ThreadContext.GetContext(thread, CONTEXT_FLAGS.CONTEXT_CONTROL);
             context.EFlags |= 0x100;
             context.Eip = eip;
             return ThreadContext.SetContext(thread, context);
         }
GetContext()
static CONTEXT Components.Cypress.ThreadContext.GetContext (IntPtr thread, CONTEXT_FLAGS flags) static
Definition at line 12 of file ThreadContext.cs.
References flags, and Components.PInvoke.Kernel32.GetThreadContext().
Referenced by Components.Cypress.ThreadContext.DisableSingleStep(), Components.Cypress.ThreadContext.EnableSingleStep(), Components.Cypress.ProcessMemory.ReadArg(), Components.Cypress.ProcessMemory.ReadArgs(), and Components.Cypress.ThreadContext.SetEip().
         {
             CONTEXT context = new CONTEXT() { ContextFlags = flags };
             var result = Kernel32.GetThreadContext(thread, ref context);
             return context;
         }
SetContext()
static bool Components.Cypress.ThreadContext.SetContext (IntPtr thread, CONTEXT context) static
Definition at line 19 of file ThreadContext.cs.
References Components.PInvoke.Kernel32.SetThreadContext().
Referenced by Components.Cypress.ThreadContext.DisableSingleStep(), Components.Cypress.ThreadContext.EnableSingleStep(), and Components.Cypress.ThreadContext.SetEip().
         {
             return Kernel32.SetThreadContext(thread, ref context);
         }
SetEip()
static bool Components.Cypress.ThreadContext.SetEip (IntPtr thread, uint eip) static
Definition at line 24 of file ThreadContext.cs.
References Components.PInvoke.CONTEXT.Eip, Components.Cypress.ThreadContext.GetContext(), and Components.Cypress.ThreadContext.SetContext().
Referenced by Components.Cypress.BreakpointManager.HandleException().
         {
             var context = ThreadContext.GetContext(thread, CONTEXT_FLAGS.CONTEXT_CONTROL);
             context.Eip = eip;
             return ThreadContext.SetContext(thread, context);
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/External/Debugging/ThreadContext.cs