Aphid Programming Language: AphidUI.DebugHelper Class Reference
AphidUI.DebugHelper Class Reference
Static Public Member Functions
static void Trace (string message=null, [CallerFilePathAttribute] string filePath=null, [CallerMemberName] string memberName=null, [CallerLineNumber] int lineNumber=0)
Detailed Description
Definition at line 13 of file DebugHelper.cs.
Member Function Documentation
Trace()
static void AphidUI.DebugHelper.Trace (string message = null, [CallerFilePathAttribute] string filePath = null, [CallerMemberName] string memberName = null, [CallerLineNumber] int lineNumber = 0) static
Definition at line 16 of file DebugHelper.cs.
References Path.
Referenced by AphidUI.Internal.CodeCanvas.OnRender(), AphidUI.Internal.CodeCanvas.SetText(), AphidUI.Internal.CodeCanvas.UpdateSize(), AphidUI.Internal.CodeCanvas.UserControl_KeyDown(), and AphidUI.Internal.CodeCanvas.UserControl_MouseDown().
         {
             if (message == null)
             {
                 var m = string.Format(
                     "[{0}] {1}() in {2} line {3}",
                     DateTime.Now.ToString("hh:mm:ss"),
                     memberName,
                     Path.GetFileName(filePath),
                     lineNumber);
                 System.Diagnostics.Trace.WriteLine(m);
             }
             else
             {
                 throw new NotImplementedException();
             }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/AphidUI/DebugHelper.cs