Aphid Programming Language: Components.Aphid.Parser.ParserErrorMessage Class Reference
Components.Aphid.Parser.ParserErrorMessage Class Reference
Static Public Member Functions
static string Create (string code, AphidParserException exception)
Detailed Description
Definition at line 9 of file ParserErrorMessage.cs.
Member Function Documentation
Create()
static string Components.Aphid.Parser.ParserErrorMessage.Create (string code, AphidParserException exception) static
Definition at line 11 of file ParserErrorMessage.cs.
References code, Components.Aphid.Parser.AphidParserException.ExpectedToken, Components.Aphid.Parser.AphidParserException.Expression, Components.Aphid.Lexer.TokenHelper.GetCodeExcerpt(), Components.Aphid.Lexer.TokenHelper.GetIndexPosition(), Components.Aphid.Lexer.AphidToken.Index, Components.Aphid.Lexer.AphidToken.Lexeme, Components.Aphid.Parser.AphidParserException.Message, sb, Components.Aphid.Lexer.AphidToken.TokenType, and Components.Aphid.Parser.AphidParserException.UnexpectedToken.
Referenced by Components.Aphid.UI.AphidCli.GetErrorMessage().
         {
             if (exception.ExpectedToken == AphidTokenType.None && exception.Expression == null)
             {
                 return exception.Message;
             }
             var sb = new StringBuilder();
             sb.AppendFormat(
                 "Unexpected {0} '{1}'",
                 exception.UnexpectedToken.TokenType.ToString().ToLower(),
                 exception.UnexpectedToken.Lexeme);
             if (exception.ExpectedToken != default(AphidTokenType))
             {
                 sb.AppendFormat(" expected {0}", exception.ExpectedToken);
             }
             if (exception.UnexpectedToken.Index < code.Length)
             {
                 var line = TokenHelper.GetIndexPosition(code, exception.UnexpectedToken.Index);
                 sb.AppendFormat(
                     " on line {0}\r\n\r\n{1}\r\n",
                     line.Item1,
                     TokenHelper.GetCodeExcerpt(code, exception.UnexpectedToken));
             }
             else
             {
                 //sb.AppendFormat("\r\n{0}", exception.);
             }
             return sb.ToString();
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Parser/ParserErrorMessage.cs