Aphid Programming Language: Components.Aphid.TypeSystem.InteropTypeResolver Class Reference
Components.Aphid.TypeSystem.InteropTypeResolver Class Reference
Public Member Functions
InteropTypeResolver (AphidInterpreter interpreter)
Type TryResolveType (string[] imports, string[] path, bool isType=false)
Type ResolveType (string[] imports, string[] path, bool isFatal=true, bool isType=false)
Public Member Functions inherited from Components.Aphid.Interpreter.AphidRuntimeComponent
AphidRuntimeComponent (AphidInterpreter interpreter)
Static Public Member Functions
static Type ResolveType (string name)
static string Unalias (string name)
Additional Inherited Members
Properties inherited from Components.Aphid.Interpreter.AphidRuntimeComponent
AphidInterpreter Interpreter [get]
Detailed Description
Definition at line 11 of file InteropTypeResolver.cs.
Constructor & Destructor Documentation
InteropTypeResolver()
Components.Aphid.TypeSystem.InteropTypeResolver.InteropTypeResolver (AphidInterpreter interpreter)
Definition at line 124 of file InteropTypeResolver.cs.
             : base(interpreter)
         {
         }
Member Function Documentation
ResolveType() [1/2]
Type Components.Aphid.TypeSystem.InteropTypeResolver.ResolveType (string [] imports, string [] path, bool isFatal = true, bool isType = false)
Definition at line 134 of file InteropTypeResolver.cs.
References Type.
Referenced by Components.Aphid.Interpreter.AphidInterpreter.CallStaticInteropFunction().
         {
             lock (_typeCache)
             {
                 return ResolveTypeCore(imports, path, isFatal, isType);
             }
         }
ResolveType() [2/2]
static Type Components.Aphid.TypeSystem.InteropTypeResolver.ResolveType (string name) static
Definition at line 203 of file InteropTypeResolver.cs.
References n, name, t, Type, and Components.Aphid.TypeSystem.InteropTypeResolver.Unalias().
         {
             var n = InteropTypeResolver.Unalias(name);
             foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
             {
                 var t = asm.GetType(n);
                 if (t != null)
                 {
                     return t;
                 }
             }
             return null;
         }
TryResolveType()
Type Components.Aphid.TypeSystem.InteropTypeResolver.TryResolveType (string [] imports, string [] path, bool isType = false)
Definition at line 129 of file InteropTypeResolver.cs.
References Type.
         {
             return ResolveType(imports, path, isFatal: false, isType: isType);
         }
Unalias()
static string Components.Aphid.TypeSystem.InteropTypeResolver.Unalias (string name) static
Definition at line 220 of file InteropTypeResolver.cs.
References name.
Referenced by Components.Aphid.TypeSystem.InteropTypeResolver.ResolveType().
         {
             switch (name)
             {
                 case "string": return "System.String";
                 case "bool": return "System.Boolean";
                 case "byte": return "System.Byte";
                 case "ushort": return "System.UInt16";
                 case "uint": return "System.UInt32";
                 case "ulong": return "System.UInt64";
                 case "sbyte": return "System.Byte";
                 case "short": return "System.Int16";
                 case "int": return "System.Int32";
                 case "long": return "System.Int64";
                 case "float": return "System.Single";
                 case "double": return "System.Double";
                 case "decimal": return "System.Decimal";
                 case "void": return "System.Void";
                 default: return name;
             }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/TypeSystem/ClrInterop/InteropTypeResolver.cs