Aphid Programming Language: Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute > Class Template Reference
Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute > Class Template Reference
Public Member Functions
DynamicDataClassExtractor ()
Type BuildType (string typeName)
object InstantiatePopulated (TType sourceInstance, string typeName)
Detailed Description
Type Constraints
TAttribute : Attribute
Definition at line 15 of file DynamicDataClassExtractor.cs.
Constructor & Destructor Documentation
DynamicDataClassExtractor()
Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute >.DynamicDataClassExtractor ()
Definition at line 20 of file DynamicDataClassExtractor.cs.
         {
             _sourcePropertyTable = new Lazy<Dictionary<string, PropertyInfo>>(
                 () => GetPropertyTable(typeof(TType)));
         }
Member Function Documentation
BuildType()
Type Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute >.BuildType (string typeName)
Definition at line 34 of file DynamicDataClassExtractor.cs.
References Components.Aphid.Compiler.CodeHelper.Assign(), code, Components.Aphid.Compiler.CodeHelper.FieldRef(), Components.Aphid.Compiler.CSharpHelper.GenerateCode(), Name, p, Components.Aphid.Compiler.CodeHelper.Return(), Type, Components.Aphid.Compiler.CodeHelper.TypeRef(), Components.Aphid.Compiler.CodeHelper.VarRef(), and x.
         {
             var nameTable = _sourcePropertyTable.Value;
             var type2 = new CodeTypeDeclaration(typeName)
             {
                 CustomAttributes = new CodeAttributeDeclarationCollection(
                     new[] { new CodeAttributeDeclaration(CodeHelper.TypeRef<SerializableAttribute>()) })
             };
             var fields = nameTable
                 .ToDictionary(
                 x => x.Key,
                 x => new CodeMemberField(x.Value.PropertyType, string.Format("_autoField_{0}", x.Key)));
             var props = nameTable
                     .Select(x => new CodeMemberProperty
                     {
                         Attributes = MemberAttributes.Public,
                         Type = CodeHelper.TypeRef(x.Value.PropertyType),
                         Name = x.Key,
                         HasGet = true,
                         HasSet = true,
                         CustomAttributes = new CodeAttributeDeclarationCollection(
                             new[] { new CodeAttributeDeclaration(CodeHelper.TypeRef<TAttribute>()) })
                     })
                     .ToArray();
             foreach (var p in props)
             {
                 var field = CodeHelper.FieldRef(fields[p.Name].Name);
                 p.GetStatements.Add(CodeHelper.Return(field));
                 p.SetStatements.Add(CodeHelper.Assign(field, CodeHelper.VarRef("value")));
             }
             type2.Members.AddRange(fields.Select(x => x.Value).ToArray());
             type2.Members.AddRange(props);
             var code = CSharpHelper.GenerateCode(type2);
             using (var provider = new CSharpCodeProvider())
             {
                 var options = new CompilerParameters
                 {
                     GenerateExecutable = false,
                     GenerateInMemory = true,
                 };
                 var references = nameTable
                     .Select(x => x.Value.PropertyType.Assembly.Location)
                     .Concat(new[] { typeof(SerializableAttribute), typeof(TAttribute) }
                         .Select(x => x.Assembly.Location))
                     .Distinct()
                     .ToArray();
                 options.ReferencedAssemblies.AddRange(references);
                 var results = provider.CompileAssemblyFromSource(options, code);
                 return results.CompiledAssembly.GetType(typeName);
             }
         }
InstantiatePopulated()
object Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute >.InstantiatePopulated (TType sourceInstance, string typeName)
Definition at line 99 of file DynamicDataClassExtractor.cs.
References p, and t.
         {
             var t = BuildType(typeName);
             var instance = Activator.CreateInstance(t);
             var dstPropTable = GetPropertyTable(t);
             foreach (var p in _sourcePropertyTable.Value)
             {
                 dstPropTable[p.Key].SetValue(instance, p.Value.GetValue(sourceInstance));
             }
             return instance;
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/AphidUI/Components/DynamicDataClassExtractor.cs