Aphid Programming Language: Components.Aphid.Tests.Integration.Shared.ScriptedTests Class Reference
Components.Aphid.Tests.Integration.Shared.ScriptedTests Class Reference
Public Member Functions
void RunTestScript (AphidInterpreter interpreter, string funcName)
Properties
static IEnumerable Tests [get]
Properties inherited from Components.Aphid.Tests.Integration.Shared.AphidTests
virtual bool LoadStd [get]
Additional Inherited Members
Static Public Member Functions inherited from Components.Aphid.Tests.Integration.Shared.AphidTests
static void IsFalse (bool value)
static void IsTrue (bool value)
static void IsFoo (object value)
static void Is9 (object value)
static void IsNull (object value)
static void NotNull (object value)
static void IsFail (Action action)
static void AllFail (params Action[] actions)
static void IsThrow (Action action)
static void AllThrow (params Action[] actions)
static void IsThrow< TException > (Action action)
static void AllThrow< TException > (params Action[] actions)
Protected Member Functions inherited from Components.Aphid.Tests.Integration.Shared.AphidTests
virtual List< AphidExpression > ParseScript (AphidInterpreter interpreter, string script)
AphidInterpreter GetNextInterpreter ()
AphidObject Execute (string script)
void Execute (string script, Action< AphidObject > action)
void Is (string script, Func< AphidObject, bool > predicate)
void Is< TValue > (string script, Func< TValue, bool > predicate)
List< AphidToken > GetTokens (string script)
void AssertTokens (string script, AphidToken[] tokens)
AphidToken Token (AphidTokenType type, string lexeme)
AphidToken Token (AphidTokenType type)
void AssertEquals (object expected, string script)
void AssertFoo (string script)
void Assert9 (string script)
void AssertTrue (string script)
void AssertFalse (string script)
void AssertExpEquals (object expected, string expression)
void AssertExpFoo (string expression)
void AssertExp9 (string expression)
void AssertExpTrue (string expression)
void AssertExpFalse (string expression)
void AssertCollectionIs< TElement > (string script, params TElement[] expected)
Detailed Description
Definition at line 17 of file ScriptedTests.cs.
Member Function Documentation
RunTestScript()
void Components.Aphid.Tests.Integration.Shared.ScriptedTests.RunTestScript (AphidInterpreter interpreter, string funcName)
Definition at line 20 of file ScriptedTests.cs.
References Components.Aphid.Interpreter.AphidInterpreter.CallFunction(), Components.Aphid.Interpreter.AphidInterpreter.CurrentScope, lastException, out, sb, Components.Aphid.Interpreter.AphidInterpreter.TakeOwnership(), and Components.Aphid.TypeSystem.AphidObject.TryResolve().
         {
             interpreter.TakeOwnership();
             var result = interpreter.CallFunction(funcName);
             if (result != null && result.Value != null && result.Value.GetType() == typeof(bool))
             {
                 var sb = new StringBuilder(string.Format("Function {0} returned false.", funcName));
                 AphidObject lastException;
                 if (interpreter.CurrentScope.TryResolve("lastException", out lastException) &&
                     lastException != null)
                 {
                     foreach (var kvp in lastException)
                     {
                         sb.AppendFormat("{0}: {1}\r\n\r\n", kvp.Key, kvp.Value);
                     }
                 }
                 Assert.True(result.GetBool(), sb.ToString());
             }
         }
Property Documentation
Tests
IEnumerable Components.Aphid.Tests.Integration.Shared.ScriptedTests.Tests static get
Definition at line 58 of file ScriptedTests.cs.
         {
             get
             {
                 var aphidDir = new FileInfo(typeof(AphidTests).Assembly.Location).Directory;
                 var testScripts = aphidDir
                     .GetDirectories("ScriptedTests")
                     .Single()
                     .GetFiles("*.alx", SearchOption.AllDirectories)
                     .Where(x =>
                         x.Name.ToLower() != "test.alx" &&
                         x.Name.ToLower() != "testbase.alx" &&
                         x.Name.ToLower() != "aoptest.alx");
                 var testList = new List<TestCaseData>();
                 var asm = System.Reflection.Assembly.GetExecutingAssembly();
                 foreach (var s in testScripts)
                 {
                     var script = File.ReadAllText(s.FullName);
                     var interpreter = new AphidInterpreter();
                     interpreter.Loader.SearchPaths.Add(aphidDir.FullName);
                     interpreter.Loader.SearchPaths.Add(s.Directory.FullName);
                     interpreter.Interpret(_prologueAst);
                     interpreter.Interpret(script);
                     var scope = interpreter.CurrentScope;
                     var tests = scope.Keys
                         .SkipWhile(x => x != "tests")
                         .Skip(1)
                         .Where(x => scope[x].Value != null && scope[x].Value is AphidFunction)
                         .ToArray();
                     foreach (var t in tests)
                     {
                         yield return new TestCaseData(interpreter, t)
                             .SetCategory(Path.GetFileNameWithoutExtension(s.Name))
                             .SetName(FormatTestName(t));
                     }
                 }
             }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid.Tests.Integration/Shared/ScriptedTests.cs