Aphid Programming Language: AphidUI.CodeViewer Class Reference
AphidUI.CodeViewer Class Reference
Interaction logic for CodeViewer.xaml
Public Member Functions
CodeViewer ()
void Clear ()
void AppendCode (Paragraph paragraph, string code)
void AppendCode (string code)
void SetCode (string code)
void AppendOutput (string output)
void AppendOutput (string code, string output, bool isError=false)
void AppendException (string code, string label, Exception e)
void AppendParserException (string code, Exception e)
Static Public Member Functions
static void CodeChanged (DependencyObject sender, DependencyPropertyChangedEventArgs args)
Static Public Attributes
static readonly DependencyProperty CodeProperty
Properties
string Code [get, set]
Detailed Description
Interaction logic for CodeViewer.xaml
Definition at line 22 of file CodeViewer.xaml.cs.
Constructor & Destructor Documentation
CodeViewer()
AphidUI.CodeViewer.CodeViewer ()
Definition at line 33 of file CodeViewer.xaml.cs.
Referenced by AphidUI.CodeViewer.CodeChanged().
         {
             InitializeComponent();
         }
Member Function Documentation
AppendCode() [1/2]
void AphidUI.CodeViewer.AppendCode (Paragraph paragraph, string code)
Definition at line 95 of file CodeViewer.xaml.cs.
References code, Components.Aphid.Lexer.AphidLexer.GetAllTokens(), run, t, and tokens.
Referenced by AphidUI.CodeViewer.AppendCode(), AphidUI.CodeViewer.AppendOutput(), and AphidUI.CodeViewer.SetCode().
         {
             code = code.Replace("\r\n", "\n").Replace("\r", "\n") + " ";
             var tokens = new AphidLexer(code).GetAllTokens();
             foreach (var t in tokens)
             {
                 var run = new Run(t.Lexeme)
                 {
                     Foreground = new SolidColorBrush(GetColor(t.TokenType))
                 };
                 paragraph.Inlines.Add(run);
             }
             Document.Blocks.Add(paragraph);
             ScrollToEnd();
         }
AppendCode() [2/2]
void AphidUI.CodeViewer.AppendCode (string code)
Definition at line 114 of file CodeViewer.xaml.cs.
References AphidUI.CodeViewer.AppendCode(), and code.
         {
             AppendCode(new Paragraph(), code);
         }
AppendException()
void AphidUI.CodeViewer.AppendException (string code, string label, Exception e)
Definition at line 153 of file CodeViewer.xaml.cs.
References AphidUI.CodeViewer.AppendOutput(), code, and e.
Referenced by AphidUI.CodeViewer.AppendParserException().
         {
             AppendOutput(code, string.Format("{0}: {1}", label, e.Message), isError: true);
         }
AppendOutput() [1/2]
void AphidUI.CodeViewer.AppendOutput (string output)
Definition at line 125 of file CodeViewer.xaml.cs.
Referenced by AphidUI.CodeViewer.AppendException(), and AphidUI.ViewModels.AphidReplViewModel.Stop().
         {
             var paragraph = new Paragraph();
             paragraph.Inlines.Add(new Run(output));
             Document.Blocks.Add(paragraph);
         }
AppendOutput() [2/2]
void AphidUI.CodeViewer.AppendOutput (string code, string output, bool isError = false)
Definition at line 134 of file CodeViewer.xaml.cs.
References AphidUI.CodeViewer.AppendCode(), and code.
         {
             var paragraph = new Paragraph();
             AppendCode(paragraph, code);
             paragraph.Inlines.Add(new Run("=> ") { FontWeight = FontWeights.ExtraBlack });
             if (isError)
             {
                 paragraph.Inlines.Add(new Run(output));
             }
             else
             {
                 AppendCode(paragraph, output);
             }
             Document.Blocks.Add(paragraph);
             ScrollToEnd();
         }
AppendParserException()
void AphidUI.CodeViewer.AppendParserException (string code, Exception e)
Definition at line 158 of file CodeViewer.xaml.cs.
References AphidUI.CodeViewer.AppendException(), code, and e.
         {
             AppendException(code, "Parser error", e);
         }
Clear()
void AphidUI.CodeViewer.Clear ()
Definition at line 38 of file CodeViewer.xaml.cs.
Referenced by AphidUI.ViewModels.AphidReplViewModel.AphidReplViewModel(), AphidUI.ViewModels.AphidReplViewModel.ClearConsole(), AphidUI.ViewModels.AphidReplViewModel.Reset(), and AphidUI.CodeViewer.SetCode().
         {
             Document.Blocks.Clear();
         }
CodeChanged()
static void AphidUI.CodeViewer.CodeChanged (DependencyObject sender, DependencyPropertyChangedEventArgs args) static
Definition at line 43 of file CodeViewer.xaml.cs.
References args, and AphidUI.CodeViewer.CodeViewer().
         {
             var viewer = (CodeViewer)sender;
             viewer.SetCode((string)args.NewValue);
         }
SetCode()
void AphidUI.CodeViewer.SetCode (string code)
Definition at line 119 of file CodeViewer.xaml.cs.
References AphidUI.CodeViewer.AppendCode(), AphidUI.CodeViewer.Clear(), and code.
         {
             Clear();
             AppendCode(code);
         }
Member Data Documentation
CodeProperty
readonly DependencyProperty AphidUI.CodeViewer.CodeProperty static
Initial value:
= DependencyProperty.Register(
          "Code", typeof(string), typeof(CodeViewer), new PropertyMetadata(null, CodeChanged))
Definition at line 30 of file CodeViewer.xaml.cs.
Property Documentation
Code
string AphidUI.CodeViewer.Code get set
Definition at line 25 of file CodeViewer.xaml.cs.
         {
             get { return (string)this.GetValue(CodeProperty); }
             set { this.SetValue(CodeProperty, value); }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/AphidUI/CodeViewer.xaml.cs