Aphid Programming Language: Components.Aphid.TypeSystem.TypeExtender Class Reference
Components.Aphid.TypeSystem.TypeExtender Class Reference
Public Member Functions
TypeExtender (AphidInterpreter interpreter)
string GetCtorName (string type)
string GetDynamicName (string type)
string GetName (string type, string nameStr)
string [] FanStaticInteropTypeName (Type type)
string [] FanAphidName (AphidObject obj)
string [] FanInteropName (AphidObject obj)
string GetInteropName (AphidObject obj)
string GetInteropName (Type t)
void Extend (IdentifierExpression type, AphidObject extensions, string ctorHandler, string dynamicHandler)
void Extend (string type, AphidObject extensions, string ctorHandler, string dynamicHandler)
void Extend (string type, string[] attributes, AphidObject extensions, string ctorHandler, string dynamicHandler)
AphidObject TryResolve (AphidObject scope, AphidObject obj, string key, bool isAphidType, bool isCtor, bool isDynamic, bool returnRef)
AphidObject TryResolve (AphidObject scope, Type staticType, string key, bool isAphidType, bool isCtor, bool isDynamic, bool returnRef)
AphidObject TryResolve (AphidObject scope, AphidObject obj, string[] classHierarchy, string key, bool isAphidType, bool isCtor, bool isDynamic, bool isStatic, bool returnRef)
Public Member Functions inherited from Components.Aphid.Interpreter.AphidRuntimeComponent
AphidRuntimeComponent (AphidInterpreter interpreter)
Additional Inherited Members
Properties inherited from Components.Aphid.Interpreter.AphidRuntimeComponent
AphidInterpreter Interpreter [get]
Detailed Description
Definition at line 10 of file TypeExtender.cs.
Constructor & Destructor Documentation
TypeExtender()
Components.Aphid.TypeSystem.TypeExtender.TypeExtender (AphidInterpreter interpreter)
Definition at line 12 of file TypeExtender.cs.
             : base(interpreter)
         {
         }
Member Function Documentation
Extend() [1/3]
void Components.Aphid.TypeSystem.TypeExtender.Extend (IdentifierExpression type, AphidObject extensions, string ctorHandler, string dynamicHandler)
Definition at line 115 of file TypeExtender.cs.
References Components.Aphid.Parser.IdentifierExpression.Attributes, Components.Aphid.Parser.IdentifierExpression.Identifier, and x.
Referenced by Components.Aphid.Library.StandardLibrary.Extend().
         {
             Extend(
                 type.Identifier,
                 type.Attributes.Select(x => x.Identifier).ToArray(),
                 extensions,
                 ctorHandler,
                 dynamicHandler);
         }
Extend() [2/3]
void Components.Aphid.TypeSystem.TypeExtender.Extend (string type, AphidObject extensions, string ctorHandler, string dynamicHandler)
Definition at line 129 of file TypeExtender.cs.
         {
             Extend(type, new string[0], extensions, ctorHandler, dynamicHandler);
         }
Extend() [3/3]
void Components.Aphid.TypeSystem.TypeExtender.Extend (string type, string [] attributes, AphidObject extensions, string ctorHandler, string dynamicHandler)
Definition at line 138 of file TypeExtender.cs.
References keys(), and Components.Aphid.TypeSystem.AphidAlias.Resolve().
         {
             if (AphidAlias.Resolve(type) == null)
             {
                 var interopType = Interpreter.InteropTypeResolver.ResolveType(
                     Interpreter.GetImports().ToArray(),
                     new[] { type },
                     isType: true);
                 if (attributes != null)
                 {
                     if (attributes.Length == 1)
                     {
                         if (attributes[0] == AphidType.List)
{
                             interopType = typeof(List<>).MakeGenericType(interopType);
                         }
                         else
{
                             throw GetInteropTypeException(attributes, type);
                         }
                     }
                     else if (attributes.Length != 0)
                     {
                         throw GetInteropTypeException(attributes, type);
                     }
                 }
                 type = GetInteropName(interopType);
             }
             foreach (var extension in extensions)
             {
                 var nameStr = extension.Key;
                 var keys = new List<string> { GetName(type, nameStr) };
                 if (nameStr == dynamicHandler)
                 {
                     keys.Add(GetDynamicName(type));
                 }
                 if (nameStr == ctorHandler)
                 {
                     keys.Add(GetCtorName(type));
                 }
                 foreach (var key in keys)
                 {
                     if (Interpreter.CurrentScope.ContainsKey(key))
                     {
                         Interpreter.CurrentScope[key] = extension.Value;
                     }
                     else
                     {
                         Interpreter.CurrentScope.Add(key, extension.Value);
                     }
                 }
             }
         }
FanAphidName()
string [] Components.Aphid.TypeSystem.TypeExtender.FanAphidName (AphidObject obj)
Definition at line 47 of file TypeExtender.cs.
References obj.
         {
             return FanInteropNameCore(obj, includeAphidType: true);
         }
FanInteropName()
string [] Components.Aphid.TypeSystem.TypeExtender.FanInteropName (AphidObject obj)
Definition at line 52 of file TypeExtender.cs.
References obj.
         {
             return FanInteropNameCore(obj, includeAphidType: false);
         }
FanStaticInteropTypeName()
string [] Components.Aphid.TypeSystem.TypeExtender.FanStaticInteropTypeName (Type type)
Definition at line 34 of file TypeExtender.cs.
         {
             var names = new List<string>();
             while (type != null)
             {
                 names.Add(GetInteropName(type));
                 type = type.BaseType;
             }
             return names.ToArray();
         }
GetCtorName()
string Components.Aphid.TypeSystem.TypeExtender.GetCtorName (string type)
Definition at line 17 of file TypeExtender.cs.
         {
             return GetName(type, "$ctor");
         }
GetDynamicName()
string Components.Aphid.TypeSystem.TypeExtender.GetDynamicName (string type)
Definition at line 22 of file TypeExtender.cs.
         {
             return GetName(type, null);
         }
GetInteropName() [1/2]
string Components.Aphid.TypeSystem.TypeExtender.GetInteropName (AphidObject obj)
Definition at line 76 of file TypeExtender.cs.
References obj.
         {
             return GetInteropName(obj.Value.GetType());
         }
GetInteropName() [2/2]
string Components.Aphid.TypeSystem.TypeExtender.GetInteropName (Type t)
Definition at line 81 of file TypeExtender.cs.
References n, p, Components.Aphid.TypeSystem.AphidAlias.Resolve(), sb, and t.
         {
             var n = AphidAlias.Resolve(t) ?? t.FullName;
             if (!t.IsGenericType)
             {
                 return n;
             }
             else
             {
                 var isFirstTypeArg = true;
                 var sb = new StringBuilder(n);
                 sb.Append('<');
                 foreach (var p in t.GetGenericArguments())
                 {
                     if (isFirstTypeArg)
                     {
                         isFirstTypeArg = false;
                     }
                     else
                     {
                         sb.Append(',');
                     }
                     sb.Append(p.FullName);
                 }
                 sb.Append('>');
                 return sb.ToString();
             }
         }
GetName()
string Components.Aphid.TypeSystem.TypeExtender.GetName (string type, string nameStr)
Definition at line 27 of file TypeExtender.cs.
         {
             return nameStr != null ?
                 string.Format("$ext.{0}.{1}", type, nameStr) :
                 string.Format("$ext.{0}", type);
         }
TryResolve() [1/3]
AphidObject Components.Aphid.TypeSystem.TypeExtender.TryResolve (AphidObject scope, AphidObject obj, string key, bool isAphidType, bool isCtor, bool isDynamic, bool returnRef)
Definition at line 211 of file TypeExtender.cs.
References obj, and scope.
         {
             return TryResolve(
                 scope,
                 obj,
                 isAphidType ? FanAphidName(obj) : FanInteropName(obj),
                 key,
                 isAphidType,
                 isCtor,
                 isDynamic,
                 isStatic: false,
                 returnRef: returnRef);
         }
TryResolve() [2/3]
AphidObject Components.Aphid.TypeSystem.TypeExtender.TryResolve (AphidObject scope, Type staticType, string key, bool isAphidType, bool isCtor, bool isDynamic, bool returnRef)
Definition at line 232 of file TypeExtender.cs.
References scope.
         {
             return TryResolve(
                 scope,
                 null,
                 FanStaticInteropTypeName(staticType),
                 key,
                 isAphidType,
                 isCtor,
                 isDynamic,
                 isStatic: true,
                 returnRef: returnRef);
         }
TryResolve() [3/3]
AphidObject Components.Aphid.TypeSystem.TypeExtender.TryResolve (AphidObject scope, AphidObject obj, string [] classHierarchy, string key, bool isAphidType, bool isCtor, bool isDynamic, bool isStatic, bool returnRef)
Definition at line 253 of file TypeExtender.cs.
References func, Name, obj, out, scope, selector, skip, and x.
         {
             AphidObject val = null;
             var selector =
                 isDynamic ? (Func<string, string>)(x => GetDynamicName(x)) :
                 isCtor ? (Func<string, string>)(x => GetCtorName(x)) :
                 (Func<string, string>)(x => GetName(x, key));
             if (classHierarchy
                 .Select(selector)
                 .FirstOrDefault(x => scope.TryResolve(x, out val)) == null)
             {
                 return null;
             }
             AphidObject result;
             var func = val.Value as AphidFunction;
             if (func != null)
             {
                 var function = func.Clone();
                 //var function = func;
                 var skipOffset = isStatic ? 1 : 0;
                 function.ParentScope = new AphidObject { Parent = scope };
                 if (!isStatic)
                 {
                     function.ParentScope.Add(AphidName.ImplicitArg, obj);
                 }
                 function.ParentScope.Add(AphidName.Extension, new AphidObject(true));
                 function.ParentScope.Add(AphidName.StaticExtension, new AphidObject(isStatic));
                 if (function.Args.Any())
                 {
                     if (!isStatic)
                     {
                         function.ParentScope.Add(function.Args[0], obj);
                     }
                     int skip;
                     if (isDynamic && function.Args.Length >= 2 - skipOffset)
                     {
                         function.ParentScope.Add(
                             function.Args[1 - skipOffset],
                             new AphidObject(key));
                         skip = 2 - skipOffset;
                     }
                     else
                     {
                         skip = 1 - skipOffset;
                     }
                     function.Args = function.Args.Skip(skip).ToArray();
                 }
                 result = new AphidObject(function);
             }
             else
             {
                 result = !returnRef ? val[key] : val;
             }
             return !returnRef ? result : new AphidObject(new AphidRef() { Name = key, Object = result });
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/TypeSystem/TypeExtender.cs