Aphid Programming Language: Components.TypeLoader Class Reference
Components.TypeLoader Class Reference
Public Member Functions
TypeLoader ()
IEnumerable< Assembly > GetAssemblies ()
IEnumerable< Type > GetAllTypes (List< string > imports)
IEnumerable< Type > GetStaticTypes (List< string > imports)
Type ResolveFullType (string fullTypeName)
Assembly [] TryGetAssemblies (string[] namespaces)
IEnumerable< TPlugin > LoadType< TPlugin > ()
void Dispose ()
Static Public Member Functions
static IEnumerable< TPlugin > LoadType< TPlugin > (Assembly asm)
Detailed Description
Definition at line 12 of file TypeLoader.cs.
Constructor & Destructor Documentation
TypeLoader()
Components.TypeLoader.TypeLoader ()
Definition at line 29 of file TypeLoader.cs.
         {
             AppDomain.CurrentDomain.AssemblyLoad += OnAssemblyLoad;
         }
Member Function Documentation
Dispose()
void Components.TypeLoader.Dispose ()
Definition at line 174 of file TypeLoader.cs.
Referenced by Components.Aphid.Tests.Integration.Shared.InteropTestBase.Dispose(), and Components.Aphid.UI.AphidScopeObjectAutocompletionSource.Dispose().
         {
             AppDomain.CurrentDomain.AssemblyLoad -= OnAssemblyLoad;
         }
GetAllTypes()
IEnumerable<Type> Components.TypeLoader.GetAllTypes (List< string > imports)
Definition at line 52 of file TypeLoader.cs.
References Components.External.Memoizer< TArg, TResult >.Call().
         {
             lock (_cacheSync)
             {
                 return _getAllTypesMemoizer.Call(GetAllTypesCore, imports);
             }
         }
GetAssemblies()
IEnumerable<Assembly> Components.TypeLoader.GetAssemblies ()
Definition at line 44 of file TypeLoader.cs.
References Components.RevertibleLazy< T >.Value, and x.
Referenced by Components.TypeLoader.LoadType< TPlugin >().
         {
             lock (_cacheSync)
             {
                 return _assemblies.Value.SelectMany(x => x.Value).Distinct();
             }
         }
GetStaticTypes()
IEnumerable<Type> Components.TypeLoader.GetStaticTypes (List< string > imports)
Definition at line 72 of file TypeLoader.cs.
         {
             lock (_cacheSync)
             {
                 return _getStaticTypesMemoizer.Call(GetStaticTypesCore, imports);
             }
         }
LoadType< TPlugin >() [1/2]
static IEnumerable<TPlugin> Components.TypeLoader.LoadType< TPlugin > (Assembly asm) static
Definition at line 154 of file TypeLoader.cs.
References x.
         {
             return asm
                 .GetTypes()
                 .Where(x => !x.IsAbstract && x.IsDerivedFromOrImplements(typeof(TPlugin)))
                 .Select(Activator.CreateInstance)
                 .Cast<TPlugin>();
         }
LoadType< TPlugin >() [2/2]
IEnumerable<TPlugin> Components.TypeLoader.LoadType< TPlugin > ()
Definition at line 163 of file TypeLoader.cs.
References Components.TypeLoader.GetAssemblies().
         {
             return GetAssemblies().SelectMany(LoadType<TPlugin>);
         }
ResolveFullType()
Type Components.TypeLoader.ResolveFullType (string fullTypeName)
Definition at line 87 of file TypeLoader.cs.
References asms, i, Components.RevertibleLazy< T >.IsValueCreated, Components.RevertibleLazy< T >.Revert(), t, Components.TypeLoader.TryGetAssemblies(), and Type.
         {
             var ns = fullTypeName;
             int i;
             var namespaceList = new List<string>();
             while ((i = ns.LastIndexOf('.')) != -1)
             {
                 ns = ns.Remove(i);
                 namespaceList.Add(ns);
             }
             var namespaces = namespaceList.ToArray();
             Assembly[] asms;
             lock (_cacheSync)
             {
                 var hadAsms = _assemblies.IsValueCreated;
                 if ((asms = TryGetAssemblies(namespaces)) == null && !hadAsms)
                 {
                     throw GetResolveException(fullTypeName);
                 }
                 else
                 {
                     _assemblies.Revert();
                     if ((asms = TryGetAssemblies(namespaces)) == null)
                     {
                         throw GetResolveException(fullTypeName);
                     }
                 }
             }
             Type t;
             for (i = 0; i < asms.Length; i++)
             {
                 if ((t = asms[i].GetType(fullTypeName)) != null)
                 {
                     return t;
                 }
             }
             throw GetResolveException(fullTypeName);
         }
TryGetAssemblies()
Assembly [] Components.TypeLoader.TryGetAssemblies (string [] namespaces)
Definition at line 134 of file TypeLoader.cs.
References asms, i, out, t, and Components.RevertibleLazy< T >.Value.
Referenced by Components.TypeLoader.ResolveFullType().
         {
             lock (_cacheSync)
             {
                 var t = _assemblies.Value;
                 Assembly[] asms;
                 for (var i = 0; i < namespaces.Length; i++)
                 {
                     if (t.TryGetValue(namespaces[i], out asms))
                     {
                         return asms;
                     }
                 }
                 return null;
             }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/External/Common/TypeLoader.cs