Aphid Programming Language: Mantispid.RuleStructResolver Class Reference
Mantispid.RuleStructResolver Class Reference
Public Member Functions
RuleStructResolver (IEnumerable< RuleStruct > ruleTypes)
RuleStruct Resolve (string name)
bool Is (RuleStruct ruleStruct, string name)
bool Is (string ruleStruct, string name)
Public Attributes
IEnumerable< RuleStruct > _ruleTypes
Detailed Description
Definition at line 9 of file RuleStructResolver.cs.
Constructor & Destructor Documentation
RuleStructResolver()
Mantispid.RuleStructResolver.RuleStructResolver (IEnumerable< RuleStruct > ruleTypes)
Definition at line 13 of file RuleStructResolver.cs.
References Mantispid.RuleStructResolver._ruleTypes.
         {
             _ruleTypes = ruleTypes;
         }
Member Function Documentation
Is() [1/2]
bool Mantispid.RuleStructResolver.Is (RuleStruct ruleStruct, string name)
Definition at line 23 of file RuleStructResolver.cs.
References Mantispid.RuleStruct.BaseName, Mantispid.RuleStruct.Name, name, and Mantispid.RuleStructResolver.Resolve().
Referenced by Mantispid.RuleStructResolver.Is().
         {
             RuleStruct parent;
             return
                 ruleStruct.Name == name || ruleStruct.BaseName == name ? true :
                 ((parent = Resolve(ruleStruct.BaseName)) != null) ? Is(parent, name) :
                 false;
         }
Is() [2/2]
bool Mantispid.RuleStructResolver.Is (string ruleStruct, string name)
Definition at line 33 of file RuleStructResolver.cs.
References Mantispid.RuleStructResolver.Is(), name, and Mantispid.RuleStructResolver.Resolve().
         {
             RuleStruct rule;
             return ruleStruct == name ||
                 ((rule = Resolve(ruleStruct)) != null && Is(rule, name));
         }
Resolve()
RuleStruct Mantispid.RuleStructResolver.Resolve (string name)
Definition at line 18 of file RuleStructResolver.cs.
References Mantispid.RuleStructResolver._ruleTypes, name, and x.
Referenced by Mantispid.RuleStructResolver.Is().
         {
             return _ruleTypes.SingleOrDefault(x => x.Name == name);
         }
Member Data Documentation
_ruleTypes
IEnumerable<RuleStruct> Mantispid.RuleStructResolver._ruleTypes
Definition at line 11 of file RuleStructResolver.cs.
Referenced by Mantispid.RuleStructResolver.Resolve(), and Mantispid.RuleStructResolver.RuleStructResolver().
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Compiler/Medusa/Mantispid/RuleStructResolver.cs