Aphid Programming Language: Components.External.ConsolePlus.Cli Class Reference
Components.External.ConsolePlus.Cli Class Reference
Static Public Member Functions
static void Write (string format, params object[] arg)
Writes a format string to the console.
static void Write (string message)
static void WriteLine (string format, params object[] arg)
Writes a format string and a new line to the console.
static void WriteLine (string message)
static void WriteLine ()
static void DumpTable (IEnumerable< KeyValuePair< string, string >> nameValuePairs)
static IEnumerable< KeyValuePair< string, string > > CreateTable (object obj, bool escapeLines)
static void Dump< T > (T obj, DumpMode mode)
static void Dump< T > (T obj)
static void WriteHeader (string text, string style="")
static void WriteSubheader (string text, string style="")
static string Escape (string value)
static string FormatEscape (string value)
static string FormatEscape (object value)
static string StyleEscape (object value)
static string StyleEscape (string value)
static string EraseStyles (string text)
static void EraseStyles (string text, Func< StringBuilder, StringBuilder > callback)
static void WriteMessage (ConsoleColor tokenColor, char token, string format, params object[] arg)
static void WriteInfoMessage (string format, params object[] arg)
static void WriteQueryMessage (string format, params object[] arg)
static void WriteSuccessMessage (string format, params object[] arg)
static void WriteErrorMessage (string format, params object[] arg)
static void WriteCriticalErrorMessage (string format, params object[] arg)
static void WriteLine (string format, object arg0)
static void WriteLine (string format, object arg0, object arg1)
static void WriteLine (string format, object arg0, object arg1, object arg2)
static void WriteLine (string format, object arg0, object arg1, object arg2, object arg3)
static void WriteLine (string format, object arg0, object arg1, object arg2, object arg3, object arg4)
static void WriteLine (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5)
static void WriteLine (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6)
static void WriteLine (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7)
static void Write (string format, object arg0)
static void Write (string format, object arg0, object arg1)
static void Write (string format, object arg0, object arg1, object arg2)
static void Write (string format, object arg0, object arg1, object arg2, object arg3)
static void Write (string format, object arg0, object arg1, object arg2, object arg3, object arg4)
static void Write (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5)
static void Write (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6)
static void Write (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7)
static void WriteInfoMessage (string format, object arg0)
static void WriteInfoMessage (string format, object arg0, object arg1)
static void WriteInfoMessage (string format, object arg0, object arg1, object arg2)
static void WriteInfoMessage (string format, object arg0, object arg1, object arg2, object arg3)
static void WriteInfoMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4)
static void WriteInfoMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5)
static void WriteInfoMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6)
static void WriteInfoMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7)
static void WriteQueryMessage (string format, object arg0)
static void WriteQueryMessage (string format, object arg0, object arg1)
static void WriteQueryMessage (string format, object arg0, object arg1, object arg2)
static void WriteQueryMessage (string format, object arg0, object arg1, object arg2, object arg3)
static void WriteQueryMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4)
static void WriteQueryMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5)
static void WriteQueryMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6)
static void WriteQueryMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7)
static void WriteSuccessMessage (string format, object arg0)
static void WriteSuccessMessage (string format, object arg0, object arg1)
static void WriteSuccessMessage (string format, object arg0, object arg1, object arg2)
static void WriteSuccessMessage (string format, object arg0, object arg1, object arg2, object arg3)
static void WriteSuccessMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4)
static void WriteSuccessMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5)
static void WriteSuccessMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6)
static void WriteSuccessMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7)
static void WriteErrorMessage (string format, object arg0)
static void WriteErrorMessage (string format, object arg0, object arg1)
static void WriteErrorMessage (string format, object arg0, object arg1, object arg2)
static void WriteErrorMessage (string format, object arg0, object arg1, object arg2, object arg3)
static void WriteErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4)
static void WriteErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5)
static void WriteErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6)
static void WriteErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7)
static void WriteCriticalErrorMessage (string format, object arg0)
static void WriteCriticalErrorMessage (string format, object arg0, object arg1)
static void WriteCriticalErrorMessage (string format, object arg0, object arg1, object arg2)
static void WriteCriticalErrorMessage (string format, object arg0, object arg1, object arg2, object arg3)
static void WriteCriticalErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4)
static void WriteCriticalErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5)
static void WriteCriticalErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6)
static void WriteCriticalErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7)
static void WriteInfoMessage (string message)
static void WriteQueryMessage (string message)
static void WriteSuccessMessage (string message)
static void WriteErrorMessage (string message)
static void WriteCriticalErrorMessage (string message)
Public Attributes
const int MessageCountStart = 0x10
const char QueryChar = '?'
Properties
static bool UseTrace [get, set]
static bool Async [get, set]
static int BufferWidth [get]
static int BufferHeight [get]
static Action< string > WriteHandler [get, set]
static Action< string > WriteLineHandler [get, set]
Detailed Description
Definition at line 14 of file Cli.cs.
Member Function Documentation
CreateTable()
static IEnumerable<KeyValuePair<string, string> > Components.External.ConsolePlus.Cli.CreateTable (object obj, bool escapeLines) static
Definition at line 292 of file Cli.cs.
References e, obj, Replace(), t, ToString(), and x.
         {
             Func<PropertyInfo, string> tryGet = x =>
             {
                 try
                 {
 #if NET35
                     return (x.GetValue(obj, null) ?? "null").ToString();
 #else
                     return (x.GetValue(obj) ?? "null").ToString();
 #endif
                 }
                 catch (Exception e)
                 {
                     return string.Format("Error getting value: {0}", e);
                 }
             };
             var t = obj.GetType();
             return t
                 .GetProperties()
                 .Select(x => new KeyValuePair<string, string>(
                     x.Name,
                     escapeLines ?
                         tryGet(x).Replace("\r", "\\r").Replace("\n", "\\n") :
                         tryGet(x)
                 ));
         }
Dump< T >() [1/2]
static void Components.External.ConsolePlus.Cli.Dump< T > (T obj, DumpMode mode) static
Definition at line 320 of file Cli.cs.
References obj.
         {
             var nvps = CreateTable(obj, mode == DumpMode.Table);
             if (mode == DumpMode.Table)
             {
                 DumpTable(nvps);
             }
             else if (mode == DumpMode.Details)
             {
                 DumpDetails(nvps);
             }
             else
             {
                 throw new ArgumentException("Invalid mode.");
             }
         }
Dump< T >() [2/2]
static void Components.External.ConsolePlus.Cli.Dump< T > (T obj) static
Definition at line 338 of file Cli.cs.
References obj.
         {
             Dump(obj, DumpMode.Table);
         }
DumpTable()
static void Components.External.ConsolePlus.Cli.DumpTable (IEnumerable< KeyValuePair< string, string >> nameValuePairs) static
Definition at line 197 of file Cli.cs.
References header, name, string, value, WriteLine, x, and y.
         {
             if (nameValuePairs.Count() == 0)
             {
                 return;
             }
             const int paddingSize = 0;
             var longestNameLength = nameValuePairs.OrderByDescending(x => x.Key.Length).First().Key.Length;
             if (longestNameLength < nameHeader.Length)
             {
                 longestNameLength = nameHeader.Length;
             }
             else if (longestNameLength > maxNameLength)
             {
                 longestNameLength = maxNameLength;
             }
             var longestValueLength = nameValuePairs.OrderByDescending(x => x.Value.Length).First().Value.Length;
             if (longestValueLength < valueHeader.Length)
             {
                 longestValueLength = valueHeader.Length;
             }
             else if (longestValueLength > maxValueLength)
             {
                 longestValueLength = maxValueLength;
                 if (longestNameLength < maxNameLength)
                 {
                     longestValueLength += maxNameLength - longestNameLength;
                 }
             }
             var padding = new string(' ', paddingSize);
             var headerColor = "~White~~|DarkGray~";
             var totalLength = paddingSize * 4 + 3 + longestNameLength + longestValueLength;
             //var newLine = totalLength == BufferWidth ? "" : "\r\n";
             var newLine = "\r\n";
             Func<string, string, bool, string> createRow = (name, value, header) =>
             {
                 if (name.Length > maxNameLength)
                 {
                     name = name.Remove(maxNameLength - 3) + "~Yellow~...~R~";
                 }
                 if (value.Length > longestValueLength)
                 {
                     value = value.Remove(longestValueLength - 3) + "~Yellow~...~R~";
                 }
                 var delim = "" + (header ? headerColor : "") + padding;
                 var reset = (header ? "~R~" : "");
                 return delim + name.PadRight(longestNameLength + paddingSize) + reset +
                     delim + value.PadRight(longestValueLength + paddingSize) + reset + "";
             };
             var divider = new string('', totalLength - 2).ToCharArray();
             var verticalRuleOffset = longestNameLength + paddingSize * 2;
             divider[verticalRuleOffset] = '';
             var hrTop = "" + new string(divider) + "";
             divider[verticalRuleOffset] = '';
             var hrMiddle = "" + new string(divider) + "";
             divider[verticalRuleOffset] = '';
             var hrBottom = "" + new string(divider) + "";
             var rows = nameValuePairs
                 .Select(x => createRow(x.Key, x.Value, false))
                 .Aggregate((x, y) => x + newLine + y);
             WriteLine(hrTop + newLine +
                 createRow(nameHeader, valueHeader, true) + newLine +
                 hrMiddle + newLine +
                 rows + newLine +
                 hrBottom);
         }
EraseStyles() [1/2]
static string Components.External.ConsolePlus.Cli.EraseStyles (string text) static
Definition at line 642 of file Cli.cs.
References aggr, and text.
         {
             var aggr = new StringBuilder();
             EraseStyles(text, aggr.Append);
             return aggr.ToString();
         }
EraseStyles() [2/2]
static void Components.External.ConsolePlus.Cli.EraseStyles (string text, Func< StringBuilder, StringBuilder > callback) static
Definition at line 653 of file Cli.cs.
References buffer, c, i, and text.
         {
             {
                 var buffer = new StringBuilder();
                 var state = CliLexerState.ReadingText;
                 for (int i = 0; i < text.Length; i++)
                 {
                     var c = text[i];
                     switch (state)
                     {
                         case CliLexerState.ReadingText:
                             if (c == '~')
{
                                 state = CliLexerState.ReadingTokenBeginning;
                                 if (buffer.Length != 0)
{
                                     callback(buffer);
                                     buffer = new StringBuilder();
                                 }
                             }
                             else
{
                                 buffer.Append(c);
                             }
                             break;
                         case CliLexerState.ReadingTokenBeginning:
                             if (c == '~')
{
                                 buffer.Append('~');
                                 state = CliLexerState.ReadingText;
                             }
                             else
{
                                 state = CliLexerState.ReadingToken;
                             }
                             break;
                         case CliLexerState.ReadingToken:
                             if (c == '~')
{
                                 state = CliLexerState.ReadingText;
                             }
                             break;
                         default:
                             throw new NotImplementedException();
                     }
                 }
                 if (state == CliLexerState.ReadingToken)
                 {
                     throw new ArgumentException("Invalid token in format string");
                 }
                 if (buffer.Length != 0)
                 {
                     callback(buffer);
                 }
             }
         }
Escape()
static string Components.External.ConsolePlus.Cli.Escape (string value) static
Definition at line 609 of file Cli.cs.
References value.
Referenced by Components.External.ConsolePlus.Cli.WriteSubheader(), and Components.Aphid.UI.AphidCli.WriteSubheader().
         {
             return !string.IsNullOrEmpty(value) ?
                 value
                     .Replace("{", "{{")
                     .Replace("}", "}}")
                     .Replace("~", "~~") :
                 value;
         }
FormatEscape() [1/2]
static string Components.External.ConsolePlus.Cli.FormatEscape (string value) static
Definition at line 619 of file Cli.cs.
References value.
Referenced by Components.Aphid.Interpreter.AphidInterpreter.CreateExpressionException(), and Components.Aphid.Interpreter.AphidInterpreter.CreateValueException().
         {
             return value.Replace("{", "{{").Replace("}", "}}");
         }
FormatEscape() [2/2]
static string Components.External.ConsolePlus.Cli.FormatEscape (object value) static
Definition at line 624 of file Cli.cs.
References value.
         {
             return FormatEscape(value.ToString());
         }
StyleEscape() [1/2]
static string Components.External.ConsolePlus.Cli.StyleEscape (object value) static
Definition at line 629 of file Cli.cs.
References value.
Referenced by Components.Aphid.UI.AphidCli.DumpException(), and Components.Aphid.UI.AphidCli.DumpStackTrace().
         {
             return StyleEscape(value.ToString());
         }
StyleEscape() [2/2]
static string Components.External.ConsolePlus.Cli.StyleEscape (string value) static
Definition at line 634 of file Cli.cs.
References value.
         {
             return !string.IsNullOrEmpty(value) ? value.Replace("~", "~~") : value;
         }
Write() [1/10]
static void Components.External.ConsolePlus.Cli.Write (string format, object arg0) static
Definition at line 57 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, false, arg0);
             }
Write() [2/10]
static void Components.External.ConsolePlus.Cli.Write (string format, object arg0, object arg1) static
Definition at line 63 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, false, arg0, arg1);
             }
Write() [3/10]
static void Components.External.ConsolePlus.Cli.Write (string format, object arg0, object arg1, object arg2) static
Definition at line 69 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, false, arg0, arg1, arg2);
             }
Write() [4/10]
static void Components.External.ConsolePlus.Cli.Write (string format, object arg0, object arg1, object arg2, object arg3) static
Definition at line 75 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, false, arg0, arg1, arg2, arg3);
             }
Write() [5/10]
static void Components.External.ConsolePlus.Cli.Write (string format, object arg0, object arg1, object arg2, object arg3, object arg4) static
Definition at line 81 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, false, arg0, arg1, arg2, arg3, arg4);
             }
Write() [6/10]
static void Components.External.ConsolePlus.Cli.Write (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) static
Definition at line 87 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, false, arg0, arg1, arg2, arg3, arg4, arg5);
             }
Write() [7/10]
static void Components.External.ConsolePlus.Cli.Write (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6) static
Definition at line 93 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, false, arg0, arg1, arg2, arg3, arg4, arg5, arg6);
             }
Write() [8/10]
static void Components.External.ConsolePlus.Cli.Write (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7) static
Definition at line 99 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, false, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
             }
Write() [9/10]
static void Components.External.ConsolePlus.Cli.Write (string format, params object [] arg) static
Writes a format string to the console.
Parameters
format The format string.
arg The arguments.
Definition at line 155 of file Cli.cs.
References format.
Referenced by Components.External.ConsolePlus.InteractiveConsole.DrawPrompt(), Components.External.ConsolePlus.InteractiveConsole.Update(), and Components.External.ConsolePlus.CliProgressBar.Write().
         {
             WriteCore(format, false, arg);
         }
Write() [10/10]
static void Components.External.ConsolePlus.Cli.Write (string message) static
Definition at line 163 of file Cli.cs.
         {
             WriteCore(message, false, null);
         }
WriteCriticalErrorMessage() [1/10]
static void Components.External.ConsolePlus.Cli.WriteCriticalErrorMessage (string format, object arg0) static
Definition at line 299 of file Cli.g.cs.
References format.
             {
                 WriteCriticalErrorMessage(format, new object[] { arg0 });
             }
WriteCriticalErrorMessage() [2/10]
static void Components.External.ConsolePlus.Cli.WriteCriticalErrorMessage (string format, object arg0, object arg1) static
Definition at line 305 of file Cli.g.cs.
References format.
             {
                 WriteCriticalErrorMessage(format, new object[] { arg0, arg1 });
             }
WriteCriticalErrorMessage() [3/10]
static void Components.External.ConsolePlus.Cli.WriteCriticalErrorMessage (string format, object arg0, object arg1, object arg2) static
Definition at line 311 of file Cli.g.cs.
References format.
             {
                 WriteCriticalErrorMessage(format, new object[] { arg0, arg1, arg2 });
             }
WriteCriticalErrorMessage() [4/10]
static void Components.External.ConsolePlus.Cli.WriteCriticalErrorMessage (string format, object arg0, object arg1, object arg2, object arg3) static
Definition at line 317 of file Cli.g.cs.
References format.
             {
                 WriteCriticalErrorMessage(format, new object[] { arg0, arg1, arg2, arg3 });
             }
WriteCriticalErrorMessage() [5/10]
static void Components.External.ConsolePlus.Cli.WriteCriticalErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4) static
Definition at line 323 of file Cli.g.cs.
References format.
             {
                 WriteCriticalErrorMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4 });
             }
WriteCriticalErrorMessage() [6/10]
static void Components.External.ConsolePlus.Cli.WriteCriticalErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) static
Definition at line 329 of file Cli.g.cs.
References format.
             {
                 WriteCriticalErrorMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5 });
             }
WriteCriticalErrorMessage() [7/10]
static void Components.External.ConsolePlus.Cli.WriteCriticalErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6) static
Definition at line 335 of file Cli.g.cs.
References format.
             {
                 WriteCriticalErrorMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5, arg6 });
             }
WriteCriticalErrorMessage() [8/10]
static void Components.External.ConsolePlus.Cli.WriteCriticalErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7) static
Definition at line 341 of file Cli.g.cs.
References format.
             {
                 WriteCriticalErrorMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 });
             }
WriteCriticalErrorMessage() [9/10]
static void Components.External.ConsolePlus.Cli.WriteCriticalErrorMessage (string message) static
Definition at line 373 of file Cli.g.cs.
             {
                 WriteCriticalErrorMessage(message.Replace("{", "{{").Replace("}", "}}"), new object[0]);
             }
WriteCriticalErrorMessage() [10/10]
static void Components.External.ConsolePlus.Cli.WriteCriticalErrorMessage (string format, params object [] arg) static
Definition at line 767 of file Cli.cs.
References format.
Referenced by Components.Aphid.Debugging.AphidMemoryDump.Create(), and Components.Aphid.UI.AphidRepl.Run().
         {
             WriteMessage(
                 ConsoleColor.Red,
                 FatalErrorChar,
                 format,
                 arg);
         }
WriteErrorMessage() [1/10]
static void Components.External.ConsolePlus.Cli.WriteErrorMessage (string format, object arg0) static
Definition at line 251 of file Cli.g.cs.
References format.
             {
                 WriteErrorMessage(format, new object[] { arg0 });
             }
WriteErrorMessage() [2/10]
static void Components.External.ConsolePlus.Cli.WriteErrorMessage (string format, object arg0, object arg1) static
Definition at line 257 of file Cli.g.cs.
References format.
             {
                 WriteErrorMessage(format, new object[] { arg0, arg1 });
             }
WriteErrorMessage() [3/10]
static void Components.External.ConsolePlus.Cli.WriteErrorMessage (string format, object arg0, object arg1, object arg2) static
Definition at line 263 of file Cli.g.cs.
References format.
             {
                 WriteErrorMessage(format, new object[] { arg0, arg1, arg2 });
             }
WriteErrorMessage() [4/10]
static void Components.External.ConsolePlus.Cli.WriteErrorMessage (string format, object arg0, object arg1, object arg2, object arg3) static
Definition at line 269 of file Cli.g.cs.
References format.
             {
                 WriteErrorMessage(format, new object[] { arg0, arg1, arg2, arg3 });
             }
WriteErrorMessage() [5/10]
static void Components.External.ConsolePlus.Cli.WriteErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4) static
Definition at line 275 of file Cli.g.cs.
References format.
             {
                 WriteErrorMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4 });
             }
WriteErrorMessage() [6/10]
static void Components.External.ConsolePlus.Cli.WriteErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) static
Definition at line 281 of file Cli.g.cs.
References format.
             {
                 WriteErrorMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5 });
             }
WriteErrorMessage() [7/10]
static void Components.External.ConsolePlus.Cli.WriteErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6) static
Definition at line 287 of file Cli.g.cs.
References format.
             {
                 WriteErrorMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5, arg6 });
             }
WriteErrorMessage() [8/10]
static void Components.External.ConsolePlus.Cli.WriteErrorMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7) static
Definition at line 293 of file Cli.g.cs.
References format.
             {
                 WriteErrorMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 });
             }
WriteErrorMessage() [9/10]
static void Components.External.ConsolePlus.Cli.WriteErrorMessage (string message) static
Definition at line 367 of file Cli.g.cs.
             {
                 WriteErrorMessage(message.Replace("{", "{{").Replace("}", "}}"), new object[0]);
             }
WriteErrorMessage() [10/10]
static void Components.External.ConsolePlus.Cli.WriteErrorMessage (string format, params object [] arg) static
Definition at line 758 of file Cli.cs.
References format.
         {
             WriteMessage(
                 ConsoleColor.Red,
                 ErrorChar,
                 format,
                 arg);
         }
WriteHeader()
static void Components.External.ConsolePlus.Cli.WriteHeader (string text, string style = "") static
Definition at line 351 of file Cli.cs.
References string, style, and text.
Referenced by Components.External.ConsolePlus.CliApplication< TArgs, TConfig >.Launch().
         {
             var divider = new string('', BufferWidth - 3).ToCharArray();
             var hrTop = "" + new string(divider) + "\r\n";
             var hrMiddle = "" + style + " " + text.PadRight(BufferWidth - 4).Replace("~", "~~") + "~R~\r\n";
             var hrBottom = "" + new string(divider) + "\r\n";
             Write(hrTop + hrMiddle + hrBottom);
         }
WriteInfoMessage() [1/10]
static void Components.External.ConsolePlus.Cli.WriteInfoMessage (string format, object arg0) static
Definition at line 107 of file Cli.g.cs.
References format.
             {
                 WriteInfoMessage(format, new object[] { arg0 });
             }
WriteInfoMessage() [2/10]
static void Components.External.ConsolePlus.Cli.WriteInfoMessage (string format, object arg0, object arg1) static
Definition at line 113 of file Cli.g.cs.
References format.
             {
                 WriteInfoMessage(format, new object[] { arg0, arg1 });
             }
WriteInfoMessage() [3/10]
static void Components.External.ConsolePlus.Cli.WriteInfoMessage (string format, object arg0, object arg1, object arg2) static
Definition at line 119 of file Cli.g.cs.
References format.
             {
                 WriteInfoMessage(format, new object[] { arg0, arg1, arg2 });
             }
WriteInfoMessage() [4/10]
static void Components.External.ConsolePlus.Cli.WriteInfoMessage (string format, object arg0, object arg1, object arg2, object arg3) static
Definition at line 125 of file Cli.g.cs.
References format.
             {
                 WriteInfoMessage(format, new object[] { arg0, arg1, arg2, arg3 });
             }
WriteInfoMessage() [5/10]
static void Components.External.ConsolePlus.Cli.WriteInfoMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4) static
Definition at line 131 of file Cli.g.cs.
References format.
             {
                 WriteInfoMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4 });
             }
WriteInfoMessage() [6/10]
static void Components.External.ConsolePlus.Cli.WriteInfoMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) static
Definition at line 137 of file Cli.g.cs.
References format.
             {
                 WriteInfoMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5 });
             }
WriteInfoMessage() [7/10]
static void Components.External.ConsolePlus.Cli.WriteInfoMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6) static
Definition at line 143 of file Cli.g.cs.
References format.
             {
                 WriteInfoMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5, arg6 });
             }
WriteInfoMessage() [8/10]
static void Components.External.ConsolePlus.Cli.WriteInfoMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7) static
Definition at line 149 of file Cli.g.cs.
References format.
             {
                 WriteInfoMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 });
             }
WriteInfoMessage() [9/10]
static void Components.External.ConsolePlus.Cli.WriteInfoMessage (string message) static
Definition at line 349 of file Cli.g.cs.
             {
                 WriteInfoMessage(message.Replace("{", "{{").Replace("}", "}}"), new object[0]);
             }
WriteInfoMessage() [10/10]
static void Components.External.ConsolePlus.Cli.WriteInfoMessage (string format, params object [] arg) static
Definition at line 731 of file Cli.cs.
References format.
Referenced by Components.Aphid.Library.Net.HttpServer.Start().
         {
             WriteMessage(
                 ConsoleColor.White,
                 InfoChar,
                 format,
                 arg);
         }
WriteLine() [1/11]
static void Components.External.ConsolePlus.Cli.WriteLine (string format, object arg0) static
Definition at line 9 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, true, arg0);
             }
WriteLine() [2/11]
static void Components.External.ConsolePlus.Cli.WriteLine (string format, object arg0, object arg1) static
Definition at line 15 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, true, arg0, arg1);
             }
WriteLine() [3/11]
static void Components.External.ConsolePlus.Cli.WriteLine (string format, object arg0, object arg1, object arg2) static
Definition at line 21 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, true, arg0, arg1, arg2);
             }
WriteLine() [4/11]
static void Components.External.ConsolePlus.Cli.WriteLine (string format, object arg0, object arg1, object arg2, object arg3) static
Definition at line 27 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, true, arg0, arg1, arg2, arg3);
             }
WriteLine() [5/11]
static void Components.External.ConsolePlus.Cli.WriteLine (string format, object arg0, object arg1, object arg2, object arg3, object arg4) static
Definition at line 33 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, true, arg0, arg1, arg2, arg3, arg4);
             }
WriteLine() [6/11]
static void Components.External.ConsolePlus.Cli.WriteLine (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) static
Definition at line 39 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, true, arg0, arg1, arg2, arg3, arg4, arg5);
             }
WriteLine() [7/11]
static void Components.External.ConsolePlus.Cli.WriteLine (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6) static
Definition at line 45 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, true, arg0, arg1, arg2, arg3, arg4, arg5, arg6);
             }
WriteLine() [8/11]
static void Components.External.ConsolePlus.Cli.WriteLine (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7) static
Definition at line 51 of file Cli.g.cs.
References format.
             {
                 WriteCore(format, true, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
             }
WriteLine() [9/11]
static void Components.External.ConsolePlus.Cli.WriteLine (string format, params object [] arg) static
Writes a format string and a new line to the console.
Parameters
format The format string.
arg The arguments.
Definition at line 176 of file Cli.cs.
References format.
Referenced by Components.External.ConsolePlus.CliApplication< TArgs, TConfig >.Launch(), Components.External.ConsolePlus.CliApplication< TArgs, TConfig >.ParseArguments(), Components.External.ConsolePlus.CliApplication< TArgs, TConfig >.Process< TElement >(), Components.External.ConsolePlus.CliArgWriter.WriteArguments< TArgs >(), Components.External.ConsolePlus.CliApplication< TArgs, TConfig >.WriteFatalError(), Components.External.ConsolePlus.CliApplication< TArgs, TConfig >.WriteMessage(), Components.External.ConsolePlus.Cli.WriteMessage(), and Components.External.ConsolePlus.Cli.WriteSubheader().
         {
             WriteCore(format, true, arg);
         }
WriteLine() [10/11]
static void Components.External.ConsolePlus.Cli.WriteLine (string message) static
Definition at line 184 of file Cli.cs.
         {
             WriteCore(message, true, null);
         }
WriteLine() [11/11]
static void Components.External.ConsolePlus.Cli.WriteLine () static
Definition at line 192 of file Cli.cs.
         {
             WriteLineHandler("");
         }
WriteMessage()
static void Components.External.ConsolePlus.Cli.WriteMessage (ConsoleColor tokenColor, char token, string format, params object [] arg) static
Definition at line 724 of file Cli.cs.
References format, token, and Components.External.ConsolePlus.Cli.WriteLine().
         {
             Cli.WriteLine(
                 string.Format(_messageFormat, tokenColor, token, format),
                 arg);
         }
WriteQueryMessage() [1/10]
static void Components.External.ConsolePlus.Cli.WriteQueryMessage (string format, object arg0) static
Definition at line 155 of file Cli.g.cs.
References format.
             {
                 WriteQueryMessage(format, new object[] { arg0 });
             }
WriteQueryMessage() [2/10]
static void Components.External.ConsolePlus.Cli.WriteQueryMessage (string format, object arg0, object arg1) static
Definition at line 161 of file Cli.g.cs.
References format.
             {
                 WriteQueryMessage(format, new object[] { arg0, arg1 });
             }
WriteQueryMessage() [3/10]
static void Components.External.ConsolePlus.Cli.WriteQueryMessage (string format, object arg0, object arg1, object arg2) static
Definition at line 167 of file Cli.g.cs.
References format.
             {
                 WriteQueryMessage(format, new object[] { arg0, arg1, arg2 });
             }
WriteQueryMessage() [4/10]
static void Components.External.ConsolePlus.Cli.WriteQueryMessage (string format, object arg0, object arg1, object arg2, object arg3) static
Definition at line 173 of file Cli.g.cs.
References format.
             {
                 WriteQueryMessage(format, new object[] { arg0, arg1, arg2, arg3 });
             }
WriteQueryMessage() [5/10]
static void Components.External.ConsolePlus.Cli.WriteQueryMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4) static
Definition at line 179 of file Cli.g.cs.
References format.
             {
                 WriteQueryMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4 });
             }
WriteQueryMessage() [6/10]
static void Components.External.ConsolePlus.Cli.WriteQueryMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) static
Definition at line 185 of file Cli.g.cs.
References format.
             {
                 WriteQueryMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5 });
             }
WriteQueryMessage() [7/10]
static void Components.External.ConsolePlus.Cli.WriteQueryMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6) static
Definition at line 191 of file Cli.g.cs.
References format.
             {
                 WriteQueryMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5, arg6 });
             }
WriteQueryMessage() [8/10]
static void Components.External.ConsolePlus.Cli.WriteQueryMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7) static
Definition at line 197 of file Cli.g.cs.
References format.
             {
                 WriteQueryMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 });
             }
WriteQueryMessage() [9/10]
static void Components.External.ConsolePlus.Cli.WriteQueryMessage (string message) static
Definition at line 355 of file Cli.g.cs.
             {
                 WriteQueryMessage(message.Replace("{", "{{").Replace("}", "}}"), new object[0]);
             }
WriteQueryMessage() [10/10]
static void Components.External.ConsolePlus.Cli.WriteQueryMessage (string format, params object [] arg) static
Definition at line 740 of file Cli.cs.
References format.
Referenced by Components.Aphid.Library.Net.HttpServer.Start().
         {
             WriteMessage(
                 ConsoleColor.White,
                 QueryChar,
                 format,
                 arg);
         }
WriteSubheader()
static void Components.External.ConsolePlus.Cli.WriteSubheader (string text, string style = "") static
Definition at line 361 of file Cli.cs.
References Components.External.ConsolePlus.Cli.Escape(), string, style, text, and Components.External.ConsolePlus.Cli.WriteLine().
Referenced by Components.External.ConsolePlus.CliArgWriter.WriteArguments< TArgs >(), and Components.External.ConsolePlus.CliApplication< TArgs, TConfig >.WriteFatalError().
         {
             Cli.WriteLine(
                 "{0}  {1}{2}{3}",
                 style,
                 Cli.Escape(text),
                 new string(' ', BufferWidth - text.Length - 3),
                 "~R~");
         }
WriteSuccessMessage() [1/10]
static void Components.External.ConsolePlus.Cli.WriteSuccessMessage (string format, object arg0) static
Definition at line 203 of file Cli.g.cs.
References format.
             {
                 WriteSuccessMessage(format, new object[] { arg0 });
             }
WriteSuccessMessage() [2/10]
static void Components.External.ConsolePlus.Cli.WriteSuccessMessage (string format, object arg0, object arg1) static
Definition at line 209 of file Cli.g.cs.
References format.
             {
                 WriteSuccessMessage(format, new object[] { arg0, arg1 });
             }
WriteSuccessMessage() [3/10]
static void Components.External.ConsolePlus.Cli.WriteSuccessMessage (string format, object arg0, object arg1, object arg2) static
Definition at line 215 of file Cli.g.cs.
References format.
             {
                 WriteSuccessMessage(format, new object[] { arg0, arg1, arg2 });
             }
WriteSuccessMessage() [4/10]
static void Components.External.ConsolePlus.Cli.WriteSuccessMessage (string format, object arg0, object arg1, object arg2, object arg3) static
Definition at line 221 of file Cli.g.cs.
References format.
             {
                 WriteSuccessMessage(format, new object[] { arg0, arg1, arg2, arg3 });
             }
WriteSuccessMessage() [5/10]
static void Components.External.ConsolePlus.Cli.WriteSuccessMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4) static
Definition at line 227 of file Cli.g.cs.
References format.
             {
                 WriteSuccessMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4 });
             }
WriteSuccessMessage() [6/10]
static void Components.External.ConsolePlus.Cli.WriteSuccessMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) static
Definition at line 233 of file Cli.g.cs.
References format.
             {
                 WriteSuccessMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5 });
             }
WriteSuccessMessage() [7/10]
static void Components.External.ConsolePlus.Cli.WriteSuccessMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6) static
Definition at line 239 of file Cli.g.cs.
References format.
             {
                 WriteSuccessMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5, arg6 });
             }
WriteSuccessMessage() [8/10]
static void Components.External.ConsolePlus.Cli.WriteSuccessMessage (string format, object arg0, object arg1, object arg2, object arg3, object arg4, object arg5, object arg6, object arg7) static
Definition at line 245 of file Cli.g.cs.
References format.
             {
                 WriteSuccessMessage(format, new object[] { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 });
             }
WriteSuccessMessage() [9/10]
static void Components.External.ConsolePlus.Cli.WriteSuccessMessage (string message) static
Definition at line 361 of file Cli.g.cs.
             {
                 WriteSuccessMessage(message.Replace("{", "{{").Replace("}", "}}"), new object[0]);
             }
WriteSuccessMessage() [10/10]
static void Components.External.ConsolePlus.Cli.WriteSuccessMessage (string format, params object [] arg) static
Definition at line 749 of file Cli.cs.
References format.
         {
             WriteMessage(
                 ConsoleColor.Green,
                 SuccessChar,
                 format,
                 arg);
         }
Member Data Documentation
MessageCountStart
const int Components.External.ConsolePlus.Cli.MessageCountStart = 0x10
Definition at line 16 of file Cli.cs.
QueryChar
const char Components.External.ConsolePlus.Cli.QueryChar = '?'
Definition at line 23 of file Cli.cs.
Property Documentation
Async
bool Components.External.ConsolePlus.Cli.Async static get set
Definition at line 77 of file Cli.cs.
 { get; set; }
BufferHeight
int Components.External.ConsolePlus.Cli.BufferHeight static get
Definition at line 99 of file Cli.cs.
         {
             get
             {
                 try
                 {
                     return Console.BufferHeight;
                 }
                 catch
                 {
                     return 40;
                 }
             }
         }
BufferWidth
int Components.External.ConsolePlus.Cli.BufferWidth static get
Definition at line 84 of file Cli.cs.
Referenced by Components.External.ConsolePlus.CliProgressBar.Write(), and Components.Aphid.UI.AphidCli.WriteSubheader().
         {
             get
             {
                 try
                 {
                     return Console.BufferWidth;
                 }
                 catch
                 {
                     return 80;
                 }
             }
         }
UseTrace
bool Components.External.ConsolePlus.Cli.UseTrace static get set
Definition at line 58 of file Cli.cs.
         {
             get { return Cli._useTrace; }
             set
             {
                 Cli._useTrace = value;
                 if (value)
                 {
                     WriteHandler = x => Trace.Write(x);
                     WriteLineHandler = x => Trace.WriteLine(x);
                 }
                 else
                 {
                     WriteHandler = Console.Write;
                     WriteLineHandler = Console.WriteLine;
                 }
             }
         }
WriteHandler
Action<string> Components.External.ConsolePlus.Cli.WriteHandler static get set
Definition at line 113 of file Cli.cs.
 { get; set; }
WriteLineHandler
Action<string> Components.External.ConsolePlus.Cli.WriteLineHandler static get set
Definition at line 115 of file Cli.cs.
 { get; set; }
The documentation for this class was generated from the following files:
c:/source/Aphid/Components.Aphid/External/ConsolePlus/Cli.cs
c:/source/Aphid/Components.Aphid/External/ConsolePlus/Cli.g.cs