Aphid Programming Language: Components.Cypress.BreakpointManager Class Reference
Components.Cypress.BreakpointManager Class Reference
Public Member Functions
BreakpointManager (ProcessMemory memory)
bool SetBreakpoint (IntPtr address)
bool HandleException (DebuggerEventArgs e, Action< IntPtr > breakpointHit)
Properties
Dictionary< IntPtr, byte > BreakpointTable [get]
Dictionary< IntPtr, uint > HitTable [get]
int MaxHits [get, set]
Cache< uint, IntPtr > ThreadCache [get, set]
Detailed Description
Definition at line 13 of file BreakpointManager.cs.
Constructor & Destructor Documentation
BreakpointManager()
Components.Cypress.BreakpointManager.BreakpointManager (ProcessMemory memory)
Definition at line 27 of file BreakpointManager.cs.
References Components.PInvoke.Kernel32.OpenThread(), and x.
         {
             BreakpointTable = new Dictionary<IntPtr, byte>();
             HitTable = new Dictionary<IntPtr, uint>();
             MaxHits = 0x1;
             ThreadCache = new Cache<uint, IntPtr>(x => Kernel32.OpenThread(
                 ThreadAccess.THREAD_GET_CONTEXT | ThreadAccess.THREAD_SET_CONTEXT,
                 false,
                 x));
             mem = memory;
         }
Member Function Documentation
HandleException()
bool Components.Cypress.BreakpointManager.HandleException (DebuggerEventArgs e, Action< IntPtr > breakpointHit)
Definition at line 54 of file BreakpointManager.cs.
References byte, Components.Cypress.ThreadContext.DisableSingleStep(), e, Components.Cypress.ThreadContext.EnableSingleStep(), if(), out, Components.Cypress.ThreadContext.SetEip(), Components.Cypress.ProcessMemory.Write(), and x.
         {
             switch (e.DebugEvent.Exception.ExceptionRecord.ExceptionCode)
             {
                 case ExceptionCode.EXCEPTION_BREAKPOINT:
                     var addr = (IntPtr)e.DebugEvent.Exception.ExceptionRecord.ExceptionAddress;
                     byte originalByte;
                     if (!BreakpointTable.TryGetValue(addr, out originalByte))
                     {
                         return false;
                     }
                     uint hits;
                     lock (HitTable)
                     {
                         hits = ++HitTable[addr];
                         var hits2 = HitTable.OrderByDescending(x => x.Value).ToArray();
                     }
                     var writeResult = mem.Write(addr, new[] { originalByte });
                     if (MaxHits <= 0 || hits < MaxHits)
                     {
                         ThreadContext.EnableSingleStep(ThreadCache[e.DebugEvent.dwThreadId], (uint)addr);
                     }
                     else
                     {
                         ThreadContext.SetEip(ThreadCache[e.DebugEvent.dwThreadId], (uint)addr);
                     }
                     lastBreakpoint = addr;
                     breakpointHit(addr);
                     e.DebugEvent.ContinueHandled();
                     return true;
                 case ExceptionCode.EXCEPTION_SINGLE_STEP:
                     mem.Write(lastBreakpoint, new byte[] { 0xCC });
                     lastBreakpoint = IntPtr.Zero;
                     ThreadContext.DisableSingleStep(ThreadCache[e.DebugEvent.dwThreadId]);
                     e.DebugEvent.ContinueHandled();
                     return true;
                 default:
                     return false;
             }
         }
SetBreakpoint()
bool Components.Cypress.BreakpointManager.SetBreakpoint (IntPtr address)
Definition at line 39 of file BreakpointManager.cs.
References buffer, byte, Components.Cypress.ProcessMemory.ReadBytes(), and Components.Cypress.ProcessMemory.Write().
         {
             if (BreakpointTable.ContainsKey(address))
             {
                 return false;
             }
             var buffer = mem.ReadBytes(address, 0x1);
             BreakpointTable.Add(address, buffer[0]);
             HitTable.Add(address, 0);
             mem.Write(address, new byte[] { 0xCC });
             return true;
         }
Property Documentation
BreakpointTable
Dictionary<IntPtr, byte> Components.Cypress.BreakpointManager.BreakpointTable get
Definition at line 17 of file BreakpointManager.cs.
 { get; private set; }
HitTable
Dictionary<IntPtr, uint> Components.Cypress.BreakpointManager.HitTable get
Definition at line 19 of file BreakpointManager.cs.
 { get; private set; }
MaxHits
int Components.Cypress.BreakpointManager.MaxHits get set
Definition at line 21 of file BreakpointManager.cs.
 { get; set; }
ThreadCache
Cache<uint, IntPtr> Components.Cypress.BreakpointManager.ThreadCache get set
Definition at line 23 of file BreakpointManager.cs.
 { get; set; }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/External/Debugging/BreakpointManager.cs