Aphid Programming Language: Components.Aphid.UI.AphidScopeObjectAutocompletionSource Class Reference
Components.Aphid.UI.AphidScopeObjectAutocompletionSource Class Reference
Public Member Functions
AphidScopeObjectAutocompletionSource (AphidObject currentScope)
IEnumerable< Autocomplete > GetWords (string text, int offset, bool allowEmptySearch, out string searchBuffer)
void Dispose ()
Detailed Description
Definition at line 15 of file AphidScopeObjectAutocompletionSource.cs.
Constructor & Destructor Documentation
AphidScopeObjectAutocompletionSource()
Components.Aphid.UI.AphidScopeObjectAutocompletionSource.AphidScopeObjectAutocompletionSource (AphidObject currentScope)
Definition at line 50 of file AphidScopeObjectAutocompletionSource.cs.
         {
             _currentScope = currentScope;
         }
Member Function Documentation
Dispose()
void Components.Aphid.UI.AphidScopeObjectAutocompletionSource.Dispose ()
Definition at line 456 of file AphidScopeObjectAutocompletionSource.cs.
References Components.TypeLoader.Dispose().
         {
             _loader.Dispose();
         }
GetWords()
IEnumerable<Autocomplete> Components.Aphid.UI.AphidScopeObjectAutocompletionSource.GetWords (string text, int offset, bool allowEmptySearch, out string searchBuffer)
Implements Components.External.ConsolePlus.IAutocompletionSource.
Definition at line 55 of file AphidScopeObjectAutocompletionSource.cs.
References Components.Aphid.Lexer.AphidLexer.GetTokens(), if(), Components.Aphid.Parser.AphidExpression.Index, Components.Aphid.Lexer.AphidToken.Index, Components.Aphid.Lexer.AphidToken.Lexeme, Components.Aphid.Parser.AphidParser.Parse(), text, tokens, Components.Aphid.Lexer.AphidToken.TokenType, and x.
         {
             var subStr = offset == text.Length ? text : text.Remove(offset);
             var tokens = AphidLexer.GetTokens(subStr);
             var lastSkipTokenIndex = tokens.FindLastIndex(x => _skipTokenTypes.Contains(x.TokenType));
             if (lastSkipTokenIndex >= 0)
             {
                 tokens = tokens.Skip(lastSkipTokenIndex + 1).ToList();
             }
             AphidToken lastToken = default(AphidToken);
             var inLastToken =
                 tokens.Count != 0 &&
                 (lastToken = tokens[tokens.Count - 1]).TokenType == AphidTokenType.Identifier &&
                 lastToken.Index + lastToken.Lexeme.Length == offset;
             var isMemberAccess = lastToken.TokenType == AphidTokenType.MemberOperator;
             if (lastToken.TokenType == AphidTokenType.newKeyword)
             {
                 searchBuffer = "";
                 return FilterAndSortWords(CreateTypeAutocomplete(null));
             }
             else if (tokens.Count >= 2 &&
                 tokens[tokens.Count - 2].TokenType == AphidTokenType.newKeyword)
             {
                 searchBuffer = tokens[tokens.Count - 1].Lexeme;
                 return FilterAndSortWords(CreateTypeAutocomplete(searchBuffer));
             }
             AphidExpression exp = null;
             AphidToken[] expTokens = null;
             try
             {
                 var parseTokens = inLastToken ?
                     tokens :
                     tokens.Take(tokens.Count - 1).ToList();
                 if (parseTokens.Count > 0)
                 {
                     exp = AphidParser.Parse(parseTokens, subStr).LastOrDefault();
                     expTokens = tokens.SkipWhile(x => x.Index != exp.Index).ToArray();
                 }
                 else
                 {
                     expTokens = tokens.ToArray();
                 }
             }
             catch { }
             IEnumerable<Autocomplete> words;
             if (expTokens != null)
             {
                 words = ResolveAphidObject(expTokens, inLastToken);
             }
             else
             {
                 words = GetGlobalWords();
             }
             if (inLastToken)
             {
                 words = words.Where(x => x.Text != lastToken.Lexeme && x.Text.StartsWith(lastToken.Lexeme));
                 searchBuffer = lastToken.Lexeme;
             }
             else
             {
                 searchBuffer = "";
                 if (!allowEmptySearch && !isMemberAccess && !isMemberAccess)
                 {
                     return null;
                 }
             }
             return FilterAndSortWords(words);
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/UI/AphidScopeObjectAutocompletionSource.cs