Aphid Programming Language: Components.PInvoke.Kernel32 Class Reference
Components.PInvoke.Kernel32 Class Reference
Public Member Functions
static bool WaitForDebugEvent (ref DEBUG_EVENT lpDebugEvent, int dwMilliseconds)
static bool CreateProcess (string lpApplicationName, string lpCommandLine, IntPtr lpProcessAttributes, IntPtr lpThreadAttributes, bool bInheritHandles, ProcessCreationFlags dwCreationFlags, IntPtr lpEnvironment, string lpCurrentDirectory, STARTUPINFO lpStartupInfo, PROCESS_INFORMATION lpProcessInformation)
static bool ContinueDebugEvent (uint dwProcessId, uint dwThreadId, ContinueStatus dwContinueStatus)
static bool GetThreadContext (IntPtr hThread, [In, Out] ref CONTEXT lpContext)
static bool SetThreadContext (IntPtr hThread, [In] ref CONTEXT lpContext)
static IntPtr OpenThread (ThreadAccess dwDesiredAccess, bool bInheritHandle, uint dwThreadId)
static bool CloseHandle (IntPtr hObject)
static bool ReadProcessMemory (IntPtr hProcess, IntPtr lpBaseAddress, [Out] byte[] lpBuffer, int dwSize, out int lpNumberOfBytesRead)
static bool WriteProcessMemory (IntPtr hProcess, IntPtr lpBaseAddress, byte[] lpBuffer, int nSize, out int lpNumberOfBytesWritten)
static bool DebugActiveProcessStop (uint dwProcessId)
static bool DebugActiveProcess (uint dwProcessId)
static bool DebugSetProcessKillOnExit (bool KillOnExit)
static int VirtualQueryEx (IntPtr hProcess, IntPtr lpAddress, out MEMORY_BASIC_INFORMATION lpBuffer, uint dwLength)
static bool VirtualProtectEx (IntPtr hProcess, IntPtr lpAddress, UIntPtr dwSize, MemoryProtection flNewProtect, out MemoryProtection lpflOldProtect)
static IntPtr VirtualAllocEx (IntPtr hProcess, IntPtr lpAddress, uint dwSize, AllocationType flAllocationType, MemoryProtection flProtect)
static IntPtr VirtualAlloc (UIntPtr lpAddress, UIntPtr dwSize, AllocationType flAllocationType, MemoryProtection flProtect)
static bool TerminateProcess (IntPtr hProcess, uint uExitCode)
static UInt32 WaitForSingleObject (IntPtr hHandle, UInt32 dwMilliseconds)
static bool SetConsoleMode (IntPtr hConsoleHandle, int mode)
static bool GetConsoleMode (IntPtr handle, out int mode)
static IntPtr GetStdHandle (int handle)
static uint GetCurrentThreadId ()
Detailed Description
Definition at line 9 of file Kernel32.cs.
Member Function Documentation
CloseHandle()
static bool Components.PInvoke.Kernel32.CloseHandle (IntPtr hObject)
Referenced by Components.Cypress.ProcessMemory.GetContext(), Components.Cypress.NativeDebugger.ProcessDebugEvents(), and Components.Cypress.NativeDebugger.StartProcess().
ContinueDebugEvent()
static bool Components.PInvoke.Kernel32.ContinueDebugEvent (uint dwProcessId, uint dwThreadId, ContinueStatus dwContinueStatus)
Referenced by Components.PInvoke.DEBUG_EVENT.ContinueDebugEvent().
CreateProcess()
static bool Components.PInvoke.Kernel32.CreateProcess (string lpApplicationName, string lpCommandLine, IntPtr lpProcessAttributes, IntPtr lpThreadAttributes, bool bInheritHandles, ProcessCreationFlags dwCreationFlags, IntPtr lpEnvironment, string lpCurrentDirectory, STARTUPINFO lpStartupInfo, PROCESS_INFORMATION lpProcessInformation)
Referenced by Components.Cypress.NativeDebugger.StartProcess().
DebugActiveProcess()
static bool Components.PInvoke.Kernel32.DebugActiveProcess (uint dwProcessId)
Referenced by Components.Cypress.NativeDebugger.Attach().
DebugActiveProcessStop()
static bool Components.PInvoke.Kernel32.DebugActiveProcessStop (uint dwProcessId)
DebugSetProcessKillOnExit()
static bool Components.PInvoke.Kernel32.DebugSetProcessKillOnExit (bool KillOnExit)
Referenced by Components.Cypress.NativeDebugger.Attach(), and Components.Cypress.NativeDebugger.StartProcess().
GetConsoleMode()
static bool Components.PInvoke.Kernel32.GetConsoleMode (IntPtr handle, out int mode)
Referenced by Components.External.ConsolePlus.VT100.Enable().
GetCurrentThreadId()
static uint Components.PInvoke.Kernel32.GetCurrentThreadId ()
Referenced by Components.Cypress.MemoryDump.Create().
GetStdHandle()
static IntPtr Components.PInvoke.Kernel32.GetStdHandle (int handle)
Referenced by Components.External.ConsolePlus.VT100.Enable().
GetThreadContext()
static bool Components.PInvoke.Kernel32.GetThreadContext (IntPtr hThread, [In, Out] ref CONTEXT lpContext)
Referenced by Components.Cypress.ThreadContext.GetContext(), and Components.Cypress.ProcessMemory.GetContext().
OpenThread()
static IntPtr Components.PInvoke.Kernel32.OpenThread (ThreadAccess dwDesiredAccess, bool bInheritHandle, uint dwThreadId)
Referenced by Components.Cypress.BreakpointManager.BreakpointManager(), and Components.Cypress.ProcessMemory.GetContext().
ReadProcessMemory()
static bool Components.PInvoke.Kernel32.ReadProcessMemory (IntPtr hProcess, IntPtr lpBaseAddress, [Out] byte [] lpBuffer, int dwSize, out int lpNumberOfBytesRead)
Referenced by Components.Cypress.NativeDebugger.ProcessDebugEvents(), and Components.Cypress.ProcessMemory.ReadBytes().
SetConsoleMode()
static bool Components.PInvoke.Kernel32.SetConsoleMode (IntPtr hConsoleHandle, int mode)
Referenced by Components.External.ConsolePlus.VT100.Enable().
SetThreadContext()
static bool Components.PInvoke.Kernel32.SetThreadContext (IntPtr hThread, [In] ref CONTEXT lpContext)
Referenced by Components.Cypress.ThreadContext.SetContext().
TerminateProcess()
static bool Components.PInvoke.Kernel32.TerminateProcess (IntPtr hProcess, uint uExitCode)
VirtualAlloc()
static IntPtr Components.PInvoke.Kernel32.VirtualAlloc (UIntPtr lpAddress, UIntPtr dwSize, AllocationType flAllocationType, MemoryProtection flProtect)
VirtualAllocEx()
static IntPtr Components.PInvoke.Kernel32.VirtualAllocEx (IntPtr hProcess, IntPtr lpAddress, uint dwSize, AllocationType flAllocationType, MemoryProtection flProtect)
Referenced by Components.Cypress.ProcessMemory.Allocate().
VirtualProtectEx()
static bool Components.PInvoke.Kernel32.VirtualProtectEx (IntPtr hProcess, IntPtr lpAddress, UIntPtr dwSize, MemoryProtection flNewProtect, out MemoryProtection lpflOldProtect)
VirtualQueryEx()
static int Components.PInvoke.Kernel32.VirtualQueryEx (IntPtr hProcess, IntPtr lpAddress, out MEMORY_BASIC_INFORMATION lpBuffer, uint dwLength)
Referenced by Components.Cypress.ProcessMemory.ReadMemoryInfo().
WaitForDebugEvent()
static bool Components.PInvoke.Kernel32.WaitForDebugEvent (ref DEBUG_EVENT lpDebugEvent, int dwMilliseconds)
Referenced by Components.Cypress.NativeDebugger.ProcessDebugEvents().
WaitForSingleObject()
static UInt32 Components.PInvoke.Kernel32.WaitForSingleObject (IntPtr hHandle, UInt32 dwMilliseconds)
WriteProcessMemory()
static bool Components.PInvoke.Kernel32.WriteProcessMemory (IntPtr hProcess, IntPtr lpBaseAddress, byte [] lpBuffer, int nSize, out int lpNumberOfBytesWritten)
Referenced by Components.Cypress.ProcessMemory.Write().
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/External/PInvoke/Kernel32.cs