Aphid Programming Language: Components.StringExtension Class Reference
Components.StringExtension Class Reference
Static Public Member Functions
static string Repeat (this string s, int Count)
static string Indent (this string s, string indent="\)
static string SubstringAtIndexOf (this string s, string Value)
static string SubstringAtIndexOf (this string s, string Value, int Offset)
static string SubstringAtIndexOf (this string s, char Value)
static string SubstringAtIndexOf (this string s, char Value, int Offset)
static string SubstringAtLastIndexOf (this string s, string Value)
static string SubstringAtLastIndexOf (this string s, string Value, int Offset)
static string SubstringAtLastIndexOf (this string s, char Value)
static string SubstringAtLastIndexOf (this string s, char Value, int Offset)
static string RemoveAtIndexOf (this string s, string Value)
static string RemoveAtIndexOf (this string s, string Value, int Offset)
static string RemoveAtIndexOf (this string s, char Value)
static string RemoveAtIndexOf (this string s, char Value, int Offset)
static string RemoveAtLastIndexOf (this string s, string Value)
static string RemoveAtLastIndexOf (this string s, string Value, int Offset)
static string RemoveAtLastIndexOf (this string s, char Value)
static string RemoveAtLastIndexOf (this string s, char Value, int Offset)
static string Slice (this string s, int StartIndex, int EndIndex)
static string [] Split (this string s, int Index)
static string [] SplitLines (this string s, StringSplitOptions Options)
static int LeastIndexOf (this string s, params char[] Chars)
static byte [] GetBytes (this string s)
static string [] SplitLines (this string s)
static string Aggregate (this IEnumerable< string > s)
static string Aggregate (this IEnumerable< string > s, string Delimiter)
static string GetSurroundingLines (this string s, int Index, int LinesAbove, int LinesBelow)
static string GetLine (this string s, int Index)
static int GetLineNumber (this string s, int Index)
static int GetLineIndex (this string s, int lineNumber)
static string NormalizeLines (this string s)
static string InsertLineNumbers (this string s, int startLine)
static string InsertLineNumbers (this string s)
static int [] IndexesOf (this string s, string value)
Detailed Description
Definition at line 9 of file StringExtension.cs.
Member Function Documentation
Aggregate() [1/2]
static string Components.StringExtension.Aggregate (this IEnumerable< string > s) static
Definition at line 133 of file StringExtension.cs.
References x, and y.
         {
             return s.Aggregate((x, y) => x + y);
         }
Aggregate() [2/2]
static string Components.StringExtension.Aggregate (this IEnumerable< string > s, string Delimiter) static
Definition at line 138 of file StringExtension.cs.
References x, and y.
         {
             return s.Aggregate((x, y) => x + Delimiter + y);
         }
GetBytes()
static byte [] Components.StringExtension.GetBytes (this string s) static
Definition at line 123 of file StringExtension.cs.
         {
             return _encoding.GetBytes(s);
         }
GetLine()
static string Components.StringExtension.GetLine (this string s, int Index) static
Definition at line 155 of file StringExtension.cs.
         {
             return s.GetSurroundingLines(Index, 0, 0);
         }
GetLineIndex()
static int Components.StringExtension.GetLineIndex (this string s, int lineNumber) static
Definition at line 165 of file StringExtension.cs.
References i.
         {
             if (lineNumber == 0)
                 return 0;
             var currentLine = 0;
             for (int i = 0; i < s.Length; i++)
             {
                 if (s[i] == '\n')
                 {
                     if (++currentLine == lineNumber)
                         return i + 1;
                 }
             }
             return -1;
         }
GetLineNumber()
static int Components.StringExtension.GetLineNumber (this string s, int Index) static
Definition at line 160 of file StringExtension.cs.
         {
             return s.Split(Index)[0].SplitLines().Length - 1;
         }
GetSurroundingLines()
static string Components.StringExtension.GetSurroundingLines (this string s, int Index, int LinesAbove, int LinesBelow) static
Definition at line 143 of file StringExtension.cs.
References x.
         {
             var strings = s
                 .Split(Index)
                 .Select(x => x.SplitLines(StringSplitOptions.None))
                 .ToArray();
             return strings[0].Skip(strings[0].Length - LinesAbove - 1).Aggregate("\r\n") +
                 strings[1].Take(LinesBelow + 1).Aggregate("\r\n");
         }
Indent()
static string Components.StringExtension.Indent (this string s, string indent = "\t") static
Definition at line 16 of file StringExtension.cs.
         {
             return s.Insert(0, indent).Replace("\n", "\n" + indent);
         }
IndexesOf()
static int [] Components.StringExtension.IndexesOf (this string s, string value) static
Definition at line 217 of file StringExtension.cs.
References i, and value.
         {
             var indexes = new List<int>();
             var i = -1;
             while ((i = s.IndexOf(value, i + 1)) != -1)
             {
                 indexes.Add(i);
             }
             return indexes.ToArray();
         }
InsertLineNumbers() [1/2]
static string Components.StringExtension.InsertLineNumbers (this string s, int startLine) static
Definition at line 191 of file StringExtension.cs.
References i, sb, and ToString().
Referenced by Components.StringExtension.InsertLineNumbers().
         {
             var sb = new StringBuilder(s);
             int line = startLine;
             Func<string> getLineStr = () => (line++.ToString().PadLeft(4, '0') + ": ");
             sb.Insert(0, getLineStr());
             for (int i = 0; i < sb.Length; i++)
             {
                 if (sb[i] == '\n')
                 {
                     sb.Insert(i + 1, getLineStr());
                 }
             }
             return sb.ToString();
         }
InsertLineNumbers() [2/2]
static string Components.StringExtension.InsertLineNumbers (this string s) static
Definition at line 212 of file StringExtension.cs.
References Components.StringExtension.InsertLineNumbers().
         {
             return InsertLineNumbers(s, 1);
         }
LeastIndexOf()
static int Components.StringExtension.LeastIndexOf (this string s, params char [] Chars) static
Definition at line 116 of file StringExtension.cs.
References x.
         {
             return Chars.Select(x => s.IndexOf(x)).OrderBy(x => x).First();
         }
NormalizeLines()
static string Components.StringExtension.NormalizeLines (this string s) static
Definition at line 183 of file StringExtension.cs.
         {
             return s
                 .Replace("\r\n", "\n")
                 .Replace('\r', '\n')
                 .Replace("\n", "\r\n");
         }
RemoveAtIndexOf() [1/4]
static string Components.StringExtension.RemoveAtIndexOf (this string s, string Value) static
Definition at line 61 of file StringExtension.cs.
         {
             return s.Remove(s.IndexOf(Value));
         }
RemoveAtIndexOf() [2/4]
static string Components.StringExtension.RemoveAtIndexOf (this string s, string Value, int Offset) static
Definition at line 66 of file StringExtension.cs.
         {
             return s.Remove(s.IndexOf(Value) + Offset);
         }
RemoveAtIndexOf() [3/4]
static string Components.StringExtension.RemoveAtIndexOf (this string s, char Value) static
Definition at line 71 of file StringExtension.cs.
         {
             return s.Remove(s.IndexOf(Value));
         }
RemoveAtIndexOf() [4/4]
static string Components.StringExtension.RemoveAtIndexOf (this string s, char Value, int Offset) static
Definition at line 76 of file StringExtension.cs.
         {
             return s.Remove(s.IndexOf(Value) + Offset);
         }
RemoveAtLastIndexOf() [1/4]
static string Components.StringExtension.RemoveAtLastIndexOf (this string s, string Value) static
Definition at line 81 of file StringExtension.cs.
         {
             return s.Remove(s.LastIndexOf(Value));
         }
RemoveAtLastIndexOf() [2/4]
static string Components.StringExtension.RemoveAtLastIndexOf (this string s, string Value, int Offset) static
Definition at line 86 of file StringExtension.cs.
         {
             return s.Remove(s.LastIndexOf(Value) + Offset);
         }
RemoveAtLastIndexOf() [3/4]
static string Components.StringExtension.RemoveAtLastIndexOf (this string s, char Value) static
Definition at line 91 of file StringExtension.cs.
         {
             return s.Remove(s.LastIndexOf(Value));
         }
RemoveAtLastIndexOf() [4/4]
static string Components.StringExtension.RemoveAtLastIndexOf (this string s, char Value, int Offset) static
Definition at line 96 of file StringExtension.cs.
         {
             return s.Remove(s.LastIndexOf(Value) + Offset);
         }
Repeat()
static string Components.StringExtension.Repeat (this string s, int Count) static
Definition at line 11 of file StringExtension.cs.
References Count.
         {
             return new StringBuilder().Insert(0, s, Count).ToString();
         }
Slice()
static string Components.StringExtension.Slice (this string s, int StartIndex, int EndIndex) static
Definition at line 101 of file StringExtension.cs.
         {
             return s.Substring(StartIndex, EndIndex - StartIndex);
         }
Split()
static string [] Components.StringExtension.Split (this string s, int Index) static
Definition at line 106 of file StringExtension.cs.
         {
             return new[] { s.Remove(Index), s.Substring(Index) };
         }
SplitLines() [1/2]
static string [] Components.StringExtension.SplitLines (this string s, StringSplitOptions Options) static
Definition at line 111 of file StringExtension.cs.
Referenced by Components.StringExtension.SplitLines().
         {
             return s.Split(new[] { "\r\n" }, Options);
         }
SplitLines() [2/2]
static string [] Components.StringExtension.SplitLines (this string s) static
Definition at line 128 of file StringExtension.cs.
References Components.StringExtension.SplitLines().
         {
             return SplitLines(s, StringSplitOptions.None);
         }
SubstringAtIndexOf() [1/4]
static string Components.StringExtension.SubstringAtIndexOf (this string s, string Value) static
Definition at line 21 of file StringExtension.cs.
         {
             return s.Substring(s.IndexOf(Value));
         }
SubstringAtIndexOf() [2/4]
static string Components.StringExtension.SubstringAtIndexOf (this string s, string Value, int Offset) static
Definition at line 26 of file StringExtension.cs.
         {
             return s.Substring(s.IndexOf(Value) + Offset);
         }
SubstringAtIndexOf() [3/4]
static string Components.StringExtension.SubstringAtIndexOf (this string s, char Value) static
Definition at line 31 of file StringExtension.cs.
         {
             return s.Substring(s.IndexOf(Value));
         }
SubstringAtIndexOf() [4/4]
static string Components.StringExtension.SubstringAtIndexOf (this string s, char Value, int Offset) static
Definition at line 36 of file StringExtension.cs.
         {
             return s.Substring(s.IndexOf(Value) + Offset);
         }
SubstringAtLastIndexOf() [1/4]
static string Components.StringExtension.SubstringAtLastIndexOf (this string s, string Value) static
Definition at line 41 of file StringExtension.cs.
         {
             return s.Substring(s.LastIndexOf(Value));
         }
SubstringAtLastIndexOf() [2/4]
static string Components.StringExtension.SubstringAtLastIndexOf (this string s, string Value, int Offset) static
Definition at line 46 of file StringExtension.cs.
         {
             return s.Substring(s.LastIndexOf(Value) + Offset);
         }
SubstringAtLastIndexOf() [3/4]
static string Components.StringExtension.SubstringAtLastIndexOf (this string s, char Value) static
Definition at line 51 of file StringExtension.cs.
         {
             return s.Substring(s.LastIndexOf(Value));
         }
SubstringAtLastIndexOf() [4/4]
static string Components.StringExtension.SubstringAtLastIndexOf (this string s, char Value, int Offset) static
Definition at line 56 of file StringExtension.cs.
         {
             return s.Substring(s.LastIndexOf(Value) + Offset);
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/External/Common/StringExtension.cs