Aphid Programming Language: Components.Aphid.Debugging.AphidMemoryDump Class Reference
Components.Aphid.Debugging.AphidMemoryDump Class Reference
Static Public Member Functions
static string Create ()
Detailed Description
Definition at line 12 of file AphidMemoryDump.cs.
Member Function Documentation
Create()
static string Components.Aphid.Debugging.AphidMemoryDump.Create () static
Definition at line 14 of file AphidMemoryDump.cs.
References Components.Cypress.MemoryDump.Create(), f, Components.External.PathHelper.GetExecutingPath(), and Components.External.ConsolePlus.Cli.WriteCriticalErrorMessage().
         {
             try
             {
                 var f = PathHelper.GetExecutingPath(
                     string.Format("AphidMemory-{0}.dmp", Guid.NewGuid()));
                 MemoryDump.Create(f);
                 Cli.WriteCriticalErrorMessage("Created memory dump '{0}'.", f);
                 return f;
             }
             catch
             {
                 Cli.WriteCriticalErrorMessage("Failed creating memory dump.");
                 return null;
             }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Debugging/AphidMemoryDump.cs