Aphid Programming Language: Boxelder.AphidTreeHelper Class Reference
Boxelder.AphidTreeHelper Class Reference
Static Public Member Functions
static AphidExpression [] FirstOrDefaultPath (List< AphidExpression > ast, Func< AphidExpression, bool > predicate)
static AphidExpression [] FirstOrDefaultPath (AphidExpression expression, Func< AphidExpression, bool > predicate)
Detailed Description
Definition at line 10 of file AphidTreeHelper.cs.
Member Function Documentation
FirstOrDefaultPath() [1/2]
static AphidExpression [] Boxelder.AphidTreeHelper.FirstOrDefaultPath (List< AphidExpression > ast, Func< AphidExpression, bool > predicate) static
Definition at line 14 of file AphidTreeHelper.cs.
References ast, predicate, and x.
Referenced by Boxelder.LambdaPositionMutator.EndRecursiveMutationPass(), Boxelder.AphidTreeHelper.FirstOrDefaultPath(), and Boxelder.LambdaPositionMutator.MutateCore().
         {
             return ast
                 .Select(x => FirstOrDefaultPath(x, predicate))
                 .Where(x => x != null)
                 .FirstOrDefault();
         }
FirstOrDefaultPath() [2/2]
static AphidExpression [] Boxelder.AphidTreeHelper.FirstOrDefaultPath (AphidExpression expression, Func< AphidExpression, bool > predicate) static
Definition at line 24 of file AphidTreeHelper.cs.
References expression, Boxelder.AphidTreeHelper.FirstOrDefaultPath(), Components.Aphid.Parser.IParentNode.GetChildren(), predicate, and x.
         {
             IParentNode parent;
             _expressions.Push(expression);
             try
             {
                 if (predicate(expression))
                 {
                     return _expressions.ToArray();
                 }
                 else if ((parent = expression as IParentNode) != null)
                 {
                     return parent
                         .GetChildren()
                         .Select(x => FirstOrDefaultPath(x, predicate))
                         .Where(x => x != null)
                         .FirstOrDefault();
                 }
                 else
                 {
                     return null;
                 }
             }
             finally
             {
                 _expressions.Pop();
             }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Boxelder/AphidTreeHelper.cs