Aphid Programming Language: Components.Aphid.Interpreter.AphidInterpreter Class Reference
Components.Aphid.Interpreter.AphidInterpreter Class Reference
Public Member Functions
AphidInterpreter ()
AphidInterpreter (bool createLoader)
AphidInterpreter (AphidObject currentScope)
AphidInterpreter (AphidObject currentScope, bool createLoader)
List< string > GetImports ()
void AddImport (string name)
AphidObject GetReturnValue ()
void SetScriptFilename (string filename)
string GetScriptFilename ()
void EnterScope ()
bool LeaveScope (bool bubbleReturnValue=false)
void EnterSharedScope (AphidObject sharedScope)
void EnterSharedScope (AphidObject sharedScope, bool createChild)
void LeaveSharedScope ()
void WriteOut (string text)
AphidObject CallFunction (string name, params object[] parms)
AphidObject CallFunction (AphidFunction function, params object[] parms)
AphidObject CallFunctionWithScope (AphidFunction function, AphidObject scope, params object[] parms)
AphidObject CallFunction (AphidObject function, params object[] args)
AphidObject CallStaticInteropFunction (CallExpression callExpression)
string [] FlattenPath (AphidExpression exp)
void PushFrame (string name)
void PushFrame (AphidExpression callExpression, AphidExpression functionExpression, IEnumerable< object > args)
void PushFrame (AphidExpression callExpression, Lazy< string > name, IEnumerable< object > args)
void PushFrame (AphidFrame frame)
void PopFrame ()
AphidObject CallInteropFunction (AphidExpression callExpression, AphidInteropMethodInfo methodInfo, AphidInteropMember interopMembers)
AphidObject WrapInteropValue (object value)
object InterpretStream (string code)
object Interpret (AphidExpression expression)
void InterpretFile (string filename)
void InterpretFile (string filename, bool isTextDocument)
void Interpret (string code)
void Interpret (string code, bool isTextDocument)
void Interpret (List< AphidExpression > expressions)
AphidFrame [] GetStackTrace ()
void ResetState ()
void Continue ()
void SingleStep ()
void Pause ()
AphidRuntimeException CreateRuntimeException (string message, params object[] args)
AphidRuntimeException CreateRuntimeException (AphidExpression expression, object obj)
AphidRuntimeException CreateValueException (object obj, string message, params object[] args)
AphidRuntimeException CreateExpressionException (AphidExpression expression, object obj, string message, params object[] args)
AphidRuntimeException CreateInternalException (string message, params object[] args)
bool SetIsInTryCatchFinally (bool value)
Type GetIpcContextType ()
void RegisterIpcServer ()
AphidIpcContext CreateIpcClientContext ()
void InsertNext (IEnumerable< AphidExpression > block)
void TakeOwnership ()
Properties
AphidObject CurrentScope [get]
int OwnerThread [get]
AphidAssemblyBuilder AsmBuilder [get]
InteropMethodResolver InteropMethodResolver [get]
OperatorHelper OperatorHelper [get]
ValueHelper ValueHelper [get]
InteropTypeResolver InteropTypeResolver [get]
TypeExtender TypeExtender [get]
AphidTypeConverter TypeConverter [get]
AphidFunctionConverter FunctionConverter [get]
AphidIpcContext IpcContext [get]
Action< AphidExpression > HandleExecutionBreak [get, set]
AphidSerializer Serializer [get, set]
TextWriter Out [get, set]
Func< string, string > OutFilter [get, set]
Func< string, string > GatorEmitFilter [get, set]
AphidLoader Loader [get]
AphidExpression CurrentStatement [get]
AphidExpression CurrentExpression [get]
bool StrictMode [get, set]
Func< List< AphidExpression >, AphidExecutionContext, List< AphidExpression > > OnInterpretBlock [get, set]
bool OnInterpretBlockExecuting [get]
Action< AphidExecutionContext< AphidExpression > > OnInterpretStatement [get, set]
bool OnInterpretStatementExecuting [get]
Action< AphidExecutionContext< AphidExpression > > OnInterpretExpression [get, set]
bool OnInterpretExpressionExecuting [get]
Action< AphidExecutionContext< ObjectExpression > > OnInterpretObject [get, set]
bool OnInterpretObjectExecuting [get]
Detailed Description
Definition at line 124 of file AphidInterpreter.cs.
Constructor & Destructor Documentation
AphidInterpreter() [1/4]
Components.Aphid.Interpreter.AphidInterpreter.AphidInterpreter ()
Definition at line 225 of file AphidInterpreter.cs.
             : this(createLoader: true)
         {
         }
AphidInterpreter() [2/4]
Components.Aphid.Interpreter.AphidInterpreter.AphidInterpreter (bool createLoader)
Definition at line 230 of file AphidInterpreter.cs.
             : this(new AphidObject(), createLoader)
         {
             // Optimize by generating all built-in
             // variables here without having to perform
             // key existence checks.
         }
AphidInterpreter() [3/4]
Components.Aphid.Interpreter.AphidInterpreter.AphidInterpreter (AphidObject currentScope)
Definition at line 238 of file AphidInterpreter.cs.
             : this(currentScope, createLoader: true)
         {
         }
AphidInterpreter() [4/4]
Components.Aphid.Interpreter.AphidInterpreter.AphidInterpreter (AphidObject currentScope, bool createLoader)
Definition at line 243 of file AphidInterpreter.cs.
             : this(currentScope, createLoader, null)
         {
         }
Member Function Documentation
AddImport()
void Components.Aphid.Interpreter.AphidInterpreter.AddImport (string name)
Definition at line 428 of file AphidInterpreter.cs.
References name.
         {
             var imports = GetImports();
             if (!imports.Contains(name))
             {
                 imports.Add(name);
             }
         }
CallFunction() [1/3]
AphidObject Components.Aphid.Interpreter.AphidInterpreter.CallFunction (string name, params object [] parms)
Definition at line 2182 of file AphidInterpreter.cs.
References func, and name.
Referenced by Components.Aphid.Library.ThreadingLibrary.Lock(), and Components.Aphid.Tests.Integration.Shared.ScriptedTests.RunTestScript().
         {
             var idExp = new IdentifierExpression(name);
             PushFrame(idExp, idExp, parms);
             try
             {
                 var val = InterpretIdentifierExpression(idExp);
                 var func = ValueHelper.Unwrap(val) as AphidFunction;
                 return CallFunction(func, parms);
             }
             finally
             {
                 PopFrame();
             }
         }
CallFunction() [2/3]
AphidObject Components.Aphid.Interpreter.AphidInterpreter.CallFunction (AphidFunction function, params object [] parms)
Definition at line 2201 of file AphidInterpreter.cs.
         {
             return CallFunctionWithScope(function, null, parms);
         }
CallFunction() [3/3]
AphidObject Components.Aphid.Interpreter.AphidInterpreter.CallFunction (AphidObject function, params object [] args)
Definition at line 2340 of file AphidInterpreter.cs.
References args, func, and value.
         {
             var value = function.Value;
             var func = value as AphidFunction;
             if (func != null)
             {
                 return CallFunction(func, args);
             }
             var func2 = value as AphidInteropFunction;
             if (func2 != null)
             {
                 return CallInteropFunction(func2, (AphidObject[])args);
             }
             throw CreateRuntimeException("Object is not function: {0}", function);
         }
CallFunctionWithScope()
AphidObject Components.Aphid.Interpreter.AphidInterpreter.CallFunctionWithScope (AphidFunction function, AphidObject scope, params object [] parms)
Definition at line 2207 of file AphidInterpreter.cs.
References Components.Aphid.Interpreter.AphidInterpreter.Loader, scope, and Components.Aphid.Interpreter.AphidLoader.SearchPaths.
         {
             var parmsWrapped = parms.Select(ValueHelper.Wrap).ToArray();
             if (Thread.CurrentThread.ManagedThreadId == OwnerThread)
             {
                 return CallFunctionCore(function, scope, parmsWrapped);
             }
             else
             {
                 var child = new AphidInterpreter(CurrentScope.CreateChild())
                 {
                     Serializer = Serializer,
                     StrictMode = StrictMode,
                 };
                 child.Loader.SearchPaths.AddRange(Loader.SearchPaths);
                 return child.CallFunctionCore(function, scope, parmsWrapped);
             }
         }
CallInteropFunction()
AphidObject Components.Aphid.Interpreter.AphidInterpreter.CallInteropFunction (AphidExpression callExpression, AphidInteropMethodInfo methodInfo, AphidInteropMember interopMembers)
Definition at line 2816 of file AphidInterpreter.cs.
References Components.Aphid.TypeSystem.AphidInteropMethodInfo.Arguments, Components.Aphid.TypeSystem.AphidInteropMethodInfo.GenericArguments, Components.Aphid.TypeSystem.AphidInteropMethodInfo.Method, and Components.Aphid.TypeSystem.AphidInteropMember.Target.
         {
             MethodBase method;
             if (!methodInfo.Method.IsGenericMethod)
             {
                 method = methodInfo.Method;
             }
             else
             {
                 method = ((MethodInfo)methodInfo.Method).MakeGenericMethod(methodInfo.GenericArguments);
             }
             var convertedArgs = TypeConverter.Convert(
                 methodInfo.Arguments,
                 methodInfo.GenericArguments);
             PushFrame(
                 callExpression,
                 new Lazy<string>(() =>
                     string.Format("{0}.{1}", method.DeclaringType.FullName, method.Name)),
                 convertedArgs);
             try
             {
                 return ValueHelper.Wrap(
                     method.Invoke(
                         interopMembers.Target,
                         convertedArgs));
             }
             finally
             {
                 PopFrame();
             }
         }
CallStaticInteropFunction()
AphidObject Components.Aphid.Interpreter.AphidInterpreter.CallStaticInteropFunction (CallExpression callExpression)
Definition at line 2384 of file AphidInterpreter.cs.
References args, Components.Aphid.Parser.CallExpression.Args, Components.Aphid.Parser.CallExpression.FunctionExpression, if(), Components.Aphid.TypeSystem.AphidInteropMethodInfo.Method, Components.Aphid.TypeSystem.InteropMethodResolver.Resolve(), and Components.Aphid.TypeSystem.InteropTypeResolver.ResolveType().
         {
             var path = FlattenPath(callExpression.FunctionExpression);
             var pathStr = string.Join(".", path);
             var imports = GetImports();
             var type = InteropTypeResolver.ResolveType(GetImports().ToArray(), path);
             var methodName = path.Last();
             var args = callExpression.Args
                 .Select(InterpretExpression)
                 .Select(ValueHelper.Unwrap)
                 .ToArray();
             var methodInfo = InteropMethodResolver.Resolve(type, methodName, args);
             MethodBase method;
             if (!methodInfo.GenericArguments.Any())
             {
                 method = methodInfo.Method;
             }
             else
             {
                 var m = (MethodInfo)methodInfo.Method;
                 if (methodInfo.GenericArguments.Length != m.GetGenericArguments().Length)
                 {
                     throw CreateRuntimeException(
                         "Generic type parameter mismatch between {0} and {1}.",
                         methodInfo.Method.ToString(),
                         m.ToString());
                 }
                 method = m.MakeGenericMethod(m.GetGenericArguments());
             }
             var convertedArgs = TypeConverter.Convert(
                 methodInfo.Arguments,
                 methodInfo.GenericArguments);
             return ValueHelper.Wrap(method.Invoke(null, convertedArgs));
         }
Continue()
void Components.Aphid.Interpreter.AphidInterpreter.Continue ()
Definition at line 4832 of file AphidInterpreter.cs.
         {
             _breakpointReset.Set();
             if (_isSingleStepping)
             {
                 _isSingleStepping = false;
                 _singleStepReset.Set();
             }
         }
CreateExpressionException()
AphidRuntimeException Components.Aphid.Interpreter.AphidInterpreter.CreateExpressionException (AphidExpression expression, object obj, string message, params object [] args)
Definition at line 4905 of file AphidInterpreter.cs.
References args, expression, Components.External.ConsolePlus.Cli.FormatEscape(), and obj.
         {
             return CreateRuntimeException(
                 string.Format(
                     "{0} {1}",
                     message,
                     Cli.FormatEscape(GetExpressionValueString(expression, obj))),
                 args);
         }
CreateInternalException()
AphidRuntimeException Components.Aphid.Interpreter.AphidInterpreter.CreateInternalException (string message, params object [] args)
Definition at line 4927 of file AphidInterpreter.cs.
References args.
         {
             return new AphidInternalException(
                 this,
                 CurrentScope,
                 CurrentStatement,
                 CurrentExpression,
                 message,
                 args);
         }
CreateIpcClientContext()
AphidIpcContext Components.Aphid.Interpreter.AphidInterpreter.CreateIpcClientContext ()
Definition at line 4977 of file AphidInterpreter.cs.
         {
             return IpcContext = new AphidIpcContext();
         }
CreateRuntimeException() [1/2]
AphidRuntimeException Components.Aphid.Interpreter.AphidInterpreter.CreateRuntimeException (string message, params object [] args)
Definition at line 4870 of file AphidInterpreter.cs.
References args.
Referenced by Components.Aphid.Library.StandardLibrary.CovertToNumber(), Components.Aphid.Library.EnvironmentLibrary.Kill(), and Components.Aphid.Library.StreamLibrary.StreamWrite().
         {
             return new AphidRuntimeException(
                 this,
                 CurrentScope,
                 CurrentStatement,
                 CurrentExpression,
                 message,
                 args);
         }
CreateRuntimeException() [2/2]
AphidRuntimeException Components.Aphid.Interpreter.AphidInterpreter.CreateRuntimeException (AphidExpression expression, object obj)
Definition at line 4882 of file AphidInterpreter.cs.
References expression, and obj.
         {
             return CreateRuntimeException(
                 "Unhandled exception caused by ",
                 GetExpressionValueString(expression, obj));
         }
CreateValueException()
AphidRuntimeException Components.Aphid.Interpreter.AphidInterpreter.CreateValueException (object obj, string message, params object [] args)
Definition at line 4892 of file AphidInterpreter.cs.
References args, Components.External.ConsolePlus.Cli.FormatEscape(), and obj.
Referenced by Components.Aphid.TypeSystem.AphidObject.Resolve().
         {
             return CreateRuntimeException(
                 string.Format("{0} {1}",
                     message,
                     Cli.FormatEscape(GetValueString(obj))),
                 args);
         }
EnterScope()
void Components.Aphid.Interpreter.AphidInterpreter.EnterScope ()
Definition at line 496 of file AphidInterpreter.cs.
References Components.Aphid.Debugging.AphidTrace.Trace().
         {
 #if TRACE_SCOPE
             _scopeTrace.Trace("Enter scope begin");
 #endif
             CurrentScope = new AphidObject(null, CurrentScope);
             CurrentScope.Add(AphidName.Scope, CurrentScope);
             CurrentScope.Add(AphidName.Parent, CurrentScope.Parent);
 #if TRACE_SCOPE
             _scopeTrace.Trace("Enter scope end");
 #endif
         }
EnterSharedScope() [1/2]
void Components.Aphid.Interpreter.AphidInterpreter.EnterSharedScope (AphidObject sharedScope)
Definition at line 556 of file AphidInterpreter.cs.
         {
             EnterSharedScope(sharedScope, createChild: true);
         }
EnterSharedScope() [2/2]
void Components.Aphid.Interpreter.AphidInterpreter.EnterSharedScope (AphidObject sharedScope, bool createChild)
Definition at line 561 of file AphidInterpreter.cs.
         {
             if (_localScope != null)
             {
                 throw CreateRuntimeException(
                     "Already in shared scope, cannot enter another.");
             }
             _localScope = CurrentScope;
             CurrentScope = !createChild ?
                 sharedScope :
                 new AphidObject(null, sharedScope);
             PushFrame("[Shared Scope]");
         }
FlattenPath()
string [] Components.Aphid.Interpreter.AphidInterpreter.FlattenPath (AphidExpression exp)
Definition at line 2435 of file AphidInterpreter.cs.
References x.
         {
             var pathExps = Flatten(exp);
             if (!pathExps.All(x => x.Type == AphidExpressionType.IdentifierExpression))
             {
                 throw CreateRuntimeException("Invalid interop call path '{0}'", exp);
             }
             var path = pathExps
                 .Select(x => ((IdentifierExpression)x).Identifier)
                 .ToArray();
             return path;
         }
GetImports()
List<string> Components.Aphid.Interpreter.AphidInterpreter.GetImports ()
Definition at line 410 of file AphidInterpreter.cs.
References Components.DefaultSingleton< T >.Current, out, and Components.Aphid.TypeSystem.AphidObject.Value.
         {
             AphidObject imports = null;
             if (CurrentScope.TryResolve(AphidName.Imports, out imports))
             {
                 return (List<string>)imports.Value;
             }
             else
             {
                 var list = new List<string>(AphidConfig.Current.Imports);
                 CurrentScope.Add(AphidName.Imports, new AphidObject(list));
                 return list;
             }
         }
GetIpcContextType()
Type Components.Aphid.Interpreter.AphidInterpreter.GetIpcContextType ()
Definition at line 4965 of file AphidInterpreter.cs.
References Type.
         {
             return typeof(AphidIpcContext);
         }
GetReturnValue()
AphidObject Components.Aphid.Interpreter.AphidInterpreter.GetReturnValue ()
Definition at line 439 of file AphidInterpreter.cs.
Referenced by Components.Aphid.UI.AphidCli.DumpExpression(), and Components.Aphid.Tests.Integration.Shared.AphidTests.Execute().
         {
             return GetReturnValue(false);
         }
GetScriptFilename()
string Components.Aphid.Interpreter.AphidInterpreter.GetScriptFilename ()
Definition at line 479 of file AphidInterpreter.cs.
References out, and Components.Aphid.TypeSystem.AphidObject.TryResolve().
         {
             AphidObject scriptObj;
             if (CurrentScope != null)
             {
                 return CurrentScope.TryResolve(AphidName.Script, out scriptObj) ?
                     scriptObj != null ? scriptObj.GetString() : null :
                     null;
             }
             else
             {
                 return null;
             }
         }
GetStackTrace()
AphidFrame [] Components.Aphid.Interpreter.AphidInterpreter.GetStackTrace ()
Definition at line 4725 of file AphidInterpreter.cs.
Referenced by Components.Aphid.UI.AphidCli.DumpStackTrace().
         {
             return _frames.ToArray();
         }
InsertNext()
void Components.Aphid.Interpreter.AphidInterpreter.InsertNext (IEnumerable< AphidExpression > block)
Definition at line 4983 of file AphidInterpreter.cs.
         {
             if (_insertNextBuffer != null)
             {
                 CreateRuntimeException("Cannot insert block, buffer already set.");
             }
             _insertNextBuffer = block;
         }
Interpret() [1/4]
object Components.Aphid.Interpreter.AphidInterpreter.Interpret (AphidExpression expression)
Definition at line 4350 of file AphidInterpreter.cs.
References expression.
Referenced by Components.Aphid.UI.AphidCli.DumpExpression(), Components.Aphid.Tests.Integration.Shared.AphidTests.Execute(), and Components.Aphid.UI.AphidCli.ExecuteCode().
         {
 #if APHID_SET_CODE_VAR
             SetAstCode(new List<AphidExpression> { expression });
 #endif
             return InterpretExpression(expression);
         }
Interpret() [2/4]
void Components.Aphid.Interpreter.AphidInterpreter.Interpret (string code)
Definition at line 4559 of file AphidInterpreter.cs.
References code, and Interpret().
         {
             Interpret(code, false);
         }
Interpret() [3/4]
void Components.Aphid.Interpreter.AphidInterpreter.Interpret (string code, bool isTextDocument)
Definition at line 4565 of file AphidInterpreter.cs.
References code, and Interpret().
         {
             Interpret(code, null, isTextDocument);
         }
Interpret() [4/4]
void Components.Aphid.Interpreter.AphidInterpreter.Interpret (List< AphidExpression > expressions)
Definition at line 4585 of file AphidInterpreter.cs.
References Interpret(), Components.Aphid.Interpreter.AphidInterpreter.Loader, and Components.Aphid.Interpreter.AphidLoader.SearchPaths.
         {
             if (OwnerThread == -1)
             {
                 OwnerThread = Thread.CurrentThread.ManagedThreadId;
 #if APHID_SET_CODE_VAR
                 SetAstCode(expressions);
 #endif
                 Interpret(expressions, resetIsReturning: true);
             }
             else if (OwnerThread == Thread.CurrentThread.ManagedThreadId)
             {
 #if APHID_SET_CODE_VAR
                 SetAstCode(expressions);
 #endif
                 Interpret(expressions, resetIsReturning: true);
             }
             else
             {
                 var child = new AphidInterpreter(CurrentScope.CreateChild())
                 {
                     Serializer = Serializer,
                     StrictMode = StrictMode,
                 };
                 child.Loader.SearchPaths.AddRange(Loader.SearchPaths);
                 child.Interpret(expressions);
             }
         }
InterpretFile() [1/2]
void Components.Aphid.Interpreter.AphidInterpreter.InterpretFile (string filename)
Definition at line 4538 of file AphidInterpreter.cs.
         {
             InterpretFile(filename, false);
         }
InterpretFile() [2/2]
void Components.Aphid.Interpreter.AphidInterpreter.InterpretFile (string filename, bool isTextDocument)
Definition at line 4544 of file AphidInterpreter.cs.
References code, and Interpret().
         {
             var fullFilename = Loader.FindScriptFile(filename);
             if (fullFilename == null)
             {
                 throw CreateRuntimeException("Cannot find script {0}", filename);
             }
             SetScriptFilename(fullFilename);
             var code = File.ReadAllText(filename);
             Interpret(code, filename, isTextDocument);
         }
InterpretStream()
object Components.Aphid.Interpreter.AphidInterpreter.InterpretStream (string code)
Definition at line 4325 of file AphidInterpreter.cs.
References ast, code, Components.Aphid.Parser.AphidMutator.MutateRecursively(), and Components.Aphid.Parser.AphidParser.Parse().
Referenced by Components.Aphid.Interpreter.AphidIpcContext.Eval().
         {
             var ast = AphidParser.Parse(code);
 #if APHID_SET_CODE_VAR
             SetAstCode(ast);
 #endif
             var mutatedAst = new PartialOperatorMutator().MutateRecursively(ast);
             mutatedAst = new AphidMacroMutator().MutateRecursively(mutatedAst);
             mutatedAst = new AphidIdDirectiveMutator().MutateRecursively(mutatedAst);
             foreach (var exp in mutatedAst)
             {
                 InterpretExpression(exp);
                 if (_isReturning)
                 {
                     _isReturning = false;
                     return GetReturnValue(true);
                 }
             }
             return null;
         }
LeaveScope()
bool Components.Aphid.Interpreter.AphidInterpreter.LeaveScope (bool bubbleReturnValue = false)
Definition at line 512 of file AphidInterpreter.cs.
References ret, and Components.Aphid.Debugging.AphidTrace.Trace().
         {
 #if TRACE_SCOPE
             _scopeTrace.Trace("Leave scope begin");
 #endif
             if (CurrentScope.Parent == null)
             {
 #if TRACE_SCOPE
                 _scopeTrace.Trace("Internal error leaving scope, parent scope is null.");
 #endif
                 throw CreateInternalException(
                     "Internal error leaving scope, parent scope is null.");
             }
             if (bubbleReturnValue)
             {
                 var ret = GetReturnValue(true);
                 CurrentScope = CurrentScope.Parent;
                 if (ret != null)
                 {
                     SetReturnValue(ret);
 #if TRACE_SCOPE
                     _scopeTrace.Trace("Leave scope end");
 #endif
                     return true;
                 }
             }
             else
             {
                 CurrentScope = CurrentScope.Parent;
             }
 #if TRACE_SCOPE
             _scopeTrace.Trace("Leave scope end");
 #endif
             return false;
         }
LeaveSharedScope()
void Components.Aphid.Interpreter.AphidInterpreter.LeaveSharedScope ()
Definition at line 578 of file AphidInterpreter.cs.
         {
             PopFrame();
             if (_localScope == null)
             {
                 throw CreateRuntimeException(
                     "Leave shared scope failed, not in shared scope.");
             }
             CurrentScope = _localScope;
             _localScope = null;
         }
Pause()
void Components.Aphid.Interpreter.AphidInterpreter.Pause ()
Definition at line 4864 of file AphidInterpreter.cs.
         {
             SingleStep();
         }
PopFrame()
void Components.Aphid.Interpreter.AphidInterpreter.PopFrame ()
Definition at line 2720 of file AphidInterpreter.cs.
References Components.Aphid.Debugging.AphidTrace.TraceText().
         {
 #if BINARY_FRAME_PERFORMANCE_TRACE || TEXT_FRAME_PERFORMANCE_TRACE
             var tup = _frameStopwatchStack.Pop();
             tup.Item2.Stop();
             var id = Thread.CurrentThread.ManagedThreadId;
 #endif
 #if TEXT_FRAME_PERFORMANCE_TRACE
             _framePerformanceTrace.TraceText(
                 "{0:x8} < {1} - {2:n0} ticks / {3:n0}ms\r\n",
                 id,
                 tup.Item1,
                 tup.Item2.ElapsedTicks,
                 tup.Item2.ElapsedMilliseconds);
 #endif
 #if BINARY_FRAME_PERFORMANCE_TRACE
             _framePerformanceBinaryWriter.Write(id);
             _framePerformanceBinaryWriter.Write(false);
             _framePerformanceBinaryWriter.Write(tup.Item1);
             _framePerformanceBinaryWriter.Write(tup.Item2.ElapsedTicks);
             _framePerformanceBinaryWriter.Write(tup.Item2.ElapsedMilliseconds);
 #endif
             if (!_isInTryCatchFinally)
             {
                 _frames.Pop();
             }
             else
             {
                 _queuedFramePops++;
             }
         }
PushFrame() [1/4]
void Components.Aphid.Interpreter.AphidInterpreter.PushFrame (string name)
Definition at line 2629 of file AphidInterpreter.cs.
References name.
         {
             PushFrame(CreateNameFrame(name));
         }
PushFrame() [2/4]
void Components.Aphid.Interpreter.AphidInterpreter.PushFrame (AphidExpression callExpression, AphidExpression functionExpression, IEnumerable< object > args)
Definition at line 2635 of file AphidInterpreter.cs.
References args, name, Components.Aphid.Parser.AphidExpression.ToString(), Components.Aphid.Parser.AphidNode.Type, and x.
         {
             var name = new Lazy<string>(() =>
             {
                 switch (functionExpression.Type)
                 {
                     case AphidExpressionType.IdentifierExpression:
                         return ((IdentifierExpression)functionExpression).Identifier;
                     case AphidExpressionType.BinaryOperatorExpression:
                         var operands = Flatten(functionExpression);
                         return operands.All(x => x.Type == AphidExpressionType.IdentifierExpression) ?
                             FlattenAndJoinPath(functionExpression) :
                             functionExpression.ToString();
                     default:
                         return functionExpression.ToString();
                 }
             });
             PushFrame(callExpression, name, args);
         }
PushFrame() [3/4]
void Components.Aphid.Interpreter.AphidInterpreter.PushFrame (AphidExpression callExpression, Lazy< string > name, IEnumerable< object > args)
Definition at line 2663 of file AphidInterpreter.cs.
References args, name, and Components.Aphid.Debugging.AphidTrace.TraceText().
         {
             _frames.Push(new AphidFrame(this, CurrentScope, callExpression, name, args));
 #if BINARY_FRAME_PERFORMANCE_TRACE || TEXT_FRAME_PERFORMANCE_TRACE
             var id = Thread.CurrentThread.ManagedThreadId;
 #endif
 #if TEXT_FRAME_PERFORMANCE_TRACE
             _framePerformanceTrace.TraceText("{0:x8} > {1}\r\n", id, name.Value);
 #endif
 #if BINARY_FRAME_PERFORMANCE_TRACE
             // Todo: Pack enter/leave in as high order bit of thread id
             _framePerformanceBinaryWriter.Write(id);
             _framePerformanceBinaryWriter.Write(true);
             _framePerformanceBinaryWriter.Write(name.Value);
 #endif
 #if BINARY_FRAME_PERFORMANCE_TRACE || TEXT_FRAME_PERFORMANCE_TRACE
             var sw = new Stopwatch();
             _frameStopwatchStack.Push(Tuple.Create(name.Value, sw));
             sw.Start();
 #endif
         }
PushFrame() [4/4]
void Components.Aphid.Interpreter.AphidInterpreter.PushFrame (AphidFrame frame)
Definition at line 2693 of file AphidInterpreter.cs.
References frame, and Components.Aphid.Debugging.AphidTrace.TraceText().
         {
             _frames.Push(frame);
 #if BINARY_FRAME_PERFORMANCE_TRACE || TEXT_FRAME_PERFORMANCE_TRACE
             var id = Thread.CurrentThread.ManagedThreadId;
 #endif
 #if TEXT_FRAME_PERFORMANCE_TRACE
             _framePerformanceTrace.TraceText("{0:x8} > {1}\r\n", id, frame.Name);
 #endif
 #if BINARY_FRAME_PERFORMANCE_TRACE
             // Todo: Pack enter/leave in as high order bit of thread id
             _framePerformanceBinaryWriter.Write(id);
             _framePerformanceBinaryWriter.Write(true);
             _framePerformanceBinaryWriter.Write(frame.Name);
 #endif
 #if BINARY_FRAME_PERFORMANCE_TRACE || TEXT_FRAME_PERFORMANCE_TRACE
             var sw = new Stopwatch();
             _frameStopwatchStack.Push(Tuple.Create(frame.Name, sw));
             sw.Start();
 #endif
         }
RegisterIpcServer()
void Components.Aphid.Interpreter.AphidInterpreter.RegisterIpcServer ()
Definition at line 4971 of file AphidInterpreter.cs.
References Components.Aphid.Interpreter.AphidIpcContext.Register().
         {
             AphidIpcContext.Register(this);
         }
ResetState()
void Components.Aphid.Interpreter.AphidInterpreter.ResetState ()
Definition at line 4745 of file AphidInterpreter.cs.
References Components.Aphid.Interpreter.AphidName.Return.
         {
             while (CurrentScope != null && CurrentScope.Parent != null)
             {
                 CurrentScope = CurrentScope.Parent;
             }
             // Todo: Add test cases to cover try/catch influence
             CurrentStatement = null;
             _isReturning = false;
             _isContinuing = false;
             _isBreaking = false;
             _isInTryCatchFinally = false;
             _frames.Clear();
             _frames.Push(CreateEntryFrame());
             _queuedFramePops = 0;
             if (CurrentScope.ContainsKey(AphidName.Return))
             {
                 CurrentScope.Remove(AphidName.Return);
             }
             if (CurrentScope.ContainsKey(AphidName.Block))
             {
                 CurrentScope.Remove(AphidName.Block);
             }
             if (CurrentScope.ContainsKey(AphidName.Script))
             {
                 CurrentScope.Remove(AphidName.Script);
             }
 #if APHID_SET_CODE_VAR
             if (CurrentScope.ContainsKey(AphidName.Code))
             {
                 CurrentScope.Remove(AphidName.Code);
             }
 #endif
         }
SetIsInTryCatchFinally()
bool Components.Aphid.Interpreter.AphidInterpreter.SetIsInTryCatchFinally (bool value)
Definition at line 4956 of file AphidInterpreter.cs.
Referenced by Components.Aphid.UI.AphidCli.TryAction().
         {
             var old = _isInTryCatchFinally;
             _isInTryCatchFinally = true;
             return old;
         }
SetScriptFilename()
void Components.Aphid.Interpreter.AphidInterpreter.SetScriptFilename (string filename)
Definition at line 463 of file AphidInterpreter.cs.
References obj.
         {
             var obj = new AphidObject(filename);
             if (!CurrentScope.ContainsKey(AphidName.Script))
             {
                 CurrentScope.Add(AphidName.Script, obj);
             }
             else
             {
                 CurrentScope.Remove(AphidName.Script);
                 CurrentScope.Add(AphidName.Script, obj);
             }
         }
SingleStep()
void Components.Aphid.Interpreter.AphidInterpreter.SingleStep ()
Definition at line 4844 of file AphidInterpreter.cs.
         {
             _isSingleStepping = true;
             if (_singleStepReset == null)
             {
                 _singleStepReset = new AutoResetEvent(true);
             }
             else
             {
                 _singleStepReset.Set();
             }
             if (_breakpointReset != null)
             {
                 _breakpointReset.Set();
             }
         }
TakeOwnership()
void Components.Aphid.Interpreter.AphidInterpreter.TakeOwnership ()
Definition at line 4994 of file AphidInterpreter.cs.
Referenced by Components.Aphid.Tests.Integration.Shared.ScriptedTests.RunTestScript().
         {
             OwnerThread = Thread.CurrentThread.ManagedThreadId;
         }
WrapInteropValue()
AphidObject Components.Aphid.Interpreter.AphidInterpreter.WrapInteropValue (object value)
Definition at line 2856 of file AphidInterpreter.cs.
References Components.Aphid.TypeSystem.AphidObject.IsAphidType(), and value.
         {
             if (AphidObject.IsAphidType(value))
             {
                 return ValueHelper.Wrap(value);
             }
             else
             {
                 throw CreateValueException(value, "Cannot wrap value");
             }
         }
WriteOut()
void Components.Aphid.Interpreter.AphidInterpreter.WriteOut (string text)
Definition at line 617 of file AphidInterpreter.cs.
References text.
         {
             if (Out != null)
             {
                 if (OutFilter != null)
                 {
                     text = OutFilter(text);
                 }
                 Out.Write(text);
             }
         }
Property Documentation
AsmBuilder
AphidAssemblyBuilder Components.Aphid.Interpreter.AphidInterpreter.AsmBuilder get
Definition at line 189 of file AphidInterpreter.cs.
 { get; private set; }
CurrentExpression
AphidExpression Components.Aphid.Interpreter.AphidInterpreter.CurrentExpression get
Definition at line 221 of file AphidInterpreter.cs.
 { get; private set; }
CurrentScope
AphidObject Components.Aphid.Interpreter.AphidInterpreter.CurrentScope get
Definition at line 165 of file AphidInterpreter.cs.
Referenced by AphidUI.ViewModels.AphidReplViewModel.Dump(), and Components.Aphid.Tests.Integration.Shared.ScriptedTests.RunTestScript().
         {
             get { return _currentScope; }
             private set
             {
 #if TRACE_SCOPE
                 if (_scopeTrace != null)
                 {
                     _scopeTrace.Trace("Set scope begin");
                 }
 #endif
                 _currentScope = value;
 #if TRACE_SCOPE
                 if (_scopeTrace != null)
                 {
                     _scopeTrace.Trace("Set scope end");
                 }
 #endif
             }
         }
CurrentStatement
AphidExpression Components.Aphid.Interpreter.AphidInterpreter.CurrentStatement get
Definition at line 219 of file AphidInterpreter.cs.
 { get; private set; }
FunctionConverter
AphidFunctionConverter Components.Aphid.Interpreter.AphidInterpreter.FunctionConverter get
Definition at line 203 of file AphidInterpreter.cs.
 { get; private set; }
GatorEmitFilter
Func<string, string> Components.Aphid.Interpreter.AphidInterpreter.GatorEmitFilter get set
Definition at line 215 of file AphidInterpreter.cs.
 { get; set; }
HandleExecutionBreak
Action<AphidExpression> Components.Aphid.Interpreter.AphidInterpreter.HandleExecutionBreak get set
Definition at line 207 of file AphidInterpreter.cs.
 { get; set; }
InteropMethodResolver
InteropMethodResolver Components.Aphid.Interpreter.AphidInterpreter.InteropMethodResolver get
Definition at line 191 of file AphidInterpreter.cs.
 { get; private set; }
InteropTypeResolver
InteropTypeResolver Components.Aphid.Interpreter.AphidInterpreter.InteropTypeResolver get
Definition at line 197 of file AphidInterpreter.cs.
 { get; private set; }
IpcContext
AphidIpcContext Components.Aphid.Interpreter.AphidInterpreter.IpcContext get
Definition at line 205 of file AphidInterpreter.cs.
 { get; private set; }
Loader
AphidLoader Components.Aphid.Interpreter.AphidInterpreter.Loader get
Definition at line 217 of file AphidInterpreter.cs.
Referenced by Components.Aphid.Interpreter.AphidInterpreter.CallFunctionWithScope(), Components.Aphid.Tests.Integration.Shared.AphidTests.Execute(), Components.Aphid.Interpreter.AphidInterpreter.Interpret(), and Components.Aphid.Tests.Integration.Shared.AphidTests.ParseScript().
 { get; private set; }
OnInterpretBlock
Func<List<AphidExpression>, AphidExecutionContext, List<AphidExpression> > Components.Aphid.Interpreter.AphidInterpreter.OnInterpretBlock get set
Definition at line 18 of file AphidInterpreter.Events.cs.
 { get; set; }
OnInterpretBlockExecuting
bool Components.Aphid.Interpreter.AphidInterpreter.OnInterpretBlockExecuting get
Definition at line 19 of file AphidInterpreter.Events.cs.
 { get; private set; }
OnInterpretExpression
Action<AphidExecutionContext<AphidExpression> > Components.Aphid.Interpreter.AphidInterpreter.OnInterpretExpression get set
Definition at line 24 of file AphidInterpreter.Events.cs.
 { get; set; }
OnInterpretExpressionExecuting
bool Components.Aphid.Interpreter.AphidInterpreter.OnInterpretExpressionExecuting get
Definition at line 25 of file AphidInterpreter.Events.cs.
 { get; private set; }
OnInterpretObject
Action<AphidExecutionContext<ObjectExpression> > Components.Aphid.Interpreter.AphidInterpreter.OnInterpretObject get set
Definition at line 27 of file AphidInterpreter.Events.cs.
 { get; set; }
OnInterpretObjectExecuting
bool Components.Aphid.Interpreter.AphidInterpreter.OnInterpretObjectExecuting get
Definition at line 28 of file AphidInterpreter.Events.cs.
 { get; private set; }
OnInterpretStatement
Action<AphidExecutionContext<AphidExpression> > Components.Aphid.Interpreter.AphidInterpreter.OnInterpretStatement get set
Definition at line 21 of file AphidInterpreter.Events.cs.
 { get; set; }
OnInterpretStatementExecuting
bool Components.Aphid.Interpreter.AphidInterpreter.OnInterpretStatementExecuting get
Definition at line 22 of file AphidInterpreter.Events.cs.
 { get; private set; }
OperatorHelper
OperatorHelper Components.Aphid.Interpreter.AphidInterpreter.OperatorHelper get
Definition at line 193 of file AphidInterpreter.cs.
 { get; private set; }
Out
TextWriter Components.Aphid.Interpreter.AphidInterpreter.Out get set
Definition at line 211 of file AphidInterpreter.cs.
 { get; set; }
OutFilter
Func<string, string> Components.Aphid.Interpreter.AphidInterpreter.OutFilter get set
Definition at line 213 of file AphidInterpreter.cs.
 { get; set; }
OwnerThread
int Components.Aphid.Interpreter.AphidInterpreter.OwnerThread get
Definition at line 187 of file AphidInterpreter.cs.
 { get; private set; }
Serializer
AphidSerializer Components.Aphid.Interpreter.AphidInterpreter.Serializer get set
Definition at line 209 of file AphidInterpreter.cs.
Referenced by Components.Aphid.Library.StandardLibrary.Deserialize(), Components.Aphid.Interpreter.AphidIpcContext.Eval(), and Components.Aphid.Library.StandardLibrary.Serialize().
 { get; set; }
StrictMode
bool Components.Aphid.Interpreter.AphidInterpreter.StrictMode get set
Definition at line 223 of file AphidInterpreter.cs.
 { get; set; }
TypeConverter
AphidTypeConverter Components.Aphid.Interpreter.AphidInterpreter.TypeConverter get
Definition at line 201 of file AphidInterpreter.cs.
 { get; private set; }
TypeExtender
TypeExtender Components.Aphid.Interpreter.AphidInterpreter.TypeExtender get
Definition at line 199 of file AphidInterpreter.cs.
Referenced by Components.Aphid.Library.StandardLibrary.Extend().
 { get; private set; }
ValueHelper
ValueHelper Components.Aphid.Interpreter.AphidInterpreter.ValueHelper get
Definition at line 195 of file AphidInterpreter.cs.
Referenced by Components.Aphid.Library.StandardLibrary.SetValue().
 { get; private set; }
The documentation for this class was generated from the following files:
c:/source/Aphid/Components.Aphid/Interpreter/AphidInterpreter.cs
c:/source/Aphid/Components.Aphid/Interpreter/AphidInterpreter.Events.cs
c:/source/Aphid/Components.Aphid/Interpreter/AphidInterpreter.g.cs