Aphid Programming Language: Components.Aphid.Serialization.AphidSerializer Class Reference
Components.Aphid.Serialization.AphidSerializer Class Reference
Public Member Functions
AphidSerializer (AphidInterpreter interpreter)
string Serialize (AphidObject o)
AphidObject Deserialize (string obj)
Public Member Functions inherited from Components.Aphid.Interpreter.AphidRuntimeComponent
AphidRuntimeComponent (AphidInterpreter interpreter)
Public Attributes
const string Root = "obj"
Properties
bool IgnoreFunctions [get, set]
bool IgnoreSpecialVariables [get, set]
bool QuoteToStringResults [get, set]
Properties inherited from Components.Aphid.Interpreter.AphidRuntimeComponent
AphidInterpreter Interpreter [get]
Detailed Description
Definition at line 30 of file AphidSerializer.cs.
Constructor & Destructor Documentation
AphidSerializer()
Components.Aphid.Serialization.AphidSerializer.AphidSerializer (AphidInterpreter interpreter)
Definition at line 46 of file AphidSerializer.cs.
             : base(interpreter)
         {
             IgnoreFunctions = true;
         }
Member Function Documentation
Deserialize()
AphidObject Components.Aphid.Serialization.AphidSerializer.Deserialize (string obj)
Definition at line 282 of file AphidSerializer.cs.
References ast, lexer, Components.Aphid.Parser.AphidMutator.Mutate(), obj, Components.Aphid.Parser.AphidParser.ParseExpression(), tokens, and Components.Aphid.Parser.AphidCodeVisitor.Visit().
Referenced by Components.Aphid.Library.StandardLibrary.Deserialize().
         {
             var lexer = new AphidObjectLexer(obj);
             var tokens = lexer.GetTokens();
             var ast = new AphidObjectThisKeywordMutator().Mutate(
                 new List<AphidExpression>
                 {
                     AphidParser.ParseExpression(tokens, obj)
                 });
             if (ast.Count != 1)
             {
                 throw Interpreter.CreateRuntimeException("Invalid Aphid object string: {0}", obj);
             }
             ast[0] = new BinaryOperatorExpression(
                 new IdentifierExpression(
                     Root,
                     new List<IdentifierExpression>
                     {
                         new IdentifierExpression(AphidName.Var)
                     })
                     .WithPositionFrom(ast[0]),
                 AphidTokenType.AssignmentOperator,
                 ast[0]);
             ast.AddRange(
                 new AphidObjectReferenceVisitor()
                     .FindReferenceAssignments(ast));
             new AphidCodeVisitor(obj).Visit(ast);
             var objInterpreter = new AphidInterpreter();
             objInterpreter.Interpret(ast);
             return objInterpreter.CurrentScope[Root];
         }
Serialize()
string Components.Aphid.Serialization.AphidSerializer.Serialize (AphidObject o)
Definition at line 52 of file AphidSerializer.cs.
References sb.
Referenced by Components.Aphid.Library.StandardLibrary.Serialize().
         {
             _traversedPaths.Clear();
             _currentPath.Clear();
             _currentPath.Push("this");
             _traversed = new List<object>();
             var sb = new StringBuilder();
             Serialize(sb, o, 0);
             return sb.ToString();
         }
Member Data Documentation
Root
const string Components.Aphid.Serialization.AphidSerializer.Root = "obj"
Definition at line 32 of file AphidSerializer.cs.
Referenced by Components.Aphid.Serialization.AphidObjectReferenceVisitor.BeginVisit(), and Components.Aphid.Serialization.AphidObjectThisKeywordMutator.MutateCore().
Property Documentation
IgnoreFunctions
bool Components.Aphid.Serialization.AphidSerializer.IgnoreFunctions get set
Definition at line 40 of file AphidSerializer.cs.
 { get; set; }
IgnoreSpecialVariables
bool Components.Aphid.Serialization.AphidSerializer.IgnoreSpecialVariables get set
Definition at line 42 of file AphidSerializer.cs.
 { get; set; }
QuoteToStringResults
bool Components.Aphid.Serialization.AphidSerializer.QuoteToStringResults get set
Definition at line 44 of file AphidSerializer.cs.
 { get; set; }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Serialization/AphidSerializer.cs