Aphid Programming Language: Components.Aphid.Interpreter.AphidScriptOptimizer Class Reference
Components.Aphid.Interpreter.AphidScriptOptimizer Class Reference
Public Member Functions
AphidScriptOptimizer (AphidLoader loader)
List< AphidExpression > Optimize (string script)
List< AphidExpression > Optimize (List< AphidExpression > ast)
Detailed Description
Definition at line 11 of file AphidScriptOptimizer.cs.
Constructor & Destructor Documentation
AphidScriptOptimizer()
Components.Aphid.Interpreter.AphidScriptOptimizer.AphidScriptOptimizer (AphidLoader loader)
Definition at line 15 of file AphidScriptOptimizer.cs.
         {
             _loader = loader;
         }
Member Function Documentation
Optimize() [1/2]
List<AphidExpression> Components.Aphid.Interpreter.AphidScriptOptimizer.Optimize (string script)
Definition at line 20 of file AphidScriptOptimizer.cs.
References ast, Components.Aphid.Parser.AphidParser.Parse(), and script.
         {
             var ast = AphidParser.Parse(script, isTextDocument: false);
             return Optimize(ast);
         }
Optimize() [2/2]
List<AphidExpression> Components.Aphid.Interpreter.AphidScriptOptimizer.Optimize (List< AphidExpression > ast)
Definition at line 27 of file AphidScriptOptimizer.cs.
References ast, Components.Aphid.Interpreter.AphidLoader.FindScriptFile(), is, and Components.Aphid.Parser.StringParser.Parse().
         {
             var optimizedAst = new List<AphidExpression>();
             foreach (var exp in ast)
             {
                 var loadExp = exp as LoadScriptExpression;
                 if (loadExp != null && loadExp.FileExpression is StringExpression)
                 {
                     var filename = StringParser.Parse(((StringExpression)loadExp.FileExpression).Value);
                     filename = _loader.FindScriptFile(null, filename);
                     var childAst = Optimize(File.ReadAllText(filename));
                     optimizedAst.AddRange(childAst);
                 }
                 else
                 {
                     optimizedAst.Add(exp);
                 }
             }
             return optimizedAst;
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Interpreter/AphidScriptOptimizer.cs