Aphid Programming Language: Components.EnvironmentHelper Class Reference
Components.EnvironmentHelper Class Reference
Static Public Member Functions
static string GetArgString ()
static string GetArchitecture ()
static bool IsX86 ()
static bool IsAmd64 ()
Detailed Description
Definition at line 9 of file EnvironmentHelper.cs.
Member Function Documentation
GetArchitecture()
static string Components.EnvironmentHelper.GetArchitecture () static
Definition at line 23 of file EnvironmentHelper.cs.
Referenced by Components.EnvironmentHelper.IsAmd64(), and Components.EnvironmentHelper.IsX86().
         {
             return Environment.GetEnvironmentVariable(architectureVariable);
         }
GetArgString()
static string Components.EnvironmentHelper.GetArgString () static
Definition at line 15 of file EnvironmentHelper.cs.
References x.
         {
             return Environment
                 .GetCommandLineArgs()
                 .Select(x => !x.Any(Char.IsWhiteSpace) ? x : "\"" + x + "\"")
                 .Join(" ");
         }
IsAmd64()
static bool Components.EnvironmentHelper.IsAmd64 () static
Definition at line 33 of file EnvironmentHelper.cs.
References Components.EnvironmentHelper.GetArchitecture().
         {
             return GetArchitecture().ToLower() == _amd64;
         }
IsX86()
static bool Components.EnvironmentHelper.IsX86 () static
Definition at line 28 of file EnvironmentHelper.cs.
References Components.EnvironmentHelper.GetArchitecture().
Referenced by Components.Cypress.NativeDebugger.NativeDebugger().
         {
             return GetArchitecture().ToLower() == _x86;
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/External/Common/EnvironmentHelper.cs