Aphid Programming Language: Components.Aphid.TypeSystem.AphidObject Class Reference
Components.Aphid.TypeSystem.AphidObject Class Reference
Public Member Functions
AphidObject ()
AphidObject (object value)
AphidObject (object value, AphidObject parent)
override string ToString ()
List< AphidObject > GetList ()
IEnumerable< string > GetStringList ()
string GetString ()
decimal GetNumber ()
bool GetBool ()
AphidFunction GetFunction ()
string GetValueType ()
string GetValueType (bool includeClrTypes)
void Bind (object obj, bool invokeEvents=true)
T ConvertTo< T > ()
TElement [] ConvertToArray< TElement > ()
void CopyTo (AphidObject obj)
AphidObject Resolve (AphidInterpreter interpreter, string key, string errorMessage=null)
bool TryResolve (string key, out AphidObject value)
bool TryResolveAndRemove (string key)
AphidObject TryResolveParent (string key)
bool IsDefined (string key)
bool ResolveBool (string key)
bool IsAphidType ()
AphidObject [] FlattenScope ()
string GetTypeName ()
override bool Equals (object obj)
AphidObject CreateChild ()
Static Public Member Functions
static AphidObject ConvertFrom (Type t, object o)
static AphidObject ConvertFrom< T > (T o)
static bool IsAphidType (object obj)
Properties
bool IsScalar [get, set]
bool IsComplex [get, set]
bool IsComplexitySet [get]
int OwnerThread [get]
AphidObject Parent [get, set]
object Value [get, set]
Detailed Description
Definition at line 10 of file AphidObject.cs.
Constructor & Destructor Documentation
AphidObject() [1/3]
Components.Aphid.TypeSystem.AphidObject.AphidObject ()
Definition at line 47 of file AphidObject.cs.
         {
             OwnerThread = Thread.CurrentThread.ManagedThreadId;
         }
AphidObject() [2/3]
Components.Aphid.TypeSystem.AphidObject.AphidObject (object value)
Definition at line 52 of file AphidObject.cs.
References value.
             : this(isScalar: true)
         {
             Value = value;
         }
AphidObject() [3/3]
Components.Aphid.TypeSystem.AphidObject.AphidObject (object value, AphidObject parent)
Definition at line 58 of file AphidObject.cs.
References value.
             : this(isScalar: true)
         {
             Value = value;
             Parent = parent;
         }
Member Function Documentation
Bind()
void Components.Aphid.TypeSystem.AphidObject.Bind (object obj, bool invokeEvents = true)
Definition at line 147 of file AphidObject.cs.
References obj, Components.Aphid.TypeSystem.IAphidBindable.OnBinding(), p, and x.
Referenced by LLex.AlxFile.From().
         {
             var bindable = obj as IAphidBindable;
             if (invokeEvents && bindable != null)
             {
                 bindable.OnBinding(this);
             }
             var kvps = GetPropertyValuePairs(obj);
             foreach (var p in kvps)
             {
                 if (TrySetProperty(p.Property, obj, p.Value))
                 {
                     continue;
                 }
                 else if (p.Property.PropertyType.IsArray)
                 {
                     var elementType = p.Property.PropertyType.GetElementType();
                     var srcArray = p.Value
                         .GetList()
                         .Select(x =>
{
                             var element = Activator.CreateInstance(elementType);
                             x.Bind(element);
                             return element;
                         })
                         .ToArray();
                     var destArray = Array.CreateInstance(elementType, srcArray.Length);
                     Array.Copy(srcArray, destArray, srcArray.Length);
                     p.Property.SetValue(obj, destArray, null);
                 }
                 else if (p.Property.PropertyType.IsEnum)
                 {
                     var val = Enum.ToObject(p.Property.PropertyType, Convert.ToInt64(p.Value.Value));
                     p.Property.SetValue(obj, val, null);
                 }
                 else if (p.Value.Count == 0 ||
                     p.Property.PropertyType == typeof(bool) ||
                     p.Property.PropertyType == typeof(string) ||
                     p.Property.PropertyType == typeof(decimal))
                 {
                     p.Property.SetValue(obj, p.Value.Value, null);
                 }
                 else
                 {
                     var childObj = Activator.CreateInstance(p.Property.PropertyType);
                     p.Value.Bind(childObj);
                     p.Property.SetValue(obj, childObj, null);
                 }
             }
             if (invokeEvents && bindable != null)
             {
                 bindable.OnBound(this);
             }
         }
ConvertFrom()
static AphidObject Components.Aphid.TypeSystem.AphidObject.ConvertFrom (Type t, object o) static
Definition at line 247 of file AphidObject.cs.
References byte, items, p, properties, and t.
Referenced by Components.Aphid.Library.Net.UdpLibrary.UdpReceive(), and Components.Aphid.Library.Net.UdpLibrary.UdpSend().
         {
             IEnumerable enumerable;
             if (t == typeof(sbyte) ||
                 t == typeof(byte) ||
                 t == typeof(short) ||
                 t == typeof(ushort) ||
                 t == typeof(int) ||
                 t == typeof(uint) ||
                 t == typeof(long) ||
                 t == typeof(ulong) ||
                 t == typeof(float) ||
                 t == typeof(double))
             {
                 return new AphidObject(Convert.ToDecimal(o));
             }
             else if (t.IsPrimitive || t == typeof(string) || t == typeof(decimal))
             {
                 return new AphidObject(o);
             }
             else if ((enumerable = o as IEnumerable) != null)
             {
                 var items = new List<AphidObject>();
                 foreach (var element in enumerable)
                 {
                     items.Add(ConvertFrom(element.GetType(), element));
                 }
                 return new AphidObject(items);
             }
             else
             {
                 var ao = new AphidObject();
                 var properties = GetPropertyInfo(o);
                 foreach (var p in properties)
                 {
                     var val = ConvertFrom(
                         p.Property.PropertyType,
                         p.Property.GetValue(o, null));
                     ao.Add(p.Name, val);
                 }
                 return ao;
             }
         }
ConvertFrom< T >()
static AphidObject Components.Aphid.TypeSystem.AphidObject.ConvertFrom< T > (T o) static
Definition at line 297 of file AphidObject.cs.
         {
             return ConvertFrom(typeof(T), o);
         }
ConvertTo< T >()
T Components.Aphid.TypeSystem.AphidObject.ConvertTo< T > ()
Type Constraints
T : new()
Definition at line 207 of file AphidObject.cs.
References obj.
                     : new()
         {
             var obj = new T();
             Bind(obj);
             return obj;
         }
ConvertToArray< TElement >()
TElement [] Components.Aphid.TypeSystem.AphidObject.ConvertToArray< TElement > ()
Type Constraints
TElement : new()
Definition at line 216 of file AphidObject.cs.
References i.
                            : new()
         {
             var list = GetList();
             var array = new TElement[list.Count];
             for (int i = 0; i < list.Count; i++)
             {
                 array[i] = list[i].ConvertTo<TElement>();
             }
             return array;
         }
CopyTo()
void Components.Aphid.TypeSystem.AphidObject.CopyTo (AphidObject obj)
Definition at line 230 of file AphidObject.cs.
References obj.
         {
             obj.Value = Value;
             foreach (var nvp in this)
             {
                 if (obj.ContainsKey(nvp.Key))
                 {
                     obj[nvp.Key] = nvp.Value;
                 }
                 else
                 {
                     obj.Add(nvp.Key, nvp.Value);
                 }
             }
         }
CreateChild()
AphidObject Components.Aphid.TypeSystem.AphidObject.CreateChild ()
Definition at line 427 of file AphidObject.cs.
         {
             return new AphidObject(null, this);
         }
Equals()
override bool Components.Aphid.TypeSystem.AphidObject.Equals (object obj)
Definition at line 422 of file AphidObject.cs.
References obj.
         {
             return base.Equals(obj);
         }
FlattenScope()
AphidObject [] Components.Aphid.TypeSystem.AphidObject.FlattenScope ()
Definition at line 389 of file AphidObject.cs.
References scope.
         {
             var scope = this;
             var scopes = new List<AphidObject> { this };
             while ((scope = scope.Parent) != null)
             {
                 scopes.Add(scope);
             }
             return scopes.ToArray();
         }
GetBool()
bool Components.Aphid.TypeSystem.AphidObject.GetBool ()
Definition at line 96 of file AphidObject.cs.
         {
             return (bool)Value;
         }
GetFunction()
AphidFunction Components.Aphid.TypeSystem.AphidObject.GetFunction ()
Definition at line 101 of file AphidObject.cs.
         {
             return Value as AphidFunction;
         }
GetList()
List<AphidObject> Components.Aphid.TypeSystem.AphidObject.GetList ()
Definition at line 76 of file AphidObject.cs.
         {
             return Value as List<AphidObject>;
         }
GetNumber()
decimal Components.Aphid.TypeSystem.AphidObject.GetNumber ()
Definition at line 91 of file AphidObject.cs.
         {
             return (decimal)Value;
         }
GetString()
string Components.Aphid.TypeSystem.AphidObject.GetString ()
Definition at line 86 of file AphidObject.cs.
References string.
         {
             return Value as string;
         }
GetStringList()
IEnumerable<string> Components.Aphid.TypeSystem.AphidObject.GetStringList ()
Definition at line 81 of file AphidObject.cs.
References x.
         {
             return GetList().Select(x => x.GetString());
         }
GetTypeName()
string Components.Aphid.TypeSystem.AphidObject.GetTypeName ()
Definition at line 402 of file AphidObject.cs.
References Count.
         {
             return Count > 0 ? AphidType.Object :
                 Value != null ? GetValueType() :
                 AphidType.Null;
         }
GetValueType() [1/2]
string Components.Aphid.TypeSystem.AphidObject.GetValueType ()
Definition at line 106 of file AphidObject.cs.
         {
             return GetValueType(true);
         }
GetValueType() [2/2]
string Components.Aphid.TypeSystem.AphidObject.GetValueType (bool includeClrTypes)
Definition at line 111 of file AphidObject.cs.
References Components.Aphid.TypeSystem.AphidAlias.Resolve(), t, Type, and Components.Aphid.TypeSystem.AphidType.Unknown.
         {
             Type t;
             return Value != null ?
                 AphidAlias.Resolve(t = Value.GetType()) ??
                     (includeClrTypes ? t.FullName : AphidType.Unknown) :
                 AphidType.Null;
         }
IsAphidType() [1/2]
bool Components.Aphid.TypeSystem.AphidObject.IsAphidType ()
Definition at line 384 of file AphidObject.cs.
Referenced by Components.Aphid.Interpreter.AphidInterpreter.WrapInteropValue().
         {
             return IsAphidType(this.Value);
         }
IsAphidType() [2/2]
static bool Components.Aphid.TypeSystem.AphidObject.IsAphidType (object obj) static
Definition at line 409 of file AphidObject.cs.
References is, and obj.
         {
             return
                 obj == null ||
                 obj is string ||
                 obj is decimal ||
                 obj is bool ||
                 obj is List<AphidObject> ||
                 obj is AphidObject ||
                 obj is AphidFunction ||
                 obj is AphidInteropFunction;
         }
IsDefined()
bool Components.Aphid.TypeSystem.AphidObject.IsDefined (string key)
Definition at line 367 of file AphidObject.cs.
References out.
         {
             AphidObject v;
             return TryResolve(key, out v);
         }
Resolve()
AphidObject Components.Aphid.TypeSystem.AphidObject.Resolve (AphidInterpreter interpreter, string key, string errorMessage = null)
Definition at line 302 of file AphidObject.cs.
References Components.Aphid.Interpreter.AphidInterpreter.CreateValueException(), obj, and out.
         {
             AphidObject obj;
             if (!TryResolve(key, out obj))
             {
                 throw errorMessage == null ?
                     interpreter.CreateValueException(this, "Could not resolve property {0}", key) :
                     interpreter.CreateValueException(this, errorMessage);
             }
             return obj;
         }
ResolveBool()
bool Components.Aphid.TypeSystem.AphidObject.ResolveBool (string key)
Definition at line 374 of file AphidObject.cs.
References out, and value.
         {
             AphidObject value;
             return
                 TryResolve(key, out value) &&
                 value.Value != null &&
                 Convert.ToBoolean(value.Value);
         }
ToString()
override string Components.Aphid.TypeSystem.AphidObject.ToString ()
Definition at line 71 of file AphidObject.cs.
References Count.
         {
             return string.Format("{{ {0}, {1} members }}", Value, Count);
         }
TryResolve()
bool Components.Aphid.TypeSystem.AphidObject.TryResolve (string key, out AphidObject value)
Definition at line 316 of file AphidObject.cs.
References out, and value.
Referenced by AphidUI.ViewModels.AphidReplViewModel.Dump(), Components.Aphid.Interpreter.AphidInterpreter.GetScriptFilename(), and Components.Aphid.Tests.Integration.Shared.ScriptedTests.RunTestScript().
         {
             if (TryGetValue(key, out value))
             {
                 return true;
             }
             else if (Parent != null)
             {
                 return Parent.TryResolve(key, out value);
             }
             else
             {
                 return false;
             }
         }
TryResolveAndRemove()
bool Components.Aphid.TypeSystem.AphidObject.TryResolveAndRemove (string key)
Definition at line 332 of file AphidObject.cs.
         {
             if (ContainsKey(key))
             {
                 Remove(key);
                 return true;
             }
             else if (Parent != null)
             {
                 return Parent.TryResolveAndRemove(key);
             }
             else
             {
                 return false;
             }
         }
TryResolveParent()
AphidObject Components.Aphid.TypeSystem.AphidObject.TryResolveParent (string key)
Definition at line 349 of file AphidObject.cs.
References out, and value.
         {
             AphidObject value;
             if (TryGetValue(key, out value))
             {
                 return this;
             }
             else if (Parent != null)
             {
                 return Parent.TryResolveParent(key);
             }
             else
             {
                 return null;
             }
         }
Property Documentation
IsComplex
bool Components.Aphid.TypeSystem.AphidObject.IsComplex get set
Definition at line 27 of file AphidObject.cs.
         {
             get { return _isComplex; }
             set
             {
                 _isComplex = value;
                 _isScalar = !value;
             }
         }
IsComplexitySet
bool Components.Aphid.TypeSystem.AphidObject.IsComplexitySet get
Definition at line 37 of file AphidObject.cs.
         {
             get { return _isScalar || _isComplex; }
         }
IsScalar
bool Components.Aphid.TypeSystem.AphidObject.IsScalar get set
Definition at line 15 of file AphidObject.cs.
         {
             get { return _isScalar; }
             set
             {
                 _isScalar = value;
                 _isComplex = !value;
             }
         }
OwnerThread
int Components.Aphid.TypeSystem.AphidObject.OwnerThread get
Definition at line 41 of file AphidObject.cs.
 { get; private set; }
Parent
AphidObject Components.Aphid.TypeSystem.AphidObject.Parent get set
Definition at line 43 of file AphidObject.cs.
 { get; set; }
Value
object Components.Aphid.TypeSystem.AphidObject.Value get set
Definition at line 45 of file AphidObject.cs.
Referenced by Components.Aphid.TypeSystem.ValueHelper< TExpected >.DeepUnwrap(), Components.Aphid.UI.AphidCli.DumpExpression(), Components.Aphid.Library.StandardLibrary.Extend(), Components.Aphid.Interpreter.AphidInterpreter.GetImports(), Components.Aphid.TypeSystem.ValueHelper< TExpected >.IsComplexAphidObject(), Components.Aphid.Library.EnvironmentLibrary.Kill(), Components.Aphid.Library.ThreadingLibrary.Lock(), Components.Aphid.Library.StandardLibrary.SetValue(), Components.Aphid.Library.Net.UdpLibrary.UdpSend(), and Components.Aphid.TypeSystem.ValueHelper< TExpected >.Unwrap().
 { get; set; }
The documentation for this class was generated from the following files:
c:/source/Aphid/Components.Aphid/TypeSystem/AphidObject.cs
c:/source/Aphid/Components.Aphid/TypeSystem/AphidObject.g.cs