Aphid Programming Language: Components.Aphid.Lexer.AphidLexer Class Reference
Components.Aphid.Lexer.AphidLexer Class Reference
Public Member Functions
int GetMode ()
void SetMode (int m)
void SetCodeMode ()
void SetTextMode ()
void SetShellMode ()
AphidLexer ()
AphidLexer (string text)
List< AphidToken > GetTokens ()
List< AphidToken > GetAllTokens ()
Static Public Member Functions
static List< AphidToken > GetTokens (string text)
static List< AphidToken > GetAllTokens (string text)
static AphidToken GetToken (string text)
static AphidToken GetToken (string text, int offset)
static AphidTokenType GetTokenType (string text)
static AphidTokenType GetTokenType (string text, int offset)
Properties
string Text [get, set]
Detailed Description
Definition at line 9 of file AphidLexer.cs.
Constructor & Destructor Documentation
AphidLexer() [1/2]
Components.Aphid.Lexer.AphidLexer.AphidLexer ()
Definition at line 5822 of file AphidParser.g.cs.
         {
         }
AphidLexer() [2/2]
Components.Aphid.Lexer.AphidLexer.AphidLexer (string text)
Definition at line 5826 of file AphidParser.g.cs.
References text.
         {
             Text = text;
         }
Member Function Documentation
GetAllTokens() [1/2]
static List<AphidToken> Components.Aphid.Lexer.AphidLexer.GetAllTokens (string text) static
Definition at line 41 of file AphidLexer.cs.
References Components.Aphid.Lexer.AphidLexer.GetAllTokens(), and text.
Referenced by AphidUI.CodeViewer.AppendCode(), Components.Aphid.Lexer.AphidLexer.GetAllTokens(), Components.Aphid.Tests.Integration.Shared.AphidTests.GetTokens(), Components.Aphid.UI.AphidSyntaxHighlighter.Highlight(), and Components.Aphid.VSPackage.AphidLanguageService.ParseSource().
         {
             return new AphidLexer(text).GetAllTokens();
         }
GetAllTokens() [2/2]
List<AphidToken> Components.Aphid.Lexer.AphidLexer.GetAllTokens ()
Definition at line 12808 of file AphidParser.g.cs.
References index, lexeme, text, and tokens.
         {
             charIndex = -1;
             AphidTokenType tokenType;
             int lastIndex = -1;
             var tokens = new List<AphidToken>();
             while ((tokenType = GetToken()) != AphidTokenType.EndOfFile)
             {
                 var index = lastIndex + 1;
                 var lexeme = text.Substring(index, charIndex - lastIndex);
                 tokens.Add(new AphidToken(tokenType, lexeme, index));
                 lastIndex = charIndex;
             }
             return tokens;
         }
GetMode()
int Components.Aphid.Lexer.AphidLexer.GetMode ()
Definition at line 11 of file AphidLexer.cs.
         {
             return mode;
         }
GetToken() [1/2]
static AphidToken Components.Aphid.Lexer.AphidLexer.GetToken (string text) static
Definition at line 46 of file AphidLexer.cs.
References text.
         {
             return GetToken(text, 0);
         }
GetToken() [2/2]
static AphidToken Components.Aphid.Lexer.AphidLexer.GetToken (string text, int offset) static
Definition at line 51 of file AphidLexer.cs.
References index, lexeme, lexer, and text.
         {
             var lexer = new AphidLexer(text);
             lexer.charIndex = offset - 1;
             var type = lexer.GetToken();
             var index = lexer.lastIndex + 1;
             var lexeme = text.Substring(index, lexer.charIndex - lexer.lastIndex);
             return new AphidToken(type, lexeme, index);
         }
GetTokens() [1/2]
static List<AphidToken> Components.Aphid.Lexer.AphidLexer.GetTokens (string text) static
Definition at line 36 of file AphidLexer.cs.
References Components.Aphid.Lexer.AphidLexer.GetTokens(), and text.
Referenced by Components.Aphid.Lexer.TokenHelper.GetBraces(), Components.Aphid.Lexer.AphidLexer.GetTokens(), Components.Aphid.UI.AphidScopeObjectAutocompletionSource.GetWords(), and Components.Aphid.UI.AphidScanner.Tokenize().
         {
             return new AphidLexer(text).GetTokens();
         }
GetTokens() [2/2]
List<AphidToken> Components.Aphid.Lexer.AphidLexer.GetTokens ()
Definition at line 12781 of file AphidParser.g.cs.
References index, lexeme, text, and tokens.
         {
             charIndex = -1;
             AphidTokenType tokenType;
             int lastIndex = -1;
             var tokens = new List<AphidToken>();
             while ((tokenType = GetToken()) != AphidTokenType.EndOfFile)
             {
                 if (tokenType != AphidTokenType.WhiteSpace && tokenType != AphidTokenType.Comment)
                 {
                     var index = lastIndex + 1;
                     var lexeme = text.Substring(index, charIndex - lastIndex);
                     tokens.Add(new AphidToken(tokenType, lexeme, index));
                 }
                 lastIndex = charIndex;
             }
             return tokens;
         }
GetTokenType() [1/2]
static AphidTokenType Components.Aphid.Lexer.AphidLexer.GetTokenType (string text) static
Definition at line 62 of file AphidLexer.cs.
References text.
         {
             return GetTokenType(text, 0);
         }
GetTokenType() [2/2]
static AphidTokenType Components.Aphid.Lexer.AphidLexer.GetTokenType (string text, int offset) static
Definition at line 67 of file AphidLexer.cs.
References lexer, and text.
         {
             var lexer = new AphidLexer(text);
             lexer.charIndex = offset - 1;
             return lexer.GetToken();
         }
SetCodeMode()
void Components.Aphid.Lexer.AphidLexer.SetCodeMode ()
Definition at line 21 of file AphidLexer.cs.
         {
             mode = 0;
         }
SetMode()
void Components.Aphid.Lexer.AphidLexer.SetMode (int m)
Definition at line 16 of file AphidLexer.cs.
         {
             mode = m;
         }
SetShellMode()
void Components.Aphid.Lexer.AphidLexer.SetShellMode ()
Definition at line 31 of file AphidLexer.cs.
         {
             mode = 2;
         }
SetTextMode()
void Components.Aphid.Lexer.AphidLexer.SetTextMode ()
Definition at line 26 of file AphidLexer.cs.
         {
             mode = 1;
         }
Property Documentation
Text
string Components.Aphid.Lexer.AphidLexer.Text get set
Definition at line 5803 of file AphidParser.g.cs.
         {
             get { return text; }
             set
             {
                 text = value;
                 lastIndex = text.Length - 1;
             }
         }
The documentation for this class was generated from the following files:
c:/source/Aphid/Components.Aphid/Lexer/AphidLexer.cs
c:/source/Aphid/Components.Aphid/Parser/AphidParser.g.cs