Aphid Programming Language: Components.Aphid.TypeSystem.AphidAlias Class Reference
Components.Aphid.TypeSystem.AphidAlias Class Reference
Static Public Member Functions
static string Resolve (Type type)
static string Resolve (string name)
Detailed Description
Definition at line 9 of file AphidAlias.cs.
Member Function Documentation
Resolve() [1/2]
static string Components.Aphid.TypeSystem.AphidAlias.Resolve (Type type) static
Definition at line 11 of file AphidAlias.cs.
Referenced by Components.Aphid.TypeSystem.TypeExtender.Extend(), Components.Aphid.TypeSystem.TypeExtender.GetInteropName(), Components.Aphid.TypeSystem.AphidType.GetName(), and Components.Aphid.TypeSystem.AphidObject.GetValueType().
         {
             return Resolve(type.Name);
         }
Resolve() [2/2]
static string Components.Aphid.TypeSystem.AphidAlias.Resolve (string name) static
Definition at line 16 of file AphidAlias.cs.
References name, and Components.Aphid.TypeSystem.AphidType.Unknown.
         {
             switch (name)
             {
                 case "List`1":
                 case AphidType.List:
                     return AphidType.List;
                 case "Decimal":
                 case AphidType.Number:
                     return AphidType.Number;
                 case "String":
                 case AphidType.String:
                     return AphidType.String;
                 case "Boolean":
                 case AphidType.Boolean:
                     return AphidType.Boolean;
                 case "AphidObject":
                 case AphidType.Object:
                     return AphidType.Object;
                 case "AphidFunction":
                 case AphidType.Function:
                     return AphidType.Function;
                 case "AphidInteropFunction":
                 case AphidType.InteropFunction:
                     return AphidType.InteropFunction;
                 case "AphidInteropPartialFunction":
                 case AphidType.PartialFunction:
                     return AphidType.PartialFunction;
                 case "AphidFunctionComposition":
                 case AphidType.FunctionComposition:
                     return AphidType.FunctionComposition;
                 case AphidType.Unknown:
                     return AphidType.Unknown;
                 default:
                     return null;
             }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/TypeSystem/AphidAlias.cs