Aphid Programming Language: Components.Aphid.Lexer.TokenHelper Class Reference
Components.Aphid.Lexer.TokenHelper Class Reference
Static Public Member Functions
static Tuple< int, int > GetIndexPosition (string text, int index)
static int GetIndex (string text, int line, int col)
static int [][] GetBraces (string text, int line, int col)
static string GetCodeExcerpt (string code, AphidToken token, int surroundingLines=4)
static string GetCodeExcerpt (string code, int index, int surroundingLines=4)
Detailed Description
Definition at line 11 of file TokenHelper.cs.
Member Function Documentation
GetBraces()
static int [][] Components.Aphid.Lexer.TokenHelper.GetBraces (string text, int line, int col) static
Definition at line 143 of file TokenHelper.cs.
References depth, Components.Aphid.Lexer.TokenHelper.GetIndex(), Components.Aphid.Lexer.TokenHelper.GetIndexPosition(), Components.Aphid.Lexer.AphidLexer.GetTokens(), i, index, text, and tokens.
Referenced by Components.Aphid.VSPackage.AphidLanguageService.ParseSource().
         {
             var index = TokenHelper.GetIndex(text, line, col);
             var str = text.Substring(index);
             var tokens = new AphidLexer(str).GetTokens();
             var startBrace = tokens[0].TokenType;
             AphidTokenType[] braces;
             switch (tokens[0].TokenType)
             {
                 case AphidTokenType.LeftBrace:
                 case AphidTokenType.RightBrace:
                     braces = new[] { AphidTokenType.LeftBrace, AphidTokenType.RightBrace };
                     break;
                 case AphidTokenType.LeftParenthesis:
                 case AphidTokenType.RightParenthesis:
                     braces = new[] { AphidTokenType.LeftParenthesis, AphidTokenType.RightParenthesis };
                     break;
                 case AphidTokenType.LeftBracket:
                 case AphidTokenType.RightBracket:
                     braces = new[] { AphidTokenType.LeftBracket, AphidTokenType.RightBracket };
                     break;
                 default:
                     throw new InvalidOperationException();
             }
             var depth = 1;
             if (startBrace == braces[0])
             {
                 var rightBraceIndex = -1;
                 for (int i = 1; i < tokens.Count; i++)
                 {
                     if (tokens[i].TokenType == braces[0])
                     {
                         depth++;
                     }
                     else if (tokens[i].TokenType == braces[1])
                     {
                         depth--;
                     }
                     if (depth == 0)
                     {
                         rightBraceIndex = index + tokens[i].Index;
                         break;
                     }
                 }
                 if (rightBraceIndex != -1)
                 {
                     var rightLineCol = TokenHelper.GetIndexPosition(text, rightBraceIndex);
                     return new[]
                     {
                         new[] { line, col },
                         new[] { rightLineCol.Item1, rightLineCol.Item2 },
                     };
                 }
             }
             else if (startBrace == braces[1])
             {
                 depth = -1;
                 var leftBraceIndex = -1;
                 str = text.Remove(index);
                 tokens = new AphidLexer(str).GetTokens();
                 for (int i = tokens.Count - 1; i >= 0; i--)
                 {
                     if (tokens[i].TokenType == braces[0])
                     {
                         depth++;
                     }
                     else if (tokens[i].TokenType == braces[1])
                     {
                         depth--;
                     }
                     if (depth == 0)
                     {
                         leftBraceIndex = tokens[i].Index;
                         break;
                     }
                 }
                 if (leftBraceIndex != -1)
                 {
                     var leftLineCol = TokenHelper.GetIndexPosition(text, leftBraceIndex);
                     return new[]
                     {
                         new[] { leftLineCol.Item1, leftLineCol.Item2 },
                         new[] { line, col },
                     };
                 }
             }
             else
             {
                 throw new InvalidOperationException();
             }
             return null;
         }
GetCodeExcerpt() [1/2]
static string Components.Aphid.Lexer.TokenHelper.GetCodeExcerpt (string code, AphidToken token, int surroundingLines = 4) static
Definition at line 252 of file TokenHelper.cs.
References code, and token.
Referenced by Components.Aphid.Parser.ParserErrorMessage.Create().
         {
             return GetCodeExcerpt(code, token.Index, surroundingLines);
         }
GetCodeExcerpt() [2/2]
static string Components.Aphid.Lexer.TokenHelper.GetCodeExcerpt (string code, int index, int surroundingLines = 4) static
Definition at line 257 of file TokenHelper.cs.
References code, i, index, sb, and x.
         {
             if (string.IsNullOrWhiteSpace(code) || index == -1)
             {
                 return null;
             }
             code = code.Replace("\r\n", "\n").Replace('\r', '\n').Replace("\n", "\r\n");
             var matches = Regex.Matches(code, @"\r\n").OfType<Match>().ToArray();
             var firstAfter = matches.FirstOrDefault(x => x.Index > index);
             int line;
             if (firstAfter != null)
             {
                 line = Array.IndexOf(matches, firstAfter);
             }
             else
             {
                 line = matches.Count();
             }
             var lines = code.Split(new[] { "\r\n" }, StringSplitOptions.None);
             var sb = new StringBuilder();
             for (int i = line - surroundingLines; i < line + surroundingLines + 1; i++)
             {
                 if (i > 0 && i < lines.Length)
                 {
                     sb.AppendLine(string.Format("({0}) {1}", i, lines[i]));
                 }
             }
             return sb.ToString();
         }
GetIndex()
static int Components.Aphid.Lexer.TokenHelper.GetIndex (string text, int line, int col) static
Definition at line 72 of file TokenHelper.cs.
References c, i, and text.
Referenced by Components.Aphid.Lexer.TokenHelper.GetBraces(), and Components.Aphid.VSPackage.AphidLanguageService.ParseSource().
         {
             if (line == 0)
             {
                 return col;
             }
             var state = LineState.RegularChar;
             int curLine = 0;
             for (int i = 0; i < text.Length; i++)
             {
                 var c = text[i];
                 switch (state)
                 {
                     case LineState.RegularChar:
                         switch (c)
{
                             case '\r':
                                 state = LineState.ReturnCarriage;
                                 break;
                             case '\n':
                                 curLine++;
                                 if (curLine == line)
{
                                     return i + col + 1;
                                 }
                                 break;
                         }
                         break;
                     case LineState.ReturnCarriage:
                         switch (c)
{
                             case '\r':
                                 for (int j = 0; j < 2; j++)
{
                                     curLine++;
                                     if (curLine == line)
{
                                         return i + col + j;
                                     }
                                 }
                                 break;
                             case '\n':
                                 curLine++;
                                 if (curLine == line)
{
                                     return i + col + 1;
                                 }
                                 state = LineState.RegularChar;
                                 break;
                             default:
                                 state = LineState.RegularChar;
                                 break;
                         }
                         break;
                 }
             }
             return -1;
         }
GetIndexPosition()
static Tuple<int, int> Components.Aphid.Lexer.TokenHelper.GetIndexPosition (string text, int index) static
Definition at line 19 of file TokenHelper.cs.
References c, i, index, and text.
Referenced by Components.Aphid.Parser.ParserErrorMessage.Create(), Components.Aphid.Lexer.TokenHelper.GetBraces(), and Components.Aphid.VSPackage.AphidLanguageService.ParseSource().
         {
             var state = LineState.RegularChar;
             var preceding = text.Remove(index);
             var line = 0;
             var col = 0;
             for (int i = 0; i < preceding.Length; i++)
             {
                 var c = preceding[i];
                 switch (state)
                 {
                     case LineState.RegularChar:
                         switch (c)
{
                             case '\r':
                                 line++;
                                 col = 0;
                                 state = LineState.ReturnCarriage;
                                 break;
                             case '\n':
                                 line++;
                                 col = 0;
                                 break;
                             default:
                                 col++;
                                 break;
                         }
                         break;
                     case LineState.ReturnCarriage:
                         switch (c)
{
                             case '\r':
                                 line++;
                                 col = 0;
                                 break;
                             case '\n':
                                 col = 0;
                                 state = LineState.RegularChar;
                                 break;
                             default:
                                 col++;
                                 state = LineState.RegularChar;
                                 break;
                         }
                         break;
                 }
             }
             return Tuple.Create(line, col);
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Lexer/TokenHelper.cs