Aphid Programming Language: Components.Aphid.VSPackage.AphidLanguageService Class Reference
Components.Aphid.VSPackage.AphidLanguageService Class Reference
Public Member Functions
override string GetFormatFilterList ()
override LanguagePreferences GetLanguagePreferences ()
override IScanner GetScanner (Microsoft.VisualStudio.TextManager.Interop.IVsTextLines buffer)
override AuthoringScope ParseSource (ParseRequest req)
Properties
override string Name [get]
Detailed Description
Definition at line 15 of file AphidLanguageService.cs.
Member Function Documentation
GetFormatFilterList()
override string Components.Aphid.VSPackage.AphidLanguageService.GetFormatFilterList ()
Definition at line 19 of file AphidLanguageService.cs.
         {
             return "Aphid files (*.alx)\n*.alx\n";
         }
GetLanguagePreferences()
override LanguagePreferences Components.Aphid.VSPackage.AphidLanguageService.GetLanguagePreferences ()
Definition at line 24 of file AphidLanguageService.cs.
         {
             return new LanguagePreferences()
             {
                 EnableMatchBracesAtCaret = true,
                 EnableCodeSense = true,
                 CodeSenseDelay = 500,
                 AutoListMembers = true,
                 EnableFormatSelection = true,
                 EnableMatchBraces = true,
                 LineNumbers = true,
                 EnableCommenting = true,
                 EnableShowMatchingBrace = true,
                 IndentStyle = IndentingStyle.Smart,
                 IndentSize = 4,
                 InsertTabs = false,
                 EnableQuickInfo = true,
                 MaxErrorMessages = 100,
                 HighlightMatchingBraceFlags = _HighlightMatchingBraceFlags.HMB_USERECTANGLEBRACES,
             };
         }
GetScanner()
override IScanner Components.Aphid.VSPackage.AphidLanguageService.GetScanner (Microsoft.VisualStudio.TextManager.Interop.IVsTextLines buffer)
Definition at line 46 of file AphidLanguageService.cs.
         {
             return new AphidScanner();
         }
ParseSource()
override AuthoringScope Components.Aphid.VSPackage.AphidLanguageService.ParseSource (ParseRequest req)
Definition at line 103 of file AphidLanguageService.cs.
References Debug, depth, Components.Aphid.Lexer.AphidLexer.GetAllTokens(), Components.Aphid.Lexer.TokenHelper.GetBraces(), Components.Aphid.Lexer.TokenHelper.GetIndex(), Components.Aphid.Lexer.TokenHelper.GetIndexPosition(), i, index, scope, tokens, and x.
         {
             Debug.WriteLine("Parse reason: {0}", req.Reason);
             var scope = new AphidAuthoringScope();
             scope.Identifiers = GetTokens(req.Text)
                 .Where(x => x.TokenType == AphidTokenType.Identifier)
                 .Select(x => x.Lexeme)
                 .Distinct()
                 .ToArray();
             switch (req.Reason)
             {
                 case ParseReason.QuickInfo:
                     break;
                 case ParseReason.MemberSelect:
                     break;
                 case ParseReason.DisplayMemberList:
                     break;
                 case ParseReason.CompleteWord:
                     break;
                 case ParseReason.MatchBraces:
                 case ParseReason.MemberSelectAndHighlightBraces:
                 case ParseReason.HighlightBraces:
                     var braces = TokenHelper.GetBraces(
                         req.Text,
                         req.Line,
                         req.Col - 1);
                     if (braces != null)
                     {
                         req.Sink.MatchPair(CreateSpan(braces[0][0], braces[0][1]), CreateSpan(braces[1][0], braces[1][1]), 1);
                     }
                     var index = TokenHelper.GetIndex(req.Text, req.Line, req.Col - 1);
                     var str = req.Text.Substring(index);
                     var tokens = new AphidLexer(str).GetAllTokens();
                     var depth = 1;
                     var rightBraceIndex = -1;
                     for (int i = 1; i < tokens.Count; i++)
                     {
                         switch (tokens[i].TokenType)
{
                             case AphidTokenType.LeftBrace:
                                 depth++;
                                 break;
                             case AphidTokenType.RightBrace:
                                 depth--;
                                 break;
                         }
                         if (depth == 0)
{
                             rightBraceIndex = index + tokens[i].Index;
                             break;
                         }
                     }
                     if (rightBraceIndex != -1)
                     {
                         var rightLineCol = TokenHelper.GetIndexPosition(req.Text, rightBraceIndex);
                         req.Sink.MatchPair(CreateSpan(req.Line, req.Col - 1), CreateSpan(rightLineCol.Item1, rightLineCol.Item2), 1);
                     }
                     break;
                 case ParseReason.Check:
                     CheckParseRequest(req);
                     break;
                 default:
                     break;
             }
             return scope;
         }
Property Documentation
Name
override string Components.Aphid.VSPackage.AphidLanguageService.Name get
Definition at line 52 of file AphidLanguageService.cs.
         {
             get { return "Aphid"; }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid.VSPackage/AphidLanguageService.cs