Aphid Programming Language: Coywolf.AphidPhpEmitter Class Reference
Coywolf.AphidPhpEmitter Class Reference
Public Member Functions
override string Compile (string filename, List< AphidExpression > ast)
override void Emit (List< AphidExpression > statements)
Protected Member Functions
override void EmitHeader ()
override void BeginStatement (AphidExpression expression)
override void BeginExpression (AphidExpression expression)
override void EndExpression (AphidExpression expression)
override void Emit (AphidExpression expression, bool isStatement=false)
override void EmitGatorOpenExpression (GatorOpenExpression expression, bool isStatement=false)
override void EmitGatorCloseExpression (GatorCloseExpression expression, bool isStatement=false)
override void EmitTextExpression (TextExpression expression, bool isStatement=false)
override void EmitGatorEmitExpression (GatorEmitExpression expression, bool isStatement=false)
override void EmitIdentifierExpression (IdentifierExpression expression, bool isStatement=false)
override void EmitUnaryOperatorExpression (UnaryOperatorExpression expression, bool isStatement=false)
override void EmitBinaryOperatorExpression (BinaryOperatorExpression expression, bool isStatement=false)
override void EmitTernaryOperatorExpression (TernaryOperatorExpression expression, bool isStatement=false)
override void EmitStringExpression (StringExpression expression, bool isStatement=false)
override void EmitFunctionExpression (FunctionExpression expression, bool isStatement=false)
override void EmitPartialFunctionExpression (PartialFunctionExpression expression, bool isStatement=false)
void EmitUsed (List< AphidExpression > args, List< AphidExpression > body)
override void EmitCallExpression (CallExpression expression, bool isStatement=false)
override void EmitForEachExpression (ForEachExpression expression, bool isStatement=false)
override void EmitIfExpression (IfExpression expression, bool isStatement=false)
override void EmitWhileExpression (WhileExpression expression, bool isStatement=false)
override void EmitObjectExpression (ObjectExpression expression, bool isStatement=false)
void EmitClassDeclaration (ObjectExpression classDecl)
void EmitClassMember (ObjectExpression classDecl, BinaryOperatorExpression member)
void EmitEchoStatement (CallExpression expression)
Protected Member Functions inherited from Components.Aphid.Compiler.AphidStringEmitter
void Indent ()
void Unindent ()
string GetTabs ()
void AppendTabs ()
void AppendLine ()
void Append (string format, params object[] args)
void Append (string value)
void Append (object value)
string GetOperator (Dictionary< AphidTokenType, string > table, AphidTokenType op)
virtual string GetUnaryPrefixOperator (AphidTokenType op)
virtual string GetUnaryPostfixOperator (AphidTokenType op)
virtual string GetBinaryOperator (AphidTokenType op)
virtual void EmitNumberExpression (NumberExpression expression, bool isStatement=false)
virtual void EmitNullExpression (NullExpression expression, bool isStatement=false)
virtual void EmitBooleanExpression (BooleanExpression expression, bool isStatement=false)
virtual void EmitArrayExpression (ArrayExpression expression, bool isStatement=false)
virtual void EmitArrayAccessExpression (ArrayAccessExpression expression, bool isStatement=false)
void EmitTuple (IEnumerable< AphidExpression > items, string prefix="", string suffix="")
virtual void EmitBreakExpression (BreakExpression expression, bool isStatement=false)
virtual void EmitDoWhileExpression (DoWhileExpression expression, bool isStatement=false)
virtual void EmitDynamicMemberExpression (DynamicMemberExpression expression, bool isStatement=false)
virtual void EmitExtendExpression (ExtendExpression expression, bool isStatement=false)
virtual void EmitForExpression (ForExpression expression, bool isStatement=false)
virtual void EmitLoadLibraryExpression (LoadLibraryExpression expression, bool isStatement=false)
virtual void EmitLoadScriptExpression (LoadScriptExpression expression, bool isStatement=false)
virtual void EmitPatternExpression (PatternExpression expression, bool isStatement=false)
virtual void EmitPatternMatchingExpression (PatternMatchingExpression expression, bool isStatement=false)
virtual void EmitSwitchCase (SwitchCase expression, bool isStatement=false)
virtual void EmitSwitchExpression (SwitchExpression expression, bool isStatement=false)
virtual void EmitThisExpression (ThisExpression expression, bool isStatement=false)
virtual void EmitTryExpression (TryExpression expression, bool isStatement=false)
virtual void EndStatement (AphidExpression expression)
Additional Inherited Members
Protected Attributes inherited from Components.Aphid.Compiler.AphidStringEmitter
StringBuilder _out = new StringBuilder()
Properties inherited from Components.Aphid.Compiler.AphidStringEmitter
Stack< List< AphidExpression > > Scope [get]
Detailed Description
Definition at line 14 of file AphidPhpEmitter.cs.
Member Function Documentation
BeginExpression()
override void Coywolf.AphidPhpEmitter.BeginExpression (AphidExpression expression) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 83 of file AphidPhpEmitter.cs.
References expression.
         {
             if (_isPhp && expression.Type == AphidExpressionType.TextExpression)
             {
                 //Append("?>");
                 _isPhp = false;
             }
             else if (expression.Type == AphidExpressionType.GatorEmitExpression)
             {
                 if (_isPhp)
                 {
                     //Append("?>");
                 }
                 else
                 {
                     _isPhp = true;
                 }
             }
             else if (!_isPhp &&
                 expression.Type != AphidExpressionType.TextExpression &&
                 expression.Type != AphidExpressionType.GatorEmitExpression)
             {
                 //Append("<?php\r\n");
                 _isPhp = true;
             }
             base.BeginExpression(expression);
         }
BeginStatement()
override void Coywolf.AphidPhpEmitter.BeginStatement (AphidExpression expression) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 70 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), expression, and Components.Aphid.Compiler.AphidStringEmitter.GetTabs().
         {
             if (expression.Type != AphidExpressionType.GatorEmitExpression &&
                 expression.Type != AphidExpressionType.GatorOpenExpression &&
                 expression.Type != AphidExpressionType.GatorCloseExpression &&
                 expression.Type != AphidExpressionType.TextExpression)
             {
                 Append(GetTabs());
             }
             base.BeginStatement(expression);
         }
Compile()
override string Coywolf.AphidPhpEmitter.Compile (string filename, List< AphidExpression > ast) virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 45 of file AphidPhpEmitter.cs.
References ast.
         {
             var mutators = new AphidMutator[]
             {
                 new IncludeMutator(),
                 new AphidMacroMutator(),
                 new PartialOperatorMutator(),
                 new PipelineToCallMutator(),
             };
             foreach (var mutator in mutators)
             {
                 ast = mutator.MutateRecursively(ast);
             }
             return base.Compile(filename, ast);
         }
Emit() [1/2]
override void Coywolf.AphidPhpEmitter.Emit (List< AphidExpression > statements) virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 122 of file AphidPhpEmitter.cs.
Referenced by Coywolf.AphidPhpEmitter.EmitBinaryOperatorExpression(), Coywolf.AphidPhpEmitter.EmitCallExpression(), Coywolf.AphidPhpEmitter.EmitClassMember(), Coywolf.AphidPhpEmitter.EmitForEachExpression(), Coywolf.AphidPhpEmitter.EmitFunctionExpression(), Coywolf.AphidPhpEmitter.EmitGatorEmitExpression(), Coywolf.AphidPhpEmitter.EmitIfExpression(), Coywolf.AphidPhpEmitter.EmitObjectExpression(), Coywolf.AphidPhpEmitter.EmitPartialFunctionExpression(), Coywolf.AphidPhpEmitter.EmitTernaryOperatorExpression(), Coywolf.AphidPhpEmitter.EmitUnaryOperatorExpression(), and Coywolf.AphidPhpEmitter.EmitWhileExpression().
         {
             base.Emit(statements);
             if (!_isPhp)
             {
                 _isPhp = true;
                 //Append("<?php ");
             }
         }
Emit() [2/2]
override void Coywolf.AphidPhpEmitter.Emit (AphidExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 133 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), and expression.
         {
             base.Emit(expression, isStatement);
             if (isStatement &&
                 expression.Type != AphidExpressionType.TextExpression &&
                 expression.Type != AphidExpressionType.GatorOpenExpression &&
                 expression.Type != AphidExpressionType.GatorCloseExpression &&
                 expression.Type != AphidExpressionType.GatorEmitExpression &&
                 expression.Type != AphidExpressionType.IfExpression &&
                 expression.Type != AphidExpressionType.WhileExpression &&
                 expression.Type != AphidExpressionType.ForEachExpression)
             {
                 Append(";\r\n");
             }
         }
EmitBinaryOperatorExpression()
override void Coywolf.AphidPhpEmitter.EmitBinaryOperatorExpression (BinaryOperatorExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 247 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Coywolf.AphidPhpEmitter.Emit(), and expression.
         {
             switch (expression.Operator)
             {
                 case AphidTokenType.AdditionOperator:
                     Append("__add(");
                     Emit(expression.LeftOperand);
                     Append(", ");
                     Emit(expression.RightOperand);
                     Append(")");
                     break;
                 case AphidTokenType.MemberOperator:
                     Emit(expression.LeftOperand);
                     Append("->");
                     if (expression.RightOperand.Type == AphidExpressionType.IdentifierExpression)
                     {
                         Append(expression.RightOperand.ToIdentifier().Identifier);
                     }
                     else
                     {
                         Emit(expression.RightOperand);
                     }
                     break;
                 default:
                     base.EmitBinaryOperatorExpression(expression, isStatement);
                     break;
             }
         }
EmitCallExpression()
override void Coywolf.AphidPhpEmitter.EmitCallExpression (CallExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 378 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Components.Aphid.Compiler.AphidStringEmitter.AppendTabs(), Coywolf.AphidPhpEmitter.Emit(), Coywolf.AphidPhpEmitter.EmitEchoStatement(), Components.Aphid.Compiler.AphidStringEmitter.EmitTuple(), expression, Components.Aphid.Compiler.AphidStringEmitter.GetTabs(), Components.Aphid.Compiler.AphidStringEmitter.Indent(), and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
         {
             switch (expression.FunctionExpression.Type)
             {
                 case AphidExpressionType.IdentifierExpression:
                     switch (expression.FunctionExpression.ToIdentifier().Identifier)
                     {
                         case "echo":
                             EmitEchoStatement(expression);
                             return;
                     }
                     break;
                 case AphidExpressionType.FunctionExpression:
                 case AphidExpressionType.PartialFunctionExpression:
                     Append("call_user_func(\r\n");
                     Indent();
                     AppendTabs();
                     Emit(expression.FunctionExpression);
                     if (expression.Args.Any())
                     {
                         Append(",\r\n{0}", GetTabs());
                         EmitTuple(expression.Args);
                     }
                     Unindent();
                     Append(")");
                     return;
             }
             base.EmitCallExpression(expression, isStatement);
         }
EmitClassDeclaration()
void Coywolf.AphidPhpEmitter.EmitClassDeclaration (ObjectExpression classDecl) protected
Definition at line 501 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Coywolf.AphidPhpEmitter.EmitClassMember(), first, Components.Aphid.Compiler.AphidStringEmitter.GetTabs(), Components.Aphid.Parser.IdentifierExpression.Identifier, Components.Aphid.Parser.ObjectExpression.Identifier, Components.Aphid.Compiler.AphidStringEmitter.Indent(), out, and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
Referenced by Coywolf.AphidPhpEmitter.EmitObjectExpression().
         {
             string[] unparsed;
             var attrs = AphidAttributeParser.Parse<ObjectStatementAttributes>(
                 classDecl.Identifier,
                 out unparsed);
             if (attrs.IsInterface && attrs.IsAbstract)
             {
                 throw new InvalidOperationException("Interfaces cannot be abstract.");
             }
             else if ((attrs.IsInterface && attrs.IsClass) ||
                 (!attrs.IsInterface && !attrs.IsClass))
             {
                 throw new InvalidOperationException("Type must be interface or class.");
             }
             if (attrs.IsAbstract)
             {
                 Append("abstract ");
             }
             Append(attrs.IsClass ? "class " : "interface ");
             Append(classDecl.Identifier.Identifier);
             bool first = true, extend = true;
             foreach (var attr in unparsed)
             {
                 if (extend)
                 {
                     if (attr == "impl")
                     {
                         extend = false;
                         first = true;
                     }
                     else
                     {
                         if (first)
{
                             Append(" extends ");
                             first = false;
                         }
                         else
{
                             Append(", ");
                         }
                         Append(attr);
                     }
                 }
                 else
                 {
                     if (first)
                     {
                         Append(" implements ");
                         first = false;
                     }
                     else
                     {
                         Append(", ");
                     }
                     Append(attr);
                 }
             }
             Append(" {\r\n");
             Indent();
             foreach (var member in classDecl.Pairs)
             {
                 EmitClassMember(classDecl, member);
             }
             Unindent();
             Append(GetTabs() + "}");
         }
EmitClassMember()
void Coywolf.AphidPhpEmitter.EmitClassMember (ObjectExpression classDecl, BinaryOperatorExpression member) protected
Definition at line 581 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Coywolf.AphidPhpEmitter.Emit(), Components.Aphid.Compiler.AphidStringEmitter.EmitTuple(), func, Components.Aphid.Compiler.AphidStringEmitter.GetTabs(), id, Components.Aphid.Compiler.AphidStringEmitter.Indent(), Components.Aphid.Parser.BinaryOperatorExpression.LeftOperand, Components.Aphid.Parser.BinaryOperatorExpression.RightOperand, Components.Aphid.Parser.AphidNode.Type, and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
Referenced by Coywolf.AphidPhpEmitter.EmitClassDeclaration().
         {
             if (member.LeftOperand.Type != AphidExpressionType.IdentifierExpression)
             {
                 throw new InvalidOperationException("Expected identifier expression on lhs of class member.");
             }
             var id = member.LeftOperand.ToIdentifier();
             var attrs = AphidAttributeParser.Parse<MemberDeclarationAttributes>(id);
             if ((attrs.IsPrivate && attrs.IsProtected) ||
                 (attrs.IsPrivate && attrs.IsPublic) ||
                 (attrs.IsProtected && attrs.IsPrivate) ||
                 (attrs.IsProtected && attrs.IsPublic) ||
                 (attrs.IsPublic && attrs.IsPrivate) ||
                 (attrs.IsPublic && attrs.IsProtected))
             {
                 throw new InvalidOperationException("Member must be private, protected, or public.");
             }
             if (!attrs.IsPrivate && !attrs.IsProtected && !attrs.IsPublic)
             {
                 attrs.IsPrivate = true;
             }
             if (attrs.IsPrivate && attrs.IsAbstract)
             {
                 throw new InvalidOperationException("Member cannot be both private and abstract.");
             }
             var access =
                 attrs.IsPrivate ? "private " :
                 attrs.IsProtected ? "protected " :
                 "public ";
             Append(GetTabs() + access);
             if (attrs.IsAbstract)
             {
                 Append("abstract ");
             }
             if (member.RightOperand.Type == AphidExpressionType.FunctionExpression)
             {
                 attrs.IsFunction = true;
             }
             if (attrs.IsFunction)
             {
                 Append("function ");
             }
             else
             {
                 Append("$");
             }
             Append(id.Identifier);
             var hasInitializer =
                 member.RightOperand.Type != AphidExpressionType.IdentifierExpression ||
                 id.Identifier != member.RightOperand.ToIdentifier().Identifier;
             if (!attrs.IsFunction)
             {
                 if (hasInitializer)
                 {
                     Append(" = ");
                     Emit(member.RightOperand);
                 }
             }
             else
             {
                 if (hasInitializer)
                 {
                     if (member.RightOperand.Type != AphidExpressionType.FunctionExpression)
                     {
                         throw new InvalidOperationException();
                     }
                     var func = member.RightOperand.ToFunction();
                     Append("(");
                     EmitTuple(func.Args);
                     Append(") {\r\n");
                     Indent();
                     Emit(func.Body);
                     Unindent();
                     Append(GetTabs() + "}\r\n\r\n");
                 }
             }
             if (!attrs.IsFunction || !hasInitializer)
             {
                 Append(";\r\n");
             }
         }
EmitEchoStatement()
void Coywolf.AphidPhpEmitter.EmitEchoStatement (CallExpression expression) protected
Definition at line 679 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Components.Aphid.Compiler.AphidStringEmitter.EmitTuple(), and expression.
Referenced by Coywolf.AphidPhpEmitter.EmitCallExpression().
         {
             Append("echo ");
             EmitTuple(expression.Args);
         }
EmitForEachExpression()
override void Coywolf.AphidPhpEmitter.EmitForEachExpression (ForEachExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 411 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Coywolf.AphidPhpEmitter.Emit(), expression, Components.Aphid.Compiler.AphidStringEmitter.GetTabs(), Components.Aphid.Compiler.AphidStringEmitter.Indent(), and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
         {
             Append("foreach (");
             Emit(expression.Collection);
             Append(" as ");
             Emit(expression.Element);
             Append("){\r\n");
             Indent();
             Emit(expression.Body);
             Unindent();
             Append(GetTabs() + "}\r\n");
         }
EmitFunctionExpression()
override void Coywolf.AphidPhpEmitter.EmitFunctionExpression (FunctionExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 304 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Coywolf.AphidPhpEmitter.Emit(), Components.Aphid.Compiler.AphidStringEmitter.EmitTuple(), Coywolf.AphidPhpEmitter.EmitUsed(), expression, Components.Aphid.Compiler.AphidStringEmitter.GetTabs(), Components.Aphid.Compiler.AphidStringEmitter.Indent(), and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
         {
             Append("function (");
             EmitTuple(expression.Args);
             Append(") ");
             EmitUsed(expression.Args, expression.Body);
             Append("{\r\n");
             Indent();
             Emit(expression.Body);
             Unindent();
             Append(GetTabs() + "}");
         }
EmitGatorCloseExpression()
override void Coywolf.AphidPhpEmitter.EmitGatorCloseExpression (GatorCloseExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 155 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append().
         {
             Append("?>");
         }
EmitGatorEmitExpression()
override void Coywolf.AphidPhpEmitter.EmitGatorEmitExpression (GatorEmitExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 165 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Coywolf.AphidPhpEmitter.Emit(), and expression.
         {
             Append("<?= ");
             Append("htmlentities(");
             Emit(expression.Expression, isStatement: false);
             Append(", ENT_QUOTES)");
             Append(" ?>");
         }
EmitGatorOpenExpression()
override void Coywolf.AphidPhpEmitter.EmitGatorOpenExpression (GatorOpenExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 150 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append().
         {
             Append("<?php\r\n");
         }
EmitHeader()
override void Coywolf.AphidPhpEmitter.EmitHeader () protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 63 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append().
         {
             Append(_header);
             base.EmitHeader();
         }
EmitIdentifierExpression()
override void Coywolf.AphidPhpEmitter.EmitIdentifierExpression (IdentifierExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 174 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), and expression.
         {
             //if (expression.Attributes.Any())
             //{
             //    throw new NotImplementedException();
             //}
             foreach (var attr in expression.Attributes)
             {
                 Append("{0} ", attr.Identifier);
             }
             Append(
                 "{0}{1}",
                 !IsBuildInFunction(expression.Identifier) ? "$" : "",
                 expression.Identifier);
         }
EmitIfExpression()
override void Coywolf.AphidPhpEmitter.EmitIfExpression (IfExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 424 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Coywolf.AphidPhpEmitter.Emit(), expression, Components.Aphid.Compiler.AphidStringEmitter.GetTabs(), Components.Aphid.Compiler.AphidStringEmitter.Indent(), and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
         {
             Append("if (");
             Emit(expression.Condition);
             Append(") {\r\n");
             Indent();
             Emit(expression.Body);
             Unindent();
             Append(GetTabs() + "}");
             if (expression.ElseBody != null)
             {
                 Append(" else {\r\n");
                 Indent();
                 Emit(expression.ElseBody);
                 Unindent();
                 Append(GetTabs() + "}");
             }
             Append("\r\n");
         }
EmitObjectExpression()
override void Coywolf.AphidPhpEmitter.EmitObjectExpression (ObjectExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 457 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Coywolf.AphidPhpEmitter.Emit(), Coywolf.AphidPhpEmitter.EmitClassDeclaration(), and expression.
         {
             if (expression.Identifier != null)
             {
                 if (isStatement)
                 {
                     EmitClassDeclaration(expression);
                     return;
                 }
                 else
                 {
                     throw new NotImplementedException();
                 }
             }
             Append("[");
             var isFirst = true;
             foreach (var kvp in expression.Pairs)
             {
                 if (isFirst)
                 {
                     isFirst = false;
                 }
                 else
                 {
                     Append(", ");
                 }
                 var key = kvp.LeftOperand.Type == AphidExpressionType.IdentifierExpression ?
                     new StringExpression(string.Format(
                         "'{0}'",
                         kvp.LeftOperand.ToIdentifier().Identifier)) :
                     (StringExpression)kvp.LeftOperand;
                 Emit(key);
                 Append(" => ");
                 Emit(kvp.RightOperand);
             }
             Append("]");
         }
EmitPartialFunctionExpression()
override void Coywolf.AphidPhpEmitter.EmitPartialFunctionExpression (PartialFunctionExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 317 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Coywolf.AphidPhpEmitter.Emit(), Coywolf.AphidPhpEmitter.EmitUsed(), and expression.
         {
             var arg = NextId();
             Append("(function(${0}) ", arg);
             EmitUsed(
                 new List<AphidExpression>(),
                 expression.GetChildren().ToList());
             Append("{ return ");
             var callArgs = expression.Call.Args
                 .Concat(new[] { new IdentifierExpression(arg) })
                 .ToList();
             Emit(new CallExpression(
                 expression.Call.FunctionExpression,
                 callArgs.ToList()));
             Append("; })");
         }
EmitStringExpression()
override void Coywolf.AphidPhpEmitter.EmitStringExpression (StringExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 291 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), expression, and Components.Aphid.Parser.StringParser.Parse().
         {
             var escaped = StringParser
                 .Parse(expression.Value)
                 .Replace("\\", "\\\\")
                 .Replace("\n", "\\n")
                 .Replace("\r", "\\r")
                 .Replace("\"", "\\\"")
                 .Replace("$", "\\$");
             Append("\"{0}\"", escaped);
         }
EmitTernaryOperatorExpression()
override void Coywolf.AphidPhpEmitter.EmitTernaryOperatorExpression (TernaryOperatorExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 278 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Coywolf.AphidPhpEmitter.Emit(), and expression.
         {
             Append("((");
             Emit(expression.FirstOperand);
             Append(")");
             Append(" ? ");
             Append("(");
             Emit(expression.SecondOperand);
             Append(") : (");
             Emit(expression.ThirdOperand);
             Append("))");
         }
EmitTextExpression()
override void Coywolf.AphidPhpEmitter.EmitTextExpression (TextExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 160 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), and expression.
         {
             Append(expression.Text);
         }
EmitUnaryOperatorExpression()
override void Coywolf.AphidPhpEmitter.EmitUnaryOperatorExpression (UnaryOperatorExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 192 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Coywolf.AphidPhpEmitter.Emit(), Components.Aphid.Compiler.AphidStringEmitter.EmitTuple(), expression, out, and value.
         {
             switch (expression.Operator)
             {
                 case AphidTokenType.newKeyword:
                     switch (expression.Operand.Type)
                     {
                         case AphidExpressionType.ObjectExpression:
                             Append("(object)");
                             Emit(expression.Operand.ToObject());
                             break;
                         case AphidExpressionType.CallExpression:
                             var call = expression.Operand.ToCall();
                             if (call.FunctionExpression.Type != AphidExpressionType.IdentifierExpression)
{
                                 throw new InvalidOperationException("Expected identifier in new expression.");
                             }
                             var id = call.FunctionExpression.ToIdentifier();
                             if (id.Attributes.Any())
{
                                 throw new InvalidOperationException("Unexpected attributes in new expression.");
                             }
                             Append("new {0}(", id.Identifier);
                             EmitTuple(call.Args);
                             Append(")");
                             break;
                         default:
                             throw new NotImplementedException();
                     }
                     break;
                 default:
                     string value;
                     if (!_unaryPrefixOperators.TryGetValue(expression.Operator, out value))
                     {
                         base.EmitUnaryOperatorExpression(expression, isStatement);
                     }
                     else
                     {
                         Append(value);
                         Emit(expression.Operand);
                     }
                     break;
             }
         }
EmitUsed()
void Coywolf.AphidPhpEmitter.EmitUsed (List< AphidExpression > args, List< AphidExpression > body) protected
Definition at line 339 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), args, Components.Aphid.Compiler.AphidStringEmitter.EmitTuple(), Coywolf.Visitors.PhpUseIdFinder.Find(), Coywolf.Visitors.LocalFinder.Find(), Coywolf.DeclarationHelper.GetDeclaredIdentifier(), Components.Aphid.Compiler.AphidStringEmitter.Scope, x, and y.
Referenced by Coywolf.AphidPhpEmitter.EmitFunctionExpression(), and Coywolf.AphidPhpEmitter.EmitPartialFunctionExpression().
         {
             var argIds = args
                 .Select(x => x.ToIdentifier())
                 .ToArray();
             var parentVariables = Scope
                 .SelectMany(x => x)
                 .Select(DeclarationHelper.GetDeclaredIdentifier)
                 .Where(x => x != null && !argIds.Any(y => x.Identifier == y.Identifier))
                 .Distinct()
                 .ToArray();
             var locals = new LocalFinder()
                 .Find(body)
                 .Where(x => !parentVariables.Any(y => x.Identifier == y.Identifier))
                 .ToArray();
             var used = new PhpUseIdFinder()
                 .Find(body)
                 .Cast<IdentifierExpression>()
                 .Select(x => x.Identifier)
                 .Distinct()
                 .Where(x =>
                     !argIds
                         .Concat(locals)
                         .Any(y => y.Identifier == x) &&
                     !IsBuildInFunction(x))
                 .Select(x => new IdentifierExpression(x))
                 .ToArray();
             if (used.Any())
             {
                 Append("use (");
                 EmitTuple(used, prefix: "&");
                 Append(") ");
             }
         }
EmitWhileExpression()
override void Coywolf.AphidPhpEmitter.EmitWhileExpression (WhileExpression expression, bool isStatement = false) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 446 of file AphidPhpEmitter.cs.
References Components.Aphid.Compiler.AphidStringEmitter.Append(), Coywolf.AphidPhpEmitter.Emit(), expression, Components.Aphid.Compiler.AphidStringEmitter.GetTabs(), Components.Aphid.Compiler.AphidStringEmitter.Indent(), and Components.Aphid.Compiler.AphidStringEmitter.Unindent().
         {
             Append("while (");
             Emit(expression.Condition);
             Append(") {\r\n");
             Indent();
             Emit(expression.Body);
             Unindent();
             Append("{0}}}\r\n", GetTabs());
         }
EndExpression()
override void Coywolf.AphidPhpEmitter.EndExpression (AphidExpression expression) protected virtual
Reimplemented from Components.Aphid.Compiler.AphidStringEmitter.
Definition at line 112 of file AphidPhpEmitter.cs.
References expression.
         {
             if (expression.Type == AphidExpressionType.GatorEmitExpression)
             {
                 _isPhp = false;
             }
             base.EndExpression(expression);
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Coywolf/AphidPhpEmitter.cs