Aphid Programming Language: Mantispid.ParserCode Class Reference
Mantispid.ParserCode Class Reference
Static Public Member Functions
static CodeTypeReference GetTypeRef (ParserIdentifier property)
static CodeTypeReference GetListTypeRef (CodeTypeReference typeArg)
Detailed Description
Definition at line 11 of file ParserCode.cs.
Member Function Documentation
GetListTypeRef()
static CodeTypeReference Mantispid.ParserCode.GetListTypeRef (CodeTypeReference typeArg) static
Definition at line 45 of file ParserCode.cs.
References Components.Aphid.Compiler.CodeHelper.TypeRef().
Referenced by Mantispid.ParserCode.GetTypeRef().
         {
             var listTypeRef = CodeHelper.TypeRef(typeof(List<>));
             listTypeRef.TypeArguments.Add(typeArg);
             return listTypeRef;
         }
GetTypeRef()
static CodeTypeReference Mantispid.ParserCode.GetTypeRef (ParserIdentifier property) static
Definition at line 13 of file ParserCode.cs.
References Mantispid.ParserCode.GetListTypeRef(), Mantispid.ParserIdentifier.IsList, Mantispid.ParserIdentifier.Type, and Components.Aphid.Compiler.CodeHelper.TypeRef().
         {
             CodeTypeReference typeRef;
             switch (property.Type)
             {
                 case "bool":
                     typeRef = CodeHelper.TypeRef<bool>();
                     break;
                 case "string":
                     typeRef = CodeHelper.TypeRef<string>();
                     break;
                 case "decimal":
                     typeRef = CodeHelper.TypeRef<decimal>();
                     break;
                 default:
                     typeRef = CodeHelper.TypeRef(property.Type);
                     break;
             }
             if (property.IsList)
             {
                 return ParserCode.GetListTypeRef(typeRef);
             }
             return typeRef;
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Compiler/Medusa/Mantispid/ParserCode.cs