Aphid Programming Language: Components.External.ConsolePlus.VT100 Class Reference
Components.External.ConsolePlus.VT100 Class Reference
Static Public Member Functions
static string GetString (IEnumerable< ColoredText > coloredTextCollection)
static string GetString (ColoredText coloredText)
static StringBuilder Append (StringBuilder sb, ColoredText coloredText)
static string Rgb (bool bg, byte r, byte g, byte b)
static string Foreground (byte[] rgb)
static string Foreground (byte r, byte g, byte b)
static string Background (byte[] rgb)
static string Background (byte r, byte g, byte b)
static void Enable ()
static void DumpColors (bool background=false)
Public Attributes
const string Reset = "\x1b[0m"
Properties
static bool IsEnabled [get]
Detailed Description
Definition at line 12 of file VT100.cs.
Member Function Documentation
Append()
static StringBuilder Components.External.ConsolePlus.VT100.Append (StringBuilder sb, ColoredText coloredText) static
Definition at line 35 of file VT100.cs.
References Components.External.ConsolePlus.VT100.Background(), Components.External.ConsolePlus.ColoredText.BackgroundRgb, Components.External.ConsolePlus.VT100.Foreground(), Components.External.ConsolePlus.ColoredText.ForegroundRgb, Components.External.ConsolePlus.VT100.Reset, sb, and Components.External.ConsolePlus.ColoredText.Text.
         {
             if (IsEnabled)
             {
                 if (coloredText.ForegroundRgb != null)
                 {
                     sb.Append(VT100.Foreground(coloredText.ForegroundRgb));
                 }
                 if (coloredText.BackgroundRgb != null)
                 {
                     sb.Append(VT100.Background(coloredText.BackgroundRgb));
                 }
                 sb.Append(coloredText.Text);
                 sb.Append(VT100.Reset);
             }
             else
             {
                 sb.Append(coloredText.Text);
             }
             return sb;
         }
Background() [1/2]
static string Components.External.ConsolePlus.VT100.Background (byte [] rgb) static
Definition at line 80 of file VT100.cs.
Referenced by Components.External.ConsolePlus.VT100.Append().
         {
             return Rgb(true, rgb[0], rgb[1], rgb[2]);
         }
Background() [2/2]
static string Components.External.ConsolePlus.VT100.Background (byte r, byte g, byte b) static
Definition at line 85 of file VT100.cs.
References r.
         {
             return Rgb(true, r, g, b);
         }
DumpColors()
static void Components.External.ConsolePlus.VT100.DumpColors (bool background = false) static
Definition at line 128 of file VT100.cs.
References byte, Components.External.ConsolePlus.VT100.Foreground(), Components.External.ConsolePlus.VT100.Reset, and x.
         {
             Enable();
             var str = typeof(SystemColor)
                 .GetFields()
                 .Where(x => x.FieldType == typeof(byte[]))
                 .ToDictionary(x => (byte[])x.GetValue(null), x => x.Name)
                 .OrderBy(x =>
                     x.Key[0] << 0x10 |
                     x.Key[1] << 0x8 |
                     x.Key[2])
                 .Select(x => string.Format(
                     "{0}{1}{2}{3}",
                     VT100.Foreground(x.Key),
                     background ? LogBackground(x.Key) : "",
                     x.Value,
                     VT100.Reset))
                 .Join(" ");
             Console.WriteLine(str);
         }
Enable()
static void Components.External.ConsolePlus.VT100.Enable () static
Definition at line 90 of file VT100.cs.
References Components.PInvoke.Kernel32.GetConsoleMode(), Components.PInvoke.Kernel32.GetStdHandle(), handle, Components.PInvoke.Win32.INVALID_HANDLE_VALUE, out, and Components.PInvoke.Kernel32.SetConsoleMode().
         {
             var handle = Kernel32.GetStdHandle(Win32.STD_OUTPUT_HANDLE);
             if (handle == Win32.INVALID_HANDLE_VALUE)
             {
                 throw CreateException("Kernel32!GetStdHandle()");
             }
             int mode;
             if (!Kernel32.GetConsoleMode(handle, out mode))
             {
                 throw CreateException("kernel32!GetConsoleMode()");
             }
             if (!Kernel32.SetConsoleMode(handle, mode | 0x4))
             {
                 throw CreateException("kernel32!SetConsoleMode()");
             }
             IsEnabled = true;
         }
Foreground() [1/2]
static string Components.External.ConsolePlus.VT100.Foreground (byte [] rgb) static
Definition at line 70 of file VT100.cs.
Referenced by Components.External.ConsolePlus.VT100.Append(), and Components.External.ConsolePlus.VT100.DumpColors().
         {
             return Rgb(false, rgb[0], rgb[1], rgb[2]);
         }
Foreground() [2/2]
static string Components.External.ConsolePlus.VT100.Foreground (byte r, byte g, byte b) static
Definition at line 75 of file VT100.cs.
References r.
         {
             return Rgb(false, r, g, b);
         }
GetString() [1/2]
static string Components.External.ConsolePlus.VT100.GetString (IEnumerable< ColoredText > coloredTextCollection) static
Definition at line 18 of file VT100.cs.
References Append(), and sb.
Referenced by Components.Aphid.UI.AphidCli.Highlight().
         {
             var sb = new StringBuilder();
             foreach (var ct in coloredTextCollection)
             {
                 Append(sb, ct);
             }
             return sb.ToString();
         }
GetString() [2/2]
static string Components.External.ConsolePlus.VT100.GetString (ColoredText coloredText) static
Definition at line 30 of file VT100.cs.
References Append().
         {
             return Append(new StringBuilder(), coloredText).ToString();
         }
Rgb()
static string Components.External.ConsolePlus.VT100.Rgb (bool bg, byte r, byte g, byte b) static
Definition at line 60 of file VT100.cs.
References r.
         {
             return string.Format(
                 "\x1b[{0}8;2;{1};{2};{3}m",
                 bg ? 4 : 3,
                 r,
                 g,
                 b);
         }
Member Data Documentation
Reset
const string Components.External.ConsolePlus.VT100.Reset = "\x1b[0m"
Definition at line 14 of file VT100.cs.
Referenced by Components.External.ConsolePlus.VT100.Append(), and Components.External.ConsolePlus.VT100.DumpColors().
Property Documentation
IsEnabled
bool Components.External.ConsolePlus.VT100.IsEnabled static get
Definition at line 16 of file VT100.cs.
 { get; private set; }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/External/ConsolePlus/VT100.cs