Aphid Programming Language: Components.External.PathHelper Class Reference
Components.External.PathHelper Class Reference
Static Public Member Functions
static string GetEntryDirectory ()
static string GetEntryPath (params string[] paths)
static string GetExecutingDirectory ()
static string GetExecutingPath (params string[] paths)
static string GetSiblingFileName (string path, string filename)
Detailed Description
Definition at line 11 of file PathHelper.cs.
Member Function Documentation
GetEntryDirectory()
static string Components.External.PathHelper.GetEntryDirectory () static
Definition at line 13 of file PathHelper.cs.
References FileInfo().
         {
             return new FileInfo(Assembly.GetEntryAssembly().Location).DirectoryName;
         }
GetEntryPath()
static string Components.External.PathHelper.GetEntryPath (params string [] paths) static
Definition at line 18 of file PathHelper.cs.
References Path.
         {
             return Path.Combine(new[] { GetEntryDirectory() }.Concat(paths).ToArray());
         }
GetExecutingDirectory()
static string Components.External.PathHelper.GetExecutingDirectory () static
Definition at line 23 of file PathHelper.cs.
References Path.
         {
             return Path.GetDirectoryName(Assembly.GetCallingAssembly().Location);
         }
GetExecutingPath()
static string Components.External.PathHelper.GetExecutingPath (params string [] paths) static
Definition at line 28 of file PathHelper.cs.
References Path.
Referenced by Components.Aphid.Debugging.AphidMemoryDump.Create(), and Components.External.ConsolePlus.CliApplication< TArgs, TConfig >.Launch().
         {
             return Path.Combine(new[] { Path.GetDirectoryName(Assembly.GetCallingAssembly().Location) }.Concat(paths).ToArray());
         }
GetSiblingFileName()
static string Components.External.PathHelper.GetSiblingFileName (string path, string filename) static
Definition at line 33 of file PathHelper.cs.
References Path.
         {
             return Path.Combine(Path.GetDirectoryName(path), filename);
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/External/Common/PathHelper.cs