Aphid Programming Language: Components.Aphid.Interpreter.AphidLoader Class Reference
Components.Aphid.Interpreter.AphidLoader Class Reference
Public Member Functions
AphidLoader (AphidInterpreter interpreter)
void LoadModule (string moduleFile)
void LoadModule (Assembly module)
void LoadLibrary (Type libraryType, AphidObject scope)
void LoadLibrary (string libraryType, AphidObject scope)
void LoadLibrary< TLibrary > (AphidObject scope)
string FindScriptFile (string scriptFile)
string FindScriptFile (string appDir, string scriptFile)
List< AphidExpression > LoadScript (string scriptFile, bool isTextDocument=false)
void SetMember (AphidObject scope, string path, object value)
Public Member Functions inherited from Components.Aphid.Interpreter.AphidRuntimeComponent
AphidRuntimeComponent (AphidInterpreter interpreter)
Properties
List< string > SearchPaths [get]
Properties inherited from Components.Aphid.Interpreter.AphidRuntimeComponent
AphidInterpreter Interpreter [get]
Detailed Description
Definition at line 11 of file AphidLoader.cs.
Constructor & Destructor Documentation
AphidLoader()
Components.Aphid.Interpreter.AphidLoader.AphidLoader (AphidInterpreter interpreter)
Definition at line 27 of file AphidLoader.cs.
             : base(interpreter)
         {
             _modules = new List<Assembly> { Assembly.GetExecutingAssembly() };
         }
Member Function Documentation
FindScriptFile() [1/2]
string Components.Aphid.Interpreter.AphidLoader.FindScriptFile (string scriptFile)
Definition at line 97 of file AphidLoader.cs.
References Path.
Referenced by Components.Aphid.Parser.IncludeMutator.MutateCore(), Components.Aphid.Interpreter.AphidScriptOptimizer.Optimize(), and Components.Aphid.Tests.Integration.Shared.AphidTests.ParseScript().
         {
             return FindScriptFile(
                 Path.GetDirectoryName(Assembly.GetEntryAssembly().Location),
                 scriptFile);
         }
FindScriptFile() [2/2]
string Components.Aphid.Interpreter.AphidLoader.FindScriptFile (string appDir, string scriptFile)
Definition at line 104 of file AphidLoader.cs.
References f, files, p, Path, and x.
         {
             Func<string, string>[] extensionStrategies = new Func<string, string>[]
             {
                 x => x + ".alx",
                 x => x,
             };
             var files = extensionStrategies.Select(x => x(scriptFile));
             foreach (var file in files)
             {
                 if (File.Exists(file))
                 {
                     return file;
                 }
             }
             var searchPathSets = new List<List<string>> { _searchPaths };
             if (appDir != null)
             {
                 searchPathSets.Add(new List<string> { appDir });
             }
             foreach (var paths in searchPathSets)
             {
                 foreach (var file in files)
                 {
                     foreach (var p in paths)
                     {
                         var f = Path.Combine(p, file);
                         if (File.Exists(f))
{
                             return f;
                         }
                     }
                 }
             }
             return null;
         }
LoadLibrary() [1/2]
void Components.Aphid.Interpreter.AphidLoader.LoadLibrary (Type libraryType, AphidObject scope)
Definition at line 51 of file AphidLoader.cs.
References is, scope, x, and y.
         {
             var methods = libraryType
                 .GetMethods(
                     BindingFlags.Static |
                     BindingFlags.NonPublic |
                     BindingFlags.Public)
                 .Select(x => new
                 {
                     Method = x,
                     Attributes = x
                         .GetCustomAttributes(true)
                         .Where(y => y is AphidInteropFunctionAttribute)
                         .Cast<AphidInteropFunctionAttribute>()
                         .ToArray()
                 })
                 .SelectMany(x => x.Attributes.Select(y => Tuple.Create(y, x.Method)));
             foreach (var method in methods)
             {
                 SetMember(scope, method.Item1.Name, new AphidInteropFunction(method.Item1, method.Item2));
             }
         }
LoadLibrary() [2/2]
void Components.Aphid.Interpreter.AphidLoader.LoadLibrary (string libraryType, AphidObject scope)
Definition at line 75 of file AphidLoader.cs.
References scope, and t.
         {
             foreach (var module in _modules)
             {
                 var t = module.GetType(libraryType);
                 if (t != null)
                 {
                     LoadLibrary(t, scope);
                     return;
                 }
             }
             throw new InvalidOperationException();
         }
LoadLibrary< TLibrary >()
void Components.Aphid.Interpreter.AphidLoader.LoadLibrary< TLibrary > (AphidObject scope)
Definition at line 92 of file AphidLoader.cs.
References scope.
         {
             LoadLibrary(typeof(TLibrary), scope);
         }
LoadModule() [1/2]
void Components.Aphid.Interpreter.AphidLoader.LoadModule (string moduleFile)
Definition at line 33 of file AphidLoader.cs.
         {
             var asm = Assembly.LoadFile(moduleFile);
             if (!_modules.Contains(asm))
             {
                 _modules.Add(asm);
             }
         }
LoadModule() [2/2]
void Components.Aphid.Interpreter.AphidLoader.LoadModule (Assembly module)
Definition at line 43 of file AphidLoader.cs.
         {
             if (!_modules.Contains(module))
             {
                 _modules.Add(module);
             }
         }
LoadScript()
List<AphidExpression> Components.Aphid.Interpreter.AphidLoader.LoadScript (string scriptFile, bool isTextDocument = false)
Definition at line 148 of file AphidLoader.cs.
References ast, dir, e, f, Components.Aphid.Parser.AphidMutator.MutateRecursively(), Components.Aphid.Parser.AphidParser.Parse(), and Path.
         {
             var f = FindScriptFile(null, scriptFile);
             if (f != null)
             {
                 if (f.Contains(Path.DirectorySeparatorChar))
                 {
                     var dir = Path.GetFullPath(Path.GetDirectoryName(f));
                     if (!_searchPaths.Contains(dir))
                     {
                         _searchPaths.Add(dir);
                     }
                 }
                 List<AphidExpression> ast;
                 try
                 {
                     ast = AphidParser.Parse(File.ReadAllText(f), f, isTextDocument);
                 }
                 catch (AphidParserException e)
                 {
                     throw new AphidLoadScriptException(
                         Interpreter,
                         Interpreter.CurrentScope,
                         Interpreter.CurrentStatement,
                         Interpreter.CurrentExpression,
                         f,
                         e);
                 }
                 catch (AphidRuntimeException e)
                 {
                     throw new AphidLoadScriptException(
                         Interpreter,
                         Interpreter.CurrentScope,
                         Interpreter.CurrentStatement,
                         Interpreter.CurrentExpression,
                         f,
                         e);
                 }
                 catch (Exception e)
                 {
                     throw new AphidLoadScriptException(
                         Interpreter,
                         Interpreter.CurrentScope,
                         Interpreter.CurrentStatement,
                         Interpreter.CurrentExpression,
                         f,
                         e);
                 }
                 var mutatedAst = new PartialOperatorMutator().MutateRecursively(ast);
                 mutatedAst = new AphidMacroMutator().MutateRecursively(mutatedAst);
                 mutatedAst = new AphidIdDirectiveMutator().MutateRecursively(mutatedAst);
                 Interpreter.Interpret(mutatedAst);
                 return mutatedAst;
             }
             else
             {
                 throw Interpreter.CreateRuntimeException("Cannot find script {0}", scriptFile);
             }
         }
SetMember()
void Components.Aphid.Interpreter.AphidLoader.SetMember (AphidObject scope, string path, object value)
Definition at line 215 of file AphidLoader.cs.
References scope, and value.
         {
             var members = path.Split('.');
             var currentObj = scope;
             foreach (var m in members)
             {
                 if (!currentObj.ContainsKey(m))
                 {
                     currentObj.Add(m, new AphidObject());
                 }
                 currentObj = currentObj[m];
             }
             currentObj.Value = value;
         }
Property Documentation
SearchPaths
List<string> Components.Aphid.Interpreter.AphidLoader.SearchPaths get
Definition at line 23 of file AphidLoader.cs.
Referenced by Components.Aphid.Interpreter.AphidInterpreter.CallFunctionWithScope(), Components.Aphid.Tests.Integration.Shared.AphidTests.Execute(), and Components.Aphid.Interpreter.AphidInterpreter.Interpret().
         {
             get { return _searchPaths; }
         }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Interpreter/AphidLoader.cs