Aphid Programming Language: Components.Aphid.Parser.IncludeMutator Class Reference
Components.Aphid.Parser.IncludeMutator Class Reference
Public Member Functions
IncludeMutator (string applicationDirectory, bool useImplicitReturns)
IncludeMutator (string applicationDirectory)
IncludeMutator ()
Public Member Functions inherited from Components.Aphid.Parser.AphidMutator
AphidMutator ()
List< AphidExpression > Mutate (List< AphidExpression > ast)
List< AphidExpression > MutateRecursively (List< AphidExpression > expression)
virtual void Reset ()
Protected Member Functions
override List< AphidExpression > MutateCore (AphidExpression expression, out bool hasChanged)
Protected Member Functions inherited from Components.Aphid.Parser.AphidMutator
virtual List< AphidExpression > OnMutate (List< AphidExpression > ast)
virtual void BeginRecursiveMutationPass (List< AphidExpression > ast)
virtual void EndRecursiveMutationPass (List< AphidExpression > ast)
void FinalizeMutation ()
Properties
bool UseImplicitReturns [get]
AphidLoader Loader [get]
Properties inherited from Components.Aphid.Parser.AphidMutator
Stack< AphidExpression > Ancestors [get]
bool HasMutated [get]
bool IsStatement [get]
bool HasFinalized [get]
Detailed Description
Definition at line 12 of file IncludeMutator.cs.
Constructor & Destructor Documentation
IncludeMutator() [1/3]
Components.Aphid.Parser.IncludeMutator.IncludeMutator (string applicationDirectory, bool useImplicitReturns)
Definition at line 25 of file IncludeMutator.cs.
         {
             _applicationDirectory = applicationDirectory;
             UseImplicitReturns = useImplicitReturns;
         }
IncludeMutator() [2/3]
Components.Aphid.Parser.IncludeMutator.IncludeMutator (string applicationDirectory)
Definition at line 31 of file IncludeMutator.cs.
             : this(applicationDirectory, true)
         {
         }
IncludeMutator() [3/3]
Components.Aphid.Parser.IncludeMutator.IncludeMutator ()
Definition at line 36 of file IncludeMutator.cs.
             : this(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location))
         {
         }
Member Function Documentation
MutateCore()
override List<AphidExpression> Components.Aphid.Parser.IncludeMutator.MutateCore (AphidExpression expression, out bool hasChanged) protected virtual
Implements Components.Aphid.Parser.AphidMutator.
Definition at line 41 of file IncludeMutator.cs.
References code, expression, Components.Aphid.Parser.LoadScriptExpression.FileExpression, Components.Aphid.Interpreter.AphidLoader.FindScriptFile(), Components.Aphid.Parser.StringParser.Parse(), Components.Aphid.Parser.AphidParser.Parse(), and script.
         {
             var loadExp = expression as LoadScriptExpression;
             if (loadExp == null)
             {
                 hasChanged = false;
                 return null;
             }
             hasChanged = true;
             var scriptExp = loadExp.FileExpression as StringExpression;
             if (scriptExp == null)
             {
                 throw new AphidParserException("Invalid load script operand", loadExp);
             }
             var script = _loader.FindScriptFile(_applicationDirectory, StringParser.Parse(scriptExp.Value));
             if (!File.Exists(script))
             {
                 throw new AphidParserException("Could not find script", scriptExp);
             }
             var code = File.ReadAllText(script);
             return AphidParser.Parse(code, useImplicitReturns: UseImplicitReturns);
             //var tokens = new AphidLexer().GetTokens();
             //return new AphidParser(tokens) { UseImplicitReturns = UseImplicitReturns }.Parse();
         }
Property Documentation
Loader
AphidLoader Components.Aphid.Parser.IncludeMutator.Loader get
Definition at line 21 of file IncludeMutator.cs.
         {
             get { return _loader; }
         }
UseImplicitReturns
bool Components.Aphid.Parser.IncludeMutator.UseImplicitReturns get
Definition at line 18 of file IncludeMutator.cs.
 { get; private set; }
The documentation for this class was generated from the following file:
c:/source/Aphid/Components.Aphid/Parser/IncludeMutator.cs