Aphid Programming Language: Components.Aphid.Parser.IParentNode Interface Reference
Components.Aphid.Parser.IParentNode Interface Reference
Public Member Functions
IEnumerable< AphidExpression > GetChildren ()
Detailed Description
Definition at line 8 of file IParentNode.cs.
Member Function Documentation
GetChildren()
IEnumerable<AphidExpression> Components.Aphid.Parser.IParentNode.GetChildren ()
Implemented in Components.Aphid.Parser.WhileExpression, Components.Aphid.Parser.TryExpression, Components.Aphid.Parser.TernaryOperatorExpression, Components.Aphid.Parser.SwitchExpression, Components.Aphid.Parser.SwitchCase, Components.Aphid.Parser.UsingExpression, Components.Aphid.Parser.UnaryOperatorExpression, Components.Aphid.Parser.PatternMatchingExpression, Components.Aphid.Parser.PatternExpression, Components.Aphid.Parser.PartialOperatorExpression, Components.Aphid.Parser.PartialFunctionExpression, Components.Aphid.Parser.ObjectExpression, Components.Aphid.Parser.LoadScriptExpression, Components.Aphid.Parser.LoadLibraryExpression, Components.Aphid.Parser.IfExpression, Components.Aphid.Parser.IdentifierExpression, Components.Aphid.Parser.GatorEmitExpression, Components.Aphid.Parser.FunctionExpression, Components.Aphid.Parser.ForExpression, Components.Aphid.Parser.ForEachExpression, Components.Aphid.Parser.ExtendExpression, Components.Aphid.Parser.DynamicMemberExpression, Components.Aphid.Parser.DoWhileExpression, Components.Aphid.Parser.CallExpression, Components.Aphid.Parser.BinaryOperatorBodyExpression, Components.Aphid.Parser.BinaryOperatorExpression, Components.Aphid.Parser.ArrayExpression, and Components.Aphid.Parser.ArrayAccessExpression.
Referenced by Boxelder.AphidTreeHelper.FirstOrDefaultPath(), Components.Aphid.Parser.AphidVisitor.GetChildren(), and Components.Aphid.Parser.AphidCodeVisitor.Visit().
The documentation for this interface was generated from the following file:
c:/source/Aphid/Components.Aphid/Parser/IParentNode.cs