Aphid Programming Language: c:/source/Aphid/Build/package.alx File Reference
package.alx File Reference
Functions
package ({ name:'Aphid', config:'Debug', root:'..', mainModule:'Aphid\\bin\\{config}\\Aphid.exe', files:[ 'README.md', 'Aphid\\bin\\{config}\\Aphid.pdb', 'AphidUI\\bin\\{config}\\AphidUI.exe', 'AphidUI\\bin\\{config}\\AphidUI.pdb', 'Components.Aphid\\bin\\{config}\\Components.Aphid.dll', 'Components.Aphid\\bin\\{config}\\Components.Aphid.pdb', [ 'AphidHdl\\bin\\{config}\\av.exe', 'Aphid2Verilog\\av.exe'], [ 'AphidHdl\\bin\\{config}\\av.pdb', 'Aphid2Verilog\\av.pdb'], [ 'Components.Aphid\\bin\\{config}\\Components.Aphid.dll', 'Aphid2Verilog\\Components.Aphid.dll'], [ 'Components.Aphid\\bin\\{config}\\Components.Aphid.pdb', 'Aphid2Verilog\\Components.Aphid.pdb'], [ 'Coywolf\\bin\\{config}\\cw.exe', 'Aphid2Php\\cw.exe'], [ 'Coywolf\\bin\\{config}\\cw.pdb', 'Aphid2Php\\cw.pdb'], [ 'Components.Aphid\\bin\\{config}\\Components.Aphid.dll', 'Aphid2Php\\Components.Aphid.dll'], [ 'Components.Aphid\\bin\\{config}\\Components.Aphid.pdb', 'Aphid2Php\\Components.Aphid.pdb'], [ 'Boxelder\\bin\\{config}\\be.exe', 'Aphid2Python\\be.exe'], [ 'Boxelder\\bin\\{config}\\be.pdb', 'Aphid2Python\\be.pdb'], [ 'Components.Aphid\\bin\\{config}\\Components.Aphid.dll', 'Aphid2Python\\Components.Aphid.dll'], [ 'Components.Aphid\\bin\\{config}\\Components.Aphid.pdb', 'Aphid2Python\\Components.Aphid.pdb'], l('Benchmark'), l('Conversion'), l('Dbg'), l('DebugDeploy'), l('Env'), l('IL'), l('IO'), l('Ipc'), l('List'), l('Meta'), l('NativeDebugging'), l('PowerShell'), l('Process'), l('Query'), l('RemoteShell'), l('Remoting'), l('Sandbox'), l('Serialization'), l('Shell'), l('Std'), l('String'), l('StringEmitter'), l('Tcp'), l('Threading'), l('Udp'), l('Web'), l('Wmi'), l('Wpf'), l('Xml'), t('AphidUI'), t('ILMerge'), t('MakeExe'), t('TestLoop'), t('ViewModelCompiler'), s("AbstractSyntaxTreeExample.alx"), s("ConditionalOperatorExample.alx"), s("CustomOperatorExample.alx"), s("FibonacciExample.alx"), s("FunctionExample.alx"), s("HelloWorld.alx"), s("ILExample.alx"), s("InteropExample.alx"), s("LambdaExample.alx"), s("MacroExample.alx"), s("NativeDebuggerExample.alx"), s("ParallelForExample.alx"), s("PartialFunctionExample.alx"), s("PatternMatchingExample.alx"), s("PipeliningExample.alx"), s("RuntimeErrorExample.alx"), s("TcpExample.alx"), s("TextDocumentExample.alxt"), s("VbsExample.alx"),] })
Variables
_f = macro(@(fmt) { fmt :: [ $_ ] })
var l = @() [ _f('Components.Aphid\\Library\\{0}.alx'), _f('Library\\{0}.alx') ]
var t = @() [ _f('Components.Aphid\\Tools\\{0}.alx'), _f('Tools\\{0}.alx') ]
var s = @() [ _f('Aphid\\Samples\\{0}'), _f('Samples\\{0}') ]
Function Documentation
package()
package ({ name:'Aphid', config:'Debug', root:'..', mainModule:'Aphid\\bin\\{config}\\Aphid.exe', files:[ 'README.md', 'Aphid\\bin\\{config}\\Aphid.pdb', 'AphidUI\\bin\\{config}\\AphidUI.exe', 'AphidUI\\bin\\{config}\\AphidUI.pdb', 'Components.Aphid\\bin\\{config}\\Components.Aphid.dll', 'Components.Aphid\\bin\\{config}\\Components.Aphid.pdb', [ 'AphidHdl\\bin\\{config}\\av.exe', 'Aphid2Verilog\\av.exe'], [ 'AphidHdl\\bin\\{config}\\av.pdb', 'Aphid2Verilog\\av.pdb'], [ 'Components.Aphid\\bin\\{config}\\Components.Aphid.dll', 'Aphid2Verilog\\Components.Aphid.dll'], [ 'Components.Aphid\\bin\\{config}\\Components.Aphid.pdb', 'Aphid2Verilog\\Components.Aphid.pdb'], [ 'Coywolf\\bin\\{config}\\cw.exe', 'Aphid2Php\\cw.exe'], [ 'Coywolf\\bin\\{config}\\cw.pdb', 'Aphid2Php\\cw.pdb'], [ 'Components.Aphid\\bin\\{config}\\Components.Aphid.dll', 'Aphid2Php\\Components.Aphid.dll'], [ 'Components.Aphid\\bin\\{config}\\Components.Aphid.pdb', 'Aphid2Php\\Components.Aphid.pdb'], [ 'Boxelder\\bin\\{config}\\be.exe', 'Aphid2Python\\be.exe'], [ 'Boxelder\\bin\\{config}\\be.pdb', 'Aphid2Python\\be.pdb'], [ 'Components.Aphid\\bin\\{config}\\Components.Aphid.dll', 'Aphid2Python\\Components.Aphid.dll'], [ 'Components.Aphid\\bin\\{config}\\Components.Aphid.pdb', 'Aphid2Python\\Components.Aphid.pdb'], l('Benchmark'), l('Conversion'), l('Dbg'), l('DebugDeploy'), l('Env'), l('IL'), l('IO'), l('Ipc'), l('List'), l('Meta'), l('NativeDebugging'), l('PowerShell'), l('Process'), l('Query'), l('RemoteShell'), l('Remoting'), l('Sandbox'), l('Serialization'), l('Shell'), l('Std'), l('String'), l('StringEmitter'), l('Tcp'), l('Threading'), l('Udp'), l('Web'), l('Wmi'), l('Wpf'), l('Xml'), t('AphidUI'), t('ILMerge'), t('MakeExe'), t('TestLoop'), t('ViewModelCompiler'), s("AbstractSyntaxTreeExample.alx"), s("ConditionalOperatorExample.alx"), s("CustomOperatorExample.alx"), s("FibonacciExample.alx"), s("FunctionExample.alx"), s("HelloWorld.alx"), s("ILExample.alx"), s("InteropExample.alx"), s("LambdaExample.alx"), s("MacroExample.alx"), s("NativeDebuggerExample.alx"), s("ParallelForExample.alx"), s("PartialFunctionExample.alx"), s("PatternMatchingExample.alx"), s("PipeliningExample.alx"), s("RuntimeErrorExample.alx"), s("TcpExample.alx"), s("TextDocumentExample.alxt"), s("VbsExample.alx"),] })
Variable Documentation
_f
_f = macro(@(fmt) { fmt :: [ $_ ] })
Definition at line 4 of file package.alx.
l
var l = @() [ _f('Components.Aphid\\Library\\{0}.alx'), _f('Library\\{0}.alx') ]
Definition at line 6 of file package.alx.
Referenced by c(), LLex.AlxFile::From(), and Components.External.ConsolePlus.CliArgReader::SetProperties().
s
var s = @() [ _f('Aphid\\Samples\\{0}'), _f('Samples\\{0}') ]
Definition at line 8 of file package.alx.
t
var t = @() [ _f('Components.Aphid\\Tools\\{0}.alx'), _f('Tools\\{0}.alx') ]
Definition at line 7 of file package.alx.
Referenced by AphidUI.CodeViewer::AppendCode(), Components.Aphid.TypeSystem.OperatorHelper::BinaryOr(), Components.Aphid.TypeSystem.AphidTypeConverter::CanConvertArray(), Components.Aphid.TypeSystem.AphidObject::ConvertFrom(), Components.External.ConsolePlus.Cli::CreateTable(), Components.Aphid.Compiler.AphidAssemblyBuilder::CreateType(), LLex.LexerGenerator::EmitState(), Components.Json.JsonFormatter::Format(), LLex.AlxFile::From(), Components.Aphid.VSPackage.AphidAuthoringScope::GetDeclarations(), Components.Aphid.UI.AphidCli::GetErrorMessage(), Components.NamespaceEqualityComparer::GetHashCode(), Components.Aphid.TypeSystem.TypeExtender::GetInteropName(), Components.Aphid.TypeSystem.AphidType::GetName(), Components.Aphid.TypeSystem.AphidObject::GetValueType(), Component.AphidUI.DynamicDataClassExtractor< TType, TAttribute >::InstantiatePopulated(), LLex.LLexFile::Interpret(), Components.Aphid.Interpreter.AphidLoader::LoadLibrary(), Components.Aphid.Parser.ScriptMutator::MutateCore(), AphidUI.CodeTextBox::OnAcceptsReturnChanged(), AphidUI.CodeTextBox::OnTextChanged(), Components.TypeLoader::ResolveFullType(), Components.Aphid.TypeSystem.InteropTypeResolver::ResolveType(), Components.Aphid.VSPackage.AphidScanner::ScanTokenAndProvideInfoAboutIt(), AphidUI.Internal.CodeCanvas::SetText(), Components.TypeLoader::TryGetAssemblies(), and Components.Aphid.TypeSystem.ValueHelper< TExpected >::UnwrapAndBoxCollection().